### ISSUE TITLE
大佬，请问支持10000行*8000列的表格吗

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#1]
支持横向列的可视化dom优化吗

**Comment by xuliangzhan** [comment]
是可以支持滚动渲染，但对于量太大的表格建议使用原生的table

**Comment by lishihong** [comment]
怎么配置可以同时支持横向和纵向滚动渲染

**Comment by lishihong** [comment]
不一次性加载，加载更多，怎么做

**Comment by lishihong** [comment]
大佬，npm 上是不是还没更新 ~

**Comment by xuliangzhan** [comment]
暂时不支持，可以 body-scroll 滚动事件配合 load 自行实现异步递增

**Comment by liufan121** [comment]
> 暂时不支持，可以 body-scroll 滚动事件配合 load 自行实现异步递增

大佬  body-scroll事件无效怎么回事啊
