### ISSUE TITLE
点击某一行某一列进行背景标色

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#10]

**Comment by xuliangzhan** [comment]
这个自行处理就行，cell-class-name 配合 cell-click

**Comment by lishihong** [comment]
当我点击后 再修改cell-class-name，表格还会重新去渲染吗，我怎么改class-name后没起作用

**Comment by lishihong** [comment]
![微信截图_20190517165611](https://user-images.githubusercontent.com/11676609/57916087-b8bfa000-78c4-11e9-96fa-df54fe425fb6.png)
我改变primeKey后，cell-class-name的那个函数还会去执行？
