### ISSUE TITLE
设置斑马纹后，点击和hover时，斑马纹的颜色没有变化

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#100]
**问题描述 Describe the bug**
设置斑马纹后，点击和hover时，斑马纹的颜色没有变化
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/img/11.8tcm0tociw9.gif)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by maxmeng93** [comment]
而且我感觉，选中和hover时颜色都太浅了，你看看这个色怎么样 rgb(230, 247, 255);

**Comment by xuliangzhan** [comment]
颜色你可以通过变量去自定义的

**Comment by maxmeng93** [comment]
点击选中行时，颜色依然没有变化
