### ISSUE TITLE
表单功能参考提议，使用弹窗式进行编辑/添加可能在列过多的时候体验更好,不过改动可能太大

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#102]
我今天找到一个表单自动生成组件。
地址：https://github.com/xaboy/form-create
文档：http://www.form-create.com/v2/guide/rule.html

他可以定义json自动生成表单。这样还可以跟 filters 融合在一起，不过这改动太大。

**Comment by xuliangzhan** [comment]
我觉得表单和表格应该没什么关系，都是独立的组件

**Comment by longa30** [comment]
是的。
