### ISSUE TITLE
怎么知道一行是已经展开还是未展开？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#103]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by tiger54910** [comment]
谢谢及时回复，父子表怎么实现？使用展开行功能来做，怎么把不同的数据加到展开行中呢？

**Comment by xuliangzhan** [comment]
不是有 [toggle-expand-change](https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=toggle-expand-change) 展开收起事件吗，自己处理数据就行
