### ISSUE TITLE
请问使用grid时，如何在toolbar中传入slots插槽？

### ISSUE THREAD

**Issue by liushengyu** [xuliangzhan/vxe-table#106]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

grid使用时，工具栏只能是按钮，且样式改不了。很多情况下就不好用了。

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
使用 [buttons](https://xuliangzhan.github.io/vxe-table/#/grid/api) 插槽就行
