### ISSUE TITLE
vxe-pager-size--select 被modal遮挡

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#107]
**问题描述 Describe the bug**
vxe-pager-size--select 不应该放到根节点上
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/vxe-table/vxe-table-bug.wnax148ihwo.gif)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
这个问题你可以通过[设置全局 zIndex](https://xuliangzhan_admin.gitee.io/vxe-table/v1/index.html#/table/start/use)

**Comment by maxmeng93** [comment]
使用z-index可以暂时解决问题，但是我觉得，这种类型的dom放在整个文档的根节点并不是最好的选择，我觉的它应该放到vxe-pager组件的根节点

**Comment by xuliangzhan** [comment]
这个在 v2.0 可能会调整
