### ISSUE TITLE
为正在编辑的行赋值问题

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#109]
**描述 Describe**

我使用 <a-input-select> 打开了一个modal ，里面嵌套了一个表格，点击表格，然后把点击的表格数据回填到正在编辑的表格上。
1. 原来我使用的方法是：新增一行时为表格新增一行数据，然后把这行数据开启编辑，但是回填数据的时候，因为tableData改变了，**所以造成了表格重新渲染，正在编辑的状态丢失，需要重新开启编辑**。
2. 现在使用的方法是： `xTable.insert({id: -1}).then(({row}) => { xTable.setActiveRow(row); })`，这样新增一可编辑行，但是没有找到如何设置、修改数据的方法。没有办法把modal上的数据回填到表格上

![image](https://raw.githubusercontent.com/maxmeng93/picee/master/vxe-table/vxe-table-bug-2.thikj8lrffh.gif)

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: 1.5.13

**Comment by maxmeng93** [comment]
如果那个a-input-select 的field为name，
``` javascript
xTable.insert({id: -1, name: '名称'}).then(({row}) => {
    console.log(row.name); // 名称 
});
```
但是，输入框却不会显示 ‘名称’ 这两个字，还是空白

**Comment by maxmeng93** [comment]
现在看来，可能还是要用我第一种方法，只是需要每次赋值后再开启编辑

**Comment by maxmeng93** [comment]
使用第二种方法也有问题，再次开启编辑后，编辑框还是为空

![image](https://raw.githubusercontent.com/maxmeng93/picee/master/vxe-table/vxe-table-bug-3.vq6zqbm41rr.gif)

**Comment by xuliangzhan** [comment]
没发现有赋值不生效问题，你应该检查写法

**Comment by maxmeng93** [comment]
你可以看我最后一张gif图，取消掉注释代码后，选择模态框中的数据后，名称没有显示，其他编号，类型没有输入框的都显示了

**Comment by maxmeng93** [comment]
demo 我明天提供

**Comment by maxmeng93** [comment]
还有我想知道，使用 insert 插入的数据应该使用什么方法 获取、修改、保存，因为它并不在我为vxe-grid传入的data里

**Comment by xuliangzhan** [comment]
任何动态插入的数据都不会同步数据源，可以通过 [getInsertRecords](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=getInsertRecords) 获取
或者直接操作数据源，比如 tableData.push({})，这个是可以通过数据源获取到的

**Comment by xuliangzhan** [comment]
增删改查的数据获取你应该看 [api](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=getInsertRecords)

**Comment by maxmeng93** [comment]
a-input-search 没有显示，是因为 `<a-input-search size="small" value={row[column.property]} onSearch={this.selectPrimer}/>` 中的 `value={row[column.property]}` 忘记写了，导致组件和值没有绑定。
