### ISSUE TITLE
使用slot template自定义时候，怎么拿到 type=index的那个索引的值

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#11]
![微信截图_20190516125245](https://user-images.githubusercontent.com/11676609/57827330-88e79e00-77d9-11e9-9f81-3600fb6afe94.png)

真实的index应该是127，我怎么拿到这个，我用的slot 里面的rowIndex,但是这个只是可视区域的index，我的可视区配置的是渲染100行。如果使用type=index，这个是可以看到127的，就是不知道怎么拿到这个type=index的值

**Comment by xuliangzhan** [comment]
更新最新看下

**Comment by lishihong** [comment]
![image](https://user-images.githubusercontent.com/11676609/58304660-c2e32080-7e27-11e9-977f-6cc3b7e2e2e3.png)
还是拿不到 真是的index哦，拿到的rowIndex 只是每次可视化渲染时候里面的index

**Comment by lishihong** [comment]
看了下源码，解决了，拿scope.seq就行了

**Comment by xuliangzhan** [comment]
seq序号和rowIndex都是可以拿到的

**Comment by xuliangzhan** [comment]
#26
