### ISSUE TITLE
表格编辑功能强化

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#110]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

可以参考下easyUI的datagrid，编辑时数据不双向绑定，只有endEdit时，才会把数据同步，而且可以通过一些方法可以为表格Editor设置值。

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
双向绑定是 vue 的机制，放弃双向那就直接用原生写组件，那就没必要用 vue 了，至于渲染频繁问题可以通过虚拟滚动或者自定义模板渲染，不要使用 v-model 绑定就行
建议除了复杂组件，输入框都使用原生的 input 渲染

**Comment by maxmeng93** [comment]
没有经过验证保存的数据按理来说是不应该同步到原数据的，如果取消编辑还要涉及数据回退

**Comment by xuliangzhan** [comment]
这个是正常的操作，最后如果验证不通过想要还原数据你可以调[数据还原](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=getInsertRecords)的方法
