### ISSUE TITLE
表格合计行 footer-cell-class-name 自定义不同列颜色时Function({footIndex, column, columnIndex})函数的footIndex为undefine

### ISSUE THREAD

**Issue by LHC087** [xuliangzhan/vxe-table#111]
**描述 Describe**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
你那个看的是旧的文档，[文档](https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=footer-cell-class-name)已更新

**Comment by LHC087** [comment]
新文档rowIndex也是undefine，是undefine的话，后面的 if (rowIndex === 0) {
                  return 'col-blue'
                } else {
                  return 'col-red'
                }就没意义了

**Comment by LHC087** [comment]
Function({$rowIndex, column, columnIndex, $columnIndex})，原来我少加了$符，但是你新文档
![image](https://user-images.githubusercontent.com/46363258/60635755-7cc9a580-9e46-11e9-9202-b9db25f3227a.png)的示例代码没更新

**Comment by xuliangzhan** [comment]
对的，使用 $rowIndex ，部分 demo 可能还没更新完整哈
