### ISSUE TITLE
单选、多选、highlight-current-row、getSelectRecords 使用有问题

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#114]
**问题描述 Describe the bug**
请看GIT演示。

1. 使用了 highlight-hover-row 和 单选方式时，点击行后，单选框选中，getSelectRecords() 获取到空数组。
2. 使用了 highlight-hover-row 和 多选方式时，点击行后，复选框没有被选中，getSelectRecords() 获取到空数组；只有点击复选框选中后，才能使用此方法获取选中的数据。
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/vxe-table/bug-5.ljobasb3lmn.gif)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: ?
 - vxe-table: ?

**Comment by maxmeng93** [comment]
设计思路可能和我的使用思路不太一样。
我觉得单选多选，除了选中数据的数量不同外，其他都应该一致，比如点击行可以选中单选表格行，那么也应该选中多选表格行。
还有就是单选无法通过 `getSelectRecords` 获取到选中的数据，但是多选可以，应该不是我使用方法有问题。

**Comment by xuliangzhan** [comment]
是不一样，多选和单选是两种完全不一样的实现，单选应该用 [getCurrentRow](https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=getCurrentRow)
具体看[文档](https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=%E7%94%A8%E4%BA%8E)

**Comment by xuliangzhan** [comment]
多选可以配置 [select-config](https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=select-config) 就能实现行点击
