### ISSUE TITLE
文档能否带个搜索功能，有个时候要查个属性，功能啊，都要找半天，比如我现在要grid中开启横向x，不知是啥属性。

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#115]
文档能否带个搜索功能，有个时候要查个属性，功能啊，都要找半天，比如我现在要grid中开启横向x，不知是啥属性。

在 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/fullQuery 中是带有横向x。但是我没有。挤到一起了。
从后台请求的json。字段。
![image](https://user-images.githubusercontent.com/17867961/60577402-e350b400-9db1-11e9-80e2-addc6b091408.png)

**Comment by longa30** [comment]
仔细看了下。Column中带了width. 我的没带。

**Comment by xuliangzhan** [comment]
设置宽度就行，超出会自动出现滚动条的
