### ISSUE TITLE
加了edit-rules验证时，选择框会被隐藏

### ISSUE THREAD

**Issue by LWD8** [xuliangzhan/vxe-table#116]
有问题图；
![image](https://user-images.githubusercontent.com/28432674/60584061-c8d10780-9dbe-11e9-89f0-c60dc666dae0.png)

正常图；
![image](https://user-images.githubusercontent.com/28432674/60584098-e69e6c80-9dbe-11e9-8357-2467bc41123b.png)

如果加了edit-rules验证，列表有时间选择的话，就会hidden隐藏了；如果没验证，则没问题；

在vxe-table 增加edit-rules 进行列表验证时，就会出现内容被隐藏掉

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by LWD8** [comment]
![image](https://user-images.githubusercontent.com/28432674/60635603-ed23f700-9e45-11e9-867f-105f28ba6d65.png)
![image](https://user-images.githubusercontent.com/28432674/60635628-fdd46d00-9e45-11e9-92d0-6a4665ccb21a.png)

已经更新到最新，但问题还在

**Comment by LWD8** [comment]
![image](https://user-images.githubusercontent.com/28432674/60635881-ee095880-9e46-11e9-8437-02a5cf33fe40.png)
这个属性影响到了，但去除后，上面的错误提示就会错位

**Comment by xuliangzhan** [comment]
你可以更新到最新，一个稳定的组件是不应该受  position: relative; 影响，正常固定  position: relative; 样式应该是没问题的
