### ISSUE TITLE
在合并行或列的基础上，进行可编辑表格上的插入行数据操作，列或行会错位

### ISSUE THREAD

**Issue by selfdialog** [xuliangzhan/vxe-table#119]
**问题描述 Describe the bug**
1.前提：在合并行好了的表格上
![@@D27`KUYM_~QB3 MQELNGE](https://user-images.githubusercontent.com/30248712/60667885-2e93c100-9e9d-11e9-8dac-664fd8785dd1.png)

2.后期操作：在可编辑表格上进行新增行数据
![X MFLSS@%FGT O}}6**问题描述 Describe the bug**
1.前提：在合并行好了的表格上
![@@D27`KUYM_~QB3 MQELNGE](https://user-images.githubusercontent.com/30248712/60667885-2e93c100-9e9d-11e9-8dac-664fd8785dd1.png)

2.后期操作：在可编辑表格上进行新增行数据
PMQ](https://user-images.githubusercontent.com/30248712/60668024-90ecc180-9e9d-11e9-9859-7e0d4038858c.png)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**
3.重现地址
https://codepen.io/selfdialog/pen/mZjReZ

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
这个你应该检查 rowspan、colspan 是否正确，结果明显不正常

**Comment by selfdialog** [comment]
> 这个你应该检查rowspan，colspan是否正确，结果明显不正常

只是合并了name行，小徐1的两行，能不能帮忙看看代码，就在上面的链接中

**Comment by xuliangzhan** [comment]
![image](https://user-images.githubusercontent.com/34864213/60669501-0dcd6a80-9ea1-11e9-905a-7079de81fca1.png)

把日志打印就一目了然，最后运算后的 colspan为0 肯定少一列

**Comment by selfdialog** [comment]
> ![image](https://user-images.githubusercontent.com/34864213/60669501-0dcd6a80-9ea1-11e9-905a-7079de81fca1.png)
> 
> 把日志打印就一目了然，最后运算后的 colspan为0 肯定少一列
> 还有 key 没正确设置也会导致其他问题

了解了，还有一个问题
![7T5)9)QX{%W`WXR{4D62`$E](https://user-images.githubusercontent.com/30248712/60669918-0e1a3580-9ea2-11e9-8dd3-02db53b3a0e5.png)
你看这个插入到第一行的时候会在两行里面显示

**Comment by xuliangzhan** [comment]
同样的问题，你看日志就行，运算结果永远都是这个结果，都是合并1、2行，你应该检查下计算逻辑
![image](https://user-images.githubusercontent.com/34864213/60670234-c0ea9380-9ea2-11e9-8ed5-aa7983e33ab2.png)
