### ISSUE TITLE
还没加入项目中去，正研究下用到项目中合不合适。主要是感谢作者的贡献，以前一直用的boostrap table，现在改用vue，这个功能比较类似

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#12]
**描述 Describe**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
开源这个也是因为vue中功能强大的表格较少，不过在1.0发布之前需要注意，可能会调整部分 API 哈
