### ISSUE TITLE
使用 `validate` 验证表格后弹出的提示没有消失

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#120]
**问题描述 Describe the bug**
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/sangon/bug-9.5blz2z2n7we.gif)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: ?
 - vxe-table: ?

**Comment by maxmeng93** [comment]
右侧表格取消编辑后，还有一个红色色块，那么本来是弹出的验证信息

**Comment by maxmeng93** [comment]
左右两个表格退出编辑的代码是一样的，唯一的区别是左侧表格提示出现在输入框下面，而右侧提示出现在输入框上方。demo迟会提供

**Comment by xuliangzhan** [comment]
取消是怎么操作的，特殊场景可以手动清除

**Comment by maxmeng93** [comment]
> 取消是怎么操作的，特殊场景可以手动清除

``` javascript
xTable.clearActived().then(() => {
    xTable.remove(row);
});
```
