### ISSUE TITLE
使用全键盘操作时如何允许编辑状态下上下左右移动有效？

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#122]
在全键盘操作下目前的功能可以在编辑单元格的状态下启用上下左右吗？应如何启用?我试的时候发现只有在非编辑状态下才可以移动单元格。

**Comment by xuliangzhan** [comment]
输入状态下方向键是操作光标，不会支持这种冲突的功能，如果需要你得自行绑定事件去实现
