### ISSUE TITLE
vxe-table-column中使用:edit-render的events属性报错

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#124]
**问题描述 Describe the bug**

![image](https://user-images.githubusercontent.com/20534088/60787546-b96e0780-a18c-11e9-89e3-741d8570ba6d.png)
![image](https://user-images.githubusercontent.com/20534088/60787568-cf7bc800-a18c-11e9-8b7d-2ababc0cb166.png)

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/20534088/60787663-241f4300-a18d-11e9-9bda-5294db9b89ba.png)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: 内核63.0以上
 - vue: 2.6.10
 - vxe-table: 1.6.4

**Comment by xuliangzhan** [comment]
那是个方法你写个字符串肯定报错

**Comment by zxWendy** [comment]
请问这个怎么解决的？vue里面写方法就是只写个名字吧，如果加上()，参数要怎么获取？

**Comment by xlz26296** [comment]
事件那是个方法，不是字符串
![image](https://user-images.githubusercontent.com/34787386/61198667-8a681080-a70d-11e9-8a33-d0fe340ed799.png)

这才是方法
![image](https://user-images.githubusercontent.com/34787386/61198769-06625880-a70e-11e9-9463-172f9742eb4a.png)

**Comment by zxWendy** [comment]
感谢明白了， 不能按VUE的那种写法，我是vxe-grid，这种写法不适用(。・∀・)ノ
