### ISSUE TITLE
[Help] vxe-table fixed 显示。

### ISSUE THREAD

**Issue by djkloop** [xuliangzhan/vxe-table#125]
**描述 Describe**

请问能否一直保持固定列的样式？

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

```
// 怎么样一直保持固定列表的样式?

// 在一开始的时候就跟固定列的样式是一样的？

// 官网里子：https://xuliangzhan.github.io/vxe-table/#/table/base/fixedFull
```
**请填写以下版本信息 please complete the following information**
 - browser: chrome 75+
 - vue: 2.6.10
 - vxe-table: 1.6.5

**Comment by xuliangzhan** [comment]
啥意思？

**Comment by djkloop** [comment]
```
// 因为fixed时候鼠标在fixed行上面是划不动的，但是用户是不知道的，


// demo: https://jsfiddle.net/0nytd71w/1/  (jsrun我一直不能保存不知道咋回事)

```
// 描述1 
![image](https://user-images.githubusercontent.com/21050914/60855449-5d5fbd80-a236-11e9-8cbd-0536f451fa26.png)
// 描述2
![image](https://user-images.githubusercontent.com/21050914/60855546-b6c7ec80-a236-11e9-88ee-3e5c9d6ea909.png)
// gif
![demo](https://user-images.githubusercontent.com/21050914/60855660-348bf800-a237-11e9-8989-2f079b46e6b8.gif)

**Comment by xuliangzhan** [comment]
列多应该是有滚动条的，要一直固定就加上样式就行

```
.vxe-table .vxe-table--fixed-left-wrapper {
  box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.12);
}
.vxe-table .vxe-table--fixed-right-wrapper {
  box-shadow: -2px 2px 6px rgba(0, 0, 0, 0.12);
}
```

**Comment by djkloop** [comment]
thx
