### ISSUE TITLE
有个东西不会写，在列表中展示下拉框（select的数据源是远程拉取的），比如性别选择，男，女；分别对应value 1和2；页面上选择后。需要将对应的男和value 值返回后台。但是不知道，select框如何加入到表格中

### ISSUE THREAD

**Issue by wb477982674** [xuliangzhan/vxe-table#127]
**描述 Describe**
新手不太会用。所以问一下

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: 最新版
 - vue: 3.0
 - vxe-table: 最新版

**Comment by XianYue-Tong** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/template
参考一下例子，可以自定义模板列，将下拉框放到表格里
然后调用表格获取全部数据的api，获得更改后的值
