### ISSUE TITLE
[Bug Report]vxe-table  props show-overflow

### ISSUE THREAD

**Issue by djkloop** [xuliangzhan/vxe-table#128]
**问题描述 Describe the bug**

table设置show-overflow有滚动条bug

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**
```
// 如果给table设置了show-overflow
// table里面会出现双滚动条
// http://jsrun.net/8rXKp/edit

```

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/21050914/60790025-15d42580-a193-11e9-83be-50f6c548a8c5.png)

**期望的结果 Expected behavior**
不显示滚动条
**请填写以下版本信息 please complete the following information**
 - browser: chrome 75+
 - vue: 2.6.10
 - vxe-table: 1.6.5

**Comment by xuliangzhan** [comment]
这个我看了没出现你说的问题？

**Comment by djkloop** [comment]
@xuliangzhan 那个测试网站的问题不能fork...
```html

<script src="//unpkg.com/vue"></script>
<script src="//unpkg.com/xe-utils"></script>
<script src="//unpkg.com/vxe-table/lib/index.js"></script>

<div id="app">
  <template>
    <div>
      <p>Bug: 如果同时设置了高度和show-overflow会出现双滚动条</p>
      <vxe-table 
        border
        height="400"
        show-overflow
        :data.sync="tableData">
        <vxe-table-column type="index" width="60" fixed="left"></vxe-table-column>
        <vxe-table-column field="name" title="Name" width="200"></vxe-table-column>
        <vxe-table-column field="role" title="Role" width="200"></vxe-table-column>
        <vxe-table-column field="sex" title="Sex" width="200"></vxe-table-column>
        <vxe-table-column field="date" title="Date" width="200"></vxe-table-column>
        <vxe-table-column field="address" title="Address" fixed="right" width="200"></vxe-table-column>
      </vxe-table>
      <p>更多详细信息请查看 API</p>
      <vxe-table 
        border
        optimized
        height="200"
        :data.sync="tableData">
        <vxe-table-column type="index" width="60" fixed="left"></vxe-table-column>
        <vxe-table-column field="name" title="Name" width="200"></vxe-table-column>
        <vxe-table-column field="role" title="Role" width="200"></vxe-table-column>
        <vxe-table-column field="sex" title="Sex" width="200"></vxe-table-column>
        <vxe-table-column field="date" title="Date" width="200"></vxe-table-column>
        <vxe-table-column field="address" title="Address" fixed="right" width="200"></vxe-table-column>
      </vxe-table>
    </div>
  </template>
</div>

```

**Comment by xuliangzhan** [comment]
chrome 75的滚动条是常规的，你那个很明显浏览器不一样，滚动条会自动隐藏

**Comment by djkloop** [comment]
![image](https://user-images.githubusercontent.com/21050914/60883988-5361ad00-a27e-11e9-9b96-094024975d53.png)

**Comment by xuliangzhan** [comment]
重现不出你的效果 哈，我用chrome 都是正常的滚动条

![image](https://user-images.githubusercontent.com/34864213/60887432-059d7280-a287-11e9-928b-d04040682b3f.png)
![image](https://user-images.githubusercontent.com/34864213/60887477-206fe700-a287-11e9-8f19-ef0386e54b42.png)

**Comment by djkloop** [comment]
macOS Mojave 10.14.3
经过昨天的二次测试（用了同事的win电脑确实没有这样的bug）但是macos上确实有这样的问题

**Comment by xuliangzhan** [comment]
我没有MacOS系统，可能不会那么快解决这个兼容性问题

**Comment by sunscheung** [comment]
@djkloop win电脑chrome浏览器 打开你的codepen地址 列就错位了。
