### ISSUE TITLE
全键盘能否支持select、checkbox??

### ISSUE THREAD

**Issue by qinjun86** [xuliangzhan/vxe-table#129]
我们想要在表格中实现全键盘录入，不同的列可能录入方式不一样，比如包含input datepicker select等，示例中的全键盘操作好像只提供了input录入方式，没有包含select登录入方式；我们也尝试了在你的element-ui自定义渲染中加入全键盘配置，但是遗憾的事不行！！！

**Comment by xuliangzhan** [comment]
这个和任何组件都没关系，开启后都能支持
