### ISSUE TITLE
新版更新后bug：最新一次添加的行，无法计入到合计中

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#130]
**问题描述 Describe the bug**
1.7.0版本的合计行功能，测试后出现新的bug：最新一次添加的行，无法计入到合计中，只有点击到其他行之后才会计入；这样会导致只有一行数据时，无法合计；多行记录时，最新一行记录容易被计算遗漏

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**
![1](https://user-images.githubusercontent.com/20534088/60807961-bfc6a880-a1b9-11e9-9d22-7ea7529186e8.gif)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: 2.6.10
 - vxe-table: 1.7.0

**Comment by xuliangzhan** [comment]
v1.7+不会再支持性能糟糕的实时计算，只会在失焦之后触发计算

**Comment by xuliangzhan** [comment]
你可以给input加个input事件，然后调用 updateFooter 方法

**Comment by XianYue-Tong** [comment]
谢谢，这个问题已经解决了；


新的问题：动态添加行：采用的自定义模板列方式

出现的问题：第一列是固定列，高度错位，合计行错位，多选状态混乱



------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 晚上8:06
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "樱祭"<1092485856@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 新版更新后bug：最新一次添加的行，无法计入到合计中 (#130)




你可以给input加个input事件，然后调用 updateFooter 方法

**Comment by xuliangzhan** [comment]
错位？

**Comment by XianYue-Tong** [comment]
对的错位了，我重新提交了错误截图。


------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 晚上8:19
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "樱祭"<1092485856@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 新版更新后bug：最新一次添加的行，无法计入到合计中 (#130)




错位？
