### ISSUE TITLE
动态添加行，采用的自定义模板列方式，第一列固定列高度错位，合计行错位，多选状态混乱；

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#131]
**问题描述 Describe the bug**
动态添加行，采用的自定义模板列方式，第一列固定列高度错位；合计行错位；多选状态混乱，只选中一行，然后表头里的全选就被勾上了；
采用:edit-render属性配置时，没有问题，使用模板列就会出现以上问题。

**重现问题的步骤 To Reproduce**
![image](https://user-images.githubusercontent.com/20534088/60809729-ee468280-a1bd-11e9-802b-d0589961a3a0.png)

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**
![1](https://user-images.githubusercontent.com/20534088/60809739-f3a3cd00-a1bd-11e9-93e0-b061ba51feab.gif)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - browser: ?
 - vue: 2.6.10
 - vxe-table: 1.7.0

**Comment by xuliangzhan** [comment]
请提供重现问题链接

**Comment by XianYue-Tong** [comment]
当列过多。出现横向滚动条的时候就会错误，代码我打包，放在附件里；HTML文件夹内有个 test_vue.html；
[固定列、合计行错位.zip](https://github.com/xuliangzhan/vxe-table/files/3368358/default.zip)

**Comment by XianYue-Tong** [comment]
代码包已发




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 晚上8:25
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "樱祭"<1092485856@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 动态添加行，采用的自定义模板列方式，第一列固定列高度错位，合计行错位，多选状态混乱； (#131)




请提供重现问题链接

**Comment by xuliangzhan** [comment]
不用你代码，你用在线链接https://jsrun.net/vIyKp/edit

**Comment by xuliangzhan** [comment]
看你模板的内容很明显就撑破单元格布局了，规范是不能超过单元格高度，要超过就要将 show-overflow 关闭并自行处理相关兼容性

**Comment by XianYue-Tong** [comment]
https://jsrun.net/vIyKp/edit
重新在线编辑了  只要单元格内容高度过高就会错位   
我这边自行处理兼容性

**Comment by xuliangzhan** [comment]
一般情况把  show-overflow  属性去掉就行，不建议单元格放那么多可视组件，性能非常糟糕的
