### ISSUE TITLE
使用vxe-grid动态定义列，但是不同的列要格式化的话，formatter怎么从ajax返回的json定义？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#132]
动态定义的列，但是想要根据不同的列生成不同的格式化内容，比如有的列是上传文档的，希望格式为为超链接形式

**Comment by xuliangzhan** [comment]
请先看文档 https://xuliangzhan.github.io/vxe-table/#/table/grid/template

**Comment by tiger54910** [comment]
因为列是从后台ajax获取的json数据，不是定义在页面上的json，就不知道怎么格式化了

**Comment by tiger54910** [comment]
或者后台格式化数据之后，比如<a href='xxx'>XXXX</a>在前端页面上能显示html也可以，好像只当做字符串来处理显示了

**Comment by xuliangzhan** [comment]
都是一样的，具体逻辑你得自行处理

**Comment by tiger54910** [comment]
解决了，谢谢
