### ISSUE TITLE
vxe-gird 能否增加单击或双击事件

### ISSUE THREAD

**Issue by Tourist-ChenHao** [xuliangzhan/vxe-table#133]
业务需求需要渲染5000条+数据 和 30多个column，目前通过vxe-table来渲染数据，已开启VDom，但还是加载缓慢。尝试使用vxe-gird来加载数据，会比较流畅一点，但是vxe-gird没有cell-dbclick事件，所以 vxe-gird 能否增加单击或双击事件，可以让我获取到dbclick  row的数据。

**Comment by xuliangzhan** [comment]
vxe-grid 继承自 vxe-table，列多的话使用 vxe-grid 因为不需要为每个列初始化实例，性能快非常多
具体看文档 https://xuliangzhan.github.io/vxe-table/#/grid/api

**Comment by Jack-Haoxuan** [comment]
vxe-grid Events只能通过Slots来实现？

**Comment by xuliangzhan** [comment]
不知道你指啥事件，API文档能支持的都能用
