### ISSUE TITLE
新增编辑行，校验提示方式问题

### ISSUE THREAD

**Issue by suweien** [xuliangzhan/vxe-table#134]
空表格新增第一行校验 默认使用tooltip
后续使用的行内校验提示
![1562736614(1)](https://user-images.githubusercontent.com/26915433/60942970-24e3e080-a317-11e9-8bc3-e7ee651658b6.jpg)
![1562736614](https://user-images.githubusercontent.com/26915433/60942971-257c7700-a317-11e9-81a3-abfa562f2049.jpg)
想不明白 你为啥 要这样我现在 因为zIndex问题  tooltip提示 直接被覆盖了  第二条以后校验的就能正常显示，难以理解你为啥这样设置

**Comment by suweien** [comment]
第一条 使用的tooltip
第二条往后却使用的行内提示 
希望统一  因为你tooltip的zIndex是死的 没法动态变导致 在我这边 tooltip提示 直接 就在dialog下面了

**Comment by xlz26296** [comment]
你可以设置zindex的 https://xuliangzhan.github.io/vxe-table/#/table/start/use

```
      Vue.use(VXETable, {
        tooltip: {
          zIndex: 3000
        }
      })
```

**Comment by xlz26296** [comment]
#51

**Comment by suweien** [comment]
但是我的行内编辑使用了复杂的自定义组件，还会弹出新的dialog，而且弹出的dialog zIndex是动态的，所以不能通过这种设置，否则会出现提示信息覆盖到新弹出的页面之上。。。。

**Comment by suweien** [comment]
@xlz26296 行内提示那样设置，可能会覆盖到新弹出的dialog之上，因为elementui 的dialog zIndex是动态的，而我的行内自定义了一些复杂的组建，会新弹出dialog。。。

**Comment by suweien** [comment]
还是希望作者统一验证提示，为啥唯独 空表格insert数据校验要使用tooltip这种提示，而后续新增的校验的提示信息却没有问题？

**Comment by xuliangzhan** [comment]
建议更新到最新，文档都详细写了 https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=valid-config
只要有设置高度默认就是内联的提示，如果想固定一种你可以通过全局设置就行，具体参数看文档

```
 Vue.use(VXETable, {
        validConfig: {
          message: inline
        }
      })
```

**Comment by suweien** [comment]
确实好使了，谢谢作者
