### ISSUE TITLE
动态添加表列，工具栏也自定义，但是希望保留“显示/隐藏”表的列的按钮功能，怎么做啊？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#135]
如标题，
1、从demo上来看，如果自定义工具栏的话，表的列的固定的，右端显示/隐藏列的下拉是有列的；
2、动态加载列和数据，使用自带的toolbar可以，但是没法添加比如搜索文本框之类的功能；
3、希望动态添加列和数据，同时可以自定义工具栏，怎么办呢？

**Comment by xuliangzhan** [comment]
不太明白你要实现什么，自带的工具栏按钮都是可以通过 slot 自定义模板的
https://xuliangzhan.github.io/vxe-table/#/table/grid/toolbar
https://xuliangzhan.github.io/vxe-table/#/table/grid/customToolbar

**Comment by tiger54910** [comment]
https://xuliangzhan.github.io/vxe-table/#/table/grid/customToolbar
谢谢，就是这个功能需求
