### ISSUE TITLE
使用列名排序的时候，点击上下三角形很难点，可否添加在列名上点击，利用列名添加切换升降序，类似于bootstraptable的做法一样，谢谢

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#136]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
sorry, 由于这个功能存在功能冲突且不利于扩展，在没有想到最优的方式之前可能不会支持
但这个功能实现是非常简单 https://xuliangzhan.github.io/vxe-table/#/table/advanced/customSort

**Comment by tiger54910** [comment]
好的，谢谢，有处理方法就好
