### ISSUE TITLE
固定列为什么要禁用列宽拖动？

### ISSUE THREAD

**Issue by yelog** [xuliangzhan/vxe-table#137]
**描述 Describe**
首先非常佩服作者写的插件，今日测试过程中发现固定列不能拖动列宽，看了源码发现被作者禁用掉了。

因为感觉固定列宽的拖动也是一个痒点需求，作者是否可以告知禁用的原因。

代码位置：`packages/header/src/header.js:249` ，如下图所示：

![image](https://user-images.githubusercontent.com/14227866/61129773-ba35cf00-a4e7-11e9-91ff-5e3a57561afe.png)

**Comment by xuliangzhan** [comment]
固定列的拖动需要处理的相关的逻辑较多、涉及范围较广，在没有想到最优方案之前不会支持；
疑点：既然是固定列，又为何能拖动，本身逻辑上就有些冲突

**Comment by yelog** [comment]
不是**列顺序**的拖动，而是**列宽**的调整，**固定列**只是固定列的位置，跟列宽没什么关系吧。

我放开代码试了一下，没发现什么大问题，只是那条辅助线是是跟随 body 中的 列，而不是 fixed 的列。

![拖动效果](https://im2.ezgif.com/tmp/ezgif-2-e26398dc6090.gif)

**Comment by xuliangzhan** [comment]
正常的固定列场景是支持的，还有其他特殊场景要做一些处理，后续可能会支持

**Comment by xuliangzhan** [comment]
https://xuliangzhan.github.io/vxe-table/#/table/base/resizable

**Comment by yelog** [comment]
66666
