### ISSUE TITLE
无法清除单选按钮选中状态

### ISSUE THREAD

**Issue by guaijie** [xuliangzhan/vxe-table#138]
**问题描述 Describe the bug**
表格单选按钮：调用this.$refs.table.clearCurrentRow()无法清除单选按钮选中状态

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - system: win7
 - browser: 谷歌
 - vue: 2.6.10
 - vxe-table: 1.7.8

**Comment by xuliangzhan** [comment]
v1.7+ 该功能已经细分了，可以支持实现更加复杂的逻辑了；清除单选应该用这个 [clearRadioRow](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=clearRadioRow)

[  highlight-current-row 高亮行](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/current)
[ type=radio 单选行](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/radio)
