### ISSUE TITLE
表格真的很强大，非常喜欢能找到这款。但有个建议，表格编辑新增一行数据，能不能把自动生成的id字段名改改，id是后台实体常用的字段，导致跟后台冲突

### ISSUE THREAD

**Issue by virycs** [xuliangzhan/vxe-table#139]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by virycs** [comment]
因为这个问题，我特意插入一个空id，还是给自动生成的覆盖了，只能在保存的时候把这个id去掉

**Comment by xuliangzhan** [comment]
组件不会污染任何属性，唯一主键都是配置的 [row-id](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=row-)

**Comment by virycs** [comment]
addRecord () {
      let newRecord = {
        id: '',
        detail: '',
        creator: this.$store.state.user.userName,
        askInfoId: this.form.askInfoId,
        updateTime: formatDate(new Date())
      }
      this.$refs.grid.insert(newRecord).then(({ row }) => {
        debugger
        this.$refs.grid.setActiveCell(row, 'detail')
      })
    }   这个代码调试，row里面的id的确是自动生成值了

**Comment by virycs** [comment]
还有个问题，表格在Iview的对话框Modal里面，配了show-overflow，但是弹出的tooltip在对话底层，覆盖了，有没有办法解决？我试过vxe-table-plugin-iview，没有用

**Comment by xuliangzhan** [comment]
调用代码呢？

**Comment by virycs** [comment]
id覆盖的在附件里面


下面这个是表格放到对话框，showOverflow弹出的tooltip在对话底层
<Modal class="track" v-model="showTrackingDetail" footer-hide title="跟踪详情" width=1000>
      <record ref="record"/>
</Modal>




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年7月13日(星期六) 晚上7:22
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "龙龙"<383625498@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 表格真的很强大，非常喜欢能找到这款。但有个建议，表格编辑新增一行数据，能不能把自动生成的id字段名改改，id是后台实体常用的字段，导致跟后台冲突 (#139)




调用代码呢？

**Comment by xuliangzhan** [comment]
我说的是表格的调用代码

**Comment by virycs** [comment]
methods: {
    toolbarButtonClickEvent ({ button }, event) {
      switch (button.code) {
        case 'add':
          this.addRecord()
          break
        case 'mysave':
          this.save()
          break
      }
    },
    addRecord () {
      let newRecord = {
        id: '',
        detail: '',
        creator: this.$store.state.user.userName,
        askInfoId: this.form.askInfoId,
        updateTime: formatDate(new Date())
      }
      this.$refs.grid.insert(newRecord).then(({ row }) => {
        debugger
        this.$refs.grid.setActiveCell(row, 'detail')
      })
    }
}调用就是点击toolbar里面的button触发addRecord () 方法

**Comment by xuliangzhan** [comment]
这看起来都是正常的，现在是有什么问题？

**Comment by virycs** [comment]
this.$refs.grid.insert(newRecord).then(({ row }) => {
debugger
this.$refs.grid.setActiveCell(row, 'detail')
})问题就是这里插入完后，回调里面的row.id自动赋值了，比如id: 1563017162221

**Comment by virycs** [comment]
<vxe-grid resizable
        stripe
        highlight-hover-row
        showHeaderOverflow
        showOverflow
        class="vxe-table-iview"
        ref="grid" max-height="800" size="small"
        :toolbar="toolbar"
        :pager-config="{pageSize: 10, pageSizes: [10, 15, 20, 50, 100]}"
        :proxy-config="tableProxy"
        :columns="columns"
        :edit-config="{key: 'id', trigger: 'click', mode: 'cell', showStatus: true}"
        :props="{rowId: 'row-id'}"
        @toolbar-button-click="toolbarButtonClickEvent"></vxe-grid>  这是我的表格配置，不知道 :props="{rowId: 'row-id'}"这个配的对不对，现在这个rowId配合不配都有上面那个问题

**Comment by virycs** [comment]
另外tooltip被覆盖已经通过配置解决，多谢。上面那个id自动赋值的问题我先自己规避下
Vue.use(VXETable, {
  size: 'small',
  version: 0,
  tooltip: {
    zIndex: 3000, // 对于在某些场景中，由于堆叠被覆盖时可能会用到
    theme: 'dark'
  }
})

**Comment by xuliangzhan** [comment]
id那个 key 不是你自己配置的吗

**Comment by virycs** [comment]
是我配的，但我没赋值啊，插入后id自动赋值了

**Comment by xuliangzhan** [comment]
那是唯一主键啊，没设置就默认随机数，必须唯一

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/insert

**Comment by xuliangzhan** [comment]
那个 tooltip 你也可以更新到v1.8+，zIndex默认就是3000，可以不用设置

**Comment by virycs** [comment]
我提交前置空是没问题的，只是这样提交代码就得自己写，如果没有这个id和后台冲突，就可以直接使用代理ajax提交

**Comment by virycs** [comment]
好， tooltip那个我更新试试

**Comment by suweien** [comment]
我记得rowId可以指定字段吧，指定一个其他字段不就行了？

**Comment by xuliangzhan** [comment]
所有版本都是可以指定字段使用 edt-config.key 配置， v18+使用 row-id

**Comment by xuliangzhan** [comment]
按我所遇到的前后台交互规范应该不依赖id的，比如增删改查提交大概是这么个结构 {insertRecords:[],removeRecords:[],updateRecords:[]}
你这个后台会被 id 所影响，那你就只能指定其他字段或提前之前清空

**Comment by virycs** [comment]
更新后问题解决了哈，多谢，之前是没升级到v18+配置row-id不生效。后台给id影响是因为后台接收到参数反序列化成对象，id值大于int最大值报错，不管有没有insertRecords这种key区分。问题都解决了，多谢

**Comment by virycs** [comment]
配了rowId后出现新问题，表格初始化后除了第一条数据，其他数据永远会存在updateRecords中，难道后台要给这个rowId赋值？

**Comment by xuliangzhan** [comment]
这是因为你没有给默认吧，唯一主键不允许为空的，更新到最新试下，可以支持自动设置默认值

**Comment by virycs** [comment]
不应该是我给rowId赋值吧，没有值的话不是自动生成吗，跟insert一样自动生成id。已经是最新的"vxe-table": "^1.8.2",

**Comment by xuliangzhan** [comment]
v1.8.4+才能支持数据全量默认值，之前只能支持插入数据的默认值 哈

**Comment by virycs** [comment]
好的
