### ISSUE TITLE
当数据量大于500的时候  选择全选   全选的数据只有70条 ， 500或者500以下都可以全选

### ISSUE THREAD

**Issue by dafeixiong0v0** [xuliangzhan/vxe-table#14]
当数据量大于500的时候  选择全选   全选的数据只有70条 ， 500或者500以下都可以全选

**Comment by lishihong** [comment]
你看下配置说明，应该是启用了可视区渲染，大于500的时候。你可以不启用可视区渲染，如果数据量比较小。

**Comment by dafeixiong0v0** [comment]
数据量大，而且需要全选，可以启用可视区渲染的吗

**Comment by lishihong** [comment]
你全量加载数据，不会卡顿的话，就不用启用可视区渲染。我这边是有一个10000行*8000列的数据量要全量展示，不做可视区渲染，浏览器会卡死。可视区渲染，你可以添加滚动监听，做分页加载，全选应该是每问题的

**Comment by xuliangzhan** [comment]
你更新到最新版本就行，无论是多选排序筛选全部都可以支持滚动渲染的
