### ISSUE TITLE
table列和列拖动，可以用用vxe-table做这个功能?

### ISSUE THREAD

**Issue by Yourroot** [xuliangzhan/vxe-table#143]
* **这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
 楼主列拖动因为你写在底层了，因为我想扩展性table的功能，所以想你能否帮我用vxe-table做个列拖动功能，多谢你了

* **描述下，你希望得到的什么解决方案 Describe the solution you'd like**
 ?

* **是否已有其他不错的替代方案 Describe alternatives you've considered**
 ?

* **版本信息 Version information**
  * system: ?
  * browser: ?
  * vue: 2.52
  * vxe-table: 2

**Comment by xuliangzhan** [comment]
https://xuliangzhan.github.io/vxe-table/#/table/other/sortableColumn

**Comment by Yourroot** [comment]
<template>
  <div :class="{'CommonTable-wrapper': true, 'labResourceReport-Table': islabResourceReport}">
    <div class="CommonTableKuang" v-if="CommonTablePopover">
      <el-popover
      ref="`popoverCommonTableWrapper`" 
      popper-class="CommonTableelPopover_wrapper"
      placement="bottom"
      width="150"
      trigger="click">
      <el-checkbox-group v-model="checkboxVal" class="CommonTable-checkboxGroup-wrapper">
      <el-checkbox :label="Item.propName"  v-for="(Item, Index) in fileUploadAction" :key="Index"></el-checkbox>
      </el-checkbox-group>
      <div slot="reference" title="自定义配置">
        <img src="@/assets/img/configurationinventory.png" style="width:18px;"/>
      </div>
      </el-popover>
    </div>
    

    

    
        <vxe-table
        ref="tableDataRef"
          border
          resizable
           stripe
          highlight-hover-row
          highlight-current-row
          show-header-overflow
          :height="tableDataHeight"
          @selection-change="selectFn"
          @select="handleSelection"
          @select-all="handleSelectionAll"
          :optimization ="{scrollY: {gt: 50, oSize: 10, rSize: 30}}"
          :data.sync="tableData">
                <vxe-table-column type="selection" width="36" v-if="SelectionIsshow"></vxe-table-column>
                <template  v-for="(item, idex) in formThead">
                      
                        <vxe-table-column  :width="116" v-if="item.prop === 'isCheckedOut'" :field="item.prop" :title="item.propName" sortable :key="idex" show-overflow>
                          <template v-slot="{ row }">
                              <span v-if="row.isCheckedOut === '已检出'" style="color:red">{{row.isCheckedOut}}</span>
                              <span v-if="row.isCheckedOut === '检入'" style="color:black">{{row.isCheckedOut}}</span>
                          </template>
                        </vxe-table-column>
                          
                        <vxe-table-column  :width="item.width" v-else-if="item.type === 'a'"  :field="item.prop" :title="item.propName" sortable :key="idex" show-overflow>
                          <template v-slot="{ row }">
                             <a href="javascript:void(0);"  @contextmenu.prevent="CommonContextmenuClick(row)" @click="openDetile(row)"  v-rightMenu = "menudata">{{ row[item.prop] }}</a>
                          </template>
                        </vxe-table-column>
                                
                        <vxe-table-column  :width="116" v-else-if="item.type === 'TestReportNumber'"  :field="item.prop" :title="item.propName" sortable :key="idex" show-overflow>
                          <template v-slot="{ row }">
                              <span v-if="row.TestReportNumber === '无'">{{row.TestReportNumber}}</span>
                              <a v-else href="javascript:void(0);" @click="openDetile(row.TestReportNumber,'com.midea.model.report.TestReport')">{{ row.TestReportNumber }}</a>
                          </template>
                        </vxe-table-column>
                                 
                        <vxe-table-column  width="248px" v-else-if="item.type === 'ConvertRows'"   :field="item.prop" :title="item.propName" sortable :key="idex">
                          <template v-slot="{ row }">
                                <div :title="row[item.prop]">
                                    <p v-for="(item, index) in ConvertRows(row[item.prop])" :key="index">{{item}}</p>
                                </div>
                          </template>
                        </vxe-table-column>
                                
                        <vxe-table-column  :width="116" v-else-if="item.type === 'date'" :field="item.prop" :title="item.propName" sortable :key="idex" show-overflow>
                          <template v-slot="{ row }">
                               <p>{{switchConsignDate(row[item.prop])}}</p>
                          </template>
                        </vxe-table-column>
                                
                        <vxe-table-column  v-else :width="116"   :field="item.prop" :title="item.propName" sortable :key="idex" show-overflow>
                          <template v-slot="{ row }">
                                <span :class="{'labResourceReportBackground': row.Backgroundcolour, 'labResourceReportIshow': true}" >{{row[item.prop]}}</span>
                          </template>
                        </vxe-table-column>
                </template>
       </vxe-table>
  </div>
</template>

<script >
import mixinsSelect from '@/common/mixinsSelect.js';
import Sortable from 'sortablejs';

export default {
  name: 'CommonTableSubassemblys',
  mixins: [mixinsSelect],
  props: {
    tableDataHeight: { // table高度
      type: Number
    },
    tableData: { // tbaleData总数据
      type: Array,
      default: function () {
        return [];
      }
    },
    flowParams: {
      type: Object,
      default: function () {
        return {};
      }
    },
    fileUploadAction: {
      type: Array,
      default: function () {
        return [];
      }
    },
    SuperiorThis: { // 上级this
      type: Object,
      default: function () {
        return {};
      }
    },
    CommonTablePopover: {
      type: Boolean,
      default: function () {
        return true;
      }
    },
    SelectionIsshow: { // 是否显示selection
      type: Boolean,
      default: function () {
        return true;
      }
    },
    islabResourceReport: {
      type: Boolean,
      default: function () {
        return false;
      }
    },
    MarkingIndex: Number
  },
  data () {
    return {
      newTableData: [],
      checkboxVal: [],
      formThead: [],
      keys: 1,
      currentStartIndex: 0,
      currentEndIndex: 20
    };
  },
  created () {
    let formThead = [];
    if (JSON.parse(this.cacheData.get(`${this.flowParams.ObjectUrlA}testCookie`)) && JSON.parse(this.cacheData.get(`${this.flowParams.ObjectUrlA}testCookie`)).length > 0) {
      // formThead = JSON.parse(this.$common.getCookie(`${this.flowParams.ObjectUrlA}testCookie`));
       formThead = JSON.parse(this.cacheData.get(`${this.flowParams.ObjectUrlA}testCookie`));
    } else {
      formThead = this.fileUploadAction;
    }
    for (let item in formThead) {
      this.checkboxVal.push(formThead[item].propName);
    }
    this.formThead = formThead;
    this.columnDrop();
  },
  methods: {
     columnDrop () {
              this.$nextTick(() => {
                this.sortable = Sortable.create(this.$el.querySelector('.body--wrapper>.vxe-table--header .vxe-header--row'), {
                  handle: '.vxe-header--column',
                  onEnd: ({ newIndex, oldIndex }) => {
                    let currRow = this.formThead.splice(oldIndex, 1)[0]
                    this.formThead.splice(newIndex, 0, currRow)
                  }
                })
              })
            },
  ConvertRows (data) {
      if (data) {
          let Data=data.split(/\n/g)
          //  Data = data.split(/[(\r\n)\r\n]+/);
          return Data;
      }
    },
    // 日期转换
    switchConsignDate (data) {
      if (data) {
        let NewData = new Date(data.replace("-", "/").replace("-", "/"));
        let y = NewData.getFullYear();
        let m = NewData.getMonth() + 1;
        let d = NewData.getDate()
        let dd = y + '-' + m  + '-' + d 
        return dd;
      }
    },
    selectFn (val) { // 选择数据
      this.$emit('selectFn', this.$refs.tableDataRef.selection);
      if(val.length === this.tableData.length) {
      this.numbers = [];
      this.tableData.forEach((item, i) => {
        this.numbers.push(i);
      })
    }
    if(val.length === 0) {
      this.numbers = [];
    }
    },
    openDetile (row, typeName) {
      console.log(9999, this.SuperiorThis.tabParme);
      // 编号
      let self = this.SuperiorThis; // 上级this
      let id = row.id;
      let parame = {};
      if (this.flowParams.openDetileParameter) {
        let Obj = this.flowParams.openDetileParameter;
        for (let item in Obj) { // 拼接 parame参数
          parame[item] = row[Obj[item]];
        }
      } else if (typeName) {
        parame = {
          objNumber: row,
          className: typeName
        };
      }else {
        parame = {
          id: id,
          ObjectUrlA: this.flowParams.ObjectUrlA,
          className: this.flowParams.className,
          url: this.flowParams.url
        };
      }
      console.log(888, parame, self);
      this.$common.openDetile(parame, self);
    },
    handelLoadmore (currentStartIndex, currentEndIndex) {
      this.currentStartIndex = currentStartIndex;
      this.currentEndIndex = currentEndIndex;
    }
  },
  watch: {
    checkboxVal (valArr) {
      this.formThead = this.fileUploadAction.filter(i => valArr.indexOf(i.propName) >= 0);
      // this.$common.setCookie(`${this.flowParams.ObjectUrlA}testCookie`, JSON.stringify(this.formThead), 1);
       console.log('this.formThead', this.formThead);
      this.cacheData.set(`${this.flowParams.ObjectUrlA}testCookie`, JSON.stringify(this.formThead))
      this.keys = this.keys + 1; // 为了保证table 每次都会重渲 In order to ensure the table will be re-rendered each time
    },
    MarkingIndex (val) {
      this.keys = this.keys + 1;
    }
  }
};
</script>

<style lang="scss">
  .CommonTable-wrapper{
    position: relative;
    .CommonTableKuang{
      border-left: 0px;
      padding: 0px 10px;
      position: absolute;
      right: 0px;
      height: 22px;
      top: -27px;
    }
     table{
            table-layout: fixed;
            transform-style:preserve-3d;
            td{
              background: #ffffff;
            }
            .warning-row{
              td{
              background: #e4e7ed;
            }
            }
          }
  }
  .labResourceReport-Table{
    .el-table{
        .el-table__body{
          .el-table__row{
            .cell{
              padding: 0px;
              height:21px;
              .labResourceReportBackground{
                background-color: #ebeef5;
              }
              .labResourceReportIshow{
                width: 100%;
                height: 21px;
                line-height: 21px;
                display: inline-block;
                padding: 0 10px;
              }
            }
            .el-table-column--selection{
              .cell:first-child{
                padding: 0 10px;
              }
            }
          }
        }
    }
  }
  /*添加*/
  .CommonTableelPopover_wrapper{
    max-height: 300px;
    overflow: auto;
    .CommonTable-checkboxGroup-wrapper{
      .el-checkbox{
        margin-left: 0px;
        margin-right: 30px;
      }
    }
  }
</style>
 楼主我想用自己自定义表格来写，按你的方法，表头拖动会错位，表身的数据不会改变

**Comment by Yourroot** [comment]
解决了，多谢楼主

**Comment by AprilTong** [comment]
> https://xuliangzhan.github.io/vxe-table/#/table/other/sortableColumn

链接404了
