### ISSUE TITLE
table切换数据，使用:optimization ="{scrollY: {gt: 50, oSize: 26, rSize: 30}}"滚动会出现，有时候渲染节点不hui

### ISSUE THREAD

**Issue by Yourroot** [xuliangzhan/vxe-table#144]
### 问题描述 Describe the bug

 ?

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/29765892/61343661-22d2d200-a881-11e9-8dcf-0b4bd0c8f883.png)

 ?
![image](https://user-images.githubusercontent.com/29765892/61343676-33834800-a881-11e9-8d31-fd7ece1a687e.png)

### 期望的结果 Expected behavior

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
建议更新到最新试下

**Comment by Yourroot** [comment]
table切换数据,滚动条的位置不对，现在出现空白页面，我现在解决方案是直接重新渲染表格
![image](https://user-images.githubusercontent.com/29765892/61515509-5d7d6b80-aa35-11e9-8c97-a7da669ae5bd.png)

**Comment by Yourroot** [comment]
就是table切换，比如100条数据，切换到200条数据，然后滚动滚动条，再进行多次切换后，就会有白屏现象。但是节点渲染出来了，就是滚动条的位置对应不上
