### ISSUE TITLE
您好，我想全量提交表格数据，如何全量获取数据？

### ISSUE THREAD

**Issue by dennissky** [xuliangzhan/vxe-table#145]
### 描述 Describe
目前看到的api，getTableData()是渲染后的数据，getInsertRecords插入的数据，getUpdateRecords更新后的数据，getRemoveRecords()是删除后的数据，如何获取目前表格存在的数据呢(修改后的全量数据,因为我的需求是需要将数据回显，这时候如果进行更新,getTableData()与getUpdateRecords()会出现重复数据）
 ?

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 版本 Version

- os: mojave
- browser: chrome
- vue: ?
- vxe-table: 最新

**Comment by xuliangzhan** [comment]
增删改的数据都有了，实在看不出还要什么数据？

**Comment by dennissky** [comment]
只是想获取当前表格修改后的数据。包括增改和老数据，不包括删，所能看见的数据。然后提交。如果没有的话要再自己过滤一下

**Comment by xuliangzhan** [comment]
getInsertRecords、getRemoveRecords、getUpdateRecords 增删改这不就是吗？

**Comment by frede2010** [comment]
getRecords()

**Comment by XiaoMuIns** [comment]
> 只是想获取当前表格修改后的数据。包括增改和老数据，不包括删，所能看见的数据。然后提交。如果没有的话要再自己过滤一下

兄弟这个搞定了吗，我也有这个需求。

**Comment by finchguo666** [comment]
你这个表格不能获取全量数据是吗，
如果不能获取全量数据，改数据的时候，没有主键，我如何更新指定数据库的表的行数据
