### ISSUE TITLE
希望tree-grid支持选checkRowKeys包含父节点的key

### ISSUE THREAD

**Issue by heshunwq** [xuliangzhan/vxe-table#147]
### 这个需求解决了什么问题 What problem does this feature solve
假设现在有一个父节点，两个子节点。
选择其中一个子节点。需要checkRowKeys中包含选中的子节点key和父节点的key。

### 建议的 API 是什么样的 What does the proposed API look like

可以在selectConfig中配置是否支持该模式。

### 是否已有其他不错的替代方案 Describe alternatives you've considered

没有

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: 1.7.1

**Comment by xuliangzhan** [comment]
该 bug 已修复，建议更新到最新试下

**Comment by heshunwq** [comment]
@xuliangzhan 我的需求可能没表达清楚，我仔细想了下，这个功能可能和已有选择有冲突。
需求改成：希望tree-grid支持父子选择状态不关联，参考ivew里tree的check-strictly属性（https://www.iviewui.com/components/tree）

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=checkStrictly
