### ISSUE TITLE
合并行的表格导出csv的格式问题

### ISSUE THREAD

**Issue by frede2010** [xuliangzhan/vxe-table#148]
### 描述 Describe
 合并行的表格在导出csv时，格式有问题，csv文件中不会合并行，并且出现空值。这个应该怎么解决？

### 版本 Version

- os: mac os 10.14.5
- browser: Chrome
- vue: 2.6.10
- vxe-table:  v2

**Comment by xlz26296** [comment]
js 中 cvs 是不支持合并的，你这个可以在后台导出或者使用 xlsx 导出表格 https://xuliangzhan.github.io/vxe-table/#/table/other/xlsx

**Comment by frede2010** [comment]
> js 中 csv 是不支持合并的，你这个可以在后台导出或者使用 xlsx 导出表格 https://xuliangzhan.github.io/vxe-table/#/table/other/xlsx

got it, thx
