### ISSUE TITLE
vxe-table 使用自定义模板,当前分页超过一百条，行高就被压缩

### ISSUE THREAD

**Issue by qq286674943** [xuliangzhan/vxe-table#1489]
当前页每页显示小于等于100条时
![image](https://user-images.githubusercontent.com/43396146/131060898-5f1e1faa-9573-4dea-8e88-e03b0097e91e.png)
显示正常
超过100条行高就被压缩
![image](https://user-images.githubusercontent.com/43396146/131060968-fc240916-9635-497e-93bb-c03e4f46da0f.png)

**Comment by pylist** [comment]
这个问题你的 解决了么

**Comment by qq286674943** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
