### ISSUE TITLE
删除行导致选中异常

### ISSUE THREAD

**Issue by Gumplefik** [xuliangzhan/vxe-table#15]
**问题描述 Describe the bug**
表格拓展功能删除行，当选中两行时，调用删除行后，再去选择数据，select-change时间返回的数据还包含已删除的数据

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - vxe-table: ?

**Comment by Gumplefik** [comment]
属于数据更新未检测到，删除时使用forceUpdate就行了

**Comment by xuliangzhan** [comment]
你可以更新到最新试下
