### ISSUE TITLE
vxe-table和vue-element-extends有何异同？

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vxe-table#150]
### 描述 Describe

这两个项目有什么共同点，不同点。

vxe-table支持编辑吗？

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
基础的功能两个都差不多的
vue-element-extends 是封装 element-ui 的，所有功能受限于 element-ui table
vxe-table 是基于 vue2.6+ 的表格，不依赖于任何 UI 组件，基本满足 table 常用的一切需求
