### ISSUE TITLE
 npm install xe-utils vxe-table 安装的源码table.js代码不是最新的

### ISSUE THREAD

**Issue by chengfei2994** [xuliangzhan/vxe-table#151]
npm install xe-utils vxe-table 安装的源码table.js代码不是最新的
最新代码是4160多行，但是我安装的版本是1.82，table.js代码是3600多行。
我是看到api文档gird的一个scrollToRow方法，现在没发使用。

**Comment by chengfei2994** [comment]
![image](https://user-images.githubusercontent.com/33825779/61608720-59945800-ac86-11e9-9b7f-7bd68694e27c.png)

**Comment by chengfei2994** [comment]
![image](https://user-images.githubusercontent.com/33825779/61609115-a0368200-ac87-11e9-89ee-eed55c003853.png)

**Comment by xlz26296** [comment]
你看的应该是 v2 的文档，用的是 v1 的包，v1 的文档看这里 https://xuliangzhan.github.io/vxe-table/v1/index.html#/table/api

**Comment by chengfei2994** [comment]
我看的是v2的，但是我按照文档安装的啊，那我怎么样才能安装上v2的包呢？

**Comment by xuliangzhan** [comment]
v2 没发布稳定版之前你可以通过指定版本号安装 npm install vxe-table@2.0.0-beta.15

**Comment by chengfei2994** [comment]
靠谱不大神，我这是收费软件额

**Comment by xuliangzhan** [comment]
不好说，看你运气吧 哈

**Comment by chengfei2994** [comment]
我先测测吧，你这个稳定的啥时候发，我是第一次用vue，遇到列拖动和自定义列的需求，然后就找到你这插件了，感觉你们更新版本也挺勤的。

**Comment by xuliangzhan** [comment]
只要不是很特别的需求，目前应该是稳定的

**Comment by chengfei2994** [comment]
好的大神威武
