### ISSUE TITLE
可编辑表格自定义组件每次编辑后会销毁实例吗

### ISSUE THREAD

**Issue by frede2010** [xuliangzhan/vxe-table#153]
### 描述 Describe

 我封装了一个树组件，其中有个created方法。然后在可编辑表格中的一行使用了此组件，并设置edit-render 的 type 为 default。使用后发现一个问题，每次编辑这个值，都会触发子组件的created方法，这是正常的吗？
![image](https://user-images.githubusercontent.com/16717330/61633530-e27cb500-acc1-11e9-9009-41876116b150.png)
![image](https://user-images.githubusercontent.com/16717330/61633664-27a0e700-acc2-11e9-9a8c-57bf933cc75d.png)

### 版本 Version

os: mac os 10.14.5
browser: Chrome
vue: 2.6.10
vxe-table: v1.8

**Comment by xuliangzhan** [comment]
是这样的
