### ISSUE TITLE
[Bug report] vxe-table拖拽有bug

### ISSUE THREAD

**Issue by djkloop** [xuliangzhan/vxe-table#154]
### 问题描述 Describe the bug

 拖拽只有列有效果，但是行里面的数据没有更新

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://github.com/djkloop/vxe-table-issues

### 报错信息或截图 Error message or screenshots

 // 拖拽前
![image](https://user-images.githubusercontent.com/21050914/61651132-d7d51680-ace7-11e9-82c7-d75ec43835ba.png)

// 拖拽后
![image](https://user-images.githubusercontent.com/21050914/61651151-df94bb00-ace7-11e9-8688-fd8ab7932581.png)

### 期望的结果 Expected behavior

 数据正确更新

### 版本 Version

- os: macOS Mojave 10.14.5
- browser: chrome 75.0.3770.142（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 1.9.0

**Comment by xuliangzhan** [comment]
固定列不允许拖动

**Comment by djkloop** [comment]
@xuliangzhan 
上次那个问题解决了 是我自己的问题不好意思- -。
但是我刚才更新了1.10版本的vxe-table好像合并列出现了bug
复现仓库地址：https://github.com/djkloop/vxe-table-issues
// 列改变前
![image](https://user-images.githubusercontent.com/21050914/61790816-d07a4e00-ae4a-11e9-86e8-b61a8814f9d1.png)
// 列改变后
![image](https://user-images.githubusercontent.com/21050914/61790840-dec86a00-ae4a-11e9-8a74-e568814b93ee.png)

// 浏览器刚开始控制台执行图
![image](https://user-images.githubusercontent.com/21050914/61790907-10413580-ae4b-11e9-8178-679532c950a0.png)

// 改变列后浏览器控制台执行图
![image](https://user-images.githubusercontent.com/21050914/61790983-37980280-ae4b-11e9-8060-59c5ec819823.png)

**Comment by xuliangzhan** [comment]
请使用在线链接 https://codesandbox.io/s/vue-template-916h0

**Comment by djkloop** [comment]
@xuliangzhan 
复现连接：https://codesandbox.io/s/vxe-table-ceshide-demo-f95po?fontsize=14

**Comment by xlz26296** [comment]
你代码中没有设置 column-key 吧 https://xuliangzhan.github.io/vxe-table/#/table/other/sortableColumn

**Comment by djkloop** [comment]
@xlz26296 emmm...你说的问题已经解决了... 现在的问题是 在点击了右上角的菜单改变列的情况后，最底下的合计行没有实时更新... 在点击了右上角的改变列操作 最后一行的合计没有了...

**Comment by xuliangzhan** [comment]
footer 触发的问题已修复，你可以更新到最新看下

**Comment by djkloop** [comment]
@xuliangzhan 

十分感谢~
