### ISSUE TITLE
vxe-grid BUG：[vxe-table] 缺少必要的 "show-header-overflow" 参数，这可能会导致出现错误

### ISSUE THREAD

**Issue by aurthurxlc** [xuliangzhan/vxe-table#1551]
**（必填）请填写问题描述或截图：**
目前测试下来，当列数超过 63 列时，标题就无法显示成多行，控制台报错：`[vxe-table] 缺少必要的 "show-header-overflow" 参数，这可能会导致出现错误`

我的部分 gridOptions ：

```
{
      resizable: true,
      showHeaderOverflow: false,
      showOverflow: true,
      highlightHoverRow: true,
      highlightHoverColumn: true,
      stripe: true,
      keepSource: false
}
```

**（必填）请填在线链接：**
暂无

**（必填）请填写期望的结果：**
无论列数是多少，都应该可以显示成多行

**（必填）请填写以下信息：**

- OS: MAC OS 11.6
- Browser: Chrome 94
- vue: 3.2.16
- vxe-table: 4.0.30

**Comment by YXYH-12138** [comment]
我也遇到了一样的问题

**Comment by YXYH-12138** [comment]
关掉列的虚拟滚动好像就没问题了
