### ISSUE TITLE
当使用服务器端排序时，新数据应如何加载？

### ISSUE THREAD

**Issue by fooleap** [xuliangzhan/vxe-table#157]
### 问题描述 Describe the bug

我采用服务器端排序时遇到了问题，但点击排序按钮时：

1. 若采用 `loadData()` 加载数据，排序状态得以保存，但 vxe-table 会对新数据进行排序。
2. 若采用 `reloadData()` 加载数据，排序状态将被重置（即不高亮）。

不知我是否操作有误？

### 能重现问题的链接 Reproduction link

[http://jsrun.pro/SYbKp/edit](http://jsrun.pro/SYbKp/edit)

### 报错信息或截图 Error message or screenshots

 如上。

### 期望的结果 Expected behavior

服务器端排序操作，使用 `loadData` 加载数据，保存排序状态的同时，不对新数据进行排序。

### 版本 Version

- os: Windows 7
- browser: 75.0.3770.142（64 位）
- vue: 2.6.10
- vxe-table: ?

**Comment by xuliangzhan** [comment]
操作  data 或 loadData 都是一样的行为
建议更新到最新试下
