### ISSUE TITLE
在input，对table进行数据搜索，table会出现白屏现象

### ISSUE THREAD

**Issue by Yourroot** [xuliangzhan/vxe-table#158]
### 问题描述 Describe the bug
滚动表格滚动条，输入搜索条件，但是当我把input的内容删除后，这时候数据全部都有，但是显示表格是白屏的

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
链接：
 http://jsrun.pro/SybKp/edit

### 报错信息或截图 Error message or screenshots

 ?

### 期望的结果 Expected behavior

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
建议更新到最新试下
