### ISSUE TITLE
可编辑表格中，如何通过js改变某个单元格的值？

### ISSUE THREAD

**Issue by frede2010** [xuliangzhan/vxe-table#159]
### 描述 Describe

 可编辑表格中，新增一行，第一列是个下拉框，现需要根据选择下拉框中的值自动给后面几列设值，API中有关于在vue中直接操作指定列数据的方法吗？

### 版本 Version

os: mac os 10.14.5
browser: Chrome
vue: 2.6.10
vxe-table: v1.8

**Comment by xuliangzhan** [comment]
vue 的都是数据驱动，根据对应逻辑去操作数据即可

**Comment by frede2010** [comment]
> vue 的都是数据驱动，根据对应逻辑去操作数据即可

但是新插入的行不在data 中，如何操作到指定的这个新增的行列的数据呢？我现在是通过浅度克隆的原理在方法中改变行参达到改变实参的目的。不知道这样的做法正不正确

**Comment by xlz26296** [comment]
插入后不是返回 row 吗

**Comment by frede2010** [comment]
> 插入后不是返回 row 吗

不是在插入里面做的。插入后里面有个下拉框，根据下拉框选择不同的值去设置后面几列的默认值

**Comment by xuliangzhan** [comment]
那不还是 row 吗，下拉框 change 后就去改对应列的值

**Comment by frede2010** [comment]
> 那不还是 row 吗，下拉框 change 后就去改对应列的值

这个解决了，还有个其他问题。getTableData这个方法的`visibleData ` 是返回什么值？API上写的是可视的数据，但是insert新增一条数据后，visibleData缺失是空的

**Comment by frede2010** [comment]
> 那不还是 row 吗，下拉框 change 后就去改对应列的值

这个解决了，还有个其他问题。getTableData这个方法的visibleData 是返回什么值？API上写的是可视的数据，但是insert新增一条数据后，visibleData缺失是空的 @xuliangzhan

**Comment by xuliangzhan** [comment]
insert 数据的获取正确途径是 getInsertRecords，v1.11+ fullData 将包含完整数据

**Comment by frede2010** [comment]
thx，升级后OK了
