### ISSUE TITLE
使用<keep-alive>后，再动态组件里面有空白

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#16]
在keep-alive里面的vxe-table，滚动到其他位置再切换回来，是空白。如图（因子集是一个表格），先垂直滚动vxe-table到一定的位置，然后切换其他的tab，再点回来，vxe-table显示的空白，
![微信截图_20190521211901](https://user-images.githubusercontent.com/11676609/58099462-43c6d000-7c0e-11e9-8d94-4c10760b7b6a.png)
`
 <keep-alive>
      <component
        :is="currentView"
        ref="dComponent"
      />
    </keep-alive>

`

**Comment by xuliangzhan** [comment]
如果表格会被隐藏的场景下，你应该在显示之后调用 recalculate 方法重新计算

**Comment by YuanQGit** [comment]
我也有同样的问题，老哥有解决办法嘛

**Comment by xuliangzhan** [comment]
@YuanQGit  尝试调用 recalculate 方法重新计算，也不行吗？

**Comment by YuanQGit** [comment]
@xuliangzhan 是的大佬，也不行。能否考虑修复这个bug呢？

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的[链接](https://jsrun.net/vIyKp/edit)

**Comment by qiuliang1108** [comment]
@[xuliangzhan](https://github.com/xuliangzhan) recalculate 这个是可以解决空白问题的，但是滚动条的位置会发生变化
