### ISSUE TITLE
给表格添加highlightHoverRow会触发formatter对应的回调函数

### ISSUE THREAD

**Issue by guaijie** [xuliangzhan/vxe-table#160]
### 描述 Describe
给表格添加highlightHoverRow后鼠标悬浮表格会触发所有formatter对应的回调函数
同时不管是否添加highlightHoverRow，点击表格都会触发所有formatter对应的回调函数

### 版本 Version

- os: windows
- browser: 谷歌
- vue: 2.6.1
- vxe-table: 1.7.8

**Comment by xuliangzhan** [comment]
是这样的，你可以使用 v2，内部优化更好

**Comment by guaijie** [comment]
请问下版本2稳定吗

**Comment by xuliangzhan** [comment]
v2是优化版，目前v1稳定版
