### ISSUE TITLE
悬浮单元格时会重新渲染该单元格，点击单元格时会重新渲染整个表格

### ISSUE THREAD

**Issue by guaijie** [xuliangzhan/vxe-table#162]
### 问题描述 Describe the bug
悬浮单元格时会重新渲染该单元格，点击单元格时会重新渲染整个表格，可以通过为列添加formatter,并在formatter中打印日志来看渲染效果

### 期望的结果 Expected behavior
除非主动刷新，否则不重新渲染表格

### 版本 Version

- os: window7
- browser: 谷歌
- vue: 2.6.10
- vxe-table: 2.0.1

**Comment by xuliangzhan** [comment]
vue 运行机制是监听虚拟 Dom 的变化，虚拟 Dmo 由数据循环得到，渲染由 vue 缓存决定，你这个需求应该使用非 vue 框架的 table

**Comment by guaijie** [comment]
element-ui没有啊，该table只要触发了它有的事件就会重新渲染，这显然不合理吧

**Comment by xuliangzhan** [comment]
可能 element-ui 的功能比较强吧 哈
你可以用优化版 v2
或者期待 v3 的性能重构
有优化建议请提供重现问题的链接，不符合问题的要求将被关闭
