### ISSUE TITLE
安装了运行报错：Unknown custom element:<elx-editable>

### ISSUE THREAD

**Issue by garysun90** [xuliangzhan/vxe-table#167]
main.js 里

import VXETable from 'vxe-table'
import 'vxe-table/lib/index.css'
  Vue.use(VXETable)

运行起来报错：Unknown custom element: <elx-editable>did you register the component correctly

**Comment by xuliangzhan** [comment]
哪来的 elx-editable ？这是 vue-element-extends 组件的吧，不是这个
