### ISSUE TITLE
后台指定tableProxy配置

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#169]
### 这个需求解决了什么问题 What problem does this feature solve

如果:proxy-config 是从后台获取，配置里面不方便写函数体，如果能指定执行的函数名，则非常方便。

### 建议的 API 是什么样的 What does the proposed API look like
  proxyConfig.ajax中的query，delete，save 可以指定一个函数名，如
  data() {
    return {
      tableProxy: {
        props: { result: "list", total: "total" },
        ajax: {
          query: "getData"，
          delete: "del",
          save: "save"
        }
      }
}
},
  methods: {
  getData({ page, sort, filters }）{
   .......
  }
}

### 版本 Version

- os: windows 7
- browser: chrome
- vue: 2.6.10
- vxe-table:  master

**Comment by xlz26296** [comment]
你都已经拿到配置了，那就直接返回 this.getData 不就行了？

**Comment by jianliulin** [comment]
getData 不是固定唯一的，后台根据数据库判断后可能是 getData或getData2 ，如果让前台来判断，那代价就很大了，

**Comment by xlz26296** [comment]
为啥要判断？
```
let key = 'getData'
tableProxy.ajax = {query: this[key]()}
```

**Comment by xuliangzhan** [comment]
你应该在 js 自行处理

**Comment by jianliulin** [comment]
Vue里赋值一个字符串的函数名就会执行此函数普遍存在，也是非常亲民的一个功能，既然觉得不合理就略过...
