### ISSUE TITLE
表格设置selection时，需要禁用某一行进行选中

### ISSUE THREAD

**Issue by jieme** [xuliangzhan/vxe-table#17]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
在表格列为选择列时候，需要禁止选择当前行选中操作，是否有相关参数属性？
全选的时候禁止某一行选中的列，不在选中的范围内。

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
建议更新到最新可以支持该功能

**Comment by jieme** [comment]
很好用非常感谢，有个性能优化的小问题，使用了checkMethod后，鼠标移动到表格每一行列表都会重新对表格行中的记录进行执行一次checkMethod方法。
