### ISSUE TITLE
 @current-change="currentChangeEvent">  用这个事件会触发两次不知道为什么？

### ISSUE THREAD

**Issue by chinabomb** [xuliangzhan/vxe-table#170]
### 描述 Describe
点一行，currentChangeEvent会输出2行一样的数据，看官网上的例子没有问题，不知为何？
      <vxe-table
        ref="xTable"
        :loading="tableData.loading"
        :mouse-config="{selected: true}"
        :data.sync="tableData.rows"
        border
        class="vxe-table-element"
        resizable
        auto-width
        fit
        highlight-hover-row
        highlight-current-row
        @current-change="currentChangeEvent"
      >

 currentChangeEvent({ row }) {
     console.log(row.id)
    },

### 版本 Version

- os: ?
- browser: ?
- vue: 2.6.10
  "vxe-table": "^1.11.3",
    "vxe-table-plugin-element": "^1.2.1",
    "xe-utils": "^1.9.7"

**Comment by chinabomb** [comment]
问题重现链接 http://47.100.242.230/     
源码地址http://47.100.242.230.rar

**Comment by xuliangzhan** [comment]
请使用正确的在线链接 https://codesandbox.io/s/vue-template-916h0

**Comment by chinabomb** [comment]
谢谢
