### ISSUE TITLE
排完序之后能否在tableData中获取到数据

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#173]
### 这个需求解决了什么问题 What problem does this feature solve
获取排完序的数据便于处理
 ?

### 建议的 API 是什么样的 What does the proposed API look like
![image](https://user-images.githubusercontent.com/30314164/62118358-1ffbc680-b2f0-11e9-93f9-896a6a56e6ad.png)

getTableData()
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
getTableData 这个就可以表格数据

**Comment by wekerSnail** [comment]
确实可以，感谢
