### ISSUE TITLE
请问下如何修改 sort列排序默认的展示样式？  

### ISSUE THREAD

**Issue by psyche0401** [xuliangzhan/vxe-table#174]
### 描述 Describe
请问下如何修改 sort列排序默认的展示样式 ? 或是在排序事件在哪里可以改动？
 ?

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by psyche0401** [comment]
![image](https://user-images.githubusercontent.com/41417829/62188252-627bdc80-b39e-11e9-8d0b-3f0a2ee10fa8.png)
![微信截图_20190731141804](https://user-images.githubusercontent.com/41417829/62188264-6ad41780-b39e-11e9-9590-c36647be567a.png)

我想修改这个样式

**Comment by xuliangzhan** [comment]
这个你用列头自定义模板不就可以实现了
