### ISSUE TITLE
表格错行错列

### ISSUE THREAD

**Issue by sunscheung** [xuliangzhan/vxe-table#175]
### 表格错行错列

 当使用固定行列属性fixed时，表格渲染错行错列
### 报错信息或截图 
官网demo:
https://xuliangzhan.com/vxe-table/index.html#/table/base/fixed

### 期望的结果 Expected behavior

 错行错列不出现

### 版本 Version

- os: windows 7
- browser: chrome
- vue: 2.5.6
- vxe-table: 1.11.4

**Comment by sunscheung** [comment]
@xuliangzhan  我的是在chrome浏览器下看的
http://jsrun.pro/TrXKp/edit?v=2

![38c66b3c26c091138671147a358bc9e](https://user-images.githubusercontent.com/9931345/62189876-b4266600-b3a2-11e9-8f8f-a1c2feecad79.png)
![e0edf4ccbdaf3db850a046e75fd090c](https://user-images.githubusercontent.com/9931345/62189882-b688c000-b3a2-11e9-8e39-a577676f23af.png)

**Comment by sunscheung** [comment]
补充： chrome版本 75.0.3770.142
浏览器缩放到80%及以下  错行 错列 会消失。
这个是和分辨率有关系吧.....

**Comment by xuliangzhan** [comment]
只支持标准的 100% 缩放

**Comment by sunscheung** [comment]
@xuliangzhan  就是100%情况下有问题，在100%情况下错位。
但是 在火狐浏览器里没有此问题。
表头和body区域是分在两个table中的，是否是由于表头里没有用td，而body区域里用的是td呢

**Comment by xuliangzhan** [comment]
我这边没发现有不对齐的情况，你截个gif看下

**Comment by niyongdianxinjiuxing** [comment]
我也发现了，列的错位现象

**Comment by niyongdianxinjiuxing** [comment]
大分辨率的屏，就会出现

**Comment by Gumplefik** [comment]
![12312](https://user-images.githubusercontent.com/19474332/63093634-9f4bf400-bf98-11e9-9cf3-87e612eda5cb.jpg)
FIX 时滚动数据行对应不上

**Comment by xuliangzhan** [comment]
有问题请按规范提供重现链接来描述问题

**Comment by jieme** [comment]
> @Gumplefik 有问题请按规范提供重现链接来描述问题


此问题我也遇见过，右侧固定列表，并在右侧固定列表中自定义设置样式导致的，我的原因是使用了iview的button组件，设置
`<template v-slot="{ row, rowIndex }">
<Button size="small" >删除</Button>
</template>`
由于Iview中的 Button 样式内使用了padding样式，导致每一行都多1一个像素。所以看看你的样式中是否使用了padding导致样式的冲突。

**Comment by jieme** [comment]
> ![12312](https://user-images.githubusercontent.com/19474332/63093634-9f4bf400-bf98-11e9-9cf3-87e612eda5cb.jpg)
> FIX 时滚动数据行对应不上

此问题我也遇见过，右侧固定列表，并在右侧固定列表中自定义设置样式导致的，我的原因是使用了iview的button组件，设置
```
<template` v-slot="{ row, rowIndex }"> 
<Button size="small" >删除</Button> 
</template>
```
由于Iview中的 Button 样式内使用了padding样式，导致每一行都多1一个像素。所以看看你的样式中是否使用了padding导致样式的冲突。

**Comment by niyongdianxinjiuxing** [comment]
谢谢，我来试一试

 



------------------ 原始邮件 ------------------
发件人: "jieme"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 中午11:39
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "stars"<452589607@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] 表格错行错列 (#175)



 

 FIX 时滚动数据行对应不上
  
此问题我也遇见过，右侧固定列表，并在右侧固定列表中自定义设置样式导致的，我的原因是使用了iview的button组件，设置
 <template` v-slot="{ row, rowIndex }">  <Button size="small" >删除</Button>  </template>  
由于Iview中的 Button 样式内使用了padding样式，导致每一行都多1一个像素。所以看看你的样式中是否使用了padding导致样式的冲突。
