### ISSUE TITLE
如何点击筛选按钮后直接弹出element日期选择框，选择后马上筛选

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#176]
### 描述 Describe
column的配置如下：
      {
         "align" : "center",
         "field" : "BillDate",
         "filterRender" : {
            "name" : "ElDatePicker",
            "props" : {
               "clearable" : false,
               "format" : "yyyy-MM-dd",
               "type" : "daterange",
               "valueFormat" : "yyyy-MM-dd"
            }
         },
         "filters" : [
            {
               "data" : ""
            }
         ],
         "headerAlign" : "center",
         "remoteSort" : true,
         "sortable" : true,
         "title" : "凭证日期",
         "width" : 100
      }
1. 弹出el-date-picker并选择日期范围后筛选，filters中的values[0]=undefined
2.如果  filterMultiple=false ,则不显示筛选的漏斗按钮。

有没有办法，不显示el-date-picker，直接就弹出选择日期筛选，日期范围存到values？

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 版本 Version

- os: ? win7
- browser: ? chrome
- vue: ? 2.6.10
- vxe-table: ? 2.05

**Comment by xuliangzhan** [comment]
I'm sorry，无法支持，这个需要被渲染的组件支持才能实现；你可以通过自定义列头实现，在列头放个 el-date-picker

**Comment by jianliulin** [comment]
demo:
[https://codesandbox.io/s/vxe-table-ceshide-demo-bfvnb?fontsize=14](url)

请留意console.log(query.filters[0]); 打印出来的值：
{
column: ColumnConfig
field: "date"
prop: "date"
values: Array[1]
     0: undefined
}
预期values应该是日期范围，现在是空

**Comment by xuliangzhan** [comment]
自定义筛选的方式不是取 values ，而是取 datas
建议更新到最新看下 https://jsrun.pro/dwbKp/edit
