### ISSUE TITLE
API中的某些方法貌似没有

### ISSUE THREAD

**Issue by oliujunk** [xuliangzhan/vxe-table#18]
**描述 Describe**
vxe-table api 中的getAllRecords()，getSelectRecords()不可用
electron 下使用

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: electron: 2.0.4
 - vue: 2.5.16
 - vxe-table: 0.7.3

**Comment by xuliangzhan** [comment]
0.7.3是没有的，这是后面新加的方法

**Comment by oliujunk** [comment]
谢谢解答，这个挺好用的，期待持续更新
