### ISSUE TITLE
添加highlightCurrentRow无效果

### ISSUE THREAD

**Issue by guaijie** [xuliangzhan/vxe-table#181]
### 问题描述 Describe the bug
添加highlightCurrentRow，点击行没有显示高亮，查看控制台没有在行上添加class类‘current-row’，

我在基础上重新对vxe-table进行封装，并且改写类默认的props
props: {
    ...Grid.props,
    highlightHoverRow: {
      type: Boolean,
      default: true
    },
    stripe: {
      type: Boolean,
      default: true
    },
    highlightCurrentRow: {
      type: Boolean,
      default: true
    }
  }

改写后对v1有效，对v2 ：highlightCurrentRow无效

### 期望的结果 Expected behavior

 显示高亮效果

### 版本 Version

- os: window7
- browser: 版本 75.0.3770.142（正式版本） （64 位）
- vue: 2.10.6
- vxe-table: 2.0.5

**Comment by xlz26296** [comment]
这些参数都支持设置全局默认的 setup
