### ISSUE TITLE
能否将vxe-table 所以配置都放到一个对象里面

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#182]
### 这个需求解决了什么问题 What problem does this feature solve

能否将vxe-table 所有配置都放到一个对象里面，因为很多页面，要添加一个新的属性，就必须
到每个table上添加一次，如果所有的配置都在一个对象上面则非常方便
    <vxe-grid ref="vxTable" 
   :pager-config="table.pagerConfig" 
   :border="table.border" 
   :resizable="table.resizable" 
   :row-id="table.rowId" 
  :height="table.height" 
  :columns="table.columns"
  :remote-filter="table.remoteFilter" 
  :remote-sort="table.remoteSort" 
  :header-align="table.headerAlign"
  :edit-config="table.editConfig" 
  :toolbar="table.toolbar" 
  ......
  >
 可以简化为  <vxe-grid ref="vxTable"    :config ="table"  >

### 建议的 API 是什么样的 What does the proposed API look like

    <vxe-grid ref="vxTable"    :config ="table"  >

   另外希望在tableColumn 添加一个object类型的other 属性，方便用户存放自定义数据

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

### 版本 Version

- os: ? win7
- browser: ? chrome
- vue: ?  2.6.10
 xe-tal: ? 2.0.5

**Comment by xuliangzhan** [comment]
<vxe-grid ref="vxTable"  v-bind="table"  >
