### ISSUE TITLE
ajax 请求，params如何额外添加自定义参数传递给服务器

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#183]
问题如上标题

**Comment by xuliangzhan** [comment]
ajax 要什么参数自行处理不就行了？

**Comment by longa30** [comment]
外部的值传给table作为ajax请求参数

**Comment by xuliangzhan** [comment]
为啥不用 vue 的 data

**Comment by longa30** [comment]
明白了，谢谢！

**Comment by longa30** [comment]
![image](https://user-images.githubusercontent.com/17867961/62302560-27b49a00-b4ad-11e9-9e5e-25f8c879358d.png)

**Comment by xlz26296** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/grid/api?filterName=commitProxy
