### ISSUE TITLE
你好，表格编辑渲染select的时候options列表可以配置吗？

### ISSUE THREAD

**Issue by NIeeeeee** [xuliangzhan/vxe-table#184]
:edit-render="{name: 'ElSelect', options: sexList, optionProps: {label: 'spell', value: 'value'}}"
这个是拷贝你的例子里的代码。

例如我的options数据不是标准的[{ label: '', value: ''’}]形式。可能是个对象，value是对象的key值，label就是本身。这样的话请问可以自己配置吗？

**Comment by xuliangzhan** [comment]
是配置的

**Comment by NIeeeeee** [comment]
那我如果源数据是{  ‘0’: ‘x’, ‘1’: ‘xx’, '2': 'xxx' } ，那我的optionProps要怎么写呀。麻烦你了~ 求告知

**Comment by xlz26296** [comment]
下拉数据是个数组

**Comment by liyyihui** [comment]
你好我 配置了 但是不显示 要点击了才能显示出来 { field: 'SysnatureName',
    title: '应用性质',
    width: 120,
    editRender: { name: 'ElSelect',
      options: [],
      optionProps: {value: 'Sysnature', label: 'Sysnaturename'}
    }
  }  我获取到后台数据 后根据值去取应该显示的值  但是 没用显示出来  一点击 就显示出来 用的vxe-grid

**Comment by liyyihui** [comment]
你好我 配置了 但是不显示 要点击了才能显示出来 { field: 'SysnatureName',
    title: '应用性质',
    width: 120,
    editRender: { name: 'ElSelect',
      options: [],
      optionProps: {value: 'Sysnature', label: 'Sysnaturename'}
    }
  }

**Comment by xlz26296** [comment]
你应该使用在线链接来说明问题 https://codesandbox.io/s/vue-template-916h0

**Comment by liyyihui** [comment]
import Vue from "vue";
import App from "./App.vue";
import VXETable from "vxe-table";
import VXETablePluginElement from "vxe-table-plugin-element";

import "vxe-table/lib/index.css";
import "vxe-table-plugin-element/dist/style.css";
Vue.use(VXETable);
VXETable.use(VXETablePluginElement);
Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");  保存保存  说我没用被授权

**Comment by xuliangzhan** [comment]
@liyyihui  随便一个地址，点保存就行了
