### ISSUE TITLE
toolbar的配置项能否像tableColumn一样支持使用插件

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#189]
### 这个需求解决了什么问题 What problem does this feature solve

toolbar的配置项能否像tableColumn一样支持使用插件，可以editRender: { name: 'input' }，
可以渲染element，iview等控件

### 建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
啥意思？这是工具栏搞什么渲染？

**Comment by jianliulin** [comment]
从官网的demo看到目前 table 的toolbar配置如下：
              toolbar: {
                buttons: [
                  { code: 'reload', name: 'app.body.button.refresh' },
                  { code: 'insert_actived', name: '新增并激活' },
                  { code: 'myBtn', name: '自定义按钮' }
                ],
                resizable: {  storage: true  },
                setting: {   storage: true    }
              },

希望toolbar的功能更强大一点，能使用插件（如嵌入element 等第三方控件），希望能改成
toolbar: {
     buttons: [
      { code: 'aaa', editRender: {name: "ElDatePicker", props: {type: "date"}, autofocus: true} },
      { code: 'reload', editRender: {name: "ElButton", props: {type: "primary" ，title:'刷新'}} },
      { code: 'xxxx', editRender: {name: "ElButton", props: {type: "primary"，title:'自定义按钮'}} }
      ],
      resizable: {  storage: true  },
      setting: {   storage: true    }
},
以便达到类似下面的效果
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/elementPage

**Comment by xuliangzhan** [comment]
sorry, 由于这个需求不利于扩展，不会考虑支持，请使用 slot
