### ISSUE TITLE
多表头尾行合计显示错乱

### ISSUE THREAD

**Issue by wfh822** [xuliangzhan/vxe-table#19]
**问题描述 Describe the bug**
多表头尾行合计显示错乱，看了下尾行合计代码，rowspan取的都是表头所占的行数

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
建议你更新试下
