### ISSUE TITLE
activeMethod  没走这个方法

### ISSUE THREAD

**Issue by liyyihui** [xuliangzhan/vxe-table#191]
activeMethod      :edit-config="{trigger: 'click', mode: 'row',activeMethod,showStatus:true }"
   配置了没用走回调方法

**Comment by zxWendy** [comment]
请问如何解决的？遇到了同样的问题，根本没有进入activeMethod方法

**Comment by liyyihui** [comment]
换  不要用那个  就用它基本的那个 vxe-table




------------------ 原始邮件 ------------------
发件人: "Wendy Zhang"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 下午5:45
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] activeMethod  没走这个方法 (#191)




请问如何解决的？遇到了同样的问题，根本没有进入activeMethod方法

**Comment by zxWendy** [comment]
好的，感谢，试试去!

**Comment by musktang** [comment]
> 好的，感谢，试试去!

怎么样啊，必须弃用grid吗？

**Comment by liyyihui** [comment]
我是&nbsp; 自己 直接用的vxe-table&nbsp; &nbsp;来再次封装成一个 组件&nbsp; 来操作的 没用grid




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "musktang"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午2:48
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 
抄送: "lllll "<945131558@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuliangzhan/vxe-table] activeMethod  没走这个方法 (#191)



 
好的，感谢，试试去!
  
怎么样啊，必须弃用grid吗？

**Comment by musktang** [comment]
能不能分享一下实现的代码？😂

**Comment by musktang** [comment]
> 我是&nbsp; 自己 直接用的vxe-table&nbsp; &nbsp;来再次封装成一个 组件&nbsp; 来操作的 没用grid
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "musktang"<notifications@github.com&gt;; 发送时间: 2019年11月6日(星期三) 下午2:48 收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 抄送: "lllll "<945131558@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [xuliangzhan/vxe-table] activeMethod 没走这个方法 (#191) 好的，感谢，试试去! 怎么样啊，必须弃用grid吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

能不能分享一下实现的代码？😂

**Comment by liyyihui** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"musktang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午2:56
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"lllll "<945131558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] activeMethod  没走这个方法 (#191)



 
我是&nbsp; 自己 直接用的vxe-table&nbsp; &nbsp;来再次封装成一个 组件&nbsp; 来操作的 没用grid
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "musktang"<notifications@github.com&gt;; 发送时间: 2019年11月6日(星期三) 下午2:48 收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 抄送: "lllll "<945131558@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [xuliangzhan/vxe-table] activeMethod 没走这个方法 (#191) 好的，感谢，试试去! 怎么样啊，必须弃用grid吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
能不能分享一下实现的代码？😂

**Comment by Heisenberg-Mr** [comment]
@liyyihui 意思自己写一个activeMethod？😂 怎么写，可以参考一下你的写法吗

**Comment by liyyihui** [comment]
&nbsp; &nbsp;不是&nbsp; 发了你文件了吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Heisenberg-Mr"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午3:08
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 
抄送: "lllll "<945131558@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xuliangzhan/vxe-table] activeMethod  没走这个方法 (#191)




@liyyihui 意思自己写一个activeMethod？😂 怎么写，可以参考一下你的写法吗

**Comment by Heisenberg-Mr** [comment]
@liyyihui  写成这句就行？您这个哪里定义了禁止哪一列编辑？恳请指教。
activeMethod :edit-config="{trigger: 'click', mode: 'row',activeMethod,showStatus:true }"

不过我在另一个例子看到下面这个做法，感觉能行。
        <vxe-table-column field="name" title="Name" :edit-render="{name: 'ElInput', props:{disabled: true} }">

**Comment by liyyihui** [comment]
activeMethod&nbsp; &nbsp;这是 个 函数&nbsp; &nbsp; 通过你自己返回 true&nbsp; &nbsp;false&nbsp; &nbsp;就控制编辑与不能编辑






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Heisenberg-Mr"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午3:17
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 
抄送: "lllll "<945131558@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xuliangzhan/vxe-table] activeMethod  没走这个方法 (#191)




@liyyihui  写成这句就行？您这个哪里定义了禁止哪一列编辑？恳请指教。
 activeMethod :edit-config="{trigger: 'click', mode: 'row',activeMethod,showStatus:true }"
 
不过我在另一个例子看到下面这个做法，感觉能行。

**Comment by Heisenberg-Mr** [comment]
@liyyihui   
😂谢谢指教，我是这么实现的，但是只能禁止整列，您那个能不能代码多拷贝一点，我不知道您那个源代码是啥样的。实在太菜，不是很明白您的解释。
`tableColumn:[{ field: 'age', title: 'Z', width: 160, editRender: { name: 'ElInputNumber', props: { max: 35, min: 0, disabled: true } } },]`
