### ISSUE TITLE
希望在column的配置中可以配置此列的内容是否为超链接

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#192]
### 这个需求解决了什么问题 What problem does this feature solve

希望在column的配置中可以配置此列的内容是否为超链接， 点击超链就执行某个函数
        <vxe-grid
          border
          resizable
          height="300"
          :columns="tableColumn"
        @column-cell-hyperlink-click=“columnCellHyperlinkClick” >

</vxe-grid>

export default {
          data () {
            return {
              tableColumn: [
                { type: 'index', width: 50 },
                { field: 'name', title: '姓名',hyperlink { params : { url : 'aaa.com',  name : 'ddd' } },
                { field: 'address', title: '地址' }
              ]
            }
  },
 methods: {
 columnCellHyperlinkClick({ row, rowIndex, column, columnIndex}, event) {
              console.log(`超链接单元格点击${column.hyperlink.params.url  }`)
            },
}
}

### 建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
请使用 slot 自定义模板
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/template

**Comment by jianliulin** [comment]
这个功能对于选择用配置的人来说很实用，添加也不会破坏或污染现有功能，

**Comment by xuliangzhan** [comment]
你没明白我的意思，因为渲染器本身可以抽象一切可复用的功能，本身就包含你的这个需要
