### ISSUE TITLE
合并行+全键盘操作问题

### ISSUE THREAD

**Issue by JiaJunLee** [xuliangzhan/vxe-table#193]
### 问题描述 Describe the bug

合并行后使用Tab键切换cell，当切换到隐藏的cell，任意输入后出现Error

### 报错信息或截图 Error message or screenshots

![2019-08-05 16_17_16-error-1](https://user-images.githubusercontent.com/25827340/62449531-ff72b700-b79c-11e9-8be4-9ad4f1f4211f.png)
![2019-08-05 16_17_16-error-2](https://user-images.githubusercontent.com/25827340/62449545-05689800-b79d-11e9-8789-0f5dca31f1e5.png)

### 版本 Version

- os: Windows 10
- browser: Chrome x64 75.0.3770.142
- vue: v2.5.21
- vxe-table: v1.11.11

**Comment by JiaJunLee** [comment]
使用 VXETable keyboard-config参数中的 **editMethod** 方法对cell进行判空可以避免报错，但使用体验并不好，貌似背地依旧选中了被合并的隐藏cell

**Comment by xuliangzhan** [comment]
即使是合并了，实际上切换也是会移动到那个位置的
