### ISSUE TITLE
怎么使用vue的render函数渲染

### ISSUE THREAD

**Issue by lemovel** [xuliangzhan/vxe-table#194]
才用的是这种方式的render  
`render: (h, params) => {
                            return h('Input', {
                                props: {
                                    type: 'number',
                                    number: true,
                                    value: params.row.qty
                                },
                                on: {
                                    'on-blur': (event) => {
                                        let targetQty = event.target.value;
                                        params.row.qty = targetQty;
                                        this.goodsData[params.index].qty = targetQty;
                                        this.countSkuQtyAndBatterType();
                                    }
                                }
                            });
                        }`

**Comment by xuliangzhan** [comment]
请先看文档
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/template
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/template

**Comment by lemovel** [comment]
我看了，我之前是用iview的columns的render，现在想集成iview的返回数据，我这个render是上面那样的，我想请问有方法能集成吗？谢谢您，好人一生平安

**Comment by xuliangzhan** [comment]
有问题请按规范的提问题，提供问题链接

**Comment by 191895011** [comment]
你好 问题解决了,
