### ISSUE TITLE
数据量大的时候，渲染完非常卡顿，选中和编辑都非常卡

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#197]
### 描述 Describe
使用的elem的集成，数量大的时候渲染完非常的卡，大概上百条就会比较卡了
 ?

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
重现链接
https://jsrun.pro/WVbKp/edit

**Comment by xlz26296** [comment]
大数据量干嘛不启用虚拟滚动？

**Comment by wekerSnail** [comment]
我有启用啊，配置都是参照的大数据demo那块写的，可以看链接代码

**Comment by xlz26296** [comment]
你把 gt 改成 200 就行了

**Comment by wekerSnail** [comment]
确实有改善，顺便问一句这个gt的范围指的是条数吗，还是指的高度

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62517325-c64c4c80-b859-11e9-849f-9346298b9ddf.png)
另外饿了么的控件会超宽，是bug吗

**Comment by xlz26296** [comment]
gt是条数，使用2.0是可以更快
样式问题你可以根据文档搞，要么用插件要么自行实现样式兼容

**Comment by wekerSnail** [comment]
好的，感谢
