### ISSUE TITLE
如何配置能让右键快捷菜单，鼠标在cell上时候才弹出来

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#198]
### 描述 Describe
vxe-table 2.0.3版本body的快捷菜单只有鼠标在cell上时候才弹出来，在空白的地方点击是不弹出快捷菜单的，后来版本变成了，只要是table的body上右键点击都会弹出快捷菜单，如果配置才能让新版必须在cell上右键才弹出快捷菜单，另外没有配置让鼠标右键时候选中当前行，
目前在cell-context-menu 中this.$refs.vxTable.setCurrentRow(row) 设置选中，如果能有个属性设置右键是否选中当前行就更好了。

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-13zfj?fontsize=14

### 报错信息或截图 Error message or screenshots

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
不需要设置，新版更灵活，判断 params.row 如果有就是在cell中右键，如果没有就是在空白处右键

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=trigger

**Comment by jianliulin** [comment]
更新到2.0.16 后可以了，谢谢！！
