### ISSUE TITLE
右键快捷菜单怎么获取到剪切板数据

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#199]
### 描述 Describe
使用原来原生的方法无法获取到剪切板数据，
![image](https://user-images.githubusercontent.com/30314164/62524139-b0458880-b867-11e9-8df1-a7735a95a37c.png)
vxe的右键event没有clipboardData

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
右键实现粘贴功能，不知道怎么获取到复制的数据

**Comment by xuliangzhan** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/ClipboardEvent/clipboardData

**Comment by wekerSnail** [comment]
通过绑定onpaste事件是可以获取到clipboardData的，但是通过vxe的右键菜单不知道怎么获取到clipboardData，我看demo里面的粘贴也没有写具体的实现，只是alter了一个粘贴，这里确实不太懂，怎么通过context-menu-click事件获取到数据，求教大神

**Comment by xuliangzhan** [comment]
这个和表格没关系哦，你应该去看js的文档，只有粘贴相关事件中才能有权限获取内容的

**Comment by wekerSnail** [comment]
可能是我表述的不太清楚，我的意思是我如何把粘贴事件绑定到表格的右键菜单上去，没想到什么合适的方法，因为原生的右键已经被替换了，所以我直接绑定在整个表格上并不能触发原生的粘贴方法

**Comment by xuliangzhan** [comment]
你给表格绑定就行了

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62538561-b34f7180-b885-11e9-9e68-e9fef44852c0.png)
给表格绑定后我该通过什么方式去触发该事件，是在抱歉，这边确实不太懂

**Comment by xuliangzhan** [comment]
paste 就是操作粘贴时触发，看你的这个代码可能还要处理粘贴的是哪个单元格，处理逻辑比较多，你得自行去实现了

**Comment by wekerSnail** [comment]
粘贴的逻辑我确实回去自行实现，就是我现在用表格自带的右键菜单触发不了绑定的粘贴事假，处理我都写好了，就是不知道怎么触发，我之前使用的你得elem-extends-table组件的时候，激活单元格之后的右键任然是原生的右键，所以可以正常触发我绑定在表格上的粘贴事件，现在换成vxe，一直都是表格的右键菜单了，所以粘贴事件我就触发不了了，我就获取不到`event.clipboardData||window.clipboardData`中的数据了，这是我的复现链接，求指点
http://jsrun.pro/PVbKp/edit，

下面是我用之前的组件实现的粘贴截图：
- 激活单元格是原生菜单
![image](https://user-images.githubusercontent.com/30314164/62586331-aebfa300-b8ef-11e9-8bc6-990ee664e21d.png)
- 不激活是快捷菜单
![image](https://user-images.githubusercontent.com/30314164/62586345-c72fbd80-b8ef-11e9-9506-a67e4d193398.png)

**Comment by xuliangzhan** [comment]
你这方式本身是不可能行得通的，剪贴板只能在粘贴行为中才能获取，其他情况是没有权限能操作的，你应该给单元格加选中状态，选中哪个在用快捷键粘贴哪个
简单的Demo供参考 https://jsrun.pro/JVbKp/edit

**Comment by wekerSnail** [comment]
我明白什么意思了，也就是快捷菜单是实现不了原生的粘贴事件的，只能让用户使用快捷键ctrl+v去触发我绑定的粘贴事件

**Comment by xuliangzhan** [comment]
是的
