### ISSUE TITLE
列很少时候，指定 fixed=left 显示

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#20]
**问题描述 Describe the bug**
列很少时候，指定 fixed=left 显示空白  
**报错信息或截图 Error message or screenshots**

![image](https://user-images.githubusercontent.com/11676609/58224297-c73c0a80-7d4f-11e9-8654-fa2849ab5768.png)
![image](https://user-images.githubusercontent.com/11676609/58224341-f5214f00-7d4f-11e9-8d99-0a3294367432.png)

**Comment by xuliangzhan** [comment]
你更新试下

**Comment by lishihong** [comment]
更新到0.8.2 版本，只是显示空白

**Comment by xuliangzhan** [comment]
还更新到最新是空白？

**Comment by lishihong** [comment]
ok了 0.9.2版本已经ok
