### ISSUE TITLE
怎么传入自定义表单验证规则validator

### ISSUE THREAD

**Issue by 417606028** [xuliangzhan/vxe-table#200]
### 描述 Describe

 ?
 类似这样 { validator: gtZero, trigger: 'blur' }
### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 报错信息或截图 Error message or screenshots

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by huoshidehua** [comment]
@stack-Yaffel trigger:'blur' 没效果啊
