### ISSUE TITLE
insertAt之后getTableData中的tableData数据没有变化，新数据没有

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#202]
### 问题描述 Describe the bug
insertAt（）之后getTableData（）中的tableData新数据没有。fullData中有新数据，但是tableData中没有新数据

**Comment by wekerSnail** [comment]
需要手动调一下refeshData()方法才能刷新tableData数据

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62598875-47204c80-b91d-11e9-9df8-a8c1fc0c3f2f.png)
新insertAt（）的数据激活之后调用getActiveRow()方法获取到的rowIndex是-1，但是$rowIndex是正确的，这两者有什么区别呢

**Comment by xlz26296** [comment]
insert 数据的唯一获取途径是 getInsertRecords ，如果不想 vxe-table 来管理增删改，你应该使用操作数据源的方式，例如 this.tableData.push({...})

**Comment by wekerSnail** [comment]
目前需求已经实现了，只是比较好奇为什么新加入的数据没有更新进去，通过fullData和tableData结合使用也可以完成我的需求，主要是因为新加入的数据都默认加至表格末尾，如果新加入的数据也会立马排序的话，现在的需求就不好实现了，之前使用elem-extend-table新加入的数据也是会立马被排序的
