### ISSUE TITLE
如何能够在右键快捷菜单弹出前隐藏其中某个菜单项

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#203]
### 描述 Describe
右键菜单弹出前根据row的内容进行判断才能确定某个菜单项显示，某个不显示，

Menus: [
        [
          {
            code: "check",
            name: "审核"
          },
          {
            code: "uncheck",
            name: "取消审核"
          }
        ]

应用场景： 比如某行数据已经审核了，则隐藏“审核”菜单项，如果未审核则隐藏“取消审核”菜单项。

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 报错信息或截图 Error message or screenshots

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
[visibleMethod](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/menu) 就是用于显示之前控制权限的

**Comment by jianliulin** [comment]
1.visibleMethod 只能设置菜单项是否可用，能否添加设置菜单项是否visible

2.visibleMethod 必须写函数体，能否填写函数的名称（字符串），如果context-menu 是从后台抓回来的，json的结构不允许写类似 visibleMethod: data => this.visibleMethod(data)，或者能指点用别的办法达到；

3.在table的源码里看到
    openContextMenu: function openContextMenu(evnt, type, params) {
      var _this18 = this;

      var ctxMenuStore = this.ctxMenuStore,
          ctxMenuOpts = this.ctxMenuOpts;
      var config = ctxMenuOpts[type];
      var visibleMethod = ctxMenuOpts.visibleMethod;

     希望如果visibleMethod 是字符串且不为空，就替换为字符串值同名的函数。

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/menu

**Comment by jianliulin** [comment]
谢谢！！！
