### ISSUE TITLE
列固定right有问题

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#204]

**Comment by longa30** [comment]
录个给视频转gif 有点大。。上传不了

**Comment by xuliangzhan** [comment]
提供在线链接就行

**Comment by longa30** [comment]
https://pan.baidu.com/s/1gz8a0lRZb8Xm51Uw9CYZ-g

**Comment by xuliangzhan** [comment]
这个你先确定数据的完整性、正确性

**Comment by longa30** [comment]
你这说的数据是哪里的数据。。目前只有Column字段。。

**Comment by xuliangzhan** [comment]
就是 column 配置

**Comment by longa30** [comment]
版本："vxe-table": "^2.0.10",
字段原始的：Column: [
                        {type: 'index', width: 50},
                        {
                            field: 'name', title: 'app.body.label.name', filters: [
                                {label: 'a', value: '1'},
                                {label: 'a', value: '1'}
                            ], filterMultiple: true,
                            filterRender: {name: 'el-input'}
                        },
                        {field: 'sex', title: 'app.body.label.sex', showHeaderOverflow: true},
                        {field: 'address', title: 'Address', showOverflow: true}
                    ]
那个页面是对字段属性的修改。操作。
 headerClick(data, event) {//点击header头部事件。
                const {triggerResizable, triggerSort, triggerFilter, $rowIndex, column, columnIndex, $columnIndex, cell} = data
                this.widgetFormSelect = column.own//将属性传递给右侧修改

                // alert(JSON.stringify(column))
            }
//修改页的固定属性。
<el-form-item label="固定方式">
                <el-radio-group v-model="data.fixed"  size="mini">
                    <el-radio-button label="">不固定</el-radio-button>
                    <el-radio-button label="left">固定左侧</el-radio-button>
                    <el-radio-button label="right">固定右侧</el-radio-button>
                </el-radio-group>
            </el-form-item>

//修改页监听//data是header点击传递到修改也的props
 data:{
                deep:true,
                handler(val, oldVal){
                    console.log("这事："+JSON.stringify(val));
                    // alert(JSON.stringify(val))//输出如下日志
                }
            }
//
这事：{"field":"sex","title":"app.body.label.sex","showHeaderOverflow":true,"fixed":"right"}
![image](https://user-images.githubusercontent.com/17867961/62621524-a34f9480-b94e-11e9-96ae-167f98b26e21.png)

**Comment by xuliangzhan** [comment]
你先更新到最新看下，之后的版本有优化列的逻辑

**Comment by longa30** [comment]
![image](https://user-images.githubusercontent.com/17867961/62621960-c2025b00-b94f-11e9-8c17-e90d43d6d277.png)

**Comment by longa30** [comment]
更新速度真快。跟不上。

**Comment by xuliangzhan** [comment]
固定列的限制条件：
如果是非分组则无限制；
如果是分组，必须是按组且只能出现在左右两边，不允许跨列行为；

**Comment by longa30** [comment]
嗯。更新到2.0.19没有这个错误没有了。昨天还是前天看的时候好像还是10的版本。谢谢

**Comment by longa30** [comment]
谢谢！
