### ISSUE TITLE
select

### ISSUE THREAD

**Issue by liyyihui** [xuliangzhan/vxe-table#205]
当表格中有select 的时候  值变化   没用  事件吗？

**Comment by xuliangzhan** [comment]
复选框只会在手动勾选时触发对应的事件

**Comment by liyyihui** [comment]
我不是复选框  我是ElSelect 这个




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月7日(星期三) 晚上8:01
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] select (#205)




复选框只会在手动勾选时触发对应的事件

**Comment by xuliangzhan** [comment]
看错了，只要组件能支持的事件都能传，具体请看对应组件的文档

**Comment by liyyihui** [comment]
你好  我就是在Events   这个里面找没用找到




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月7日(星期三) 晚上8:07
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] select (#205)




看错了，只要组件能支持的事件都能传，具体请看对应组件的文档

**Comment by liyyihui** [comment]
你方便给我个你的QQ 吗 或者群交流的 




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上8:07
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "lllll "<945131558@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] select (#205)




看错了，只要组件能支持的事件都能传，具体请看对应组件的文档

**Comment by xuliangzhan** [comment]
I'm sorry, 你应该按规范提供问题链接，否则无法帮到你

**Comment by liyyihui** [comment]
你那个 我弄了 不知道怎么发布到 你的那个github上



------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月7日(星期三) 晚上8:15
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] select (#205)




I'm sorry, 你应该按规范提供问题链接，否则无法帮到你
