### ISSUE TITLE
新版的例子不能运行

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#207]
font-awesome/scss/font-awesome.scss
这个在example的main.js中没有找到依赖

**Comment by xuliangzhan** [comment]
没明白你的意思，组件不依赖这个图标库的

**Comment by tiger54910** [comment]
![QQ图片20190808152317](https://user-images.githubusercontent.com/14190457/62683200-7ce23580-b9f0-11e9-83a5-33c763c3aa04.png)

**Comment by xuliangzhan** [comment]
这没看出有啥问题？
