### ISSUE TITLE
可视化渲染在分页加载数据时候未起作用，所有行全部渲染了

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#21]
可视化渲染在分页加载数据时候未起作用，所有行全部渲染了。分页大小30，每次请求数据30条，然后用 this.$refs.xTable.insertAt(list,-1) 的方法增量填充数据，同样的配置和代码，换成reload(list)，可视化渲染起作用了，值渲染了配置的那么多行。
![微信截图_20190524125351](https://user-images.githubusercontent.com/11676609/58303513-04bd9800-7e23-11e9-9264-3173e491a297.png)

**Comment by xuliangzhan** [comment]
insertAt不能用于数据递增，这个是往表格真实插入数据
数据递增你应该使用load或reload

**Comment by lishihong** [comment]
ok
