### ISSUE TITLE
如何让输出的数据不含row_id

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#211]
### 描述 Describe
不希望getInsertRecords()等方法输出的数据含表格以外的数据，目前有组件自带的_XID

**Comment by xlz26296** [comment]
@wekerSnail  不要使用高级功能就不会有 rowId 了，否则要么自行指定 rowId 要么最自行滤掉

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62679681-d6923200-b9e7-11e9-8b95-cba0f681beed.png)
搜索了一下，我看我并没有配置这几个参数呀

**Comment by wekerSnail** [comment]
哪些功能会触发加上row-id呢

**Comment by xlz26296** [comment]
这个你只能使用低性能的旧版本了才能支持没有 row-id，新版本的深度优化必须要有唯一主键

**Comment by wekerSnail** [comment]
那我还是手动去除吧
