### ISSUE TITLE
tab切换在edit-config ，mode：cell状态下无法正常使用

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#212]
### 问题描述 Describe the bug
在row激活状态下可以正常左右切换，cell状态下无法正常使用，单元格不会被切换，表格会跳转错误

### 期望的结果 Expected behavior
和row模式下一样的切换效果

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/keyboard
