### ISSUE TITLE
使用elem组件时，如果有一列数据无属性，就不无法正常输入

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#214]
### 问题描述 Describe the bug
例如：
![image](https://user-images.githubusercontent.com/30314164/62747463-23791580-ba87-11e9-8178-441b54e31539.png)
li列中有name属性，但是后端该属性有一行无值，返回的对象中直接去除了该属性，怎么表格中该单元格就无法正常输入了，但是使用原生的input组件就可以，使用饿了么的不行，别的第三方的没有试
### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） 
https://jsrun.pro/iTbKp/edit
示例中，我把第一二行中name属性去除，就无法正常编辑了

### 期望的结果 Expected behavior
像内置的input一样的输入效果

**Comment by xlz26296** [comment]
这个你应该按照 vue 的规范，先定义后使用才能使用双向绑定
element 的实现本身就不支持未定义的字段 http://jsrun.pro/2TbKp/edit
你可以使用 [createData](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=createData) 方法进行自动定义

**Comment by wekerSnail** [comment]
原来的vue-element-extend组件并没有这种问题，我也是换成vxe才发现空值没法修改，数据格式时后端直接传过来的，这个我不可能把每条都处理一遍在传入表格

**Comment by wekerSnail** [comment]
但是饿了么的input如果传入的是一个对象的属性值，该属性值没有，是可以输入的

**Comment by xuliangzhan** [comment]
你应该遵循 vue 的先定义后使用的逻辑
vue-element-extend 是自动判断定义了；
vxe-table 是手动定义的，扫描会多一半的开销，应该只有少数场景会出现未定义的情况
可以通过 createData 方法自动定义

**Comment by wekerSnail** [comment]
我们这边的接口设计就是这样，空值的属性一律不返回，所以就遇到了这个问题，看到新更新的表格有了createData方法，使用了一下，发现不是很方便，还是选择了自己写一个方法去处理了，还是得感谢大佬的热心更新支持。
