### ISSUE TITLE
传给vxe-table-plugin-element中renderCell 参数不正确，是否我理解错了，请指教。

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#215]
### 描述 Describe

 ?

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

我在vxe-table-plugin-element 中添加了一点代码 
    ElInput: {
      autofocus: 'input.el-input__inner',
      **renderCell: defaultCellRender2,** //添加的行
      renderEdit: defaultCellRender,
      renderFilter: defaultFilterRender,
      filterMethod: defaultFilterMethod
    },

defaultCellRender2 函数如下：
  function defaultCellRender2(h, cellRender, params) {
    var props = cellRender.props;
    console.log(props) 
   .......
  }

  查看console 打印结果发现，table传给defaultCellRender2 中的 {cellRender}，不是列配置的cellRender，而是传了renderEdit

### 报错信息或截图 Error message or screenshots

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
自定义的组件应该用渲染器实现比较好吧

**Comment by xlz26296** [comment]
那个 cell-render  渲染器的 API 已经调整了，对应的是 renderDefault 这个
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/renderer

**Comment by jianliulin** [comment]
测试发现，不设置renderEdit ，renderCell 则不执行，设置了就会执行。

**Comment by xuliangzhan** [comment]
我觉得文档都写得很清楚喽，难道还不清楚吗😂
默认渲染器 cell-render : renderDefault
可编辑渲染器 edit-render : renderEdit + renderCell
筛选渲染器 filter-render : renderFilter +  filterMethod

**Comment by jianliulin** [comment]
例子https://codesandbox.io/s/vxe-table-ceshide-demo-93537，
 第一列：  cellRender=myLink ,   单击文字正常
 第二列： editRender=myInput ， 双击正常
 第三列： cellRender=myLink ,editRender=myInput，双击正常 ，单击文字没反应。

 希望的结果是，第三列能和第一列一样，未编辑状态渲染为<a>,单击执行对应的函数，编辑状态则为input

**Comment by xuliangzhan** [comment]
同一列 editRender  > cellRender 只能使用一种渲染器
第三列是错误的，可编辑的组合是 edit-render : renderEdit + renderCell

**Comment by jianliulin** [comment]
现在清楚了，我之前搞错了，我之前以为 editRender 和 cellRender是并列

**Comment by xuliangzhan** [comment]
那样不规范，设计思路就是同一列只能使用一种渲染器，会造成互相影响
