### ISSUE TITLE
grid 中的Slots能否添加default/header/filter/edit功能。

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#216]
需要个公共header的slots
希望如https://xuliangzhan.github.io/vxe-table/#/table/grid/customToolbar 的写法，再columns中可以覆盖。
![image](https://user-images.githubusercontent.com/17867961/62752842-ab691a80-ba9b-11e9-8922-cb8fb54376ff.png)

**Comment by xuliangzhan** [comment]
文档都有的，为啥就不看呢
https://xuliangzhan.github.io/vxe-table/#/table/grid/template

**Comment by longa30** [comment]
建议文档给个全文搜索功能。，功能太多了。。记不住这么多。。

**Comment by longa30** [comment]
这里我看来。我是希望这样的。。我是希望可以如图所示这样可以统一定义header。而您给的链接这个是再每个字段的json中定义。
![image](https://user-images.githubusercontent.com/17867961/62755034-ec196180-baa4-11e9-85ca-5e5b5a8686ab.png)

**Comment by longa30** [comment]
好的！谢谢
