### ISSUE TITLE
select-config

### ISSUE THREAD

**Issue by liyyihui** [xuliangzhan/vxe-table#217]
checkRowKeys  默认勾选开指定行 | Array<String>  这个里面装的是什么 我用下标 不行 然后 labelField 给了个字段 这个 只是显示 跟默认勾选没有关系啊

**Comment by xlz26296** [comment]
使用 checkRowKeys  功能，是需要指定 row-id 字段名的，checkRowKeys=Array<Row[rowId]>

**Comment by liyyihui** [comment]
找到了






------------------ 原始邮件 ------------------
发件人: "abc"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 下午2:39
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] select-config (#217)




使用 checkRowKeys  功能，是需要指定 row-id 字段名的，checkRowKeys=Array<Row[rowId]>

**Comment by liyyihui** [comment]
你好  我想请问下 那个ElSelect 事件的问题 我想在我tab里面的select  里面值变化的事件 我找了好久没找到 { field: 'GradeName', title: '品类级别', width: 80, editRender: { name: 'ElSelect', options: [{Lable: '全局', Value: '1'}, {Lable: '处级', Value: '2'}, {Lable: '课级', Value: '3'}], optionProps: {label: 'Lable', value: 'Value'} } }
  我是这么 写的但是我试过在editRender里面加个change:'onchange'但是没效果  我现在项目中tab 中有几个select  但是 相互之间有一定的限制  所以需要这个事件  我找值发生变化事件用current-change 高亮行来操作  但是只会触发一次  请大佬指点下 卡这了




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月11日(星期天) 下午5:34
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] select-config (#217)




Closed #217.

**Comment by xlz26296** [comment]
你应该通过问题链接来描述问题
