### ISSUE TITLE
vxe-table和vxe-grid区别

### ISSUE THREAD

**Issue by suweien** [xuliangzhan/vxe-table#218]
如题目

**Comment by longa30** [comment]
vxe-table是静态的。grid是动态的。grid可以远程json来动态生成table

**Comment by longa30** [comment]
vxe-table是静态的。grid是动态的。grid可以远程json来动态生成table，grid继承了table的属性。

**Comment by xlz26296** [comment]
除了以上，vxe-grid 的性能也比 vxe-table 快一倍，因为不需要为每一列初始化实例

**Comment by suweien** [comment]
意思即使不是用那些动态配置比如动态列啥的使用grid也是比table好呗， 那table存在的意义是啥0 0

**Comment by xuliangzhan** [comment]
table 的底层，grid 基于 table，存在即有意义；vue 多数情况还是推荐使用语义化标签的形式；而对于场景用 grid 就更加灵活，可以实现远程配置化

**Comment by chenchifeng** [comment]
请问如果tableColumn是写在外部js或者后端返回,而不是直接写在当前vue组件的话,使用vxe-grid时候一些自定义模板会不会用起来就不方便,这个时候是用vxe-table比较好一些?

**Comment by xlz26296** [comment]
@chenchifeng vxe-grid + 渲染器 本身就是为动态需求设计的，两者都能用，具体自行选择哈

**Comment by chenchifeng** [comment]
@xuliangzhan grid可以的树结构不能insert操作吗?
![图片](https://user-images.githubusercontent.com/16933868/63573799-e3eb1700-c5b8-11e9-8ec6-deaf08b4be5d.png)

**Comment by xuliangzhan** [comment]
本身不支持insert方法，但是你可以操作数据源https://xuliangzhan_admin.gitee.io/vxe-table/#/table/tree/insert

**Comment by chenchifeng** [comment]
@xuliangzhan 那请问如果使用了数据代理的话怎么插入呢?

**Comment by rayas51674** [comment]
@xuliangzhan 请问嵌套的vxe-table-column（实现表头分组）如何用grid动态json实现（如何定义column？）？

```
<vxe-table
          border
          height="400"
          :data="tableData">
          <vxe-table-column title="基本信息">
            <vxe-table-column type="seq" width="60"></vxe-table-column>
            <vxe-table-column field="name" title="Name"></vxe-table-column>
          </vxe-table-column>
          <vxe-table-column title="更多信息">
            <vxe-table-column field="role" title="Role"></vxe-table-column>
            <vxe-table-column title="详细信息">
              <vxe-table-column field="sex" title="Sex"></vxe-table-column>
              <vxe-table-column field="age" title="Age"></vxe-table-column>
            </vxe-table-column>
          </vxe-table-column>
          <vxe-table-column field="address" title="Address" show-overflow></vxe-table-column>
        </vxe-table>
```
