### ISSUE TITLE
Documentation cannot access after few seconds

### ISSUE THREAD

**Issue by doraemonxxx** [xuliangzhan/vxe-table#2185]
### 可复现的链接：

none

### 问题描述与截图：

![image](https://github.com/x-extends/vxe-table/assets/88119911/9cfa4736-3c27-4666-876a-7cb75c8d15cd)
Cannot view the official docs. After a few seconds, the message will display.

### 期望的结果：

can view the docs

### 操作系统：

windows 11

### 浏览器版本：

Chrome latest version

### vue 版本：

none

### vxe-table 版本：

none

**Comment by xlz26296** [comment]
#2174
