### ISSUE TITLE
能否添加和 element-UI相似的高度自适应

### ISSUE THREAD

**Issue by YuanQGit** [xuliangzhan/vxe-table#22]
element-ui里面，table高度可以根据父容器 大小改变而改变，为了方便用户操作，需要让table刚好沾满某屏幕 ，但是屏幕大小是不固定的。

**Comment by xuliangzhan** [comment]
不太清楚的你需求，最好能提供链接

**Comment by YuanQGit** [comment]
就是 浏览器窗口改变的时候，动态修改 table  的height值。

**Comment by xuliangzhan** [comment]
这个你可以动态设置算好后的 height 属性

**Comment by xuliangzhan** [comment]
你可以更新到最新可以支持[响应式宽高](https://xuliangzhan.github.io/vxe-table/#/table/base/autoHeight)
