### ISSUE TITLE
 tableColumn 列字段  showOverflow问题

### ISSUE THREAD

**Issue by psyche0401** [xuliangzhan/vxe-table#222]
### 描述 Describe

 ?设置了showOveflow：true ,默认显示 数据原始值，如何设置显示为：状态码转换后的文本信息？

### 能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 报错信息或截图 Error message or screenshots

 
![TIM截图20190811002831](https://user-images.githubusercontent.com/41417829/62830297-4bab7480-bc3f-11e9-872f-25d0d81a9bf1.png)
![TIM截图20190811002928](https://user-images.githubusercontent.com/41417829/62830298-5108bf00-bc3f-11e9-8d1c-bf93ce3ee2c7.png)

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by l1078228451** [comment]
grid 配置showOverflow为true，针对某一列关闭了showOverflow属性，当没出现滚动条时，该列没有col--ellipsis类名，当出现滚动条时列就会有class名为col--ellipsis的类名，这是为什么？ @xuliangzhan
