### ISSUE TITLE
getUpdateRecords()

### ISSUE THREAD

**Issue by liyyihui** [xuliangzhan/vxe-table#223]
getUpdateRecords()  这个函数  我没有修改值 但能获取到 我放入table 的 第一个

**Comment by liyyihui** [comment]
请教个问题 我在添加新数据的时候 我设置了激活第一个编辑框 会自动给我加个数据在里面   是跟我设置了row-id  的关系吗




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 晚上6:22
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] getUpdateRecords() (#223)




Closed #223.

**Comment by xuliangzhan** [comment]
表格数据必须要有唯一主键，row-id 用于指定字段名

**Comment by liyyihui** [comment]
设置了就会出现我刚说的那种情况 不设置反而没事




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 晚上8:06
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] getUpdateRecords() (#223)




表格数据必须要有唯一主键，row-id 用于指定字段名

**Comment by xuliangzhan** [comment]
不管任何情况，表格的优化机制基于行数据的唯一主键，不可能没有

**Comment by liyyihui** [comment]
好的   




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 晚上8:17
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "lllll "<945131558@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] getUpdateRecords() (#223)




不管任何情况，表格的优化机制基于行数据的唯一主键，不可能没有
