### ISSUE TITLE
Filter 如何实现默认筛选值？

### ISSUE THREAD

**Issue by gaollg** [xuliangzhan/vxe-table#225]
在远程渲染下，可能刚进入页面就有默认的排序和筛选，如下图所示。

![image](https://user-images.githubusercontent.com/2359462/62831986-5b848200-bc5a-11e9-84bd-fc4fa770d531.png)

默认排序，可以通过 sort(field, asc/desc) 方法实现。
默认筛选条件，翻阅了多遍文档，实未找到解决思路，望不吝赐教。

**其它**
另，看到有 `closeFilter()` 方法，可有弹出对应 Filter 方法？

**Comment by gaollg** [comment]
https://github.com/xuliangzhan/vxe-table/blob/master/examples/views/table/advanced/ManualFilter.vue#L109 中发现有 filter 方法。

但实际运行时，并未有 Filter 方法：
![image](https://user-images.githubusercontent.com/2359462/62836404-f39f5d00-bc94-11e9-86be-109cb9bd12d1.png)


我使用的版本是：1.12.3

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/manualFilter

**Comment by gaollg** [comment]
### 运行截图，并有 filter() 方法，但有 `clearFilter`、`closeFilter` 两个方法：
![image](https://user-images.githubusercontent.com/2359462/63012767-625eff00-bebd-11e9-8a86-68a1dddea746.png)

### 下图为 API 文档截图：
![image](https://user-images.githubusercontent.com/2359462/63012806-71de4800-bebd-11e9-958f-55123d38d007.png)

**Comment by xuliangzhan** [comment]
有问题请按规范填写并提供重现链接！
