### ISSUE TITLE
表格复选框勾选不了

### ISSUE THREAD

**Issue by Yourroot** [xuliangzhan/vxe-table#229]
### （必填）填写问题描述 Describe the bug

 通过使用cell-click来点击单元格， 使用toggleRowSelection(row)来勾选当前行，但是当这个api后再想勾选复选框，勾选不了

### （必填）填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 http://jsrun.pro/pbbKp/edit

### （选填）填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/29765892/62852226-66531b80-bd1b-11e9-9728-ea0ac206b36b.png)

### （必填）版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
这不是 bug 哦，你本身就没处理好事件冒泡，你想要自行实现点击就要解决有事件冒泡引起的重复触发，你可以判断 event.target 如果为 chockbox 就不要调用 toggleRowSelection 方法
或者使用自带的功能 select-config="{trigger: 'cell'}"

**Comment by Yourroot** [comment]
嗯，通过判断是可以的，多谢楼主
