### ISSUE TITLE
数据较多是，表格展示错误

### ISSUE THREAD

**Issue by Sicau-HsuYang** [xuliangzhan/vxe-table#23]
之前遇到过一个证券公司需求是同时支持10000条数据（不能分页）的表格的需求，尝试了一下你的表格，我载入1W条数据的时候，只能展示前面70条，不知道怎么回事。

**Comment by xuliangzhan** [comment]
描述不明确，最好提供能重现问题的[链接](https://jsrun.net/XRXKp/edit)

**Comment by Sicau-HsuYang** [comment]
我试着把高度去掉就重现了。只展示了70条数据。然后我补上高度之后，在滑动条上滑动，刚开始好好的，滑下来 再滑上去回不到1了（均在Chrome环境下。）

**Comment by xuliangzhan** [comment]
数据量大的需要设置高度，再配合参数调整 :optimized="{scrollY: {gt: 500, oSize: 30, rSize: 80}}"

**Comment by fooleap** [comment]
> 描述不明确，最好提供能重现问题的[链接](https://jsrun.net/XRXKp/edit)

你好，我也碰到滚动加载显示出现 bug 的情况。
像上面这个示例，显示情况是刚开始显示前面的，即 index 为 1 开始的那几条。一滚动，便变成 9901 开始，之后数据便只显示 9901 - 10000。

**Comment by xuliangzhan** [comment]
@fooleap 这个问题在最新版本修复了，建议更新到最新
