### ISSUE TITLE
切换到hidden的组件中，表格宽度渲染不正常

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#230]
### （必填）填写问题描述 Describe the bug
对于tab切换的组件，在切换到原来hidden的tab时，表格宽度渲染不正常，开启auto-resize之后，切过去可以重渲染成正常宽度，但是会有个一两秒的延迟，体验不好，因为页面每次打开切tab都会这样，我现在的使用场景是在dialog里面，所以每次打开弹框都会这样

**Comment by xuliangzhan** [comment]
这本身属于不合理的渲染；可以初始化多个，但不应该在隐藏的标签中去初始化，这是无法计算宽度的
正常的处理逻辑应该是可视之后再进行渲染，非正常渲染请在显示之后使用手动调用 recalculate 方法重新计算

**Comment by wekerSnail** [comment]
手动计算的方式确实可行，渲染速度比auto resize快
