### ISSUE TITLE
row-class-name无效

### ISSUE THREAD

**Issue by ningstudy** [xuliangzhan/vxe-table#231]
row-class-name点击行没有反应是为什么啊。。。

**Comment by ningstudy** [comment]
![image](https://user-images.githubusercontent.com/38598716/62910438-132ca780-bdb3-11e9-9222-a679571b8a4a.png)

**Comment by Yourroot** [comment]
这个是行添加类的

**Comment by ningstudy** [comment]
对啊 我就想实现单击行选中，现在选中是选中了，但是最前面那个框框没有打钩。。



------------------ 原始邮件 ------------------
发件人: "Yourroot"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午2:35
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "ningpeng"<862022491@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] row-class-name无效 (#231)




这个是行添加类的
