### ISSUE TITLE
虚拟滚动下自定义子组件的emit事件会失效

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#233]
### （必填）填写问题描述 Describe the bug
数据量大触发虚拟滚动之后，自定义的子组件点击触发的emit事件会报错，
![image](https://user-images.githubusercontent.com/30314164/62909811-bd570000-bdb0-11e9-8759-5c1c088842f0.png)
![image](https://user-images.githubusercontent.com/30314164/62909838-cba51c00-bdb0-11e9-90b9-782346e5f467.png)
数据量小，没有虚拟滚动时，可以正常触发

### （必填）填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） 
https://jsrun.pro/V9bKp/edit

**Comment by xuliangzhan** [comment]
滚动渲染只能支持往第一行新增，后续版本可能会考虑支持滚动渲染

**Comment by wekerSnail** [comment]
我没有新增，只是使用reloadData的方式初始化了表格，然后slots中的emit事件无法正常触发

**Comment by xuliangzhan** [comment]
请提供能重新问题的链接

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/62937795-3a5d9600-be00-11e9-9769-ce1a81475538.png)
https://jsrun.pro/V9bKp/edit
 我上面给的连接可以重现，但是用到了slots，在在线编辑器里报错，我知不道怎么在在线编辑器里运行起来

**Comment by xuliangzhan** [comment]
没发现滚动会报错，请将问题描述清楚

**Comment by wekerSnail** [comment]
滚动不会报错，点击我的自定义按钮，触犯我绑定的this.$emit()时回报我上述的错误，在数据量大使用虚拟滚动之后才会有着问题，数据小于虚拟滚动的配置时可以正常点击，父级接收到emit事件

**Comment by xuliangzhan** [comment]
这个和事件能有什么关系？截图那个警告信息是在 insert 才会提示的

**Comment by wekerSnail** [comment]
抱歉，问题确实出在我添加数据到最后一行上，不是虚拟滚动导致的

**Comment by xuliangzhan** [comment]
最新版可以虚拟滚动可以支持任意位置插入了，你可以更新看下

**Comment by wekerSnail** [comment]
感谢更新支持，不过我有个新的疑问，大数据时操作删除数据，表格不会刷新，需要滚动一下再能看到删除的数据消失，这是我操作不对还是表格本身的问题？

复现连接：https://jsrun.pro/V9bKp/edit
