### ISSUE TITLE
文档官网总是提示“当前环境不支持访问，请检查网络或相关屏蔽拦截插件，建议更换浏览器重试”

### ISSUE THREAD

**Issue by yangjunjun** [xuliangzhan/vxe-table#2337]
### 可复现的链接：

https://vxetable

### 问题描述与截图：

打开官网页面不就就会提示
![1710819186268](https://github.com/x-extends/vxe-table/assets/1180563/28e265f9-efb7-42d7-93f6-5320f0193ab7)
浏览器并没有安装广告屏蔽插件

### 期望的结果：

正常显示页面

### 操作系统：

window10

### 浏览器版本：

chrome  122.0.6261.129

### vue 版本：

最新

### vxe-table 版本：

最新

**Comment by AnglusWang** [comment]
遇到相同问题

**Comment by Clover-You** [comment]
关掉广告拦截插件

**Comment by rex-ll** [comment]
网络运营商问题，换一个网络试试

**Comment by xlz26296** [comment]
#2188
