### ISSUE TITLE
contextMenu 的visibleMethod 方法能否加入参数，以表示鼠标是否是在cell上

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#235]
### （必填）这个需求解决了什么问题 What problem does this feature solve

contextMenu 的visibleMethod 方法能否加入参数表示鼠标是否是在cell上， 
当触发方式选择为default时候，可以知道是否在cell上，以便隐藏某些需要在cell上才有效的菜单项

### （必填）建议的 API 是什么样的 What does the proposed API look like

 无

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 无

**Comment by xlz26296** [comment]
这个文档不是有吗，row & column 存在就是在 cell 上
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=visibleMethod

**Comment by jianliulin** [comment]
文档中 "该函数会在菜单显示之前执行，支持通过 Function({type, row?, rowIndex?, column?, columnIndex?}) 的返回值用来决定是否允许显示右键菜单（对于需要权限控制的选项可能会用到）"

没说明有cell? ,这个参数，console后发现了，不好意思，打扰了
