### ISSUE TITLE
checkbox设置为父子级不相关联

### ISSUE THREAD

**Issue by tiancliu** [xuliangzhan/vxe-table#236]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 ?checkbox设置为父子级不相关联后，没办法去控制全选按钮的选中与为选中

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
你都已经解除关联了，还哪来的全选？

**Comment by tiancliu** [comment]
> 你都已经解除关联了，还哪来的全选？
不是这个意思 是去控制表格的全选按钮的选中和未选中 
![image](https://user-images.githubusercontent.com/17979305/62991841-d67cb100-be83-11e9-8d0b-2e2cafdf1d6c.png)

**Comment by tiancliu** [comment]
> > 你都已经解除关联了，还哪来的全选？
> > 不是这个意思是去控制表格的全选按钮的选中和未选中
> > ![图片](https://user-images.githubusercontent.com/17979305/62991841-d67cb100-be83-11e9-8d0b-2e2cafdf1d6c.png)

可能我的表达方式有点问题哈哈，或者说 有没有方法直接代码控制全选按钮的选中和未选中，setSelection方法可以去控制嘛，但是这个需要传入每行对应的row，但是我们全选按钮是在表头那一行，没有对应的row，setSelection方法就不行嘛

**Comment by xuliangzhan** [comment]
解除关联了那就所有逻辑只能自行处理了，组件不会再有任何的数据关联
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/selection
