### ISSUE TITLE
筛选 filters 不会跟随数据响应

### ISSUE THREAD

**Issue by yelog** [xuliangzhan/vxe-table#237]
### （必填）填写问题描述 Describe the bug
当我通过 filters 绑定一个变量，如下，然后通过方法`change`修改这个变量，表头的筛选下拉并没有响应这次改动
```html
<vxe-button @click="change" >修改</vxe-button>
<vxe-table-column field="sex" title="Sex" sortable :filters="filters"></vxe-table-column>
```
```js
export default {
  data () {
    return {
      filters: [{ label: 'Man', value: '1' }, { label: 'Woman', value: '0' }]
    }
  },
  methods: {
    change () {
      this.filters = [{ label: 'Man1', value: '1' }, { label: 'Woman1', value: '0' }]
    }
  }
}
```
有时筛选下拉的内容来自于请求，所以在动态修改filters时就会出现如上问题

效果如图：

![刚开始](https://user-images.githubusercontent.com/14227866/63010160-72281480-beb8-11e9-865a-169a8bec1027.png)
![修改filters后](https://user-images.githubusercontent.com/14227866/63010269-a69bd080-beb8-11e9-8477-6b364c7b48d1.png)

**Comment by xuliangzhan** [comment]
filters 是不会双向关联的
