### ISSUE TITLE
配置toolbar.refresh 配置未达预期，求助

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#238]
### （必填）描述 Describe
1.toolbar.refresh=true，正常
2. toolbar.refresh={query: function} ，toolbar消失

想点击刷新按钮后，执行自定义的一个函数，不是执行默认的reload

### （必填）能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/embed/vxe-table-ceshide-demo-93537?fontsize=14

### 报错信息或截图 Error message or screenshots

![微信截图_20190814154848](https://user-images.githubusercontent.com/4531974/63003594-16a35a00-beab-11e9-89c2-88edfd019f28.png)

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by jianliulin** [comment]
谢谢

**Comment by waynehoo** [comment]
@jianliulin 请问这个问题解决了吗？
