### ISSUE TITLE
insert之后表格输出的数据总是和实际的数据少最新的一行

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#239]
### （必填）填写问题描述 Describe the bug
insert方法添加数据之后，表格输出不出最新的数据，我该怎么操作可以获取到最新的数据?

### （必填）填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） 

https://jsrun.pro/JebKp/edit

**Comment by wekerSnail** [comment]
之前我记得通过fullData或者getdata是可以获取到全部数据的，现在这两个方法也获取不到完整的数据

**Comment by wekerSnail** [comment]
调试发现，现在的insert效果是异步的，insert结束之后需要等一会才会更新最新的数据，直接获取确实是获取不到最新的数据的

**Comment by xuliangzhan** [comment]
insert 数据的唯一获取途径是 getInsertRecords，特殊获取方法是 getTableData
正确应该在 insert then 之后再操作

**Comment by wekerSnail** [comment]
也就是说，我如果没有等then就再次调用insert，会导致insert的数据读取不到？那假设用户insert完进行其他操作，时间很短，比then快，我该如何处理呢



发自我的小米手机
在 Xu Liangzhan <notifications@github.com>，2019年8月14日 下午5:32写道：

insert 数据的唯一获取途径是 getInsertRecords，特殊获取方法是 getTableData
正确应该在 insert then 之后再操作

**Comment by xuliangzhan** [comment]
这个你得自行控制了

**Comment by wekerSnail** [comment]
比如用户连续点击多次增加按钮呢

**Comment by xuliangzhan** [comment]
你应该通过重现链接来描述什么场景无法达到预期
