### ISSUE TITLE
element ui 自定义模板插槽的值报undefined

### ISSUE THREAD

**Issue by cuilongshui** [xuliangzhan/vxe-table#24]
**问题描述 Describe the bug**

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by cuilongshui** [comment]
解决了，vue版本太低了  要2.6.10版本的

**Comment by victorting** [comment]
我也遇到同样的问题，我的vue版本就是2.6.10的， 自定义模板插槽加载200多行的数据，出现[Vue warn]: Duplicate keys detected: 'undefined'. This may cause an update error.这样的错误提示，请问有什么解决办法吗？
