### ISSUE TITLE
大量数据开启虚拟滚动的时候，拖动滚动条，虚拟滚动不是平滑渲染

### ISSUE THREAD

**Issue by shixued** [xuliangzhan/vxe-table#240]
### （必填）描述 Describe

 ?

### （必填）能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 我目前有3000+条记录，列在20个列以内，参数设置如下，数据采用reloadData()进行加载的，在拖动y轴滚动条的时候，上下会出现白板，并没有平滑的滚动，和作者官方演示的demo比较下，差距还是很大的，请教老师如何进行优化
optimization : {
    animat: false,
    // 当表头大于 40 列时自动启用横向 X 滚动渲染
    scrollX: {
      gt: 10,
      oSize: 10,
      rSize: 40
    },
    // 当行数据大于 500 条时自动启用纵向 Y 滚动渲染
    scrollY: {
      gt: 200,
      oSize:40,
      rSize: 80
    }
  }

### 报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/29394218/63026362-a06c1b00-bedd-11e9-865b-01aeb3b6bf61.png)

### 版本 Version

- os: windows
- browser: chrome
- vue: 2.5.9
- vxe-table: 1.12.3

**Comment by xuliangzhan** [comment]
v1 的效果略差，v2 效果是最好的

**Comment by shixued** [comment]
已经升级到2.2.4问题依旧存在，期待您的指导。

**Comment by xuliangzhan** [comment]
你应该用重现链接来描述你的问题

**Comment by shixued** [comment]
非常感谢，升级到2.2.7版本后，平滑已经没问题了。
但是show-header-overflow这参数开启后，会和列宽拖动功能冲突，开启后，无法拖动列宽。这个您要是有空望您验证下。

**Comment by xuliangzhan** [comment]
有问题你应该用重现链接来描述问题
