### ISSUE TITLE
editConfig.activeMethod 方法中能否把$table 这个参数也一起传进来

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#241]
### （必填）这个需求解决了什么问题 What problem does this feature solve

editConfig.activeMethod 方法中能否把$table 这个参数也一起传进来，
文档中“该方法 Function({row, rowIndex, column, columnIndex}) 决定该单元格是否允许编辑”

![微信截图_20190815173641](https://user-images.githubusercontent.com/4531974/63086839-4c1b7680-bf83-11e9-8273-004b9c48521f.png)

### （必填）建议的 API 是什么样的 What does the proposed API look like

https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/api

### 是否已有其他不错的替代方案 Describe alternatives you've considered

无

**Comment by xuliangzhan** [comment]
这个你用 ref 不是更好吗

**Comment by jianliulin** [comment]
写的通用的方法，并不知道当前ref是那个。

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下

**Comment by jianliulin** [comment]
谢谢！！
