### ISSUE TITLE
insert进去的数据，getActiveRow读取不到正确的激活数据

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#243]
### （必填）填写问题描述 Describe the bug
目前在数据量大，有虚拟滚动时发现的，正常滚动下不知道有没有这个问题，insert进去的数据，读取不到正确的active数据。
使用场景是，我ctrl+ v粘贴事件里面，去读取激活的位置，然后覆盖原来的数据，但是新insert进去的数据，输出不了正确的位置信息，始终返回-1

### （必填）填写期望的结果 Expected behavior
输出正确的位置信息

**Comment by xuliangzhan** [comment]
你这一边新增一边删除的，真没看明白这是要做啥
逻辑层面的错误：
1：insert 方法属于临时数据，不会有索引，索引只相对于 data
3：refreshData 错误的用法，如果要将临时数据转为真实数据，请使用  this.data.push({...}) 方式
2：要想玩索引，你应该使用 this.data.push({...}) 方式，不要用 insert 方法

**Comment by wekerSnail** [comment]
我这边我做的效果其实就是把复制过来的表格数据处理之后，粘贴进页面的表格，所以需要修改原来表格里面的数据，但是没有直接修改的api,所以就先增加，然后把原来的删除了，由于是写的公共的处理，data是外部传入的，我也不好直接修改data的数据，所以才使用insert的方法

**Comment by wekerSnail** [comment]
我是在你的组件之外有套了一层封装，然后在使用

**Comment by xuliangzhan** [comment]
你为啥不直接修改数据，插入再删除又是什么做法，本来就是数据驱动的

**Comment by wekerSnail** [comment]
之前我用extend-table的时候我是先用的直接修改数据的方式去实现，发现这样操作之后，我调用接口去输出新增和修改的数据，直接修改数据的没有算到修改数据里面，所以我才全部使用插入方式算到新增里面，方便外部调用的时候直接获取到变化的数据，做提交

**Comment by xuliangzhan** [comment]
如果由表格管理增删改，那么只要动了列字段，就一定可以通过 getUpdateRecords 获取
如果放弃由表格管理，那就只能自行维护增删改关系

**Comment by wekerSnail** [comment]
所以我还是希望直接使用表格管理的数据的，自己管理会涉及不少问题要修改，现在的需求大致也能实现，是通过gatTableData中的visibleData获取到的数据，然后比对找出当前行索引的，这样貌似是可以锁定到正确的行的，如果能有修改row的api就更好了

**Comment by xuliangzhan** [comment]
数据驱动的 row 修改就行，有啥 API

**Comment by wekerSnail** [comment]
ok,也就是说我直接修改数据也可以通过getUpdateRecords获取到，不会像extend-table那样直接不算修改

**Comment by xuliangzhan** [comment]
本来就是这样的

**Comment by wekerSnail** [comment]
能否给一个设置可以关闭插入数据自动排序

**Comment by Yourroot** [comment]
你自己直接设置是否要排序就可以了吧

**Comment by xuliangzhan** [comment]
@wekerSnail 有任何问题请使用重现链接来描述

**Comment by wekerSnail** [comment]
https://jsrun.pro/nzbKp/edit
希望可以关闭自动排序，在表头有点击排序情况下插入数据也始终在表尾，方便用户操作

**Comment by xuliangzhan** [comment]
你这是用 push 刷数据了

**Comment by wekerSnail** [comment]
更新版本使用insert确实可以加到最后一行了

**Comment by wekerSnail** [comment]
但是还是没有什么好的方法可以获取到和表格页面显示一致的数据，如果我使用insert，获取到的visibleData是处理过的数据，当我再次去通过粘贴的方式修改数据时，visibleData中的数据位置其实和页面展示位置并不一致，如果我使用push，那又会导致表格自动排序
