### ISSUE TITLE
proxyConfig.ajax中的（query，delete，save）方法中能否把$table 或者$grid 参数也一起传进来

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#244]
### （必填）这个需求解决了什么问题 What problem does this feature solve

proxyConfig.ajax中的（query，delete，save）方法中能否把$table 或者$grid 参数也传进来, 谢谢！！！，

真希望所有事件函数 都能把$table 带到参数里面 

### （必填）建议的 API 是什么样的 What does the proposed API look like

https://xuliangzhan.com/vxe-table/index.html#/grid/api

### 是否已有其他不错的替代方案 Describe alternatives you've considered

无

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下

**Comment by jianliulin** [comment]
谢谢！！
