### ISSUE TITLE
在表格编辑的时候，能否将其他行也进入编辑模式

### ISSUE THREAD

**Issue by tangby** [xuliangzhan/vxe-table#247]
在一个单元格被编辑的时候，能否将与rowspan同高的行都进入编辑模式？如下图，将红框里的行也进入编辑模式。谢谢

https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/span

![table](https://user-images.githubusercontent.com/19424675/63162019-1a261500-c054-11e9-8392-3690d7776276.jpg)

**Comment by xuliangzhan** [comment]
vxe-table 是为单行编辑而设计的，多行请使用自定义模板去实现

**Comment by tangby** [comment]
好的，我再想其他办法去实现吧，谢谢啦
