### ISSUE TITLE
集成antd之后,日期选择可以返回一个时间戳吗?

### ISSUE THREAD

**Issue by chenchifeng** [xuliangzhan/vxe-table#252]
### （必填）描述 Describe
集成antd之后,有一个日期选择的地方,和需要发送给后端的是时间戳,以下这样配置edit-render之后,获得的值格式为"2019-08-20T09:15:43.333Z",然后就会和formatter属性冲突,显示Invalid Date,请问如果要获取时间戳格式的值应该怎么配置?
```html
<vxe-table-column
            show-header-overflow
            show-overflow
            :field="createtime"
            :title="'创建时间'"
            min-width="140"
            :edit-render="{ name: 'ADatePicker', props: { type: 'date', format: 'YYYY/MM/DD hh:mm:ss' } }"
            :key="index"
            :formatter="['toDateString', 'yyyy-MM-dd hh:mm:ss']"
></vxe-table-column>
```

### （必填）能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 报错信息或截图 Error message or screenshots

 ?

### 版本 Version

- os: windows10
- browser: Firefox 68.0.2(x64)
- vue: 2.5.22
- vxe-table: 2.2.9

**Comment by xlz26296** [comment]
antd 使用的是 moment 格式，而非通用的日期格式，你只能自行转换，无法用内置的
