### ISSUE TITLE
能否提供一个方法去获取到vxe-table-body实例里面的tableData

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#254]
### （必填）这个需求解决了什么问题 What problem does this feature solve

通过查看实例数据，发现body实例里面的数据是和页面展示的数据顺序一致的，包括新insert进去的数据也是有的，这个数据比较符合我们需要出处理的数据，目前的getTableData中获取的数据只有不排序和排序两种，但是几种获取方法获取到数据都有和页面展示不一致的情况，insertAt(row,-1)进去的数据在visibleData中不能获取到

### （必填）建议的 API 是什么样的 What does the proposed API look like
类似getTableData之类的调用方法

**Comment by wekerSnail** [comment]
https://jsrun.pro/pEbKp/edit

**Comment by xuliangzhan** [comment]
getTableData 的行为和 API 不一致，已修复
