### ISSUE TITLE
有没有类似饿了么sort-methods的方法

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#255]
### （必填）这个需求解决了什么问题 What problem does this feature solve
目前的表格排序，在我们的时间数据下面排序不正确。
github不知道为什么上传不了图片了，只能把效果贴到云笔记上看了：http://note.youdao.com/noteshare?id=070fe1c88c1be5d7889122628c517568&sub=BF4669CE5A9F4116B697835962838B14

**Comment by xuliangzhan** [comment]
可以支持
