### ISSUE TITLE
vxe-table-column 能否添加一个默认值（defaultValue）配置项，此默认值为insert记录时候此列的默认值

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#257]
### （必填）这个需求解决了什么问题 What problem does this feature solve
以下链接点击新增时候，帅哥栏位自动为“是”，
https://codesandbox.io/embed/vxe-table-ceshide-demo-13zfj?fontsize=14

### （必填）建议的 API 是什么样的 What does the proposed API look like
vxe-table-column：
type | 列的类型 | String
field | 列属性
**defaultValue |插入新行时，此列的默认值|**
...........

}

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
可以支持

**Comment by jianliulin** [comment]
更新了最新版，好像没发现有添加这个属性

**Comment by xuliangzhan** [comment]
默认属于编辑行为，使用 edit-render.defaultValue 进行配置
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/insert

**Comment by jianliulin** [comment]
可是并不是每一列都是可编辑的，那些显示状态的列如果是不可编辑的，那这个默认值就显得十分重要了，

**Comment by xuliangzhan** [comment]
那个不是这样玩的哦，你应该遵循 vue 的先定义后使用原则；这个只能针对插入的数据提供默认值
至于显示的不应该由表格去修改，你应该提前处理好

**Comment by jianliulin** [comment]
也不是没有定义，能显示就一定是先定义了，但不一定就允许用户手工编辑，目前能编辑的可以设置默认值也不错了！！
