### ISSUE TITLE
bug了，大于0.8.2版本，type=index 以及 slot里面取seq，都显示的有问题

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#26]
bug了，大于0.8.2版本，type=index 以及 slot里面取seq，都显示的有问题，切换回0.8.2版本正常

**Comment by xuliangzhan** [comment]
不清楚你指什么不正常

**Comment by lishihong** [comment]
就是type=index 序号不正常，不是真实的数据行 所对应的序号

**Comment by xuliangzhan** [comment]
在0.9.3+  slot 中 rowIndex 都是指向 data 真实索引（树表格除外），建议更新看下

**Comment by lishihong** [comment]
嗯  0.93 版本ok 了

**Comment by lishihong** [comment]
最新版，可视渲染时候，自定义templace，slot 拿列的索引 columIndex 拿不到了~，拿的不是真实的索引，大佬帮忙看看

**Comment by xuliangzhan** [comment]
更新到最新都是可以的
