### ISSUE TITLE
filter和固定列同时使用，筛选项位置错误

### ISSUE THREAD

**Issue by natee** [xuliangzhan/vxe-table#261]
### （必填）填写问题描述 Describe the bug
表格第一列设置`fixed`和`filter`，当有横向滚动距离时，筛选项下拉框位置错误。

```
<vxe-table-column field="name" sortable title="Name" :filters="[{label: 'id大于10', value: 10}, {label: 'id大于40', value: 40}]" :filter-method="filterMethod" fixed="left" width="80"></vxe-table-column>
```

### （必填）填写能重现问题的链接 Reproduction link

 [jsrun](http://jsrun.pro/3EbKp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/4928035/63342253-96369a80-c37d-11e9-8583-409728806db9.png)

### （必填）填写期望的结果 Expected behavior

 筛选项下拉框位置基于点击位置fixed定位

### （必填）版本 Version

- os: mac 10.14
- browser: chrome 75.0.3770.142
- vue: 2.6.10
- vxe-table: 2.3.2

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下
