### ISSUE TITLE
请问动态列顺序可以通过拖动表头进行调整吗

### ISSUE THREAD

**Issue by shixued** [xuliangzhan/vxe-table#265]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 请问组件是否支持 列的位置顺序通过表头拖动进行调整。

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/other/sortableColumn
