### ISSUE TITLE
如果超过虚拟滚动的默认500行。loadData 更新数据的时候会自动跳到第一行。不超过500行更新数据正常

### ISSUE THREAD

**Issue by xiaogaofudao** [xuliangzhan/vxe-table#266]
如果超过虚拟滚动的默认500行。loadData 更新数据的时候会自动跳到第一行。不超过500行更新数据，则可以记忆滚动条的位置

**Comment by xiaogaofudao** [comment]
vue-element-extends 表格存在同样问题。希望可以记忆用户滚动位置。下次更新不论多少数据，恢复滚动条上次记忆位置

**Comment by Yourroot** [comment]
你更新数据肯定视图会改变了
