### ISSUE TITLE
表格中实现textarea,但高度不能超过表格行高度，需要浮动显示？

### ISSUE THREAD

**Issue by zhangwuqiao** [xuliangzhan/vxe-table#267]
在表格中实现textarea,但高度可以配置一个高度和宽度，这样当激活时就自动放大，而不会把行数据显示的非常乱，做一个，但效果不好，希望能封装一下！

需求如图：
![图片](https://user-images.githubusercontent.com/38390225/63423454-ede90a80-c43e-11e9-91ef-5b6dd623e42e.png)

vxe-table:
  {
    title: '参数描述',
    field: 'desc',
    editRender: {
      name: 'textarea',
      // props: { type: 'textarea' },
      attrs: { style: 'position: absolute; left: 0; top: 0;height:23px;padding:4px 7px;z-index:999;' },
      events: {
        focus: (obj, e) => {
          e.target.style.height = '120px'
        },
        blur: (obj, e) => {
          e.target.style.height = '23px'
        }
      }
    }
  },
效果如下 ：
![图片](https://user-images.githubusercontent.com/38390225/63424284-ab283200-c440-11e9-8173-b32838f12d38.png)

![图片](https://user-images.githubusercontent.com/38390225/63424217-892eaf80-c440-11e9-924e-f109d20ed5a3.png)

这样做效果达不到预期，需要实现撑开时跨多个列，能置顶显示才能编辑，如何实现这一功能。

请帮忙解决一下，如何实现这一功能，非常有用！

**Comment by xuliangzhan** [comment]
表格只支持基础功能，这种你应该自行实现，使用渲染器或第三方组件
