### ISSUE TITLE
vxe-table-column支持自定义class

### ISSUE THREAD

**Issue by natee** [xuliangzhan/vxe-table#268]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 设置列的特殊样式，类似高亮当前列，nth-child(n)可以实现，但是如果隐藏某些列则n的值会错误。

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ```
<vxe-table-column :column-class-name="column"></vxe-table-column>
```

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=class-name

**Comment by natee** [comment]
这个功能现在已经支持了，真香
