### ISSUE TITLE
树形表格在根节点使用insertNextAt新增行后，新增行和原始行没有父子关系，但是产生了缩进

### ISSUE THREAD

**Issue by 59qg** [xuliangzhan/vxe-table#2684]
### 可复现的链接（包含复现链接与示例代码）：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-xnzymr?workspaceId=ws_VEm9TxoW6GLJcApGyugunK

### 问题描述与截图：

树形表格在根节点使用insertNextAt新增行后，新增行和原始行没有父子关系，但是产生了缩进。在控制台打印新增行的数据，发现level=1。
![image](https://github.com/user-attachments/assets/a43f9f4b-880f-43bd-b03b-590936c00221)

### 期望的结果：

新增行没有缩进

### 操作系统：

win10

### 浏览器版本：

chrome 131.0.6778.109

### vue 版本：

3.2.31

### vxe-pc-ui 版本：

4.3.6

### vxe-table 版本：

4.9.16

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
[fix v4.9.25+](https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-9xw5tt)
