### ISSUE TITLE
input绑定lable标签及事件

### ISSUE THREAD

**Issue by zhangwuqiao** [xuliangzhan/vxe-table#269]
### （必填）这个需求解决了什么问题 What problem does this feature solve

问题如图：
![图片](https://user-images.githubusercontent.com/38390225/63478701-61316180-c4bd-11e9-8744-2fc8ae9e8297.png)

### （必填）建议的 API 是什么样的 What does the proposed API look like
![图片](https://user-images.githubusercontent.com/38390225/63478825-f46a9700-c4bd-11e9-83fa-840b3b099509.png)

带标签的 input，设置后置标签或前置标签 并可绑定事件
<vxe-table-column field="sex" title="Sex" :edit-render="{
name: 'input',
addafterlabel:{
                         icon:'',
                         cursor:'pointer',
                         click:function(){
                              #实现调用相关的弹窗
                            }
                      }
}"></vxe-table-column>

具体参数如何配置，怎么方便怎么配置都可以。

### 是否已有其他不错的替代方案 Describe alternatives you've considered
使用ant-design of vue中的组件时有问题，还是原生的好用些，所以建议封闭。

**Comment by xuliangzhan** [comment]
表格只支持基础功能，这种你应该自行实现，使用渲染器或第三方组件
