### ISSUE TITLE
remove删除数据之后，再insert，删除的数据会再次出现

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#270]
### （必填）描述 Describe
remove删除数据之后，再insert，删除的数据会再次出现,如果删除之后调用updateData就可以避免这个问题，这个bug还是什么问题？

### （必填）能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://jsrun.pro/cEbKp/edit

**Comment by XianYue-Tong** [comment]
我这也遇到了同样的问题

**Comment by liyyihui** [comment]
我跟新 2.4.4  还是有这个问题呢

**Comment by hasbug** [comment]
2.5.22还存在这个bug。。。
