### ISSUE TITLE
行内编辑使用iView插件，events:{onChange:changeEvent}未生效

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#271]
### （必填）描述 Describe
            <vxe-table-column field="age" title="InputNumber" width="140" :edit-render="{name: 'InputNumber', props: {max: 35, min: 18} ,events:{onChange:changeEvent}}"></vxe-table-column>

 ?

### （必填）能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
![image](https://user-images.githubusercontent.com/20534088/63484187-66001080-c4d1-11e9-8171-a362da66fe51.png)

 ?
http://jsrun.pro/3sbKp/edit
### 报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/20534088/63483689-d5750080-c4cf-11e9-9d3c-a19705088e86.png)

 ?

### 版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
这个你应该看 ivew 的文档哦，它是固定写的 'on-change' ，是无法使用 onChange

**Comment by XianYue-Tong** [comment]
'on-change' 我也尝试过 会报错

**Comment by XianYue-Tong** [comment]
events:{onChange:changeEvent}    改变事件的正确调用方式应该是什么？

**Comment by xlz26296** [comment]
'on-change' 这不就可以吗 http://jsrun.pro/MsbKp/edit

**Comment by XianYue-Tong** [comment]
谢谢 我知道问题了  忘记加单引号了  非常感谢
