### ISSUE TITLE
页面上显示的表格数据与data里面的数据不一致

### ISSUE THREAD

**Issue by lcosmos** [xuliangzhan/vxe-table#273]
### 描述 Describe

页面上显示的表格数据与data里面的数据不一致
refreshData()刷新之后会清除增删改查数据，但是data数据并未变化

### 重现链接
https://jsfiddle.net/59cuzm3h/

### 报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/20968285/63558823-2bee4780-c581-11e9-940e-8d2008fbd9eb.png)
![image](https://user-images.githubusercontent.com/20968285/63558849-4c1e0680-c581-11e9-9140-7d2b5ca19853.png)

### 版本 Version

- os: macOS 10.14.6
- browser: Chrome 75.0.3770.142
- vue: 2.6.10
- vxe-table: 2.3.6

**Comment by xuliangzhan** [comment]
#239
#173

**Comment by xuliangzhan** [comment]
如果想要表格管理增删改数据，任何临时数据都不会同步 data；
如果想放弃表格的增删改管理；data 保持实时同步，请使用 data.push(..) 方式增删数据，可以自由的维护增删改的数据

**Comment by hasbug** [comment]
其实大家都是希望增删的数据能否绑定传入的数据，编辑表格的用户应该都是这样的。
