### ISSUE TITLE
控制动态列显示隐藏的选择栏有些浏览器显示"..."

### ISSUE THREAD

**Issue by chenchifeng** [xuliangzhan/vxe-table#274]
### （必填）填写问题描述 Describe the bug

 控制动态列显示隐藏的选择栏有些浏览器显示"..."

### （必填）填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 [重现问题的链接](https://jsrun.pro/q7bKp/edit)

### 填写报错信息或截图 Error message or screenshots

1. 没有出现问题的截图: 
![列显示隐藏2](https://user-images.githubusercontent.com/16933868/63560644-517f4f00-c589-11e9-9c92-432cc82d7acf.png)
 
2. 出现问题的截图
![列显示隐藏](https://user-images.githubusercontent.com/16933868/63560643-517f4f00-c589-11e9-8e7e-8cda0b1ac40b.png)

### （必填）填写期望的结果 Expected behavior

 可以控制是否显示为'...',或者显示'...'的时候有tooltip提示,或者直接都显示出来

### （必填）版本 Version

- os: windows10
- browser: firefox 68.x
- vue: 2.6.x
- vxe-table: 2.x

**Comment by xuliangzhan** [comment]
感觉这个用 title 应该就可以吧，因为本身就弹出层又再加一层 tooltip ？或者有哪些显示方式都可以讨论下

**Comment by chenchifeng** [comment]
@xuliangzhan 感谢
