### ISSUE TITLE
请问使用element插件的属性用props，表头只能用标签的形式来写吗？

### ISSUE THREAD

**Issue by peng6298351** [xuliangzhan/vxe-table#275]
### （必填）描述 Describe
请问我要使用element的属性，传props的时候，表头是必须写成标签的形式吗？

### 在线链接 
[这样没没问题](http://jsrun.pro/P7bKp/edit) 

 ### 截图 
![image](https://user-images.githubusercontent.com/44153193/63608878-88e11080-c608-11e9-9553-489e7a8bc80d.png)
##这样把表头直接已标签的形式写， 我使用edit-render里的props是没有问题的，能达到效果。  可是我把他写成组件已传值的方式写表头，props里的设置就没有效果 如下图所示
![image](https://user-images.githubusercontent.com/44153193/63609964-d78faa00-c60a-11e9-9d69-765ca0767ce8.png)

### 版本 Version

- os: Windows
- browser: Chrome
- vue: 2.6.10
- vxe-table: 1.5.13

**Comment by peng6298351** [comment]
麻烦再帮忙看下

**Comment by xuliangzhan** [comment]
这个我没看出 demo 链接有什么问题，能描述具体点不？

**Comment by peng6298351** [comment]
链接里怎么使用组件我不会，demo是没有问题的，demo是我想要的结果。 如果像下面这样使用组件就不行。
![image](https://user-images.githubusercontent.com/44153193/63633605-c6cc4c00-c67d-11e9-995b-abc7788f474a.png)
![image](https://user-images.githubusercontent.com/44153193/63633644-540fa080-c67e-11e9-9cb5-e5fc84952529.png)
父组件里没写完整，主要的写出来了。其实和demo里是一样的只是一个是直接使用你的，一个是以组件来的，但是以组件来就不行，
![image](https://user-images.githubusercontent.com/44153193/63633716-25de9080-c67f-11e9-8a57-dc6a01c77618.png)
你这个的这样写都可以，只是我不要那个grid的，需要自己写一个

**Comment by xuliangzhan** [comment]
这样写法是可以的，你应该检查下传参是否正确

**Comment by peng6298351** [comment]
好吧

**Comment by peng6298351** [comment]
你好，请问获取编辑数据的方法 getRecordset  是不是根据编辑状态来的，如果是那可以手动设置编辑状态吗？
如下图，我点击行右边的数据修改，我也要判断左边行不能让他编辑其他
[image: image.png]

Xu Liangzhan <notifications@github.com> 于2019年8月24日周六 下午3:42写道：
