### ISSUE TITLE
请问有获取footer行数据的方法吗

### ISSUE THREAD

**Issue by zxWendy** [xuliangzhan/vxe-table#277]

**Comment by xlz26296** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=getTableData

**Comment by zxWendy** [comment]
非常感谢，这个方法试过了，在单元格编辑完成后的事件edit-closed中，调用fetTableData获取不到footerData
![image](https://user-images.githubusercontent.com/6140203/63835843-e7144780-c9aa-11e9-8f5c-414f341713c3.png)

**Comment by zxWendy** [comment]
更新到最新版本有值了，可是不带property，怎么知道哪个字段是哪个啊
![image](https://user-images.githubusercontent.com/6140203/63838701-68220d80-c9b0-11e9-8cba-499947deda36.png)

**Comment by xuliangzhan** [comment]
footData 本身就是你自己生成的数据，为啥要用组件获取，这本身就是多此一举的操作

**Comment by zxWendy** [comment]
因为需要在别的地方重新显示，比如表格下面有个chart显示汇总信息，你没遇到不代表不存在！
