### ISSUE TITLE
按需引入Message模块出错

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#278]
### （必填）填写问题描述 Describe the bug
按需引入Message模块出错。现在只好把那段代码注释掉了
```
These dependencies were not found:

* vxe-table/lib/message in ./src/core/table.js
* vxe-table/lib/message/style in ./src/core/table.js

To install them, you can run: npm install --save vxe-table/lib/message vxe-table/lib/message/style
```

### （必填）填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）填写期望的结果 Expected behavior

 ?

### （必填）版本 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by maxmeng93** [comment]
看到是废弃掉了，不过文档没有更新。
https://xuliangzhan.com/vxe-table/index.html#/table/start/use

Excel Message 都没有了吧

**Comment by maxmeng93** [comment]
提了一个PR #279

**Comment by xuliangzhan** [comment]
新版功能更细的拆分了，Table 核心库体积减少、增加 Modal、Keyboard 模块，废弃 Message 模块
