### ISSUE TITLE
添加复制功能

### ISSUE THREAD

**Issue by garyhe0780** [xuliangzhan/vxe-table#281]
### （必填）这个需求解决了什么问题 What problem does this feature solve
像Excel一样，可以让用户复制table中某块区域的内容
 

### （必填）建议的 API 是什么样的 What does the proposed API look like
类似这样
```js
// Enables the plugin with default values
copyPaste: true,
// Enables the plugin with custom values
copyPaste: {
  columnsLimit: 25,
  rowsLimit: 50,
  pasteMode: 'shift_down',
},
```
 
### 是否已有其他不错的替代方案 Describe alternatives you've considered

 handsontable 有一个不错的实现，   [点我]( https://handsontable.com/docs/7.1.0/CopyPaste.html)

**Comment by xuliangzhan** [comment]
如果仿 excel 的话你参考这个插件 https://github.com/xuliangzhan/vxe-table-plugin-excel
