### ISSUE TITLE
loaddata是否可以这么初始化参数？

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#282]
### （必填）这个需求解决了什么问题 What problem does this feature solve
![image](https://user-images.githubusercontent.com/30314164/63768518-fdff5f00-c902-11e9-8d65-1069a3a2d10b.png)
![image](https://user-images.githubusercontent.com/30314164/63768565-1e2f1e00-c903-11e9-8841-84225dd3177f.png)
loaddata中是否可以直接像createData中那样直接初始化一遍data，来避免饿了么等组件参数未声明而导致的无法编辑问题呢，或者可以加一个参数去控制是否开启？

**Comment by wekerSnail** [comment]
试了一下，貌似并不行，依然不能编辑

**Comment by xuliangzhan** [comment]
严格意义上应该遵循 vue 的先定义后使用原则，你可以把 table 当做子组件封装，你就可以提前格式化数据了

**Comment by wekerSnail** [comment]
使用起来确实有些麻烦，我提交了一个自动初始化data的更新请求，初始化之后可以正常编辑，不知道能不能合并一下，或者有不妥的地方给改进一下
