### ISSUE TITLE
loadData真的阻断了vue的双向绑定吗？

### ISSUE THREAD

**Issue by moxao** [xuliangzhan/vxe-table#283]
### （必填）描述 Describe
API中说明当使用大数据时，使用loadData阻断双向绑定来提升性能，但是在vue开发工具中，还是看到了loadData的数据被绑定在VxeTable组件中的data中，当进行多行【两百多行】多列【近百个列】行内编辑时【多种可编辑组件】性能依然比较差，但API中的大数据行内编辑性能却不错，难道是我使用的姿势不对？
this.$refs.xTable.loadData(tableData)

### 版本 Version

- os: window 10
- browser: chrome
- vue: ~
- vxe-table: ~

**Comment by xlz26296** [comment]
可编辑的数据量多的话你可以把 [scrollY](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=scrollY) 到 200 左右

**Comment by moxao** [comment]
> 可编辑的数据量多的话你可以把 [scrollY](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=scrollY) 到 200 左右

渲染上的性能是没问题的，由于双向绑定的数据量太大行内编辑就会变的延迟很高。

**Comment by xuliangzhan** [comment]
如果渲染量比较大的话启用虚拟滚动就可以缓解卡顿问题了
