### ISSUE TITLE
关于v-slot:edit用法不明确，望解惑

### ISSUE THREAD

**Issue by ZZHHzzhh** [xuliangzhan/vxe-table#285]
### （必填）描述 Describe
![image](https://user-images.githubusercontent.com/24787702/63781089-c7820e00-c91b-11e9-8f8f-7d0725b8d9c5.png)

![image](https://user-images.githubusercontent.com/24787702/63781157-e5e80980-c91b-11e9-9cf2-10f434ca6fbe.png)

请问这样使用v-slot:edit={ row },和文档的用法一致，为啥会报错呢，希望作者大大看到能给解惑，折腾一天了

**Comment by xuliangzhan** [comment]
#286
