### ISSUE TITLE
关于v-slot:edit用法

### ISSUE THREAD

**Issue by ZZHHzzhh** [xuliangzhan/vxe-table#286]
### （必填）描述 Describe
在表格中添加input插槽，借鉴文档中的案例，输入框是可以正常展示，但是在编辑时候，会报错
 row is not defined。希望作者可以百忙之中看看，并给我些提示

### （必填）能重现问题的链接
只是本地项目，暂时没有外网访问路径

 ?

### 报错信息或截图 Error message or screenshots
这是代码
![image](https://user-images.githubusercontent.com/24787702/63782783-82aba680-c91e-11e9-8e40-0a23efc706f3.png)
这是控制台报错信息
![image](https://user-images.githubusercontent.com/24787702/63781157-e5e80980-c91b-11e9-9cf2-10f434ca6fbe.png)
 ?

### 版本 Version

- os: ? windows
- browser: ? chrome76
- vue: ?  是的
- vxe-table: ? 是的

**Comment by xuliangzhan** [comment]
我只想知道你的版本信息，你都没填，这错很明显就是 vue 版本问题，v-slot 是 vue2.6+ 的新语法，你应该检查下使用的 vue 版本

**Comment by ZZHHzzhh** [comment]
谢谢，我看了下项目是2.3版本的，我再仔细看看vue的插槽用法，很感谢这么晚还回复我的问题，祝您工作顺利，家庭美满




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 晚上11:15
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>;
抄送: "周欢"<759918086@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuliangzhan/vxe-table] 关于v-slot:edit用法 (#286)




我只想知道你的版本信息，你都没填，这错很明显就是 vue 版本问题，v-slot 是 vue2.6+ 的新语法，你应该检查下使用的 vue 版本
