### ISSUE TITLE
合计行如果是浮点数合计，小数部分会不正常 

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#288]
### （必填）这个需求解决了什么问题 What problem does this feature solve
![image](https://user-images.githubusercontent.com/20534088/63817263-1e183800-c96e-11e9-89ce-d69a6f8cf1c2.png)

 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
希望uploadFooter开放参数，可自定义小数保留的位数
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
这个和表格有什么？怎么计算是你自己的业务逻辑

**Comment by zxWendy** [comment]
对，我也有这个问题，虽然怎么计算是自己决定，但是合计行不受formatter控制，也没有额外的方法，能让真实值和显示值不一样，比如计算值是3.55556，显示保留两位小数3.55

**Comment by xlz26296** [comment]
@zxWendy 你这就多此一举了，你都知道是自己写的计算，那计算时去把精度处理一下不就行了

**Comment by XianYue-Tong** [comment]
![image](https://user-images.githubusercontent.com/20534088/63905205-19bf4e00-ca46-11e9-9fc9-abbbdf57af18.png)
我这在合计行的方法里 做了位数显示

**Comment by xlz26296** [comment]
@XianYue-Tong  官网的 XEUtils.sum 仅是提供示例而已，你想怎么处理精度自己写运算不就行了

**Comment by XianYue-Tong** [comment]
是的 我这边已经处理好了 这个确实跟表格没关系  之前想的不对

**Comment by zxWendy** [comment]
@xlz26296 我想要的是formatter的那种效果，不改变真实值，因为后面要拿出来计算，只是显示上不一样而已

**Comment by xuliangzhan** [comment]
表尾合计本身就是个方法，至于你要怎么算还是保存数据，业务逻辑自行去实现就行了

**Comment by zxWendy** [comment]
@xuliangzhan 那你显示倒是跟formatter保持一致啊，既然合计行显示在table上，起码要保持整体性吧。没要求你们一定改，只是询问下解决办法，不用那么排斥，如果你们没有解决办法，我们会寻找别的代替方法
![image](https://user-images.githubusercontent.com/6140203/63996476-68e0ae00-cb2e-11e9-9844-aa41767247a6.png)

**Comment by zxWendy** [comment]
@XianYue-Tong 不好意思，在您的问题下占用了这么久，一般遇到问题我会先搜索是否已经有别人遇到过，并被解决的，这样避免重复提问。如果您的问题已经解决了，可以点关闭的哈

**Comment by xlz26296** [comment]
@zxWendy  表尾合计并不属于列，只是额外统计信息，没有 formatter 概念

**Comment by xuliangzhan** [comment]
@zxWendy 抱歉，未通过重现链接来描述问题的，我也没法帮到你，毕竟我也不可能有时间去给每个人重现问题

**Comment by adoin** [comment]
JS 精度问题 ；
写着玩的拿去玩吧。
function currencyAdd () {
  let res = 0
  try {
    for (let i = 0; i < arguments.length; i++) {
      res += arguments[i].toFixed(2) - 0
    }
  } catch (e) {
    return '无法累加'
  }
  return res - 0
}

function currencyMinus () {
  try {
    if (arguments.length > 1) {
      let res = arguments[0]
      for (let i = 1; i < arguments.length; i++) {
        res -= arguments[i].toFixed(2) - 0
      }
      return res - 0
    } else if (arguments.length === 1) {
      return arguments[0] - 0
    } else {
      return '无相减对象'
    }
  } catch (e) {
    return '无法相减'
  }
}
