### ISSUE TITLE
table中自定义模板要怎么拿到index下标值呢！麻烦了

### ISSUE THREAD

**Issue by cuilongshui** [xuliangzhan/vxe-table#29]
**描述 Describe**
如果提供信息不详细的作者可能不会答复及解决！

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by lishihong** [comment]
更新到最新版，拿slot的rowIndex

**Comment by xuliangzhan** [comment]
#26
