### ISSUE TITLE
键盘导航中其它键直接进入编辑模式的情况下，拼音输入法下第一个字母不会被录进去

### ISSUE THREAD

**Issue by nthalo** [xuliangzhan/vxe-table#291]
### （必填）请填写问题描述 Describe the bug

 如题

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/w8q6unes/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://xuliangzhan.github.io/vxe-table/#/table/edit/keyboard

### 填写报错信息或截图 Error message or screenshots

![QQ截图20190828155425](https://user-images.githubusercontent.com/45553318/63836412-18d9de00-c9ac-11e9-9144-115ba9cde82b.png)
可以看到q并没有被包含进去

### （必填）请填写期望的结果 Expected behavior

 希望能改进这个问题

### （必填）请填写版本号 Version

- os: win10
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
这个问题早有发现，不过估计这个问题不好修复，因为第一个按钮是触发激活编辑事件的，但愿能修复吧

**Comment by xuliangzhan** [comment]
抱歉，这个功能目前无法支持

**Comment by fh345392977** [comment]
可以先按一下空格再输入，按空格进入坦克

**Comment by xuliangzhan** [comment]
[fix](https://vxeui.com/#/component/grid/keyboard/edit)
