### ISSUE TITLE
vxe-input 能否在右边添加一个可以点击的小按钮

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#292]
### （必填）这个需求解决了什么问题 What problem does this feature solve

vxe-input 能否在右边添加一个可以点击的小按钮，类似下图

### （必填）建议的 API 是什么样的 What does the proposed API look like
![微信截图_20190828161003](https://user-images.githubusercontent.com/4531974/63837586-563f6b00-c9ae-11e9-935b-46ee05ac643d.png)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
这个你可以用第三方组件库，没必要用这个
