### ISSUE TITLE
Can I toggle checkbox on keyboard navigation?

### ISSUE THREAD

**Issue by Nag729** [xuliangzhan/vxe-table#293]
### Describe
Thank you for great work!

I have a question about Keyboard Navigation on Checkbox.
**Can I toggle checkbox on keyboard?**

The checkbox I say is related to the following URL.
https://xuliangzhan.com/vxe-table/index.html#/table/base/selection

I looked for a guide and issues, but I cannot find the answer.
So, please help me.

(I'm a Japanese, sorry for Not Chinese and Not good English.)

### Version
- os: Win10
- browser: Chrome
- vue: 2.6.10
- vxe-table: 2.3.4

**Comment by xuliangzhan** [comment]
你可以参考这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/keyboard

**Comment by Nag729** [comment]
It worked! Thank you so much!

And I have two additional questions.

1. **Can I toggle Header checkbox on keyboard?**

2. **Can I focus on the checkbox after blur?**
I want to focus on the checkbox on table after I blur other form elements.
(like buttons.)

If these things are possible, please tell me how.

Thank you for your support!

**Comment by xuliangzhan** [comment]
Not sure what you mean, you should use the online link to describe the problem
