### ISSUE TITLE
data.sync是可行的吗

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#294]
### （必填）请填写问题描述 Describe
在代码中并没有找到`this.emit(update:data)`的事件，所以有点好奇sync是否起作用，或者说这边的sync是怎么实现的，准备把vxe-grid作为子组件去封装处理data
?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
组件本身不会去更改 data 的值，所以加不加都没关系，后续对于某些插件可能会用到，加上可以兼容后续如果存在某些特殊场景需要更新 data 的时候不需要任何改动了
