### ISSUE TITLE
不设置列宽度，内容自动撑开不换行，列宽度自动匹配而不是均等，超出部分显示滚动条

### ISSUE THREAD

**Issue by zdyWork** [xuliangzhan/vxe-table#295]
### （必填）请填写问题描述 Describe
想要列的宽度根据内容自动分配内容不换行，就是原生最基本的表格需求。
?

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
这个你只能自行做个选择了：
1.使用组件的计算模式是没有自适应的概念的，必须预知宽度，支持复杂功能
2.使用原生table自适应内容宽度，无法支持固定列...等复杂功能

**Comment by xiaogaofudao** [comment]
同问，是否可以保持和 el-table 相同的逻辑。表格自动充满父级宽度。每一个column 可以定部分确定的宽度。剩余的不设置宽度的column 自动分配剩余宽度。超过设置 showOverflow
