### ISSUE TITLE
列宽可以根据内容自动匹配吗？

### ISSUE THREAD

**Issue by zdyWork** [xuliangzhan/vxe-table#296]
### （必填）请填写问题描述 Describe
列宽根据内容自动匹配，不需要单独设置宽度，像原生的表格功能一样。
?

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
#295

**Comment by xuliangzhan** [comment]
内容自适应你应该使用原生的 table，这个是不支持的
