### ISSUE TITLE
树表格，默认选择

### ISSUE THREAD

**Issue by Zz1204** [xuliangzhan/vxe-table#297]
### （必填）请填写问题描述 Describe

你好，现在遇到这样一个需求：
![image](https://user-images.githubusercontent.com/34231460/63905534-2001fa00-ca47-11e9-9261-2f6b054c5a9a.png)
请求左侧用户已经有的菜单，赋值到右侧树表格当中作为默认选中；
当我第一次赋值的时候没有出现问题；
当我获取另外一个用户的菜单（此时为[]，这个用户没有菜单），修改selectConfig.checkRowKeys后，右侧的树表格依然会是第一个用户默认选中的选项；
第二次赋值后如何刷新右侧树表格的视图和他选中的选项？

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://jsfiddle.net/9jz7hv8x/25/

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: 2.4.2?

**Comment by Zz1204** [comment]
我暂时先用的v-if特性重新加载的

**Comment by xuliangzhan** [comment]
你要明白默认选中和更新选中是两个概念；
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=checkRowKeys
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=setSelection
