### ISSUE TITLE
route中keep-alive之后，表格横向滚动一些，切到别的路由在切回来，会出现列错位的情况

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#298]
### （必填）请填写问题描述 Describe the bug
![微信截图_20190829150027](https://user-images.githubusercontent.com/30314164/63919910-412c1000-ca72-11e9-8cb2-00588d84031c.png)
只有表格横向 滚动过才会出现

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
在`activated`中调用`recalculate`也无法复原，不过不影响正常的横向滚动，一滚动就会复原

**Comment by xiaogaofudao** [comment]
刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错 
_xeUtils.default.browse is not a function

**Comment by wekerSnail** [comment]
https://jsrun.pro/FJbKp/edit
我说线上怎么一直复现不了呢，原来是修复了😂

**Comment by wekerSnail** [comment]
新版本又出现了，2.6.13仍存在

**Comment by 15560099568** [comment]
> 新版本又出现了，2.6.13仍存在

现在有解决方案了吗
