### ISSUE TITLE
隐藏表头后点击会报错

### ISSUE THREAD

**Issue by name9958** [xuliangzhan/vxe-table#299]
### （必填）请填写问题描述 Describe the bug
隐藏表头后点击表格会报错，显示表头就没问题
 ?

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/52946096/63926864-290ebd80-ca7f-11e9-960a-d618cc30bae6.png)

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
#300
