### ISSUE TITLE
data-grid可以配置 index 行索引吗

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#3]

**Comment by xuliangzhan** [comment]
设置 type=index 就行

**Comment by lishihong** [comment]
`<vxe-grid
      border
      resizable
      height="600"
      :columns="tableColumn"
      :loading="loading"
      :data.sync="tableData">
    </vxe-grid>`
这种方式的，有可以设置type=index吗

**Comment by xuliangzhan** [comment]
一模一样。该怎么传还是怎么传
```javascript
tableColumn=[{type: 'index', label: '序号'}, {prop: 'name', label: '名字'}]
```

**Comment by lishihong** [comment]
棒！
