### ISSUE TITLE
（隐藏表头）show-header设置false之后控制台报错

### ISSUE THREAD

**Issue by nthalo** [xuliangzhan/vxe-table#300]
### （必填）请填写问题描述 Describe the bug

 show-header设置false之后控制台报错

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://xuliangzhan.github.io/vxe-table/#/table/edit/keyboard

### 填写报错信息或截图 Error message or screenshots

 设置:show-header="false"后表头隐藏
![QQ截图20190829171512](https://user-images.githubusercontent.com/45553318/63927721-d930f600-ca80-11e9-9084-c470f11a4093.png)
然后点击单元格是不会被选中的，蓝色框不出现，控制台报错
![QQ截图20190829171458](https://user-images.githubusercontent.com/45553318/63927929-3d53ba00-ca81-11e9-9f38-898c03716f73.png)
如果先设置成true，再设置成false，是没有问题的，但刷新页面问题就出现了
![QQ截图20190829172244](https://user-images.githubusercontent.com/45553318/63928055-7ee46500-ca81-11e9-9fc2-79235600a81e.png)

### （必填）请填写期望的结果 Expected behavior

 希望此bug能修复

### （必填）请填写版本号 Version

- os: win10
- browser: ?
- vue: 2.9.6
- vxe-table: 2.4.6

**Comment by nthalo** [comment]
还不够规范吗.....简单点说就是vxe-grid内设置了:show-header="false"隐藏表头的时候就没办法选中单元格了，会报上面的错误。

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下哈
要提 Issues 就必须提供重现链接，模板已经写得很清楚了哦，而且各种链接示例都有；
没办法额，如果提 Issues 连个重现链接都不想写清楚，那我也是一样可以看心情解决喽， 哈

**Comment by nthalo** [comment]
非常感谢，最新版本已经修复了。至于重现链接，我以后会尽量注意的
