### ISSUE TITLE
刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错 _xeUtils.default.browse is not a function

### ISSUE THREAD

**Issue by xiaogaofudao** [xuliangzhan/vxe-table#302]
刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错
_xeUtils.default.browse is not a function

**Comment by xiaogaofudao** [comment]
vxe-table 降级到 2.4.7。可以正常运行。开启 auto-resize 程序报错如下。
Error in mounted hook: "TypeError: this.bindResize is not a function"

**Comment by xlz26296** [comment]
使用方式看这里 https://github.com/xuliangzhan/vxe-table-demo

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/63989162-f5c93e80-cb11-11e9-8bc6-6f0379d1d942.png)
![image](https://user-images.githubusercontent.com/30314164/63989200-20b39280-cb12-11e9-979d-542ff6b19229.png)
更新2.5.1有遇到类似问题。xe-util有安装

**Comment by wekerSnail** [comment]
看起来是文件结构改变导致的，安装2.2.1的xe-utils就好了，不过感觉应该需要给一个说明，不然直接安装都会遇到这个问题

**Comment by xlz26296** [comment]
你应该看更新日志，控制台应该也有提示

**Comment by wekerSnail** [comment]
更新完会报如上_xeUtils.default.browse is not a function的错误，使用方法是按照demo中的写法

**Comment by xiaogaofudao** [comment]
嗯可以在文档里备注下，非常感谢

**Comment by xlz26296** [comment]
默认安装方式支持任意版本
```javascript
import Vue from 'vue'
import 'xe-utils'
import VXETable from 'vxe-table'
import 'vxe-table/lib/index.css'

Vue.use(VXETable)
```

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/63990165-95d49700-cb15-11e9-9c7f-c1903dddbed9.png)
![image](https://user-images.githubusercontent.com/30314164/63990186-ad138480-cb15-11e9-89a8-56692e0e2a17.png)
不太清楚是什么问题
这是我的配置
![image](https://user-images.githubusercontent.com/30314164/63990207-bdc3fa80-cb15-11e9-8535-64de8a8a5beb.png)

**Comment by xiaogaofudao** [comment]
我的也是这个问题。
vxe-table.js:63 Uncaught TypeError: VXETable.setup is not a function

**Comment by xiaogaofudao** [comment]
之前报的错误是没写 import 'xe-utils' 这行。现在加入这行代码。报新错误了

**Comment by wekerSnail** [comment]
我的问题和你是一致的

**Comment by zzxCNCZ** [comment]
同样的问题

**Comment by zzxCNCZ** [comment]
> 我的问题和你是一致的

你现在可行的版本是哪个啊

**Comment by thisisonepz** [comment]
如果你们只是用到table 组件的话，可以尝试注释掉这个，然后去入口文件去注册body   header  以及table和column

**Comment by thisisonepz** [comment]
![image](https://user-images.githubusercontent.com/28385124/63991988-69704900-cb1c-11e9-938a-6f1aa20f093d.png)
就像这样 然后
![image](https://user-images.githubusercontent.com/28385124/63992003-77be6500-cb1c-11e9-8fe5-369ebd987cfd.png)

**Comment by xiaogaofudao** [comment]
@xuliangzhan 经测试可以运行。加入 auto-resize 报错
Error in mounted hook: "TypeError: this.bindResize is not a function"

**Comment by zzxCNCZ** [comment]
"vxe-table": "^2.5.2",
"vxe-table-plugin-element": "^1.4.2",
"xe-utils": "^2.2.1"
可以正常运行了

**Comment by xiaogaofudao** [comment]
刚大概看了下关于 resize 这块的源码。发现是基于 定时器默认 250ms 检测宽度变化。会有一些延迟。
大佬是不是可以考虑 https://www.npmjs.com/package/resize-observer-polyfill 这块做个优化啊，都不支持在考虑 定时器方案

**Comment by xiaogaofudao** [comment]
@xuliangzhan resize Object.assign 好像没有把 methods 合并到 table methods 里面。造成 this.bindResize 和 this.unbindResize 找不到方法。

`mounted () {
    if (this.autoResize && VXETable._resize) {
      this.bindResize(this, this.$el.parentNode, this.recalculate)
    }
  },
  beforeDestroy () {
    if (VXETable._resize) {
      this.unbindResize(this, this.$el.parentNode)
    }
  },`

在beforeDestroy  没有判断 this.unbindResize 是否存在。会导致没有开启 auto-resize 直接报错

**Comment by xiaogaofudao** [comment]
目前采用在外部判断父级元素宽度是否变化，调用 recalculate 方法 进行表格宽度布局更新
测试了 resize-observer-polyfill 发现挺好用的

**Comment by xiaogaofudao** [comment]
刚才发现了一个新的问题，100% 必现。
我的使用情况大概如下：
首先每隔十几秒会调用 loadData 更新表格数据
表格内嵌到 el-tabs 选项卡
当用户切换到其他选项卡，vxe-table 处于隐藏状态。
此时在表格不可见时，并且用户把表格滚动到了 开启虚拟滚动的位置（备注：如果没有滚动数据处于第一条，则不会出现）如果这个时候调用 loadData 更新数据后，用户切换到 表格选项卡。会出现白屏现象，随便滚动下滚动条恢复正常。
目前通过业务规避此Bug。当表格不可见，不执行 loadData 函数

**Comment by xuliangzhan** [comment]
ResizeObserver 只有 Chrome 支持 ，后续版本会支持这个方式，确实非常好

**Comment by xiaogaofudao** [comment]
额发现了个新问题。。。
之前以为是 2.5.x 版本会出现白屏，然后降级为 2.4.7 测试。补充下白屏的Bug触发原因。
如果 loadData 加载数据后。用户随意滚动下滚动条。组件内部应该记录了滚动位置。如果 loadData 空数组执行清空。组件感觉没有重置滚动条位置。再次 loadData 数据。 marginTop 会直接上次记录缓存的 滚动位置。从而出现白屏。感觉和 元素是否可见，包括高度为零这种出现白屏还不太一样

**Comment by xuliangzhan** [comment]
如果有问题请通过重现链接来描述哦

**Comment by xiaogaofudao** [comment]
复现链接。 chrome 76 100% 必现

https://jsrun.pro/TxbKp/edit

**Comment by xiaogaofudao** [comment]
白屏Bug 2
https://jsrun.pro/nxbKp/edit

**Comment by xiaogaofudao** [comment]
> ResizeObserver 只有 Chrome 支持 ，后续版本会支持这个方式，确实非常好
resize-observer-polyfill 可以支持其他现代浏览器，不支持 ResizeObserver 时会自动降级为 MutationObserver 实现。MutationObserver 支持的浏览器比较广基本覆盖了

**Comment by yushengling** [comment]
@xiaogaofudao @xuliangzhan 这个BUG完全修复了吗? 目前如果需要使用,ve-utils,vxe-table应该对应的版本是多少

**Comment by wekerSnail** [comment]
最新的版本

**Comment by yushengling** [comment]
> ![image](https://user-images.githubusercontent.com/30314164/63990165-95d49700-cb15-11e9-9c7f-c1903dddbed9.png)
> ![image](https://user-images.githubusercontent.com/30314164/63990186-ad138480-cb15-11e9-89a8-56692e0e2a17.png)
> 不太清楚是什么问题
> 这是我的配置
> ![image](https://user-images.githubusercontent.com/30314164/63990207-bdc3fa80-cb15-11e9-8535-64de8a8a5beb.png)

你的这个问题解决了吗?现在你的版本号是xe-utils,vxe-table多少版本

**Comment by wekerSnail** [comment]
最新版本可以使用，或者你使用2.5.0以下的版本（不包括2.5.0）

**Comment by yushengling** [comment]
> 最新的版本

1121513
947 QQ 了解下

**Comment by wekerSnail** [comment]
按照文档和demo安装配置就可以正常使用的

**Comment by yushengling** [comment]
我看下官方最新的是vxe-table2.5.8,xe-utils2.2.2.这个版本是包装没有问题是多么?

**Comment by xiaogaofudao** [comment]
> 我看下官方最新的是vxe-table2.5.8,xe-utils2.2.2.这个版本是包装没有问题是多么?

这个版本能用如果时全局导入使用，记得把 babel.config.js 里面按需导入的配置去掉

**Comment by yushengling** [comment]
或者降至那个版本可以稳定使用,不会出现那个错误.,刚开始我使用的是vxe-table2.37,xe-utils2.07.可以正常使用.线上自动化部署就出问题了.能不能加个好友协助下怎么解决1121513947







------------------ 原始邮件 ------------------
发件人: "John Gao"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午4:30
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "余胜灵"<1121513947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] 刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错 _xeUtils.default.browse is not a function (#302)



 
我看下官方最新的是vxe-table2.5.8,xe-utils2.2.2.这个版本是包装没有问题是多么?
  
这个版本能用如果时全局导入使用，记得把 babel.config.js 里面按需导入的配置去掉

**Comment by yushengling** [comment]
我没有使用按需加载babel.config.js 







------------------ 原始邮件 ------------------
发件人: "John Gao"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午4:30
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com>; 
抄送: "余胜灵"<1121513947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [xuliangzhan/vxe-table] 刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错 _xeUtils.default.browse is not a function (#302)



 
我看下官方最新的是vxe-table2.5.8,xe-utils2.2.2.这个版本是包装没有问题是多么?
  
这个版本能用如果时全局导入使用，记得把 babel.config.js 里面按需导入的配置去掉

**Comment by xlz26296** [comment]
@yushengling 你报错的那个截图很明显就是 2.5.1 的代码，2.5.2以上不会报这个错

**Comment by yushengling** [comment]
> 刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错
> _xeUtils.default.browse is not a function
是出现这个问题
![image](https://user-images.githubusercontent.com/19568401/64106942-da796000-cdab-11e9-82ed-915b6a4153d8.png)

**Comment by xlz26296** [comment]
@yushengling 你上传个空项目看下

**Comment by xiaogaofudao** [comment]
@yushengling  请确定package.json vxe-table 版本。如果不是最新的。执行 npm update vxe-table 升级。这个报错，确定最新版本已修复

**Comment by chenchifeng** [comment]
@xiaogaofudao 请问最后怎么解决了?
我使用命令行更新了还是报错.也不知道怎么解决.
```shell
npm update xe-utils vxe-table
```
报错:
![图片](https://user-images.githubusercontent.com/16933868/64136924-8744f300-ce27-11e9-837a-d8e9e8a71363.png)

**Comment by yushengling** [comment]
> @xiaogaofudao 请问最后怎么解决了?
> 我使用命令行更新了还是报错.也不知道怎么解决.
> 
> ```shell
> npm update xe-utils vxe-table
> ```
> 
> 报错:
> ![图片](https://user-images.githubusercontent.com/16933868/64136924-8744f300-ce27-11e9-837a-d8e9e8a71363.png)
你的这个我问题解决了吗

**Comment by chenchifeng** [comment]
> 
> 
> > @xiaogaofudao 请问最后怎么解决了?
> > 我使用命令行更新了还是报错.也不知道怎么解决.
> > ```shell
> > npm update xe-utils vxe-table
> > ```
> > 
> > 
> > 报错:
> > ![图片](https://user-images.githubusercontent.com/16933868/64136924-8744f300-ce27-11e9-837a-d8e9e8a71363.png)
> > 你的这个我问题解决了吗

我现在是降级回到2.3.7了
```js
npm install vxe-table@2.3.7
npm install xe-utils@2.0.7
```

**Comment by yushengling** [comment]
npm install vxe-table@2.3.7 npm install xe-utils@2.0.7 我的版本也是退出到你说的版本@2.3.7.@2.0.7但是到了线上自动化部署,下载安装包 vxe-table还是出错



------------------ 原始邮件 ------------------
发件人: "aFung"; 
发送时间: 2019年9月3日(星期二) 上午9:42
收件人: "xuliangzhan/vxe-table";
抄送: "余胜灵"<1121513947@qq.com>;"Mention";
主题: Re: [xuliangzhan/vxe-table] 刚升级了 vxe-table. 从2.4.7 到 2.5.1。xeUtils 都是2.2.1。程序报错 _xeUtils.default.browse is not a function (#302)



  
@xiaogaofudao 请问最后怎么解决了?
 我使用命令行更新了还是报错.也不知道怎么解决.
 npm update xe-utils vxe-table
 
报错:
 
 你的这个我问题解决了吗
   
我现在是降级回到2.3.7了
 npm install vxe-table@2.3.7 npm install xe-utils@2.0.7
 
&mdash;

**Comment by DoubleWoodH** [comment]
https://github.com/xuliangzhan/vxe-table-demo
![image](https://user-images.githubusercontent.com/20528848/64254890-de93b200-cf52-11e9-9cbe-0844addb942c.png)
我按照demo的提示在 `import VXETable from 'vxe-table'` 之前 导入了 'xe-utils' 包 `import VXETable from 'vxe-table'` 解决了问题

**Comment by xiaogaofudao** [comment]
@xuliangzhan  
https://jsrun.pro/nxbKp/edit
这个白屏问题，在框架层好解决么，或者在框架层避开此问题

**Comment by xlz26296** [comment]
#230

**Comment by guaijie** [comment]
@xuliangzhan  
跟新版本后修改，以前修改的样式怎么没了
