### ISSUE TITLE
table的横纵滚动条是否可以根据浏览器的滚动条来控制

### ISSUE THREAD

**Issue by hukoutuoxian** [xuliangzhan/vxe-table#303]
### （必填）这个需求解决了什么问题 What problem does this feature solve

y轴场景:数据过长需要y向滚动 可以是否通过浏览器的y滚动条来拖动

x轴场景:数据过长需要x向滚动 可以是否通过浏览器的x滚动条来拖动

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 暂无 感觉和css可能有关系

**Comment by hukoutuoxian** [comment]
有讨论群吗  大大

**Comment by xuliangzhan** [comment]
我可能没有时间去搞群哦，有问题按规范提 Issues 就行
