### ISSUE TITLE
elx-editable-column 弹框选择数据，返回ID

### ISSUE THREAD

**Issue by liguansen** [xuliangzhan/vxe-table#304]
参考代码：
<elx-editable-column prop="materialname" label="物料名称" min-width="200":edit-render="{name: 'ElInput'}"></elx-editable-column>
![image](https://user-images.githubusercontent.com/45783888/63999247-9715bc00-cb35-11e9-9027-3776323b0bf5.png)

API上暂时没有提供弹框组件：
![image](https://user-images.githubusercontent.com/45783888/63999331-cc220e80-cb35-11e9-8cd1-e195f0ad3879.png)

较底下的API：https://gitee.com/xuliangzhan_admin/vue-element-extends

提前谢谢

**Comment by xuliangzhan** [comment]
https://github.com/xuliangzhan/vue-element-extends/issues
这个你走错片场了哈，你应该使用自定义模板去实现
