### ISSUE TITLE
vxe-table-column 的title属性是否可以增加识别html标签？现在是只能字符串，会把标签原样输出

### ISSUE THREAD

**Issue by XianYue-Tong** [xuliangzhan/vxe-table#305]
### （必填）这个需求解决了什么问题 What problem does this feature solve
![image](https://user-images.githubusercontent.com/20534088/63999480-1dca9900-cb36-11e9-856a-1c66eff91652.png)
![image](https://user-images.githubusercontent.com/20534088/63999505-2fac3c00-cb36-11e9-93cf-ed945d0129c6.png)

 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
希望title增加识别html标签，这样就可以通过标签自定义列头的样式了
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/template

**Comment by yzway** [comment]
同问，请问这个该如何处理，谢谢
