### ISSUE TITLE
不知道这个是使用姿势不正确还是BUG

### ISSUE THREAD

**Issue by 382615666** [xuliangzhan/vxe-table#306]
### （必填）请填写问题描述 Describe the bug

![image](https://user-images.githubusercontent.com/11493897/64003492-ead8d300-cb3e-11e9-9519-40a8a8072cf5.png)

 
![image](https://user-images.githubusercontent.com/11493897/64003713-689cde80-cb3f-11e9-8d3f-429384e3668d.png)

![image](https://user-images.githubusercontent.com/11493897/64004596-21afe880-cb41-11e9-88a0-62becc173f6b.png)

当把全局设置里面的 scrollX.gt 改成稍微大点的值又好了，比如20

 由于隐私问题，不方便提供在线重现链接，请见谅

 看能不能修复吧，如果不能，修改配置也能正常使用

- os: win7
- browser: chrome 70.0.3538.67
- vue: ^2.6.10
- vxe-table: ^2.2.7

**Comment by xiaogaofudao** [comment]
刚才发现了一个新的问题，100% 必现。
我的使用情况大概如下：
首先每隔十几秒会调用 loadData 更新表格数据
表格内嵌到 el-tabs 选项卡
当用户切换到其他选项卡，vxe-table 处于隐藏状态。
此时在表格不可见时，并且用户把表格滚动到了 开启虚拟滚动的位置（备注：如果没有滚动数据处于第一条，则不会出现）如果这个时候调用 loadData 更新数据后，用户切换到 表格选项卡。会出现白屏现象，随便滚动下滚动条恢复正常。
目前通过业务规避此Bug。当表格不可见，不执行 loadData 函数
