### ISSUE TITLE
大数据列表开启单元格选择 :mouse-config="{selected:true}" 出现bug

### ISSUE THREAD

**Issue by shawon1220** [xuliangzhan/vxe-table#307]
### （必填）请填写问题描述 Describe the bug
 1、大数据列表开启单元格选择 :mouse-config="{selected:true}"，单元格选择框会跟着滚动条滚动。
2、按上下键选中单元格到底部时，纵向滚动条不会滚动，单元格高亮框消失

### （必填）请填写期望的结果 Expected behavior
 1、单元格高亮应该固定在选中的单元格
 2、选中单元格到底部时，纵向滚动条应该滚动到当前行

### （必填）请填写版本号 Version
- vxe-table: 2.5.2?

**Comment by xuliangzhan** [comment]
虚拟滚动目前是不支持 mouse-config 的
