### ISSUE TITLE
showOverflow + fixed 会出现row无法对齐的问题

### ISSUE THREAD

**Issue by fh345392977** [xuliangzhan/vxe-table#308]
### （必填）请填写问题描述 Describe the bug

 showOverflow + fixed 时，如果fixed的那一列的高度大于其他列，会出现row无法对齐的问题。

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[https://jsrun.pro/uJbKp/edit](http://jsrun.pro/MJbKp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/16329330/64008489-cda90200-cb48-11e9-9001-3599e2dfbdbb.png)

### （必填）请填写期望的结果 Expected behavior

 期望可以du对齐

### （必填）请填写版本号 Version

- os: OSX 10.14.6
- browser: Chrome 76.0.3809.100（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 2.5.2

**Comment by fh345392977** [comment]
目前的解决方法是，table不设置show-overflow，给需要的列单独加上show-overflow

**Comment by xuliangzhan** [comment]
#175

**Comment by fh345392977** [comment]
出现bug的原因是，表格show-overflow时，最后的fixed那一列(这一列里是按钮)没有渲染出来，td里是空的，所以高度没撑起来。

**Comment by fh345392977** [comment]
[https://jsrun.pro/uJbKp/edit](https://jsrun.pro/uJbKp/edit)

**Comment by xuliangzhan** [comment]
这个明显就被撑坏了，样式兼容性需要自行解决的

**Comment by fh345392977** [comment]
![image](https://user-images.githubusercontent.com/16329330/64017607-95abba00-cb5c-11e9-9066-3bef4cf40da5.png)

**Comment by fh345392977** [comment]
不使用show-overflow 这个td里面就有内容，就能撑起表格

**Comment by xuliangzhan** [comment]
这个问题是样式引起的，下版本修复

**Comment by hasbug** [comment]
问题依旧，最新版。所以还得按照1楼的做法
