### ISSUE TITLE
默认的键盘导航，能否增加方向键左右切换页码的功能？

### ISSUE THREAD

**Issue by fh345392977** [xuliangzhan/vxe-table#311]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 实现了全键盘的浏览表格数据

### （必填）建议的 API 是什么样的 What does the proposed API look like

和keyboard-config保持一样，增加changePage 属性表示允许切换页码，changePage内有两个key，nextPage,prevPage,表示下一页和上一页的快捷键，默认是方向键的左右

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 因为表格只监听了上下，目前可以从外部监听左右按键，然后调用table的方法来切换实现。但这样的实现感觉怪怪的

**Comment by xuliangzhan** [comment]
实现倒是简单，只是方向键有很多特定的功能。单元格移到、光标移动、滚动条移动等...；过多等功能可能会导致冲突

**Comment by fh345392977** [comment]
我记得编辑模式下，方向键已经变成了单元格的移动。这样与编辑模式就不冲突。而且api的设计是可以指定快捷键的，冲突的事情应该可以避免。

**Comment by xuliangzhan** [comment]
这个要先设计一下 API，后续版本可以考虑支持

**Comment by xuliangzhan** [comment]
如果想要拦截按键行为，或者实现一些特定的功能，你可以通过 [vxe-table-plugin-shortcut-key](https://www.npmjs.com/package/vxe-table-plugin-shortcut-key) 该插件实现

**Comment by fh345392977** [comment]
ok，晚上试试

**Comment by geekLeopoldFitz** [comment]
请问这里如果要把enter的事件赋予给ArrowDown可以使用vxe-table-plugin-shortcut-key插件中的listener方法吗？
