### ISSUE TITLE
width和min-width为小数时列宽异常

### ISSUE THREAD

**Issue by fh345392977** [xuliangzhan/vxe-table#312]
### （必填）请填写问题描述 Describe the bug

 小数的width和min-width无效果。

### （必填）请填写能重现问题的链接（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[https://jsrun.pro/axbKp/edit](https://jsrun.pro/axbKp/edit)

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/16329330/64060845-01e1f880-cc05-11e9-9d0a-12444ef3bcc8.png)

如图所示，1.25 * 99 为小数，1.25 * 100 为整数。
结果是小数宽度没生效，列宽变成了默认值40px，而整数有效。

### （必填）请填写期望的结果 Expected behavior

即使是小数也能正常显示。

### （必填）请填写版本号 Version

- os: OSX 10.14.6
- browser: Chrome 76.0.3809.100（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 2.5.7

**Comment by xuliangzhan** [comment]
这个宽度是不支持小数的，没明白为啥要用小数呢？

**Comment by fh345392977** [comment]
有个针对rem的转换，之前转换后会出现小数，现在做了取整处理
