### ISSUE TITLE
强化列筛选功能

### ISSUE THREAD

**Issue by ChobitsSP** [xuliangzhan/vxe-table#313]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/jQuery/Light/

希望可以做到DevExtreme这样 单独一行筛选 并且增加列字段的类型dataType
根据dataType来决定header筛选form组件

**Comment by xuliangzhan** [comment]
没有具体说清楚实现了什么功能，该需求解决了什么场景问题？
