### ISSUE TITLE
可编辑表格中两列的select 联动

### ISSUE THREAD

**Issue by thewangzl** [xuliangzhan/vxe-table#314]
### （必填）这个需求解决了什么问题 What problem does this feature solve
         第一列的select值改变后，第二列（或者其他相关的多个列）的select内容能相应的变化。
 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
    
 ?

**Comment by xuliangzhan** [comment]
这属于业务逻辑，只能自行实现

**Comment by xsdream** [comment]
> 这属于业务逻辑，应该自行实现额
列公用一个options，没法实现啊，改一个其他都改了
