### ISSUE TITLE
固定列的时候 合计列不能滚动

### ISSUE THREAD

**Issue by djkloop** [xuliangzhan/vxe-table#315]
### （必填）请填写问题描述 Describe the bug

 固定列的时候合计列不能滚动

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[图片1复现链接]( https://xuliangzhan.com/vxe-table/index.html#/table/advanced/footer)

[图片2复现链接](https://jsrun.pro/MxbKp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/21050914/64095181-b0ff0b00-cd90-11e9-89cd-0cb66f653593.png)

![image](https://user-images.githubusercontent.com/21050914/64095475-7649a280-cd91-11e9-9391-069ed94c0e48.png)

### （必填）请填写期望的结果 Expected behavior

 预期合计行/其他类似的行也能滚动

### （必填）请填写版本号 Version

- os: MacOS
- browser: chrome 76.0.3809.100
- vue: 官网demo
- vxe-table: 官网demo

**Comment by xuliangzhan** [comment]
这个没发现有这个问题？

**Comment by djkloop** [comment]
![Sep-06-2019 12-48-50](https://user-images.githubusercontent.com/21050914/64401746-e06d8a80-d0a4-11e9-8f38-45fb160b016c.gif)


我刚才测试了一下.. 应该是 如果在上面的行滑动的时候合计列不能随着滑动
但是在合计行滑动的时候他能随着滑动，这是正常的


os: MacOS Mojave 1014.3
browser: chrome 76.0.3809.100
vue: 官网demo
vxe-table: 官网demo

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by djkloop** [comment]
thx, ୧(๑•̀◡•́๑)૭
