### ISSUE TITLE
vxe-grid 如何配置columns 实现多表头？

### ISSUE THREAD

**Issue by javascript666666** [xuliangzhan/vxe-table#316]
### （必填）请填写问题描述 Describe

 ?我用vxe-table可以实现表头分组，多表头 
![222](https://user-images.githubusercontent.com/25980255/64100052-57e9a400-cd9d-11e9-964b-b8d46e8f57bc.png)

- 
<vxe-table
          ref="xTable"
          border
          height="600"
          class="vxe-table-element"
          :data="tableData"
          @select-all="selectAllEvent"
          :edit-config="{trigger: 'click', mode: 'cell', showStatus: true}"
          @edit-actived="editActivedEvent"
          @edit-closed="editClosedEvent"
          >
          <vxe-table-column type="selection" title="" fixed="left" width="38"></vxe-table-column>
          <vxe-table-column field="gysmc" title="供应商名称" fixed="left" width="100"></vxe-table-column>
          <vxe-table-column field="spmc" title="商品名称" fixed="left" width="100"></vxe-table-column>
          <vxe-table-column field="spgg" title="商品规格" fixed="left" width="150"></vxe-table-column>
          <vxe-table-column field="kc" title="库存" fixed="left" width="100"></vxe-table-column>
          <vxe-table-column field="qdl" title="起订量" fixed="left" width="100"></vxe-table-column>
          <vxe-table-column field="dw" title="单位" fixed="left" width="50"></vxe-table-column>
          <vxe-table-column field="zxj" title="PLUS专享价(元)" fixed="left" width="110"></vxe-table-column>
          <vxe-table-column field="zqcb" title="30天帐期年利率(%)" fixed="left" width="120"></vxe-table-column>
          
          <vxe-table-column title="测试1">
            <vxe-table-column field="xzdz" title="选择地址" width="100" :edit-render="{type: 'default'}">
              <template v-slot:edit="scope">
                <Select v-model="scope.row.xzdz" @change="$refs.xTable.updateStatus(scope)">
                <Option v-for="item in sexList" :value="item.value" :key="item.value">{{ item.label }}</Option>
              </Select>
              </template>
              <template v-slot="{ row }">{{ getSelectLabel(row.xzdz, sexList) }}</template>
            </vxe-table-column>
            <vxe-table-column field="xdsl" title="下单数量" width="100" :edit-render="{name: 'input'}"></vxe-table-column>
              <vxe-table-column field="zqcb2" title="帐期成本(元)" width="100"></vxe-table-column>
              <vxe-table-column field="zje" title="总金额(元)" width="100"></vxe-table-column>
          </vxe-table-column>
        </vxe-table>

**现在怎么用vxe-grid配置columns实现表头分组呢？** 

<vxe-table-column title="测试1">
            <vxe-table-column field="xzdz" title="选择地址" width="100" :edit-render="{type: 'default'}">
              <template v-slot:edit="scope">
                <Select v-model="scope.row.xzdz" @change="$refs.xTable.updateStatus(scope)">
                <Option v-for="item in sexList" :value="item.value" :key="item.value">{{ item.label }}</Option>
              </Select>
              </template>
              <template v-slot="{ row }">{{ getSelectLabel(row.xzdz, sexList) }}</template>
            </vxe-table-column>
            <vxe-table-column field="xdsl" title="下单数量" width="100" :edit-render="{name: 'input'}"></vxe-table-column>
              <vxe-table-column field="zqcb2" title="帐期成本(元)" width="100"></vxe-table-column>
              <vxe-table-column field="zje" title="总金额(元)" width="100"></vxe-table-column>
          </vxe-table-column>

**Comment by xuliangzhan** [comment]
请先看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/basic

**Comment by javascript666666** [comment]
感谢！
