### ISSUE TITLE
vxe-table,2.5.8,xeutils2.2.2出现 xeUtils.default.browse is not a function

### ISSUE THREAD

**Issue by yushengling** [xuliangzhan/vxe-table#318]
### （必填）请填写问题描述 Describe the bug
vxe-table,2.5.8,xeutils2.2.2出现 xeUtils.default.browse is not a function
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/19568401/64102819-4d320d80-cda3-11e9-9b1d-af391c2b581c.png)

 ?

### （必填）请填写期望的结果 Expected behavior
能够正常运行
 ?

### （必填）请填写版本号 Version
2.5.8 2.2.2
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
#302
