### ISSUE TITLE
vxe-grid使用cellRender问题

### ISSUE THREAD

**Issue by chenchifeng** [xuliangzhan/vxe-table#319]
### （必填）请填写问题描述 Describe

 vxe-grid使用cellRender,例如让'Man'显示为'男',没效果.
如果是editRender就可以,但是这个不想让它是可编辑的.

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 [重现链接](https://jsrun.pro/yGbKp/edit)

### 请填写报错信息或截图 Error message or screenshots

 
![图片](https://user-images.githubusercontent.com/16933868/64104624-27a70300-cda7-11e9-928f-35ed4ea20db1.png)

### （必填）请填写版本号 Version

- os: windows10
- browser: all
- vue: 2.5.22
- vxe-table: 2.3.7

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/format
你可能是误解了渲染器和格式化的概念，这两者不是一个东西 
当然如果你想把渲染器当做格式化来用也不是不可以，你得自行实现就行

**Comment by chenchifeng** [comment]
感谢
