### ISSUE TITLE
vxe-grid添加的toolbar工具栏样式显示不出来

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#32]
生成toolbar的代码不一样，
<div class="vxe-button--wrapper"><vxe-button>刷新</vxe-button><vxe-button>新增</vxe-button><vxe-button>新增并激活</vxe-button><vxe-button>标记/取消</vxe-button><vxe-button>删除选中</vxe-button><vxe-button>移除</vxe-button><vxe-button>保存</vxe-button><vxe-button>导出.csv</vxe-button></div>
而例子上生成的代码：
<div class="vxe-button--wrapper"><button class="vxe-button">刷新</button><button class="vxe-button">新增</button><button class="vxe-button">新增并激活</button><button class="vxe-button">标记/取消</button><button class="vxe-button">删除选中</button><button class="vxe-button">移除</button><button class="vxe-button">保存</button><button class="vxe-button">导出.csv</button></div>
是哪里出问题呢？

**Comment by xuliangzhan** [comment]
更新到最新，参考 demo 肯定是可以的

**Comment by tiger54910** [comment]
demo运行可以的，使用文档中从unpkg引入的页面元素不一样。

**Comment by xuliangzhan** [comment]
更新到最新就行
