### ISSUE TITLE
vxe-grid 的toolbar中的button 能否添加 disabled 和visible两个属性

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#323]
### （必填）这个需求解决了什么问题 What problem does this feature solve

vxe-grid 的toolbar中的button 能否添加 disabled 和visible两个属性 ，用来控制按钮是否可用或者显示，功能就如快捷菜单中的disabled 和visible

**Comment by xuliangzhan** [comment]
这个可以支持
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/fullEdit

**Comment by jianliulin** [comment]
谢谢！！
