### ISSUE TITLE
vxe-modal 用鼠标拖动改变大小的时候，zoom事件中传进来的$modal.height一直不变

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#325]
### （必填）请填写问题描述 Describe
vxe-modal 用鼠标拖动改变大小的时候，zoom事件中传进来的$modal.height一直不变，请问从哪里可以获取改变后的modal的宽度和高度。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://codesandbox.io/s/vxe-table-ceshide-demo-yg0zt?fontsize=14

### 请填写报错信息或截图 Error message or screenshots

![微信截图_20190905101433](https://user-images.githubusercontent.com/4531974/64306633-0e2fd200-cfc6-11e9-9f8f-58334e404df0.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
这个要先拿到 element 才能获取高度 https://codesandbox.io/s/vxe-table-ceshide-demo-wu7iy

**Comment by jianliulin** [comment]
谢谢
