### ISSUE TITLE
能否把vxe-modal 改变后的（高、宽）像vxetable的列宽一样存储起来，

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#326]
### （必填）这个需求解决了什么问题 What problem does this feature solve

能否把vxe-modal 改变后的（高、宽）像vxetable的列宽一样存储起来，因为每个用户的屏幕大小不一样。

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
没有具体说清楚实现了什么功能，该需求解决了什么场景问题？
