### ISSUE TITLE
想增加一种新的表头配置方式

### ISSUE THREAD

**Issue by nthalo** [xuliangzhan/vxe-table#327]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 表头的配置能不能配置成下图这个样式？没有的话能否加上
![QQ截图20190905110956](https://user-images.githubusercontent.com/45553318/64309091-05db9500-cfce-11e9-88ec-49e7fe98cbe8.png)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
#316
