### ISSUE TITLE
表格编辑框 :edit-render="item.editRender"  怎么支持原生事件

### ISSUE THREAD

**Issue by xiaoxin1991** [xuliangzhan/vxe-table#329]
<input type="text" v-model="item.val" v-focus="focusIndex === index"  @keyup.enter="nextFocus(index)">

在表格编辑中如何实现 @keyup.enter="nextFocus(index)
现在是这样写的
![image](https://user-images.githubusercontent.com/52266789/64323338-e311a680-cff6-11e9-9e0f-772953a536d2.png)

**Comment by xuliangzhan** [comment]
#124
