### ISSUE TITLE
怎么在vxe-grid的工具栏上添加自定义的按钮？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#33]
在vxe-grid的工具栏上添加自定义的按钮的话，可以显示名称，但是怎么添加事件响应呢？

**Comment by xuliangzhan** [comment]
更新到最新，自定义按钮配合 [toolbar-button-click](http://localhost:8080/#/grid/api?filterName=toolbar-button-click) 事件监听

**Comment by tiger54910** [comment]
谢谢，这样就好了，现在是您一个人在开发这个table吗？更新得很及时。

**Comment by tiger54910** [comment]
一般来说，工具栏上还有下拉菜单形式，因为工具栏可能很多，下拉菜单具有更好的可扩展性，不知道能不能支持下拉菜单形式？

**Comment by xuliangzhan** [comment]
如果要显示更多按钮或组件，那没必要用默认的工具栏，你直接使用自定义组件就行

**Comment by tiger54910** [comment]
OK，谢谢你，有个这个组件，处理数据方便得多了。
