### ISSUE TITLE
自定义列&列宽 + localStorage,在动态列下会失效

### ISSUE THREAD

**Issue by WhiteGIT** [xuliangzhan/vxe-table#331]
### （必填）请填写问题描述 Describe the bug
自定义列&列宽 + localStorage,在动态列下会失效
步骤：
1.设置自定义列&列宽 + localStorage；
2.从后台请求表头列数据，组装后调用 loadColumn，localStorage里存的列配置都被清空了，原来被隐藏的列都出现了

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version
最新
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by solarcellsky** [comment]
这个问题我遇到了，缓存依赖 Props.id 这个必须是唯一，缓存是以这个来匹配的。因为我是公用组件开始 id 用的动态 uuid，因为每次刷新 uuid 就会变，所以是行不通的。可以用 router.path 作为 id。

`const route = useRoute();
const { path } = route;

const gridOptions = computed(() => {
  return {
    id: path.split('/').join('_'),
   ...
  };
});
`
