### ISSUE TITLE
就是这个问题我是可编辑的表格行嘛，然后我表格单元格的输入框呀或者选择时间的呀，都需要我去点击行它才出现，不点行她是个本文，  我想的是她用于都是输入框，不要那种我点击才出现输入框

### ISSUE THREAD

**Issue by livelyPeng** [xuliangzhan/vxe-table#334]
### （必填）这个需求解决了什么问题 What problem does this feature solve
就是这个问题我是可编辑的表格行嘛，然后我表格单元格的输入框呀或者选择时间的呀，都需要我去点击行它才出现，不点行她是个本文，  我想的是她用于都是输入框，不要那种我点击才出现输入框
 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
就是这个问题我是可编辑的表格行嘛，然后我表格单元格的输入框呀或者选择时间的呀，都需要我去点击行它才出现，不点行她是个本文，  我想的是她用于都是输入框，不要那种我点击才出现输入框
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered
就是这个问题我是可编辑的表格行嘛，然后我表格单元格的输入框呀或者选择时间的呀，都需要我去点击行它才出现，不点行她是个本文，  我想的是她用于都是输入框，不要那种我点击才出现输入框
 ?

**Comment by fh345392977** [comment]
我可以提供一个临时解决办法，渲染一个input出来，不使用他的默认渲染，事件可以使用同一个。另外你这个提issue的方式，emmmmm

**Comment by xlz26296** [comment]
文档貌似有例子 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/bad/edit
