### ISSUE TITLE
vxe-grid 使用 empty slot 不生效

### ISSUE THREAD

**Issue by houjiazong** [xuliangzhan/vxe-table#335]
### （必填）请填写问题描述 Describe the bug

 vxe-grid 使用 empty slot 不生效

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://codesandbox.io/embed/vue-antd-template-ebhpl

请查看App.vue文件

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/1658546/64498882-2ca90c80-d2e9-11e9-8c23-13d92df130ee.png)

### （必填）请填写期望的结果 Expected behavior

 生效

### （必填）请填写版本号 Version

- os: mac 10.14.6
- browser: chrome 版本 76.0.3809.132（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 2.5.11

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下

**Comment by houjiazong** [comment]
v2.5.13可以正常使用了
