### ISSUE TITLE
Vxecolumn能否添加一个footer-align 属性，用来设置footer 的对齐方式，功能类似header-align

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#337]
### （必填）这个需求解决了什么问题 What problem does this feature solve
Vxecolumn能否添加一个footer-align 属性，用来设置每列footer 的对齐方式，功能类似header-align.

![微信截图_20190909151308](https://user-images.githubusercontent.com/4531974/64510277-5e839880-d314-11e9-8d67-c0cf660fb617.png)

不对齐，不是很好看
![微信截图_20190909153238](https://user-images.githubusercontent.com/4531974/64511518-14e87d00-d317-11e9-808c-0c47c649bea5.png)

### （必填）建议的 API 是什么样的 What does the proposed API look like

https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/footer

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下
https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?filterName=footer-align

**Comment by jianliulin** [comment]
谢谢
