### ISSUE TITLE
表格列宽度异常变小

### ISSUE THREAD

**Issue by chenchifeng** [xuliangzhan/vxe-table#338]
### （必填）请填写问题描述 Describe the bug

表格列宽度偶尔异常变小

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[重现链接] (https://jsrun.pro/q7bKp)
也不知道怎么才能重现,目前问题主要就是发生在使用Ant Design Pro of Vue 的时候,在很多个都有vxe-table的页面中切换几次就有时候会出现.

### 填写报错信息或截图 Error message or screenshots

 
![b4b2d80690612827878448f68379e31](https://user-images.githubusercontent.com/16933868/64519945-b5469d80-d327-11e9-800b-06a723e2ba94.png)

### （必填）请填写期望的结果 Expected behavior

 能够正常显示宽度

### （必填）请填写版本号 Version

- os: win10
- browser: all
- vue: 2
- vxe-table: 2.5.8

**Comment by xlz26296** [comment]
#230
