### ISSUE TITLE
能否添加一个插槽实现在toolbar右侧刷新旁边添加一些按钮

### ISSUE THREAD

**Issue by chenchifeng** [xuliangzhan/vxe-table#341]
### 描述
请问目前有没有插槽实现在toolbar添加按钮
![图片](https://user-images.githubusercontent.com/16933868/64588563-52134480-d3d5-11e9-9258-42cfa9718947.png)

### （必填）这个需求解决了什么问题 What problem does this feature solve
目前使用vex-table的项目中的toolbar的button是根据后端返回的,有几个按钮是像刷新那个按钮那样每个页面都有的(例如还原按钮),所以想要有一个插槽在右侧刷新旁边添加一些固有的按钮

### （必填）建议的 API 是什么样的 What does the proposed API look like
类似于
```html
<template v-slot:tool>
</template>
```
 

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/toolbar

**Comment by chenchifeng** [comment]
感谢


------------------ 原始邮件 ------------------
发件人: Xu Liangzhan <notifications@github.com&gt;
发送时间: 2019年9月10日 21:26
收件人: xuliangzhan/vxe-table <vxe-table@noreply.github.com&gt;
抄送: Chi Fung <13059327127@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xuliangzhan/vxe-table] 能否添加一个插槽实现在toolbar右侧刷新旁边添加一些按钮 (#341)




建议更新到最新版本看下
 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/toolbar
