### ISSUE TITLE
vxe-model 上放置一个vxe-grid ，wxe-gird的height="auto" ，grid并的高度没有撑满model

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#342]
### （必填）请填写问题描述 Describe

vxe-model 上放置一个vxe-grid ，wxe-gird的height="auto" ，grid的高度没有撑满model

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-8scgv?fontsize=14

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/module/modal

**Comment by jianliulin** [comment]
谢谢
