### ISSUE TITLE
Select在trigger为row时，未使用checkMethod校验是否可勾选

### ISSUE THREAD

**Issue by fh345392977** [xuliangzhan/vxe-table#343]
### （必填）请填写问题描述 Describe the bug

 设置了checkMethod后，复选框确实不能勾选。但如果trigger为row，我点击整行时，这一行依然被选中了

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 [https://jsrun.pro/DtbKp/edit](https://jsrun.pro/DtbKp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/16329330/64605017-d1187500-d3f5-11e9-9bd3-e10385528e69.png)

### （必填）请填写期望的结果 Expected behavior

 整行点击时，checkMethod能发挥作用。

### （必填）请填写版本号 Version

- os: OSX 10.14.6
- browser: Chrome 76
- vue: 2.6.2
- vxe-table: 2.5.8

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下

**Comment by fh345392977** [comment]
点个赞
