### ISSUE TITLE
2.5.15更新后报错

### ISSUE THREAD

**Issue by anyclub** [xuliangzhan/vxe-table#344]
### （必填）请填写问题描述 Describe the bug
这个项目是上个月开始的,那时候的VXE版本应该是没问题的
今日因为其他问题 重新安装所有NODE依赖后报错
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
1. 是根据官网的自定义SCSS样式文件丢失
![111](https://user-images.githubusercontent.com/19922265/64624559-6ed36a80-d41d-11e9-8e79-e3f4b581a2ce.png)

2.  解决掉这个问题后又出现一个方法报错
![TIM截图20190910224713](https://user-images.githubusercontent.com/19922265/64624627-890d4880-d41d-11e9-8196-a47ddf9ebe4d.png)

 ?

### （必填）请填写期望的结果 Expected behavior
期望项目能正常运行,
若该BUG不能及时修复,望告知应该锁版本号到哪一个为宜?
 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
#302
https://github.com/xuliangzhan/vxe-table-demo

**Comment by anyclub** [comment]
万分感谢, 已解决
