### ISSUE TITLE
如何让vxe-model ，执行open() 后窗体直接是最大化？

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#345]
### （必填）请填写问题描述 Describe

如何让vxe-model ，执行open() 后窗体直接是最大化？

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

![image](https://user-images.githubusercontent.com/4531974/64664956-66ae1600-d483-11e9-8593-0994d6ce0479.png)

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
这个你可以调用 [maximize](https://xuliangzhan_admin.gitee.io/vxe-table/#/modal/api?filterName=maximize) 方法
