### ISSUE TITLE
一个vue页面v-if动态切换两个vxe-table（data不同，ref也不同），为什么视图不变。

### ISSUE THREAD

**Issue by 277896015** [xuliangzhan/vxe-table#349]
### （必填）请填写问题描述 Describe the bug

 你好，我在一个vue页面里设置了两个<template v-if>标签想用来分别动态展示不同的表格，可是切换到第二个表格显示的还是第一个表格的数据和视图。可明明两个表格绑定的数组是不同的。想了很久也不能解决

### （必填）请填写能重现问题的链接
本地项目无连接

### 填写报错信息或截图 Error message or screenshots
![1](https://user-images.githubusercontent.com/44082192/64675529-f8c71600-d4a5-11e9-8bb9-22221d79141e.png)
![2](https://user-images.githubusercontent.com/44082192/64675648-3f1c7500-d4a6-11e9-9973-af7788aad914.png)

### （必填）请填写期望的结果 Expected behavior
动态切换两个vxe-table，数据和视图同时改变
 
### （必填）请填写版本号 Version

- os: windows10
- browser: chrome
- vue: 2.0
- vxe-table: V2

**Comment by 277896015** [comment]
哈哈，解决了 给每个vxe-table 加一个 :key="Math.random()"

**Comment by xuliangzhan** [comment]
#2584
