### ISSUE TITLE
当使用表头分组后，设置隐藏列有问题

### ISSUE THREAD

**Issue by Zz1204** [xuliangzhan/vxe-table#35]
表头分组后， 设置未分组的表头隐藏列，列的表头不会隐藏
![image](https://user-images.githubusercontent.com/34231460/58614272-88c3c400-82ea-11e9-93f6-08298393b581.png)
![image](https://user-images.githubusercontent.com/34231460/58614285-924d2c00-82ea-11e9-99ae-1a658da501c4.png)

**Comment by xuliangzhan** [comment]
最新版本已修复了该问题，建议更新到最新

**Comment by Zz1204** [comment]
谢谢，这个问题已经解决了
但是表头和行内内容宽度不一致是什么原因造成的
![image](https://user-images.githubusercontent.com/34231460/58676062-806e9600-8389-11e9-9872-5004fda6b68e.png)
![image](https://user-images.githubusercontent.com/34231460/58676087-954b2980-8389-11e9-8cf8-339b862d8ce6.png)

**Comment by xuliangzhan** [comment]
宽度不一样是怎么重现的？最好提供下重现的[链接](https://jsrun.net/vIyKp/edit)
