### ISSUE TITLE
请问是否可以修改键盘导航

### ISSUE THREAD

**Issue by jenny-zhou-d** [xuliangzhan/vxe-table#352]
### （必填）请填写问题描述 Describe

是否可以修改键盘导航，如：将激活单元格编辑的F2键改为Enter键?

### 请填写版本号 Version

- os: ?
- browser: Chrome 版本：Latest
- vue: 3.0.1
- vxe-table: 2.5.15

**Comment by xuliangzhan** [comment]
#311

**Comment by lzb66855024** [comment]
checkbox 看不见..
