### ISSUE TITLE
在VUEPRESS中, GUTTER计算错误

### ISSUE THREAD

**Issue by anyclub** [xuliangzhan/vxe-table#353]
### （必填）请填写问题描述 Describe the bug

 在VUEPRESS中使用VXETABLE组件, 组件布局错误
初步判断是因VUEPRESS使用SSR渲染 无法正确计算滚动条宽\高度导致问题

是否可手动设置GUTTER宽度,或提供一个方法强制刷新?

目前使用 refreshColumn 方法无法达到效果

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
无
 ?

### 填写报错信息或截图 Error message or screenshots
![asdasd](https://user-images.githubusercontent.com/19922265/64932517-26c7a400-d872-11e9-8e91-0eab68d87393.png)
![啊实打实](https://user-images.githubusercontent.com/19922265/64932518-26c7a400-d872-11e9-869e-0242e9756d89.png)

 ?

### （必填）请填写期望的结果 Expected behavior
能正常渲染宽度
 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by anyclub** [comment]
后续打包也发现问题
document对象报错

**Comment by xuliangzhan** [comment]
Vue SSR 的使用可以参考文档 https://github.com/xuliangzhan/vxe-table-demo/tree/master/vxe-table-by-vue-nuxt
计算函数请看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=recalculate
