### ISSUE TITLE
列表中插入下拉选择框，选中后值不改变

### ISSUE THREAD

**Issue by Tiramisu1** [xuliangzhan/vxe-table#354]
### （必填）请填写问题描述 Describe the bug

 ?
列表长插入elementUI下拉选择组件，选中之后值不改变，官方用法getCascaderLabel事件报错 ：find is undefined！

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?
https://xuliangzhan.github.io/vxe-table/#/table/other/element

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?
插入下拉编辑组件，选中之后，值能正常变化

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?  2.5.2
- vxe-table: ?

**Comment by xsdream** [comment]
@xuliangzhan 我也遇到了这个问题，为什么关闭了啊，官网的demo也不行~
