### ISSUE TITLE
合并行高亮显示当前行有问题。

### ISSUE THREAD

**Issue by Leo-LL** [xuliangzhan/vxe-table#355]
### （必填）请填写问题描述 Describe
当选择了合并行，那么在hover高亮时，应该算作一行，不然hover到合并行时会很难看。
![image](https://user-images.githubusercontent.com/50311528/64939057-8afa6000-d892-11e9-9ee5-c5865e24a32a.png)

### 重现链接
https://jsrun.pro/9CbKp

### 请填写版本号 Version

- os: mac
- browser:  chrome
- vue: 2.6
- vxe-table: 2.5.15

**Comment by xuliangzhan** [comment]
这个本身就是单行操作，即使是合并了实际也是单行；你可以使用 hover + class 实现；

**Comment by xiaogaofudao** [comment]
@xuliangzhan 同问有什么好的办法吗，使用 hover 事件 + class 实现；具体怎么操作呢？

**Comment by xiaogaofudao** [comment]
感觉框架层可以除 row--current 之外单独为 第一行row 加一个 class 区别。
