### ISSUE TITLE
树表格 怎么改变前面的箭头图标 自定义

### ISSUE THREAD

**Issue by ruanzy** [xuliangzhan/vxe-table#356]
### （必填）请填写问题描述 Describe

 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
请先看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/icons

**Comment by ruanzy** [comment]
> 请先看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/icons
我知道配置 但是
VXETable.setup({
        icon: {
          tree: 'vxe-icon--caret-right',  //这里配置自定义的  不是内置的
如果自定义 自定义样式有什么规则？

**Comment by xuliangzhan** [comment]
你可以参考 [fontawesome](http://fontawesome.dashgame.com/)
```javascript
VXETable.setup({
  icon: {
    tree: 'fa fa-hand-o-right'
  }
)
```
