### ISSUE TITLE
大数据量表格，快速拖动表格滚动条有时候出现白屏。

### ISSUE THREAD

**Issue by Yourroot** [xuliangzhan/vxe-table#358]
### （必填）请填写问题描述 Describe the bug

 ?当表格有大量数据的时候，快速拖动滚动条会出现有时候白屏的现象。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?http://jsrun.pro/7CbKp/edit

### 填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/29765892/64955865-e12fc900-d8bb-11e9-8d34-683cc70c7031.png)

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xsshu** [comment]
遇到同样问题

**Comment by xuliangzhan** [comment]
看代码使用 optimization，那么是否流畅就需要自行调整哦；
如果不清楚 optimization  的调优方式，不建议使用该参数

**Comment by Yourroot** [comment]
多谢楼主
