### ISSUE TITLE
列可视化渲染时候，拿不到真实的columnIndex，拿到的是可视区的index

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#36]
vxe-table 0.9.3

更新最新版本0.9.14后，数据都出不来了，又撤回到0.9.3了

实际上已经102了 
![image](https://user-images.githubusercontent.com/11676609/58631258-942be500-8314-11e9-863a-f0955f96cb4c.png)

![image](https://user-images.githubusercontent.com/11676609/58631320-cf2e1880-8314-11e9-89a7-076e8d6eb3fd.png)

作者大大帮忙看看

![22](https://user-images.githubusercontent.com/11676609/58631955-b7579400-8316-11e9-8ed5-6b337a2d97a3.gif)

选中210X3-5、210X3-6 ，横向拖动滚动条时候，选中的项不断的往后移动，因为headerCellClassName 函数里面的回调columnIndex 不是真实的数据index，到最后210X14-6被选中了。。

**Comment by xuliangzhan** [comment]
你看col-102这个索引是不是对的，如果是对的那就不会错

**Comment by xuliangzhan** [comment]
https://jsrun.net/ULyKp

**Comment by lishihong** [comment]
> 你看class 中col-102这个索引是不是对的，如果是对的那就不会错

102这个是对的

**Comment by xuliangzhan** [comment]
那不应该是错的，你去看上面的demo，都是正确的，你可以打印下参数

**Comment by xuliangzhan** [comment]
建议更新到最新
