### ISSUE TITLE
树表格如何获取半选的节点？

### ISSUE THREAD

**Issue by suweien** [xuliangzhan/vxe-table#360]
期望能够获取树形表格中的半选节点

**Comment by suweien** [comment]
在选中一个子节点的同时也想获取到所有到根节点路径的节点

**Comment by suweien** [comment]
树表格 子节点未全选 父节点处于半选状态即一条横杠  在getSelectRecords时候只有选中的记录半选的父节点没有返回

**Comment by suweien** [comment]
期望能提供获取半选状态节点的方法

**Comment by suweien** [comment]
![image](https://user-images.githubusercontent.com/26915433/65369759-c1b1eb00-dc83-11e9-8c5b-48c833ffdd82.png)

**Comment by songhejia** [comment]
@suweien  这个问题是如何解决的呢？都好多年了
