### ISSUE TITLE
vxe-grid 这个编辑的时候怎么实时获取到输入内容，因为需求是要事实的发送请求和数据计算的

### ISSUE THREAD

**Issue by LuckyTaoTao** [xuliangzhan/vxe-table#365]
### （必填）请填写问题描述 Describe
vxe-grid 这个编辑的时候怎么实时获取到输入内容，因为需求是要事实的发送请求和数据计算的

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by LuckyTaoTao** [comment]
还有一个问题就是，希望能把currentPage和pageSize等放开，毕竟后台需要的字段名称很有可能并不是这两个

**Comment by xuliangzhan** [comment]
参考 #124
