### ISSUE TITLE
edit-rules的validator不生效

### ISSUE THREAD

**Issue by hezhihan** [xuliangzhan/vxe-table#367]
### （必填）请填写问题描述 Describe

使用可编辑表格，对其中一个字段keyNumber做自定义校验，不起作用，也不报错直接通过了。

### 请填写报错信息或截图 Error message or screenshots

无报错信息
![image](https://user-images.githubusercontent.com/48429918/65110853-61fdda80-da0c-11e9-9444-cf453ba2a09f.png)
![image](https://user-images.githubusercontent.com/48429918/65107656-d84d0d80-da09-11e9-876f-dffb67a5e185.png)
![image](https://user-images.githubusercontent.com/48429918/65107719-e1d67580-da09-11e9-85c4-7c39e8a291d6.png)

### （必填）请填写版本号 Version
- vxe-table: 1.11.4

**Comment by hasbug** [comment]
@hezhihan 最后怎么解决的？

**Comment by Nisus-Liu** [comment]
我也遇到了类似的问题, 但是我分析的原因是, `自定义校验方法 Function({ cellValue, rule, rules, row, rowIndex，column, columnIndex })` 校验方法入参没有向文档所说那样传过来, **入参只有一个`validator`属性**.
我觉得楼主的问题的原因应该也有这个原因, 另外, 你的使用方式貌似不正确. 文档说, 需要返回一个 Promise 对象, `返回一个 Promise<new Error("提示消息")>`. @hezhihan @xuliangzhan

**Comment by Gumplefik** [comment]
@xuliangzhan 2.9之前版本edit-rule中validator文档有错的，实际是callback模式的
