### ISSUE TITLE
proxyConfig.filter=true 的时候，筛选后，漏斗图标的颜色不变，且再次筛选，发现前一次的条件不见了 

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#369]
### （必填）请填写问题描述 Describe

proxyConfig.filter=true 的时候，筛选后，漏斗图标的颜色不变，且再次筛选，发现前一次的条件不见了 

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-oeo7r

### 请填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/4531974/65128009-376f4a00-da2b-11e9-9fd9-1021b1373e36.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by jianliulin** [comment]
更新到2.5.18 版本，塞选后漏斗图标正常 ，但点解reload按钮后，漏斗图仍然消失。

**Comment by xuliangzhan** [comment]
reload 和 query 是不一样的行为，具体请看文档
https://xuliangzhan_admin.gitee.io/vxe-table/#/grid/api?filterName=buttons

**Comment by jianliulin** [comment]
先filter后再reload 此时filter的条件还在，reload 会带上filter的条件，要么漏斗为蓝色，要么不带清空filter条件。
