### ISSUE TITLE
更新到最新版本后，大数据表格渲染出不来了

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#37]
vxe 0.9.14
看文档里面都是使用的vxe-grid的方式

我使用的是和之前版本差不多的vxe-table的方式，<0.9.3版本的是可以的，大于这个版本的，数据渲染不出来。一样的代码之前版本可以渲染出表格，新版本就不行。
![image](https://user-images.githubusercontent.com/11676609/58676717-d5131080-838b-11e9-99e0-5be36e52df00.png)
![image](https://user-images.githubusercontent.com/11676609/58676728-dfcda580-838b-11e9-8438-bea004f33bb9.png)
![image](https://user-images.githubusercontent.com/11676609/58676759-fc69dd80-838b-11e9-9b6e-fb791015d86c.png)

**Comment by xuliangzhan** [comment]
这个不应该有问题，报什么错吗？最好能提供重现的链接

**Comment by xuliangzhan** [comment]
建议更新到最新
