### ISSUE TITLE
current-change 事件执行错误

### ISSUE THREAD

**Issue by GevinYang** [xuliangzhan/vxe-table#370]
### （必填）请填写问题描述 Describe the bug

 current-change对本行第二次执行失效，如下图

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 暂无

### 填写报错信息或截图 Error message or screenshots

 

![001](https://user-images.githubusercontent.com/50934848/65133892-047e8380-da36-11e9-8d1e-5f8b67b5073a.png)
![002](https://user-images.githubusercontent.com/50934848/65133895-05afb080-da36-11e9-8d4a-9a143718c31d.png)
![002](https://user-images.githubusercontent.com/50934848/65134099-57f0d180-da36-11e9-9bbb-7d3d880d5033.gif)

### （必填）请填写期望的结果 Expected behavior

 current-change可以对本行多次触发

### （必填）请填写版本号 Version

- os: Windows10 1809
- browser: chrome 76.0.3809.132
- vue: 2.6.10
- vxe-table: 2.5.17

**Comment by xuliangzhan** [comment]
事件的触发条件是用户行为
