### ISSUE TITLE
单元格渲染自定义输入框组件时如何传值

### ISSUE THREAD

**Issue by nthalo** [xuliangzhan/vxe-table#371]
### （必填）请填写问题描述 Describe

某个单元格要用到我写的自定义组件，但是一传值就报书写规范的错误，只有不传值才正常

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 无

### 请填写报错信息或截图 Error message or screenshots

 导入这个组件
![微信截图_20190919094430](https://user-images.githubusercontent.com/45553318/65206826-671d6100-dac2-11e9-8c14-fd5bb5eb2892.png)
然后在这儿渲染，不传值的情况下正常
![微信截图_20190919094456](https://user-images.githubusercontent.com/45553318/65206847-77cdd700-dac2-11e9-9898-a3e6ce58a805.png)
但是只要多写一点东西都会报错，两种方式都不行
![微信截图_20190919094533](https://user-images.githubusercontent.com/45553318/65206877-8e742e00-dac2-11e9-8e5f-ce63381b3948.png)
![微信截图_20190919094547](https://user-images.githubusercontent.com/45553318/65206884-903df180-dac2-11e9-8d4a-623a1ca390cd.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.6.10
- vxe-table: 2.5.14

**Comment by xlz26296** [comment]
语法问题你应该看 vue 文档 https://cn.vuejs.org/v2/guide/render-function.html#JSX

**Comment by nthalo** [comment]
已解决，这是JSX的语法， <list  test={this.test}/>
