### ISSUE TITLE
vxe-table 希望能提供method, 可以手动清除被标记的编辑过的cell状态, row的所有被编辑过的cell状态

### ISSUE THREAD

**Issue by TomWsl** [xuliangzhan/vxe-table#373]
### （必填）这个需求解决了什么问题 What problem does this feature solve
当设置了:edit-config="{showStatus: true}" 后编辑cell或者row 后会在左上角显示一个红色的小标记表示编辑过.
但是当提交数据以后只有调用table的 refreshData() 才能清除这个红色小标记. 而没有找到专门的方法来清除

### （必填）建议的 API 是什么样的 What does the proposed API look like

 clearTableEditStatus(), clearRowEditStatus(row), clearCellEditStatus(cell)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 目前只发现了2种办法来清除, 都不是很优雅需要刷新整个表格数据: 
1. 调用 refreshData(), 但是这种方法会Scroll 到 最左边 和 顶部.
2. 不想Scroll会顶部的可以用 loadTableData(tableFullData, true)

**Comment by TomWsl** [comment]
![image](https://user-images.githubusercontent.com/9360479/65222647-16bdf780-daf2-11e9-9670-29d86a3b3876.png)
类似这个当修改了cell数据以后会在左上角标红, 希望能提供一种方法可以手动清除这个标红块

**Comment by xlz26296** [comment]
正确的使用不会有手动清除的操作 
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/fullEdit

**Comment by jianliulin** [comment]
有时侯是需要的，比如某个字段是表示状态的，点击其他地方的按钮后提交后台修改了这个状态值，当成功后，前台直接修改的话，就会有一个红色标记，其实此时并不需要显示红色标签

**Comment by TomWsl** [comment]
我现在就这样修改完某一行的数据以后, 提交数据到后台更新, 后端更新成功以后, 需要手动调用方法来清除这行的红色标记

**Comment by xuliangzhan** [comment]
局部更新可以参考这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/status
