### ISSUE TITLE
编辑组件只有input select textarea 可选吗？

### ISSUE THREAD

**Issue by hasbug** [xuliangzhan/vxe-table#374]
### （必填）请填写问题描述 Describe

我看到目前V2版本编辑的控件只有input select textarea，就按照https://xuliangzhan.github.io/vxe-table/#/table/other/element，使用了element-ui组件，但时间控件那些选完后，立马被关闭了。怎么回事？并没有选到时间，值也没改变。
### 请填写版本号 Version

- os:windows
- browser: chrome
- vue: 2.X
- vxe-table:  v2

**Comment by weichen666** [comment]
如果是自定义主键，也是选中不上值得
  <vxe-table-column field="tabIndex" title="列所属页签" min-width="180px" :edit-render="{autofocus: '.custom-input'}">
              <template v-slot:edit="{row}">
                <selector-for-row-tab :tabIndex.sync="row.tabIndex" class="custom-input"></selector-for-row-tab>
              </template>
              <template v-slot="{row}">{{row.tabIndex}}</template>
            </vxe-table-column>

**Comment by weichen666** [comment]
如果是自定义主键，也是选中不上值得

`  <vxe-table-column field="tabIndex" title="列所属页签" min-width="180px" :edit-render="{autofocus: '.custom-input'}">
              <template v-slot:edit="{row}">
                <selector-for-row-tab :tabIndex.sync="row.tabIndex" class="custom-input"></selector-for-row-tab>
              </template>
              <template v-slot="{row}">{{row.tabIndex}}</template>
            </vxe-table-column>`

**Comment by hasbug** [comment]
因为我用的是element-ui，我后面按照文档中的提示安装了npm包：vxe-table-plugin-element
   可以用了。
