### ISSUE TITLE
固定列之后，表格头没法滚动

### ISSUE THREAD

**Issue by Fishcyz** [xuliangzhan/vxe-table#379]
### （必填）请填写问题描述 Describe

左右两边固定列之后，表格中间部分，内容可以滚动，表格头部无法滚动
想问下表格头部滚动的功能会不会受自定义表格头样式所影响
自定义了排序跟筛选图标

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 暂无

### 请填写报错信息或截图 Error message or screenshots

 没有报错信息

### （必填）请填写版本号 Version

- os: ?
- browser: chrome
- vue: ^2.5.2
- vxe-table: ^2.5.5

**Comment by Fishcyz** [comment]
![image](https://user-images.githubusercontent.com/13741967/65824599-78beef80-e29e-11e9-9f99-44b7e70d4f6f.png)

**Comment by tiger54910** [comment]
我这里也发现同样的问题。
![QQ图片20191007103941](https://user-images.githubusercontent.com/14190457/66281632-ccf54f80-e8ee-11e9-9692-bf62dfbfd407.png)
![QQ图片20191007103936](https://user-images.githubusercontent.com/14190457/66281634-cd8de600-e8ee-11e9-9dfe-4b0cfb0dfd60.png)

**Comment by tiger54910** [comment]
感觉selection，index列长度变化了，缩小了

**Comment by tiger54910** [comment]
上面提供截图了，链接需要用户权限呵

**Comment by xuliangzhan** [comment]
#390

**Comment by Fishcyz** [comment]
原因：vxe-table--header-wrapper样式被我屏蔽了
