### ISSUE TITLE
插入一行数据时，总会有一个13位的随机数

### ISSUE THREAD

**Issue by chinabomb** [xuliangzhan/vxe-table#38]
动态的插入一行，行里有一个下拉列表（element-ui的下拉列表），点击下拉列表编辑时，在插入行时给这个下拉列表赋值总会显示成一个13位的随机数

**Comment by xuliangzhan** [comment]
你指的唯一 key 值？你可以自行设置，保证唯一就行，否则默认随机数

**Comment by chinabomb** [comment]
谢谢，明白了
