### ISSUE TITLE
this.bindResize is not a function

### ISSUE THREAD

**Issue by javascript666666** [xuliangzhan/vxe-table#382]
### （必填）请填写问题描述 Describe the bug

 ? 警告报错 [Vue warn]: Error in mounted hook: "TypeError: this.bindResize is not a function"
 webpack-internal:///26:1896 TypeError: this.bindResize is not a function

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
![error](https://user-images.githubusercontent.com/25980255/65398812-f476f300-ddeb-11e9-982a-f7ab1b460576.png)

 ?
webpack-internal:///26:629 [Vue warn]: Error in mounted hook: "TypeError: this.bindResize is not a function"

found in

---> <VxeTable>
       <VxeGrid>
         <ReportingDemand> at D:\work\web-front\src\views\user\page\order\reportingDemand.vue
           <Index> at D:\work\web-front\src\views\user\page\index.vue
             <Root>
warn @ webpack-internal:///26:629
logError @ webpack-internal:///26:1892
globalHandleError @ webpack-internal:///26:1887
handleError @ webpack-internal:///26:1847
invokeWithErrorHandling @ webpack-internal:///26:1870
callHook @ webpack-internal:///26:4221
insert @ webpack-internal:///26:3147
invokeInsertHook @ webpack-internal:///26:6350
patch @ webpack-internal:///26:6569
Vue._update @ webpack-internal:///26:3950
updateComponent @ webpack-internal:///26:4068
get @ webpack-internal:///26:4481
run @ webpack-internal:///26:4556
flushSchedulerQueue @ webpack-internal:///26:4312
eval @ webpack-internal:///26:1988
flushCallbacks @ webpack-internal:///26:1914
webpack-internal:///26:1896 TypeError: this.bindResize is not a function
    at VueComponent.mounted (webpack-internal:///1335:628)
    at invokeWithErrorHandling (webpack-internal:///26:1862)
    at callHook (webpack-internal:///26:4221)
    at Object.insert (webpack-internal:///26:3147)
    at invokeInsertHook (webpack-internal:///26:6350)
    at VueComponent.patch [as __patch__] (webpack-internal:///26:6569)
    at VueComponent.Vue._update (webpack-internal:///26:3950)
    at VueComponent.updateComponent (webpack-internal:///26:4068)
    at Watcher.get (webpack-internal:///26:4481)
    at Watcher.run (webpack-internal:///26:4556)
### （必填）请填写期望的结果 Expected behavior

 ? 消除警告报错

### （必填）请填写版本号 Version

- os: ?
- browser: ? chrome
- vue: ? "vue": "^2.6.10",
- vxe-table: ? "vxe-table": "^2.5.22", "xe-utils": "^2.2.4",

`<vxe-grid
       auto-resize
        ref="xTable"
        border
        :loading="loading || childLoading"
        height="400"
        :toolbar="tableToolbar"
        :columns="tableColumn"
        :data="tableData"
        :resizable='true'
        header-align="center"
        :edit-rules="validRules"
         @edit-actived="editActivedEvent"
        @edit-closed="editClosedEvent"
        :edit-config="{trigger: 'click', mode: 'cell',showStatus: true}"
        @select-change="selectChangeEvent"
        @select-all="selectAllEvent"    
      >
    </vxe-grid>`

**Comment by hasbug** [comment]
今天我也出现了，之前都正常。
