### ISSUE TITLE
拖拽

### ISSUE THREAD

**Issue by graceYa1** [xuliangzhan/vxe-table#383]
### （必填）这个需求解决了什么问题 What problem does this feature solve
树形表格的拖拽，来改变数据的层级
 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
请先看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/other/sortableRow
