### ISSUE TITLE
表尾合计行 需要合并行\列

### ISSUE THREAD

**Issue by anyclub** [xuliangzhan/vxe-table#385]
感谢作者

### （必填）请填写问题描述 Describe
表尾合计行 需要合并行\列  但未找到相关API文档  colspanMethod方法只能处理DATA内部的数据
 ?

### 请填写报错信息或截图 Error message or screenshots
footer 如何 处理行\列的合并问题
 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
该功能会在 v2.6 支持
