### ISSUE TITLE
vue 打包时，报错

### ISSUE THREAD

**Issue by zhangya5847** [xuliangzhan/vxe-table#386]
### （必填）请填写问题描述 Describe
项目用的是vue-cli3，用的是未编译的源码倒入模式引入的vxe-table，development模式没有问题，打包报错。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/15855773/65476700-5b60de80-deb6-11e9-8ce7-46865510d50c.png)

### （必填）请填写版本号 Version

- os: mac
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by xlz26296** [comment]
未编译的是 ES6 代码，你应该配置对该模块的转码

**Comment by zhangya5847** [comment]
好的，明白了，谢谢
