### ISSUE TITLE
表格内容是否可以换行

### ISSUE THREAD

**Issue by qianfangyuan** [xuliangzhan/vxe-table#387]
场景：我在linux下执行的shell的输出结果贴到table里面
问题：但是shell的数据格式有换行，结果类似于：
[root@xx ~]# ll /usr/local/
total 5
drwxr-xr-x  2 root   root      4096 Mar 20  2019 bin
drwxr-xr-x  3 hadoop hadoop    4096 Jun  9  2014 common
drwxr-xr-x  2 root   root      4096 Jun 11  2010 etc
drwxr-xr-x  5 root   root      4096 Nov  6  2017 lib
drwxr-xr-x  2 root   root      4096 Mar 12  2009 lib64

但是把结果贴到table中一个cell的时候就会把换行去掉：
total 5 drwxr-xr-x  2 root   root      4096 Mar 20  2019 bin drwxr-xr-x  3 hadoop hadoop    4096 Jun  9  2014 common drwxr-xr-x  2 root   root      4096 Jun 11  2010 etc drwxr-xr-x  5 root   root      4096 Nov  6  2017 lib drwxr-xr-x  2 root   root      4096 Mar 12  2009 lib64

这个有什么办法可以展示为不把换行去掉，类似于shell的格式

**Comment by qianfangyuan** [comment]
应该是允许表格内容可以是类似于html语句

**Comment by qianfangyuan** [comment]
简单来说应该是可以把换行转换为<br>,但是table里面，全部自动进行转义了

**Comment by xlz26296** [comment]
这个业务逻辑和表格没什么关系，自定义模板使用 v-html 就行了

**Comment by qianfangyuan** [comment]
有空能不能帮忙写个例子？

**Comment by qianfangyuan** [comment]
https://github.com/xuliangzhan/vxe-table/issues/388
