### ISSUE TITLE
表格内容可以展示html

### ISSUE THREAD

**Issue by qianfangyuan** [xuliangzhan/vxe-table#388]
问题：
表格内容可以展示为html

例如：
template:
    \<vxe-grid
      border
      ref="xTable1"
      :data="tableData"
      :columns="tableColumn">
    </vxe-grid>

script:
      tableColumn: [
        { type: 'selection', width: 40 },
        {
          field: 'ip',
          title: 'IP',
          width: '120'
        },
        {
          field: 'status',
          title: 'Status',
          width: '80'
        },
        {
          field: 'msg',
          title: 'Msg',
          slots: {
            default: ({ row }) => {
              return [<span v-html="row.msg"></span>]
            }
          }
        }
      ],

我希望row.msg里面是html，可以展示为html

版本号:
- os: mac os 10.14.6
- browser: chrome 76.0.3809.132
- vue: 2.5.2
- vxe-table: 2.5.15

**Comment by yizixu** [comment]
这个slot为啥我的报Syntax Error: Unexpected token
![image](https://user-images.githubusercontent.com/24697292/65825898-35b94800-e2af-11e9-9952-0bee9c291bff.png)
