### ISSUE TITLE
自定义模板中的选中日期,上传数据时是直接传的日期字符串而不是时间戳,内部有无方法转换?

### ISSUE THREAD

**Issue by baitou** [xuliangzhan/vxe-table#389]
### （必填）请填写问题描述 Describe
使用自定义模板中的选中日期功能,上传数据给后台时是日期的字符串而不是时间戳,想咨询一下内部是否提供了方法转换
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
项目还未上线 暂时无法提供链接
 ?

### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/44676897/65580264-e7a0fd80-dfab-11e9-8bc4-0b66d8f3fb29.png)
![image](https://user-images.githubusercontent.com/44676897/65580279-ee2f7500-dfab-11e9-803d-6972dbccff89.png)
leadTime字段
 ?

### （必填）请填写版本号 Version
V2
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
转换方法你可以使用依赖库  [xe-utils](https://github.com/xuliangzhan/xe-utils) 中的函

**Comment by baitou** [comment]
> 转换方法你可以使用依赖库 [xe-utils](https://github.com/xuliangzhan/xe-utils) 中的相关函数

好的 谢谢您
