### ISSUE TITLE
使用vxe-table-plugin-element渲染ElAutocomplete无效

### ISSUE THREAD

**Issue by Zz1204** [xuliangzhan/vxe-table#39]
**描述 Describe**
看了下vxe-table-plugin-element的文档，说是支持ElAutocomplete，结果没有渲染出来，也不清楚问题出在了哪，而且还没有报错

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

![image](https://user-images.githubusercontent.com/34231460/58687148-6a75cb00-83b3-11e9-99eb-7590568a81fd.png)
![image](https://user-images.githubusercontent.com/34231460/58687174-7e213180-83b3-11e9-8e2c-87f942ab3f76.png)

**Comment by xuliangzhan** [comment]
这个更新到最新就可以了
