### ISSUE TITLE
关于如何高效提 Issue 😃

### ISSUE THREAD

**Issue by xuliangzhan** [xuliangzhan/vxe-table#390]
#### 😊高效的 Issue
* [x] 必须按模板填完需要的信息
* [x] 必须有重现链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)）
* [x] 特殊的问题可以提供 Demo 和 Gif 动态图
#### 😥以下 Issue 将直接关闭（如果连 Issue 都不提供详细的话，那么我也是没办法的喽）
* [ ] 未提供重现链接&截图
* [ ] 未按模板提供需要的信息、描述不详细

**Comment by cooalzjc** [comment]
你好我在使用vxe-table的时候，在vxe-table@2.7.24的版本下html5的canvas标签是可以用的，但是升级到@vxe-table@2.8.33的时候该标签就无效了，不能显示所画的内容，这个是为啥，，，
