### ISSUE TITLE
this.$utils为undefined，但this.$XModal是正常的，有人遇到吗

### ISSUE THREAD

**Issue by iceSnowChen** [xuliangzhan/vxe-table#391]
### （必填）请填写问题描述 Describe

 
![image](https://user-images.githubusercontent.com/37735658/65679388-92d2b500-e087-11e9-8073-6792c552392a.png)
![image](https://user-images.githubusercontent.com/37735658/65679424-a41bc180-e087-11e9-885b-21b241150a72.png)

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
Demo 中的 $utils 是 [xe-utils](https://github.com/xuliangzhan/xe-utils) 库的方法，不使用是没有这个属性的，具体参考[示例代码](https://github.com/xuliangzhan/vxe-table/blob/master/examples/plugins/utils.js)

**Comment by iceSnowChen** [comment]
> Demo 中的 $utils 是 [xe-utils](https://github.com/xuliangzhan/xe-utils) 库的方法，不使用是没有这个属性的，具体参考[示例代码](https://github.com/xuliangzhan/vxe-table/blob/master/examples/plugins/utils.js)

好的，非常感谢！
