### ISSUE TITLE
关于手动触发获取新数据的问题

### ISSUE THREAD

**Issue by lyglzhl** [xuliangzhan/vxe-table#392]
### （必填）请填写问题描述 Describe
 我打印返回来的row 但是没有最新数据，还是原来数据

 ?

### （必填）请填写能重现问题的链接
https://jsfiddle.net/2wrea1zc/2/
 ?

### 请填写报错信息或截图 Error message or screenshots
![20190927_080118](https://user-images.githubusercontent.com/6230267/65732931-ae2cd700-e0fe-11e9-917a-8566e3ac6008.gif)

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
这样写是正确的，拿到的是新的数据，没看出有问题
``javascript
this.$refs.xTable.clearActived().then(() => {
  console.warn(row)
})
```

**Comment by lyglzhl** [comment]
当我提交时，他打印出来的，只有第一个值修改了，后面的几个值都是原来的值，意思就是没有获取到最新我输入的值，不知道您明白我的意思了吗

**Comment by xuliangzhan** [comment]
是的，该问题在手动模式下确实会造成值丢失，会在2.6+修复 
https://jsfiddle.net/r75tnao1/
