### ISSUE TITLE
表格树的子节点不能被进行有效性验证(validate)

### ISSUE THREAD

**Issue by kongwenjuan** [xuliangzhan/vxe-table#393]
### （必填）请填写问题描述 Describe the bug
使用表格树时，需要对节点的名称、类型验证是否为空，不为空时才可对某一节点增加子节点信息；使用表格的validate或者fullValidate都无法对表格树子节点进行验证，只能对根节点目录进行验证。
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-bmn0s

### 填写报错信息或截图 Error message or screenshots
 
![image](https://user-images.githubusercontent.com/31580037/65735502-4da39700-e10a-11e9-94f6-57c28d6bc2aa.png)
![image](https://user-images.githubusercontent.com/31580037/65735561-74fa6400-e10a-11e9-9a66-bc4eee3cef88.png)

### （必填）请填写期望的结果 Expected behavior

 表格树中的子节点也能够被校验到是否内容正确

### （必填）请填写版本号 Version

- os: windows10
- browser: Google Chrome(77.0.3865.90)
- vue: 2.6.10
- vxe-table: 2.5.11
-vxe-table-plugin-iview：1.4.3
-iview:3.5.0

**Comment by xuliangzhan** [comment]
目前是不支持树形结构校验的，后续可能会考虑支持

**Comment by kongwenjuan** [comment]
> 续可能会考虑支持
哭...................能否尽快考虑支持呢？万分感谢！！！！

**Comment by kongwenjuan** [comment]
哭...................能否尽快考虑支持呢？万分感谢！！！！

**Comment by xuliangzhan** [comment]
这个。。。，如果急可以体验 v2.6 beta 版本哈

**Comment by Tiramisu1** [comment]
你好 ！ 请问你是怎么获取节点的 我最近做这部分遇到了问题 this.$utils.findTree报错 findTree undefined，我发现is.$utils也是undefined 但是我已经全局注册了

**Comment by kongwenjuan** [comment]
> 这个。。。，如果需要该功能可以体验 v2.6 beta 版本哈

**Comment by kongwenjuan** [comment]
import XEUtils from 'xe-utils'

**Comment by kongwenjuan** [comment]
页面里进行引用
import XEUtils from 'xe-utils'

**Comment by xlz26296** [comment]
@Tiramisu1 如果你想要用 xe-utils 的相关方法，以下方式都可以
或者
```javascript
import Vue from 'vue'
import XEUtils from 'xe-utils'
Vue.prototype.$utils = XEUtils
```
或者
```javascript
import Vue from 'vue'
import XEUtils from 'xe-utils'
import VXEUtils from 'vxe-utils'
Vue.use(VXEUtils, XEUtils)
```

**Comment by Tiramisu1** [comment]
> @ Tiramisu1如果你想要用xe-utils的相关方法，以下方式都可以
> 或者
> 
> ```js
> 进口 Vue公司 从 ' VUE '
> 进口 XEUtils  从 ' XE-utils的'
>  Vue公司。原型。$ utils  = XEUtils
> ```
> 
> 或者
> 
> ```js
> 进口 Vue公司 从 ' VUE '
> 进口 XEUtils  从 ' XE-utils的'
> 进口 VXEUtils  从 ' VXE-utils的'
>  Vue公司。使用（VXEUtils，XEUtils）
> ```
谢谢你了 
我看demo里面有一段代码 我复制下来之后直接报错了,findTree undefined请问是XEUtils 引用的问题么，因为我按照你说的办法引用之后还是报了这个错误
` let xTree = this.$refs.xTree;
      let removeRecords = xTree.getSelectRecords();
      removeRecords.forEach(row => {
        let matchObj = this.$utils.findTree(
          this.tableData,
          item => item === row,
          this.treeConfig
        );`

**Comment by Tiramisu1** [comment]
> 页面里进行引用
> import XEUtils from 'xe-utils'

你好 我在页面中引用还是在报错findTree undefined，下面是我在页面引用的代码、
`import Vue from "vue";
import XEUtils from "xe-utils";
Vue.use(XEUtils);`

**Comment by Tiramisu1** [comment]
> > @ Tiramisu1如果你想要用xe-utils的相关方法，以下方式都可以
> > 或者
> > ```js
> > 进口 Vue公司 从 ' VUE '
> > 进口 XEUtils  从 ' XE-utils的'
> >  Vue公司。原型。$ utils  = XEUtils
> > ```
> > 
> > 
> > 或者
> > ```js
> > 进口 Vue公司 从 ' VUE '
> > 进口 XEUtils  从 ' XE-utils的'
> > 进口 VXEUtils  从 ' VXE-utils的'
> >  Vue公司。使用（VXEUtils，XEUtils）
> > ```
> 
> 谢谢你了
> 我看demo里面有一段代码 我复制下来之后直接报错了,findTree undefined请问是XEUtils 引用的问题么，因为我按照你说的办法引用之后还是报了这个错误
> ` let xTree = this.$refs.xTree; let removeRecords = xTree.getSelectRecords(); removeRecords.forEach(row => { let matchObj = this.$utils.findTree( this.tableData, item => item === row, this.treeConfig );`

已经解决了 应该用Vue.prototype.$utils = XEUtils 方式引用 谢谢你!

**Comment by Tiramisu1** [comment]
> > 页面里进行引用
> > import XEUtils from 'xe-utils'
> 
> 你好 我在页面中引用还是在报错findTree undefined，下面是我在页面引用的代码、
> `import Vue from "vue"; import XEUtils from "xe-utils"; Vue.use(XEUtils);`

已经解决了 应该用Vue.prototype.$utils = XEUtils 方式引用 谢谢!

**Comment by Tiramisu1** [comment]
> 页面里进行引用
> import XEUtils from 'xe-utils'

你好 请问一下我在数组添加多条数据时,报错key值重复,可是我的key值指定的是id,请问你有遇到这个问题么?
![image](https://user-images.githubusercontent.com/29446127/66534331-78e5a780-eb48-11e9-89fe-67d04efaa73a.png)
![image](https://user-images.githubusercontent.com/29446127/66534353-89961d80-eb48-11e9-91c8-a276615dbaca.png)
![image](https://user-images.githubusercontent.com/29446127/66534368-931f8580-eb48-11e9-8035-97b55d5e420e.png)
