### ISSUE TITLE
表格树中新增子节点或者根节点时，只能在第一次操作时获取到焦点，后续新增焦点都会丢失

### ISSUE THREAD

**Issue by kongwenjuan** [xuliangzhan/vxe-table#394]
### （必填）请填写问题描述 Describe the bug
在表格树中操作新增子节点，或者表格树外部使用新增为表格树增加根节点时，只有第一次触发事件时能够对新增行的某一列进行焦点聚焦，其余触发事件后都不能焦点聚焦

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-8420y

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/31580037/65736144-b12ec400-e10c-11e9-8e46-6ff69a6603eb.png)
![image](https://user-images.githubusercontent.com/31580037/65736220-e2a78f80-e10c-11e9-8ed3-d07b50c05ea6.png)

### （必填）请填写期望的结果 Expected behavior

 每次点击新增时使用setActiveCell都能够获取到焦点，而不是只有第一次能够获取，其余操作都不能获取

### （必填）请填写版本号 Version

- os: windows10
- browser: Google Chrome(77.0.3865.90)
- vue: 2.6.10
- vxe-table: 2.5.11
-vxe-table-plugin-iview：1.4.3
-iview:3.5.0

**Comment by xuliangzhan** [comment]
如果你想要自定义渲染，那么所有逻辑都应该自行控制，如果要聚焦到自定义的输入框中，可以指定 autofocus 参数
请先看文档：https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/template
