### ISSUE TITLE
v-html 无法使用

### ISSUE THREAD

**Issue by qianfangyuan** [xuliangzhan/vxe-table#395]
v-html 无法使用：

代码：
      \<vxe-table-column field="msg" title="Msg" >
       \<template v-slot="{ row }">
          \<span v-html="row.msg"></span>
        \</template>
      \</vxe-table-column>

报错：
[Vue warn]: Error in render: "TypeError: Cannot read property 'msg' of undefined"

found in

---> <ExeShell> at src/components/Task/exeShell.vue
       <ElTabPane>
         <ElTabs>
           <Task> at src/components/Task/Task.vue
             <ElMain>
               <ElContainer>... (1 recursive calls)
                 <Index> at src/components/Index.vue
                   <App> at src/App.vue
                     <Root>

环境：
mac：10.14.6
chrome：77.0.3865.90
vxe-table：2.5.22
xe-util:2.2.4

**Comment by xuliangzhan** [comment]
请先看文档
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/template
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/template

**Comment by qianfangyuan** [comment]
可能是环境有问题，重新初始化之后就好了
