### ISSUE TITLE
想知道作者在表格中如果实现jsx支持的，并没有看到vue官方说的@vue/babel-preset-jsx @vue/babel-helper-vue-jsx-merge-props插件

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#396]
### （必填）请填写问题描述 Describe
想知道怎么实现自定义组件插槽传入的时候，怎么实现jsx支持的，目前有类似的需求要实现，但是我直接使用jsx往表格上集成，会出现不支持jsx的问题，缺少$createElemt ,查看表格源码中貌似没有引用官方说的**@vue/babel-preset-jsx @vue/babel-helper-vue-jsx-merge-props**这些插件，如果我要使用，该怎么实现类似的功能

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/65825583-2c2de100-e2ab-11e9-92b2-5bd3dbde10e0.png)
根据vue 官方的说法，使用了这个babel插件，也会内置h的render函数，但是我看表格中就大量怎么用的，但没有安装这个jsx的babel插件

**Comment by xuliangzhan** [comment]
除非你不是用 vue cli 创建的项目，否则 vue 默认全部都配置好的

**Comment by wekerSnail** [comment]
我意思是我直接用jsx语法会报错，看文档是需要安装babel-plugin-transform-vue-jsx才行的，但是我看表格是支持的，但是没有看到有用到这个插件，想问一下是通过什么方式实现的

**Comment by xuliangzhan** [comment]
jsx语法，这个和表格没啥关系了，只要表格能支持渲染的方法都是可以使用，不管你是用render、jsx还是其他，最终转换后给vue执行的都是 VNode 对象
