### ISSUE TITLE
分页查询正常，但f11出现：Invalid prop: type check failed for prop "size". Expected String with value "10", got Number with value 10.

### ISSUE THREAD

**Issue by Mr1yan** [xuliangzhan/vxe-table#398]
### （必填）请填写问题描述 Describe the bug
Invalid prop: type check failed for prop "size". Expected String with value "10", got Number with value 10.

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/11636116/65825549-96925180-e2aa-11e9-93ad-1cee97a8ffc0.png)

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: window
- browser: chrome  77.0.3865.90
- vue: 2
- vxe-table: 2.5.21

**Comment by NateScarlet** [comment]
出现同样问题，研究发现是因为 vxe-table 默认父级的 size 属性是提供给它的。

https://github.com/x-extends/vxe-table/blob/afbc8e331b1a4010eb491deeaf8506a30af54ae3/packages/mixins/size.js#L5

在父级组件中避免使用 `size` 作为属性名可以暂时避开这个问题。
