### ISSUE TITLE
cdn引入vxe-table js报如下错误

### ISSUE THREAD

**Issue by 572501797** [xuliangzhan/vxe-table#399]
vxe-table v2版本 ：
错误如下： vxe-table.js:2047 Uncaught TypeError: Cannot read property 'browse' of undefined
    at Module.fae3 (VM425 vxe-table.js:2047)
    at n (VM425 vxe-table.js:10)
    at 014b (VM425 vxe-table.js:37)
    at VM425 vxe-table.js:38
    at VM425 vxe-table.js:2
    at VM425 vxe-table.js:3

**Comment by xuliangzhan** [comment]
请先看文档
https://jsrun.pro/vIyKp/edit

**Comment by 572501797** [comment]
感谢提示，还有个问题 我这边把cdn文件下载然后引入 不能使用 是什么原因呢 ？ 是否还需要其他插件的支持

**Comment by 572501797** [comment]
> 请先看文档
> https://jsrun.pro/vIyKp/edit

感谢提示，还有个问题我这边把cdn文件下载然后约会无法使用是什么原因呢？是否还需要其他插件的支持

**Comment by WillieOng-HK** [comment]
你好，如果使用CDN 加载 还能使用全局配置吗？我是使用 plugins 和 import setup 全局配置的

```
import Vue from "vue";
import VXETable from "vxe-table";
import i18n from "../i18n";
import 'vxe-table/lib/index.css'
import VXETablePluginElement from "vxe-table-plugin-element";
import "vxe-table-plugin-element/dist/style.css";

// 将模态窗口挂载到 vue 实例中

Vue.prototype.$XModal = VXETable.modal;
VXETable.use(VXETablePluginElement);
Vue.use(VXETable, {
    // 集成 vue-i18n
    i18n: key => i18n.t(key),
    // 对参数的内容自动进行国际化翻译
    translate(key) {
        // 只翻译 "app." 开头的键值
        if (key && key.indexOf("app.") > -1) {
            return i18n.t(key);
        }
        return key;
    }
});
```

但 使用 cdn 和 webpack external 时 ，则说找不到 VXETable `./plugins/table.js`
