### ISSUE TITLE
vxe grid的分页控件更新版本有问题了吧？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#40]
**问题描述 Describe the bug**

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
什么问题？

**Comment by tiger54910** [comment]
分页下拉框选择之后显示没有变，数据查询是使用了每页大小；

**Comment by xuliangzhan** [comment]
需要更新到最新，修复了

**Comment by tiger54910** [comment]
谢谢您，不厌其烦地回复我提出的问题！
