### ISSUE TITLE
table-column中:edit-render为select时，optionProps属性绑定的label无效！

### ISSUE THREAD

**Issue by xsdream** [xuliangzhan/vxe-table#401]
### （必填）请填写问题描述 Describe the bug
table-column中:edit-render为select时，optionProps属性绑定的label无效！
 ?

### （必填）请填写能重现问题的链接
本地项目

 ?

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/31870384/66187612-b9ac6f00-e6b7-11e9-857a-1110991c2fad.png)
![image](https://user-images.githubusercontent.com/31870384/66187645-c9c44e80-e6b7-11e9-920e-45e2396ff901.png)

 ?

### （必填）请填写期望的结果 Expected behavior
表格中能正确有值显示
 ?

### （必填）请填写版本号 Version
- vxe-table: 2.5.12

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/66188326-a1d5ea80-e6b9-11e9-9b53-2eacad0deb53.png)
![image](https://user-images.githubusercontent.com/31870384/66188342-aac6bc00-e6b9-11e9-83ed-81fd858ebde9.png)
这样是可以的，但是如果反过来，就不行了
![image](https://user-images.githubusercontent.com/31870384/66188430-d0ec5c00-e6b9-11e9-8399-30640339eb80.png)
![image](https://user-images.githubusercontent.com/31870384/66188437-d5187980-e6b9-11e9-9c19-7d0a643cc6fc.png)

**Comment by xsdream** [comment]
解决了，id必须是number类型！不能是string类型！文档上给个提示吧！

**Comment by xuliangzhan** [comment]
这个没说一定要 number 类型，都是可以的
