### ISSUE TITLE
vxe-grid columns中className未生效

### ISSUE THREAD

**Issue by houjiazong** [xuliangzhan/vxe-table#403]
### （必填）请填写问题描述 Describe the bug

![image](https://user-images.githubusercontent.com/1658546/66372586-eb377a00-e9d8-11e9-8e94-36a55146b757.png)

 根据API描述 vxe-grid columns 中传入className没有生效

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vue-antd-template-dr7hv

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/1658546/66372928-e2937380-e9d9-11e9-9b54-77f063b48c91.png)

### （必填）请填写期望的结果 Expected behavior

 支持 className

### （必填）请填写版本号 Version

- os: osx 10.14.6
- browser: Chrome 版本 77.0.3865.90（正式版本） （64 位）
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by xlz26296** [comment]
我建议你把文档那个截图一整行看完整 哈

**Comment by houjiazong** [comment]
> 我建议你把文档那个截图一整行看完整 哈

嗯嗯 试了2.6 beta版是可以的😆
