### ISSUE TITLE
可编辑selected没法满足联动需求，因为列共用一个options

### ISSUE THREAD

**Issue by xsdream** [xuliangzhan/vxe-table#407]
### （必填）这个需求解决了什么问题 What problem does this feature solve

列中下拉选联动效果

### （必填）建议的 API 是什么样的 What does the proposed API look like
能够通过行控制行来控制options

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 没有

**Comment by xuliangzhan** [comment]
#314
