### ISSUE TITLE
 element-ui 组合渲染 对应表格无法编辑

### ISSUE THREAD

**Issue by GevinYang** [xuliangzhan/vxe-table#408]
### （必填）请填写问题描述 Describe the bug

 ele组件渲染、可编辑表格；单元格编辑完毕后无法保存编辑内容

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://xuliangzhan.github.io/vxe-table/#/table/plugin/elementPage

### 填写报错信息或截图 Error message or screenshots

 

![vhvhv](https://user-images.githubusercontent.com/50934848/66551109-646dd300-eb79-11e9-9656-c1118672d632.gif)

### （必填）请填写期望的结果 Expected behavior

 正常表格编辑

### （必填）请填写版本号 Version

- os: windows10 1809
- browser: Chrome 77.0.3865.90
- vue: 2.6.10
- vxe-table: unpkg版本

**Comment by GevinYang** [comment]
我还其他BUG反馈，还请您联系我企鹅905395757，感谢

**Comment by xuliangzhan** [comment]
unpkg版本是指向最新的，包括 beta 版，你可以锁定稳定版
