### ISSUE TITLE
使用第三方element库，select的@change事件不触发，没法更新值！！

### ISSUE THREAD

**Issue by xsdream** [xuliangzhan/vxe-table#409]
### （必填）请填写问题描述 Describe the bug

使用第三方element库，select的@change事件不触发，没法更新值！！

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://xuliangzhan.github.io/vxe-table/#/table/other/element
大佬你自己的demo中貌似也不能更新，你可以试试

### 填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/31870384/66551608-62f0da80-eb7a-11e9-9c99-a2f6ff5f6789.png)

### （必填）请填写期望的结果 Expected behavior

能正确更新值，触发updateStatus（）更新值

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xsdream** [comment]
help，急急急~

**Comment by xlz26296** [comment]
不是这样提 Issues 的，你应该使用在线链接，官网是 beta 版本可能是会存在些问题

**Comment by xsdream** [comment]
解决了，需要安装  vxe-table-plugin-element  插件

**Comment by xsdream** [comment]
@xlz26296 不太明白 在线链接  是什么

**Comment by 3xxx** [comment]
我也遇到，原来是这样啊，折腾了好久。感谢。
