### ISSUE TITLE
使用Vxe_grid的时候，使用ajax动态添加表列，但是显示/隐藏列的按钮下拉列表无法列出动态设置的表头，应该怎么做呢？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#41]
**描述 Describe**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
更新到最新，参考[demo](https://xuliangzhan.github.io/vxe-table/#/table/grid/dynamic)

**Comment by tiger54910** [comment]
谢谢您，回复很及时，也能够解决提出的问题，看来是可以用到项目中去了，再次感谢您！
