### ISSUE TITLE
表头分组用html的分式可以，但是通过组件来弄就不行

### ISSUE THREAD

**Issue by jsjzhengfu** [xuliangzhan/vxe-table#410]
### （必填）请填写问题描述 Describe the bug
就是通过定义一个columns传入组件，类似vxe-grid一样，然后通过递归来生成vxe-table-column；
columns的结果如图：
![image](https://user-images.githubusercontent.com/37528848/66555449-473d0280-eb81-11e9-92b2-0db96df6f88b.png)

 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://jsfiddle.net/frzg2d3k/3/   不知道为啥在这里不能运行，我在本地可以运行看到效果。帮忙看看大概的思路
 ?

### 填写报错信息或截图 Error message or screenshots
如图是通过传入columns的方式的效果。生成的结构和html的一样，但是显示的结果不一样
![image](https://user-images.githubusercontent.com/37528848/66553232-515d0200-eb7d-11e9-9512-e0d9bea801dc.png)

 ?

### （必填）请填写期望的结果 Expected behavior
如图是通过html的方式的效果
![image](https://user-images.githubusercontent.com/37528848/66553199-4609d680-eb7d-11e9-8fbb-053ffb701cce.png)

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
不明白你这样封装的用处是做什么？

**Comment by jsjzhengfu** [comment]
> 不明白你这样封装的用处是做什么？
> [＃218](https://github.com/xuliangzhan/vxe-table/issues/218)

就是想通过js的方式来生成表格的分组的列，我用elementui的表格这样弄是可以的，但是用了vxe-table就不行。因为在一些业务中，表格的表头分组是动态的，如果不通过js来配置直接用html就不知道怎么弄了。类似你封装的vxe-grid通过传入columns估计也是考虑了这些动态的情况，但是vxe-grid的columns好像没考虑到表格分组的情况

**Comment by xuliangzhan** [comment]
#316
