### ISSUE TITLE
有一列固定 手动触发可编辑表格无法 修改

### ISSUE THREAD

**Issue by wiserui** [xuliangzhan/vxe-table#412]
### （必填）请填写问题描述 Describe

第一列固定列 然后 手动触发 可编辑表格 修改这一列 固定的列没法修改

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

http://jsrun.pro/QpWKp/edit

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: windows 10
- browser: firfox 69.0.2
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by wiserui** [comment]
上面那个地址 还有一个问题是 使用 TAB 按键切换列进行编辑后 修改失败，只有鼠标点过的才能修改成功。

**Comment by xuliangzhan** [comment]
#392

**Comment by wiserui** [comment]
> 
> 
> #392
> 该问题是在 v2.6 修复的 http://jsrun.pro/4pWKp/edit

ok，谢谢
