### ISSUE TITLE
多选表格中，通过 toggleRowSelection 方法切换行选中状态，不会触发 select-change 事件

### ISSUE THREAD

**Issue by shawchen08** [xuliangzhan/vxe-table#414]
### （必填）请填写问题描述 Describe the bug
多选表格中，通过 `toggleRowSelection` 方法切换行选中状态，不会触发 `select-change` 事件

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[在线 demo](https://codepen.io/shawchen08/pen/MWWaLNm)

### 填写报错信息或截图 Error message or screenshots

 应该触发 `select-change` 事件然而未触发

### （必填）请填写期望的结果 Expected behavior

通过` toggleRowSelection` 方法切换行选中状态，应该要触发 `select-change` 事件

### （必填）请填写版本号 Version

- os: Windows 10
- browser: Google Chrome  77.0.3865.90（正式版本）（64 位）
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by shawchen08** [comment]
虽然文档上对于 `select-change` 强调了 **手动勾选并且值发生改变**，但是，我觉得通过 `toggleRowSelection` 方法切换行选中状态，也算是手动触发，同样要触发 `select-change` 事件，不然状态响应会有遗漏

**Comment by livelyPeng** [comment]
@shawchen08 你可以使用下https://github.com/livelyPeng/pl-table

**Comment by xuliangzhan** [comment]
#370
首先从API的设计上就已经明确说明了，事件的触发条件只能是用户行为；既然都可以手动调用方法，为什么不再手动调用相关的处理方法，所以这本身就是不合理的方式；

**Comment by shawchen08** [comment]
就上面的在线 demo 而言，左上角那个按钮也是用户点击，这种不触发 select-change 事件，如何响应状态？

**Comment by xuliangzhan** [comment]
你说全选吗？全选是触发 select-all 这个事件，你可以在这个事件里面去处理所有子项的逻辑

**Comment by shawchen08** [comment]
`切换第二行选中` 这个按钮

**Comment by xuliangzhan** [comment]
这个用户的触发源在按钮中而不是勾选行，你是手动调用 toggleRowSelection，这不属于复选框的用户行为，不会触发

**Comment by shawchen08** [comment]
就算要自行处理，但是代码中对于对象相等判断用的是全等（或者 indexOf），是不可靠的，真实场景中，**数据经过多层组件之间的传递，早已不是原来的对象**
[复现场景](https://codepen.io/shawchen08/pen/MWWaLNm)
复现步骤：
1. 在左边表格选中任意一行
2. 在右边点击删除
3. 注意观察左下角的 **选中人** ，另外左侧表格的选中状态未更改

[具体代码](https://github.com/xuliangzhan/vxe-table/blob/master/packages/table/src/methods.js#L1312)

**Comment by xuliangzhan** [comment]
首先js中的对象是引用传递，不可能会存在对象被自动改变引用的
当引用被改变了，你就应该检查写法。很明显看代码中row你强制把他引用改了，导致row不是原来的row
![image](https://user-images.githubusercontent.com/34864213/66698815-c95d3080-ed13-11e9-8849-d4747fa54877.png)
```javascript
this.$refs.xTable1.toggleRowSelection(row)
```

**Comment by shawchen08** [comment]
比如，重新请求数据，这时对象就不再是原来的对象，而如果 toggleRowSelection 能触发 select-all 这将不再是问题
[https://codepen.io/shawchen08/pen/MWWaLNm](https://codepen.io/shawchen08/pen/MWWaLNm)

**Comment by xuliangzhan** [comment]
如果是这种场景，应该通过设置 rowId 为行数据的主键，通过主键方法 getRowById 去获取 row

**Comment by shawchen08** [comment]
非常感谢解答，这个 issue 可以关了，我其实还是希望作者可以考虑一下，只要复选框状态改变就触发 select-change 事件，另外 toggleRowSelection 这类 api 能不能支持主键这种实现方式

**Comment by xuliangzhan** [comment]
toggleRowSelection 相关方法是不支持主键，你可以通过 getRowById 转换一下就行
