### ISSUE TITLE
配置式表格进行展开行时slot语法解析有错误

### ISSUE THREAD

**Issue by chinavane** [xuliangzhan/vxe-table#415]
### （必填）请填写问题描述 Describe
配置式表格进行展开行时应用了slots，通过return返回html肉，但是却报了Uncaught SyntaxError: Unexpected token '<'错误。
 
```tableColumn: [
                        { type: 'index', width: 50 },
                        { type: 'selection', width: 50 },
                        {
                            type: 'expand', width: 50, slots: {
                                default: ({ row, column }) => {
                                    return [
                                        <a class="link" href="https://xuliangzhan.github.io/vxe-table/">我是超链接：</a>
                                    ]
                                }
                            }
                        },
                        { field: 'customerName', title: '客户名称', sortable: true },
                        { field: 'goodsNo', title: '商品编号', showHeaderOverflow: true, sortable: true },
                        { field: 'orderSn', title: '订单序号', showOverflow: true }
],```




### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: mac
- browser: chrome
- vue: 2.6.10
- vxe-table: v2

**Comment by chinavane** [comment]
`<!DOCTYPE html>
<html lang="en">

<body>
    <div id="app">
        <template>
            <div>
                <div class="btns">
                    <template v-for="item in items">
                        <el-badge :value="item.value" class="item" effect="dark" :hidden="item.value ==0">
                            <el-tag :type="item.type">
                                {{ item.label }}
                            </el-tag>
                        </el-badge>
                    </template>
                </div>
                <vxe-grid ref="xGrid" :data="tableData" highlight-hover-row="highlight-hover-row" border="border" stripe="stripe"
                    resizable="resizable" :customs.sync="customColumns" :columns="tableColumn" :toolbar="tableToolbar">
                    >
                </vxe-grid>
            </div>
        </template>
    </div>
    
    <link rel="stylesheet" href="https://unpkg.com/vxe-table/lib/index.css" />
    
    <script src="//unpkg.com/vue"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css" />
    
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    <script src="https://unpkg.com/xe-utils"></script>
    <script src="https://unpkg.com/vxe-table"></script>
    <script src="https://cdn.bootcss.com/axios/0.19.0-beta.1/axios.min.js"></script>
    <script>

        var Main = {
            data() {
                return {
                    tableData: [],
                    tableColumn: [
                        { type: 'index', width: 50 },
                        { type: 'selection', width: 50 },
                        {
                            type: 'expand', width: 50, slots: {
                                default: ({ row, column }) => {
                                    return [
                                        <a class="link" href="https://xuliangzhan.github.io/vxe-table/">我是超链接：</a>
                                    ]
                                }
                            }
                        },
                        { field: 'customerName', title: '客户名称', sortable: true },
                        { field: 'goodsNo', title: '商品编号', showHeaderOverflow: true, sortable: true },
                        { field: 'orderSn', title: '订单序号', showOverflow: true }
                    ],
                    customColumns: [
                    ],
                    items: [
                        { type: '', label: '标签一', value: 0 },
                        { type: 'success', label: '标签二', value: 10 },
                        { type: 'info', label: '标签三', value: 10 },
                        { type: 'danger', label: '标签四', value: 0 },
                        { type: 'warning', label: '标签五', value: 20 }
                    ],
                    tableToolbar: {
                        id: 'full_edit_1',
                        resizable: {
                            storage: true
                        },
                        setting: {
                            storage: true
                        }
                    }
                }
            },
            async created() {
                const data = {
                    "dto": {
                        "orderStatus": "10",
                        "orderBy": "z.sale_time desc",
                        "ywPersonId": "",
                        "distributionPersonId": "",
                        "orderSn": "",
                        "cylinderNo": "",
                        "goodsId": "",
                        "customerId": "",
                        "startDate": "",
                        "endDate": "2019-10-11",
                        "isVoid": "n"
                    },
                    "page": {
                        "current": "1",
                        "length": "30",
                        "count": "0",
                        "total": "1"
                    }
                };
                const res = await axios({
                    url: 'http://localhost:8099/logistics/queryLogisticsGoodsList.rpc',
                    params: data,
                    method: 'POST',
                });
                this.tableData = res.data.data;
                console.log(res.data.data)
            }

        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app')
    </script>
</body>

</html>`

**Comment by livelyPeng** [comment]
@chinavane 你可以使用下https://github.com/livelyPeng/pl-table  vxe相对来说有点难度

**Comment by xlz26296** [comment]
这种问题和表格没关系，你应该看 vue 文档 https://cn.vuejs.org/v2/guide/render-function.html#JSX
jsx 语法是要先编译成 VNode 才能在浏览器端给 vue 执行的
