### ISSUE TITLE
表头筛选功能怎么实现回车即可筛选？

### ISSUE THREAD

**Issue by fls1215** [xuliangzhan/vxe-table#418]
### （必填）请填写问题描述 Describe

请问怎么实现表头筛选的单选下拉框、文本框等的回车触发筛选功能？

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://xuliangzhan.github.io/vxe-table/#/table/plugin/elementFilter

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
这个文档有例子吧

**Comment by fls1215** [comment]
> 这个文档有例子
我没有找到，能麻烦提供下链接吗？

**Comment by xlz26296** [comment]
上面的链接就有

**Comment by fls1215** [comment]
> 你上面的那个链接就有
我试了不行的，例子本身就没有回车筛选

**Comment by xuliangzhan** [comment]
通过 [events](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/events) 绑定事件去做处理就行
