### ISSUE TITLE
增加动态定义列的分组

### ISSUE THREAD

**Issue by flywin8** [xuliangzhan/vxe-table#42]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
需要在动态列名下生成列的分组，不用的报表列头分组不同，所以需要动态渲染，之前自己在vue-element-extends下自定义组件实现的，现在是否可以在vxe-table中增加这个功能

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
是否考虑增加动态定义列的分组，目前只能动态定义列，但是不能定义列的分组，是否可以增加group的属性[{ prop:‘group1', label:'分组1' }]这种模式来实现。

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
不太明白你的意思，请先看文档哈 https://xuliangzhan.github.io/vxe-table/#/table/grid/basic

**Comment by flywin8** [comment]
> 不太明白你的意思，请先看文档哈 https://xuliangzhan.github.io/vxe-table/#/table/grid/basic

这个文档当时没有仔细看，从侧面菜单分页中没有看到动态分组的说明，这些看到了直接使用children就可以了
