### ISSUE TITLE
使用highlight-hover-row属性，光标移出表格后hover效果还在

### ISSUE THREAD

**Issue by guohongshan** [xuliangzhan/vxe-table#423]
### （必填）请填写问题描述 Describe

 ?使用highlight-hover-row属性，光标移出表格后hover效果还在

### （必填）请填写能重现问题的链接

 ? 拷过来的代码都没有改

### 请填写报错信息或截图 Error message or screenshots

 ?
![Snipaste_2019-10-14_10-02-47](https://user-images.githubusercontent.com/31247970/66726082-d724ca00-ee69-11e9-9aa5-5543a4f4c9d3.png)
此时我的光标已经移出表格了

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?2.6.10
- vxe-table: ?2.5.22

**Comment by xlz26296** [comment]
这个问题是在 2.6 修复的，你可以体验 v2.6

**Comment by guohongshan** [comment]
![image](https://user-images.githubusercontent.com/31247970/66730308-638fb680-ee83-11e9-9413-2dfbffe7c02d.png)
我看最高版本是2.5.22啊

**Comment by xlz26296** [comment]
2.6 beta 版需要手动指定，2.6 正式版还没发吧

**Comment by guohongshan** [comment]
![image](https://user-images.githubusercontent.com/31247970/66730726-119c6000-ee86-11e9-81f9-7b9170287564.png)

npm i vxe-table@2.6.0
这种方式也是找不到。正式版本什么时候发？

**Comment by guohongshan** [comment]
什么时候发布vxe-table 的2.6版本啊。

**Comment by xlz26296** [comment]
https://www.npmjs.com/package/vxe-table 发布版本这里都有的，你可以使用最新的beta版
