### ISSUE TITLE
element的自定义组件嵌套table中，无法编辑，数据无法修改

### ISSUE THREAD

**Issue by alanlja** [xuliangzhan/vxe-table#427]
### （必填）请填写问题描述 Describe the bug

 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots
![1111](https://user-images.githubusercontent.com/36754679/66814331-00784f80-ef69-11e9-8d81-b8a552a4d0ce.png)

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version
vxe-table@2.6.0-beta.12
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by hasbug** [comment]
vxe-table-plugin-element 必须组件。
https://xuliangzhan.github.io/vxe-table/#/table/other/element
