### ISSUE TITLE
行合并后，能在每个合并后的行下增加一个行尾统计吗？

### ISSUE THREAD

**Issue by xsshu** [xuliangzhan/vxe-table#428]
### （必填）这个需求解决了什么问题 What problem does this feature solve

行合并后，针对每个合并后的行增加一个行尾统计

### （必填）建议的 API 是什么样的 What does the proposed API look like

![image](https://user-images.githubusercontent.com/55428364/66819359-6ec11000-ef71-11e9-9e75-5dc74b971ceb.png)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

目前是想着后端数据处理，传到前台的时候数据就是包含了统计结果的，但是还是想问一下有没有不经过后端处理可以实现的方法

**Comment by xuliangzhan** [comment]
这种业务逻辑，你可以通过自定义模板去实现
