### ISSUE TITLE
<vxe-grid>的height属性的值只会考虑表格高度，没有限定toolbar

### ISSUE THREAD

**Issue by flashliao** [xuliangzhan/vxe-table#429]
### （必填）请填写问题描述 Describe the bug

 ? <vxe-grid>的height属性的值只会考虑表格高度，而不考虑toolbar。我想实现toolbar与表格和工具栏（toolbar）二为一的表格整体限定高度等于浏览器器的innerheight。例如样式这样
<template>

    <vxe-grid
      border
      resizable
      highlight-hover-row
      remote-filter
      ref="xGrid"
      row-id="id"
      :height="tableHeight"
      :pager-config="{pageSize: 15}"
      :toolbar="tableToolbar"
      :proxy-config="tableProxy"
      :columns="tableColumn"
      :select-config="{reserve: true}"
    ></vxe-grid>

</template>
java：

  methods: {
     getHeight(){
          this.tableHeight=window.innerHeight;
       }

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
这个问题会在 v2.6 修复
