### ISSUE TITLE
vxe-grid支持自定义column吗，vxe-table 列滚动渲染在新版本里面失效了

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#43]
vxe-grid支持自定义column吗，文档里面海量数据 都是用vxe-grid来实现的。新版本不支持vxe-table 实现海量数据吗，我试了下10000列用vxe-table，横向的滚动渲染不生效？
![image](https://user-images.githubusercontent.com/11676609/58771733-5070fe00-85e8-11e9-91e6-34d23fc3e34a.png)
![image](https://user-images.githubusercontent.com/11676609/58771743-5ff04700-85e8-11e9-928e-a74e71cd4646.png)

**Comment by xuliangzhan** [comment]
不可能会失效的，vxe-grid 的核心就是 vxe-table，没有发现你说的问题 https://jsrun.net/ULyKp

**Comment by lishihong** [comment]
多谢，最新版是ok的，已经搞定了
