### ISSUE TITLE
全局mixin里边有params,使用vxe之后报错

### ISSUE THREAD

**Issue by LuckyTaoTao** [xuliangzhan/vxe-table#431]
### （必填）请填写问题描述 Describe the bug

 
![image](https://user-images.githubusercontent.com/34666627/66883384-5e0bab00-f000-11e9-8e97-e3fec9d070f0.png)

The data property "params" is already declared as a prop. Use prop default value instead.
### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by LuckyTaoTao** [comment]
能否吧你们的有些常用属性添加前缀，避免和项目原有属性逻辑冲突

**Comment by LuckyTaoTao** [comment]
谢谢！

**Comment by xuliangzhan** [comment]
从代码结构上来设计，如果 mixin 要全局使用，将会影响全部的组件，本身就应该把相关的属性私有化，而不应该使用常用属性名，不同的第三方组件的属性命名都会存在重复的可能性，这个不应该由组件去解决

**Comment by LuckyTaoTao** [comment]
谢谢！
