### ISSUE TITLE
两个table分别放进elementui tabs组件，切换tab后，column无法撑开，导致tabale右侧空白

### ISSUE THREAD

**Issue by jingyuLin1999** [xuliangzhan/vxe-table#433]
### （必填）请填写问题描述 Describe the bug
把两个table分别放进elementui tabs组件各自的tab下，发现切换tab后，table右侧出现空白，column无法默认撑开
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
内网测试，暂无
 ?

### 填写报错信息或截图 Error message or screenshots
![微信图片_20191016153429](https://user-images.githubusercontent.com/30433062/66897869-801a2300-f02a-11e9-8d02-86bdec9c951c.png)

![微信图片_20191016153525](https://user-images.githubusercontent.com/30433062/66897927-a63fc300-f02a-11e9-9832-838082c82a27.png)

 ?

### （必填）请填写期望的结果 Expected behavior
希望切换element tab，table能自动100%撑开，要做自适应，每列不能固定宽度
 ?

### （必填）请填写版本号 Version
v2.6.0-beta.18
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
#422
