### ISSUE TITLE
clearScroll 方法不会重置列头的滚动条位置

### ISSUE THREAD

**Issue by shawchen08** [xuliangzhan/vxe-table#435]
### （必填）请填写问题描述 Describe the bug

`clearScroll` 方法不会重置**列头**的滚动条位置，对于有固定列的表格，**固定列**的纵向滚动条也不会重置，而 `scrollTo` 方法对于**列头**的滚动条位置表现正常，对于**固定列**的纵向滚动条不完全生效（clearScroll 先于 scrollTo执行的话，scrollTo 对于固定列滚动条表现异常）

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 [https://codepen.io/shawchen08/pen/ZEEOeOr](https://codepen.io/shawchen08/pen/ZEEOeOr)

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 列头滚动条位置应同步重置，固定列的也是

### （必填）请填写版本号 Version

- os: Win 10
- browser: Chrome 77.0.3865.120（正式版本）（64 位）
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by xuliangzhan** [comment]
这个问题是在 v2.6 修复的

**Comment by shawchen08** [comment]
v2.6 计划什么时候发布？

**Comment by shawchen08** [comment]
我测了一下，2.6.0-beta.19 这个版本尚未解决此问题

**Comment by xuliangzhan** [comment]
不知道你指的是哪个问题，你应该重现链接来描述细节

**Comment by shawchen08** [comment]
![image](https://user-images.githubusercontent.com/25865352/66923674-d784b700-f05b-11e9-8f27-d4327b901110.png)
步骤：
1. 滚动横向滚动条
2. 点击 clearScroll 按钮
3. 注意表头错位了

**Comment by shawchen08** [comment]
步骤：
1. 滚动横向和纵向滚动条
2. 点击 clearScroll 按钮，此时表头和固定列（第一列）都错位
![image](https://user-images.githubusercontent.com/25865352/66924142-ac4e9780-f05c-11e9-80d2-ee41ad4542dc.png)
3. 点击 scrollTo 按钮，此时固定列（第一列）仍是错位
![image](https://user-images.githubusercontent.com/25865352/66923893-39ddb780-f05c-11e9-99d0-397b45dbb0ed.png)

**Comment by shawchen08** [comment]
我看了源码，clearScroll 没有对表头和固定列做处理
https://github.com/xuliangzhan/vxe-table/blob/c68e7d2c2dfc7dd40897b83e58d035562b612f7e/packages/table/src/methods.js#L2221-L2235

**Comment by xuliangzhan** [comment]
在 2.6 中我并没有重现这个问题
 https://codepen.io/xuliangzhan/pen/JjjKOwv

**Comment by shawchen08** [comment]
2.6.0-beta.19 我是在项目中测试的，现在用最新的 2.6.0-beta.20 复原了一下场景
[https://codepen.io/shawchen08/pen/ZEEOeOr](https://codepen.io/shawchen08/pen/ZEEOeOr)
步骤：
1. 拉动两个滚动条
2. 点击 loadData 按钮，一般点击两次就会出现错位现象（而我的项目中每次都会出现，reloadData 同样存在问题）

**Comment by shawchen08** [comment]
我目前的做法是直接在 clearScroll 中暴力重置所有的滚动条位置（tableBody, tableFooter, tableHeader, rightBody, leftBody）

**Comment by xuliangzhan** [comment]
你要是使用简单粗暴哦方式那肯定也是可以的哈
可以更新到21试下

**Comment by shawchen08** [comment]
21 已经解决了这个问题
