### ISSUE TITLE
集成第三方库的文档有点问题

### ISSUE THREAD

**Issue by selfdialog** [xuliangzhan/vxe-table#436]
### 请填写问题描述 Describe

集成第三方库的文档有点问题
比如：element-ui->自定义模板的代码部分，想直接复制一下用一下，结果$utils需要引用XEUtils
和VXEUtils，还有MOCK_DATA_LIST的数据能不能提供一下
![S8H 3K(RHV3I{YQ376VL6(1](https://user-images.githubusercontent.com/30248712/66971463-ea32d680-f0c3-11e9-9f8d-85430fc8ad10.png)

### 请填写版本号 Version

- os: win10
- browser: google chrome
- vue: 2.5.x
- vxe-table: 2.6.0-beta.18

**Comment by xlz26296** [comment]
你这个问题就有点。。。
$utils 是示例代码，用不用都没任何关系
MOCK_DATA_LIST 是示例的测试数据有什么好提供的

**Comment by xlz26296** [comment]
我的意思是示例跑起来就行，示例代码全部有，不然你想要这个数据要怎么提供？
