### ISSUE TITLE
全局快捷菜单注册器能否添加设置（visible，disabled）  这个两个属性

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#437]
### （必填）这个需求解决了什么问题 What problem does this feature solve

全局快捷菜单注册器能否添加设置（visible，disabled）  这个两个属性，这样可以全局注册某个快捷菜单是可见或者有效。

### （必填）建议的 API 是什么样的 What does the proposed API look like
全局快捷菜单注册器的api为：
add(code, callback)

希望可以为：
add(code, callback,visibleCallback,disabledCallback)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xlz26296** [comment]
这个全局菜单权限控制是可以通过事件拦截器处理的
```javascript
VXETable.interceptor.add('event.showMenu', (params) => {
  params.options.forEach((list) => {
    list.forEach((item) => {
      if (isDisabled(item)) {
        item.disabled = true
      }
      if (isVisible(item)) {
        item.visible = true
      }
    })
  })
})
```

**Comment by xuliangzhan** [comment]
VXETable.interceptor.add('event.showMenu', callback) 这个完全可以解决你的需求哦

**Comment by napai** [comment]
AJAX获取数据后处理方法,  虽然可以解决! 如果有 recalculate 的回调事件 就好了!
`//获取数据
		getData(){
			this.tableLoading = true;
			this.$http.post('/user/index', this.$route.query).then((json)=>{
				if(!json) return;//前端取消请求
				this.tableLoading = false;
				this.tableData = json.data.data;
				this.tablePage.total = parseInt(json.data.total);
				this.tablePage.size = parseInt(json.data.per_page);
				this.tablePage.current = parseInt(json.data.current_page);
				//初始滚动打到顶部
				var scrollStatus = this.$refs.dataTable.getVirtualScroller();
				this.$refs.dataTable.clearScroll().then(()=>{
					this.$refs.dataTable.scrollTo(scrollStatus.scrollLeft, 0);
				});
				//修复初始加载跳动问题
				if(this.firstLoad){
					this.$refs.dataTable.recalculate().then(()=>{
						this.firstLoad = false;
						this.$refs.dataTable.$el.querySelector('.vxe-table--body').style.visibility='visible';
					});
				}
			}).catch(()=>{});
		},`
