### ISSUE TITLE
群？💬

### ISSUE THREAD

**Issue by xuliangzhan** [xuliangzhan/vxe-table#438]
* 该群仅用于 vxe-table 问题反馈、交流等
* 有问题请按规范使用[重现链接](https://github.com/xuliangzhan/vxe-table/issues/390)来描述问题
![image](https://user-images.githubusercontent.com/34864213/67100699-b904f400-f1f2-11e9-9fd2-58af71595407.png)

**Comment by GevinYang** [comment]
需要！！！（破音）

**Comment by xiaogaofudao** [comment]
申请加入了。
刚升级2.6.0 发现个重大Bug
如果滚动到虚拟列位置，然后执行 loadData(data) 方法。100%白屏，随意滚动下滚动条恢复
2.5.x 正常

**Comment by xiaogaofudao** [comment]
还有一个问题 2.x 所有版本都存在。
不论是否开启auto-resize。
页面销毁 会报如下错误
Error in beforeDestroy hook: "TypeError: this.unbindResize is not a function"
[https://github.com/xuliangzhan/vxe-table/issues/302#issuecomment-526495704](url)

**Comment by xuliangzhan** [comment]
不是这样处理的，有问题请通过重现链接来描述问题

**Comment by littlewenzi** [comment]
![image](https://user-images.githubusercontent.com/45968563/67663699-0e829300-f9a1-11e9-9c44-94869ceed34e.png)
这个是什么，照提示安装了也没有用

**Comment by littlewenzi** [comment]
![image](https://user-images.githubusercontent.com/45968563/67663961-98326080-f9a1-11e9-9ed3-49187c9edfa5.png)
 还是没有实现编辑插入element组件，选中了么有显示任何值
