### ISSUE TITLE
vxeTable中所有的事件（如 footer-method） 希望都能类似注册器一样绑定一个默认函数

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#439]
### （必填）这个需求解决了什么问题 What problem does this feature solve

希望vxeTable中所有的事件（如 footer-method） 都能类似注册器一样注入一个默认函数，如果没有在vxeTable中指定了处理函数，则执行注入的这个callback

### （必填）建议的 API 是什么样的 What does the proposed API look like

VXETable.events.add（‘footerMethod’，callback）
VXETable.events.add（‘currentChange’，callback）
VXETable.events.add（‘cellDblclick’，callback）

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
未说明该需求解决了什么问题非得这样做，没明白这样实现的用处是什么？

**Comment by jianliulin** [comment]
如果是通用的事件，注入后，不需要在每个vxe-grid 都设置一次，方便从后台获取grid配置的用户。
