### ISSUE TITLE
复选表格，当所有行的复选框禁用时，表头的复选框应该也是禁用的（目前是选中状态）

### ISSUE THREAD

**Issue by shawchen08** [xuliangzhan/vxe-table#441]
### 请填写问题描述 Describe

复选表格，当所有行的复选框禁用时，表头的复选框应该也是禁用的（目前是选中状态），以免误导用户
现状：![image](https://user-images.githubusercontent.com/25865352/67061756-e078a400-f193-11e9-901d-ff6a0b0d53d5.png)
期望：![image](https://user-images.githubusercontent.com/25865352/67061826-16b62380-f194-11e9-9a8c-ee2a42846f54.png)

### 请填写版本号 Version

- os: win10
- browser: Google Chrome 77.0.3865.120（正式版本） （64 位）
- vue: v2.6.10
- vxe-table: v2.6.0-beta.23

**Comment by xlz26296** [comment]
这个你试下开启严格模式就行 select-config={strict: true}

**Comment by shawchen08** [comment]
[https://codepen.io/shawchen08/pen/VwwKXaM](https://codepen.io/shawchen08/pen/VwwKXaM)
虽然禁用了，但还是选中状态

**Comment by shawchen08** [comment]
![image](https://user-images.githubusercontent.com/25865352/67063016-c0e37a80-f197-11e9-85fe-443eb68eb598.png)
部分禁用时，表头的不应该禁用

**Comment by xlz26296** [comment]
这个你提个 bug 哈

**Comment by MrChen999** [comment]
请问这个问题有人解决了吗？
