### ISSUE TITLE
复选表格，当有表格行的复选框被禁用时，表头的复选框状态异常

### ISSUE THREAD

**Issue by shawchen08** [xuliangzhan/vxe-table#442]
### （必填）请填写问题描述 Describe the bug

复选表格，当有表格行的复选框被禁用时，表头的复选框状态异常，详细可见#441 

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[https://codepen.io/shawchen08/pen/VwwKXaM](https://codepen.io/shawchen08/pen/VwwKXaM)

### 填写报错信息或截图 Error message or screenshots

?

### （必填）请填写期望的结果 Expected behavior

1. 所有行的复选框禁用时，表头的复选框应该被禁用
2. 表格行的复选框部分禁用时，表头复选框的表现应该与表格行的复选框全部可用时一致

### （必填）请填写版本号 Version

- os: win10
- browser: Google Chrome 77.0.3865.120（正式版本） （64 位）
- vue: v2.6.10
- vxe-table: v2.6.0-beta.23

**Comment by xuliangzhan** [comment]
建议更新试下 https://codepen.io/xuliangzhan/pen/dyyprXR
另外注意下：checkMethod({ row  }) 这个方法使用了文档没开放的其他参数可能随时都会报错

**Comment by shawchen08** [comment]
测试没发现问题，感谢及时跟进
