### ISSUE TITLE
使用elem的控件时，检验不通过的不会跳转到校验的位置，使用表格自带的输入控件是可以的

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#443]
### （必填）请填写问题描述 Describe
使用elem的控件时，检验不通过的不会跳转到相应的校验的位置，使用表格自带的输入控件是可以的，不知道使用不对还是不支持
 ?

### （必填）请填写能重现问题的链接：
 https://xuliangzhan.com/vxe-table/index.html#/table/plugin/elementPage
使用demo中的例子加上validate验证也是如此

**Comment by wekerSnail** [comment]
新版本试了已经可以了，感谢

**Comment by wekerSnail** [comment]
经常使用发现还是有些不同，输入框报错，是整个页面滚动定位到报错的位置，而下拉框报错只会滚动表格行，如果报错的在表格的可见位置，但是不在页面的可见位置，下拉框报错时不会有任何变化，输入框则会滚动整个页面定位到报错位置，[https://xuliangzhan.com/vxe-table/index.html#/table/plugin/elementPage ](url)还是这个demo，把表格上面元素高度改大，把表格顶下去就可以看出问题

**Comment by wekerSnail** [comment]
https://jsrun.pro/4vWKp/edit
复现链接，当错误提示的是input以外的控件时，页面不会整体滚动，只有input出错才会整个页面定位到可见区域

**Comment by chenjunhuiGit** [comment]
> 新版本试了已经可以了，感谢

您好，遇到了同样的问题，方便聊一下吗？我目前使用的版本是3.4.13的，表单像使用了插槽，用的element 的表单控件，校验不通过是无法定位到该项。
