### ISSUE TITLE
element组件有没有可以支持键盘操作

### ISSUE THREAD

**Issue by alanlja** [xuliangzhan/vxe-table#444]
### （必填）这个需求解决了什么问题 What problem does this feature solve
问题1：element组件有没有可以支持键盘的上下，enter键那种，
问题2：还有就是能不能就是点击一下就自动focus到element组件中，而不是需要点击两下
 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like

问题2：
![问题1](https://user-images.githubusercontent.com/36754679/67135498-e2eb0480-f24c-11e9-9465-a65de18feee7.png)
https://xuliangzhan.github.io/vxe-table/#/table/other/element
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
请先看文档哦 https://xuliangzhan.github.io/vxe-table/#/table-column/api?filterName=autofocus
