### ISSUE TITLE
可编辑的合并行表格校验的时候合计行效果消失了

### ISSUE THREAD

**Issue by bigWillow** [xuliangzhan/vxe-table#449]
问题：带可编辑的合并行功能表格校验的时候合计行效果消失了，校验后的行是展开的状态
问题链接：https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/span

编辑校验前：
![image](https://user-images.githubusercontent.com/51295007/67182825-92250880-f412-11e9-95c4-756db1e8b584.png)

编辑校验后：
![image](https://user-images.githubusercontent.com/51295007/67182906-c00a4d00-f412-11e9-8572-6a3e7139e30d.png)

期望结果：校验后合计行效果能够正常，自动渲染，或提供方法

问题 Version  ：

- os: win10
- browser:  Chrome-77.0.3865.90（正式版本） （64 位）
- vue: "^2.6.10"
- vxe-table:  "^2.5.22",

**Comment by xuliangzhan** [comment]
这个没看出有什么问题

**Comment by xiaofan007** [comment]
合并行应该是数据相同的时候才会合并，你这都已经修改值了，两行的数据已经不相同，没法合并了呀。。。

**Comment by bigWillow** [comment]
看来得修改第一个单元格时候顺便同步第二个单元格的值也改了
