### ISSUE TITLE
column的id  有bug，在下一个路由里面会递增

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#45]
column的id  有bug，在下一个路由里面会递增，在本页面只刷新数据也会一直递增，不会重置，只有刷新正个页面，id从会从0再开始递增，可以提供一个重置column的id的方法吗?
![image](https://user-images.githubusercontent.com/11676609/58771874-17855900-85e9-11e9-8802-54e7f1c86113.png)
下一步的页面id 起步就是103了，沿着上一个页面递增的。

**Comment by xuliangzhan** [comment]
这个不是问题额，id是全局唯一的，用 id 是为了实现什么？

**Comment by lishihong** [comment]
> 这个不是问题额，id是全局唯一的，用 id 是为了实现什么？

因为我取不到列的真实的columnIndex，我发现id是可以取到的真实的索引的，才用的id。

**Comment by lishihong** [comment]
> 这个不是问题额，id是全局唯一的，用 id 是为了实现什么？

多谢大佬，最新版已经ok了，可以通过columnIndex来取
