### ISSUE TITLE
checkbox 看不见..checkbox 看不见..checkbox 看不见..checkbox 看不见..

### ISSUE THREAD

**Issue by lzb66855024** [xuliangzhan/vxe-table#450]
### （必填）请填写问题描述 Describe the bug
checkbox 看不见.??? 为什么有这么大个BUG.

### （必填）请填写能重现问题的链接，例如
 ?
![Uploading
![u3](https://user-images.githubusercontent.com/22442767/67259996-7df11200-f4cb-11e9-90b1-e01368e00897.png)

![bu1](https://user-images.githubusercontent.com/22442767/67259991-76ca0400-f4cb-11e9-8456-b7ed5155ca20.png)
 图片.png…]()

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version
 最新版,
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by lzb66855024** [comment]
大神已解决.

**Comment by xlz26296** [comment]
旧版本是 selection
https://xuliangzhan_admin.gitee.io/vxe-table/#/table-column/api?filterName=checkbox

**Comment by zhl5317** [comment]
@lzb66855024 请问最终设计如何解决checkbox不显示的这个问题

**Comment by zhl5317** [comment]
@lzb66855024 请问最终是如何解决checkbox不显示这个问题

**Comment by conjeeohh** [comment]
遇到了同样的问题

**Comment by zhl5317** [comment]
> 遇到了同样的问题

我这边最终查下来是因为项目中引用了2个版本的 vxe-table , 版本互相冲突引起的

**Comment by conjeeohh** [comment]
解决了。用按需文档上的 'vxe-table/styles/cssvar.scss'文件checkbox显示不出来，换成'vxe-table/styles/index.scss'或者'vxe-table/lib/style.css'就好了
