### ISSUE TITLE
vxe-table-plugin-element 插件 ElDatePicker Props 'valueFormat' 不起作用

### ISSUE THREAD

**Issue by wenqd** [xuliangzhan/vxe-table#451]
vxe-table-plugin-element 插件 ElDatePicker Props 'valueFormat' 不起作用，显示出来的值没有按规定的格式去解析value
比如 实际值是20191010010203  会解析成五年后的一个日期
链接：https://jsrun.pro/VfWKp/edit
请查看time字段

### （必填）请填写期望的结果 Expected behavior
按定义的格式解析数据
 

### （必填）请填写版本号 Version
最新vxegrid
- os: win10
- browser:chrome

**Comment by xuliangzhan** [comment]
这个问题你更新插件就行 https://github.com/xuliangzhan/vxe-table-plugin-element/releases
