### ISSUE TITLE
element  el-autocomplete组件怎么自定义成渲染器啊

### ISSUE THREAD

**Issue by LuckyTaoTao** [xuliangzhan/vxe-table#452]
### （必填）请填写问题描述 Describe
VXETable.renderer.add('goodsName', {//自定义渲染器
  // 可编辑激活模板
  autofocus: ".custom-input",
  renderEdit(h, editRender, { row, $rowIndex, column }) {
    return [
      <el-autocomplete value={row[column.property]} fetch-suggestions={editRender.events.fetchSuggestions} select={(e) => { editRender.events.handleSelect(e, $rowIndex) }}>
        <template slot-scope={item}>
          <ul v-if="item.disabled" class="warehouse-ul title warehouseTitle">
            <li style="width:20%;">商品编号</li>
            <li style="width:50%;">商品名称</li>
            <li style="width:30%;">工厂代码</li>
          </ul>
          <ul class="warehouse-ul" v-else>
            <li style="width:20%">{item.goods_id}</li>
            <li style="width:50%">{item.value = item.goods_name}</li>
            <li style="width:30%">{item.factory_code}</li>
          </ul>
        </template>
      </el-autocomplete>
    ]
  },
  // 可编辑显示模板
  renderCell(h, editRender, { row, column }) {
    return [
      <span>{row[column.property]}</span>
    ]
  }
})
因为获取焦点或者远程搜索有一个callback回调方法，进行值得匹配，不知道应该怎么接这个值
![image](https://user-images.githubusercontent.com/34666627/67281432-f2df3e80-f501-11e9-85fa-f94405a992f4.png)

### （必填）请填写能重现问题的链接

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by LuckyTaoTao** [comment]
![image](https://user-images.githubusercontent.com/34666627/67281465-07bbd200-f502-11e9-89cd-3f8f31a830e8.png)

**Comment by xuliangzhan** [comment]
没看明白你这是要实现什么
