### ISSUE TITLE
是否支持单元格渲染其他的第三方表单组件，是否有标准的扩展方式

### ISSUE THREAD

**Issue by zrzdemon** [xuliangzhan/vxe-table#454]

**Comment by xlz26296** [comment]
使用渲染器可以添加任意vue组件到单元格渲染中，具体请看文档
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/edit

**Comment by qhhuang** [comment]
> 使用自定义模板或渲染器可以添加任意vue组件到单元格渲染中，具体请看文档
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/edit

您好.
我想改table里的tooltip 让鼠标移上去不消失...项目里用了element-ui,所以我应该不用npm install的方式引入吗.-..-

**Comment by xuliangzhan** [comment]
@qhhuang 这个是可以配置的 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=tooltip
