### ISSUE TITLE
完整校验时${rowIndex}始终是-1

### ISSUE THREAD

**Issue by sailsoft2088** [xuliangzhan/vxe-table#455]
### （必填）请填写问题描述 Describe
在vxe-table-demo\vxe-table-by-vue-cli3中照搬RowValid.vue页面，完整校验时 ${rowIndex}始终是-1，请问怎么解决？？
第 -1 行 Name 校验错误：app.body.valid.rName
第 -1 行 Name 校验错误：名称长度在 3 到 50 个字符
调试发现
getRowIndex: function getRowIndex(row) {
return this.fullDataRowMap.has(row) ? this.fullDataRowMap.get(row).index : -1;
},
fullDataRowMap的size始终为0，所以返回-1，但不知道是什么原因造成的

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots
![Uploading image.png…]()

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by a2741432** [comment]
遇到同样的问题

**Comment by sankumaci** [comment]
fullValidate传入的校验数据和表格的$table.data的数据不一致，所有所有的errMap的rowIndex都是-1

**Comment by zhihaizhen** [comment]
这个要怎么解决呢，怎么没后续了

**Comment by sankumaci** [comment]
在校验前重新赋值一下table数据；类似这样
<img width="452" alt="image" src="https://github.com/x-extends/vxe-table/assets/83257854/d9d0d3c6-1fbc-4168-8d42-b62f7427c5be">
