### ISSUE TITLE
column prop为某些值时输入框不可编辑

### ISSUE THREAD

**Issue by Gumplefik** [xuliangzhan/vxe-table#46]
**问题描述 Describe the bug**
vxe-table-column的prop参数位某些字符串时，其下的可编辑输入框不可编辑
```
<vxe-table-column
            label="描述"
            min-width="240"
            prop="price"
            :edit-render="{name: 'ElInput'}"
            >
            <template v-slot:edit="{ row }">
              <el-input v-model="row.remark"></el-input>
            </template>
            <template v-slot="{ row }">{{row.remark}}</template>
</vxe-table-column>
const item = {
  baseUnit: '',
  code: '',
  componentId: '',
  componentSpec: '',
  count: 0,
  id: '',
  materialSpecifications: '',
  materielCode: '',
  materielId: '',
  materielName: '',
  modelId: '',
  name: '',
  price: 0,
  reasonId: [],
  reasonName: '',
  remark: '',
  supplemenorderId: '',
  unit: ''
}
```
prop为remark时输入框不可编辑，为price时可编辑
**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
我没看出这个和表格本身有什么关系，具体的业务你通过自定义模板或者自定义校验去实现就行

**Comment by Gumplefik** [comment]
你应该对prop做了类型检查之类的，上面的bug意思是prop为   ‘remark’ 时，下方的编辑栏是无法触发的，怎么点击都没用，不能编辑，但是修改prop为 ‘price’ 时，表格的编辑框就可以触发编辑了
prop的值影响了可编辑表格的可编辑性，如果不能够编辑，那么应该有所警告错误之类的

**Comment by xuliangzhan** [comment]
没有任何限制的，你应该检查写法
