### ISSUE TITLE
合计能否提供显示在表头下面body和header中间的功能

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#462]
### （必填）这个需求解决了什么问题 What problem does this feature solve
合计希望能显示在表格和表身中间

**Comment by wind007** [comment]
发现 jqgrid这个插件是支持表头合计功能的，http://www.guriddo.net/demo/guriddojs，开发者大佬是基于什么原因不支持这个需求呢？

**Comment by wind007** [comment]
发现 jqgrid这个插件是支持表头合计功能的，[地址](http://www.guriddo.net/demo/guriddojs)
开发者大佬是基于什么原因不支持这个需求呢
