### ISSUE TITLE
this.bindResize is not a function"

### ISSUE THREAD

**Issue by guohongshan** [xuliangzhan/vxe-table#464]
### （必填）请填写问题描述 Describe
vxe-table 报错信息如下：this.bindResize is not a function"
 ?

### （必填）请填写能重现问题的链接，例如

 ?

### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/31247970/67612031-a16cd300-f7d1-11e9-9195-6fb14f5238f6.png)

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?2.6.4

**Comment by guohongshan** [comment]
![image](https://user-images.githubusercontent.com/31247970/67612413-0c6bd900-f7d5-11e9-9106-0b4900ed4866.png)

**Comment by xiaogaofudao** [comment]
这问题有一两个月了。目前还没修复。。。
