### ISSUE TITLE
大数据加载，虚拟滚动 不生效

### ISSUE THREAD

**Issue by zhuochengs** [xuliangzhan/vxe-table#466]
大神你好，我们在使用你们的大数据加载的时候，发现了一个诡异的问题，我们有两套环境，一套测试，一套生产，发现同样的代码，在测试环境可以正常使用 虚拟滚动，也就是说每次加载指定的行数，但是在生产环境就出现了全部加载，导致性能非常差，请问可能会是什么样的原因导致全部架子啊呢？

**Comment by zhuochengs** [comment]
是我自己的问题，已解决，谢谢

**Comment by HyalineSoft** [comment]
请问是怎样解决的，我也正好遇到了相同的问题
