### ISSUE TITLE
Please, add english translation

### ISSUE THREAD

**Issue by ecaramba** [xuliangzhan/vxe-table#47]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
Due to too much translation content, it may be processed later
