### ISSUE TITLE
当表格在弹框中时，快捷菜单样式层级不够高，导致看不见了

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#470]
### （必填）请填写问题描述 Describe the bug
当表格在弹框中时，快捷菜单样式层级不够高，导致看不见了
 ?

### （必填）请填写能重现问题的链接
http://jsrun.pro/cvWKp/edit

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
你应该根据第三方组件的 zindex 去设置表格的 zindex
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/global
```javascript
VXETable.setup({
    zIndex: 3000
})
```

**Comment by wekerSnail** [comment]
有没有不通过全局设置的方法设置z index，我需要在又弹出层的地方单独设置



发自我的小米手机
在 abc <notifications@github.com>，2019年10月29日 上午11:43写道：

你应该根据第三方组件的 zindex 去设置表格的 zindex
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/global

VXETable.setup({

    zIndex: 3000

})

**Comment by xlz26296** [comment]
局部的话就是给表格设置 [zIndex](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=zIndex)
