### ISSUE TITLE
动态设置固定列

### ISSUE THREAD

**Issue by youguangsheng** [xuliangzhan/vxe-table#471]
### （必填）这个需求解决了什么问题 What problem does this feature solve
动态设置固定列，不生效,

### （必填）建议的 API 是什么样的 What does the proposed API look like

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
请看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/dynamic
