### ISSUE TITLE
vxe-grid  支持vxe-toolbar 吗，

### ISSUE THREAD

**Issue by wenqd** [xuliangzhan/vxe-table#473]
问题描述 Describe
vxe-toolbar 组件怎么和vxe-grid关联起来

请填写能重现问题的链接
https://jsrun.pro/BvWKp/edit

### 请填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/39663153/67754373-4eb14680-fa71-11e9-8ed7-2ceb0114bf07.png)

### （必填）请填写版本号 Version
最新
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by hasbug** [comment]
https://xuliangzhan.github.io/vxe-table/#/table/grid/fullEdit

**Comment by xuliangzhan** [comment]
https://jsrun.pro/wwWKp/edit
