### ISSUE TITLE
After applying the filter, all filter items unchecked

### ISSUE THREAD

**Issue by im1x** [xuliangzhan/vxe-table#477]
### Describe the bug
After updating to version 2.6.0+, my filters did't work correctly. After applying the filter, all filter items are not selected. Previously, selected items weren't reset.

### Reproduction link
 [reproduction](https://codesandbox.io/s/vxe-table-ceshide-demo-q1ij6)

### Error message or screenshots
![menu](https://user-images.githubusercontent.com/1444150/67903757-7d1c4800-fb7d-11e9-826c-4e25c0bc740d.gif)

 ?

### Expected behavior
The state of the selected items should be saved after applying the filter.

### Version

- os: Win10
- browser: Chrome 77
- vue: 2.6.10
- vxe-table: 2.6.8

**Comment by xuliangzhan** [comment]
Please describe the issues by repeating the link.

**Comment by im1x** [comment]
> I'm sorry, please describe the issues by repeating the link.

Here is an [example ](https://codesandbox.io/s/vxe-table-ceshide-demo-q1ij6)that shows the problem.
I found out that the problem occurs when using filtering on the server. When we receive new data from the server, the filters are reset. Previously, when new data was received, filters weren't reset.

**Comment by xuliangzhan** [comment]
Fixed in 2.6.10+
