### ISSUE TITLE
vxe-button 按钮文字不显示  

### ISSUE THREAD

**Issue by jiahui336** [xuliangzhan/vxe-table#478]
### （必填）请填写问题描述 Describe

 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?https://xuliangzhan.github.io/vxe-table/#/table/module/button

### 请填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/54309037/67910603-503c5500-fbbe-11e9-8e8c-07454043b857.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by jiahui336** [comment]
https://xuliangzhan.github.io/vxe-table/#/table/module/button
![image](https://user-images.githubusercontent.com/54309037/67910629-73ff9b00-fbbe-11e9-9674-041efb6efdb0.png)

**Comment by FinnWu** [comment]
昨天也遇到这个问题了，发现是项目vue的版本太低，因为作者用的vue版本是2.6，按钮那部分用了vue2.6的api，所以导致按钮文字不显示，解决方法就是更新下vue的版本到2.6就可以了
