### ISSUE TITLE
請問：在可編輯模式下，怎麼強制輸入為大寫英文字母？

### ISSUE THREAD

**Issue by yangwb1123** [xuliangzhan/vxe-table#481]
### （必填）请填写问题描述 Describe
請問：在可編輯模式下，怎麼強制輸入為大寫英文字母？
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: Windows 10
- browser: chrome 77
- vue: 2.6
- vxe-table: 2.6.7

**Comment by yangwb1123** [comment]
用可編輯渲染器實現了，有沒有更簡單的方式實現

**Comment by xuliangzhan** [comment]
这种业务逻辑你可以封装成一个组件实现，再增加一个渲染器就可以简单调用了
