### ISSUE TITLE
请问使用row编辑模式怎么禁用一个单元格

### ISSUE THREAD

**Issue by peng6298351** [xuliangzhan/vxe-table#482]
### 问题描述
   在使用editRender的时候，我使用的时row模式，现在时要求根据数据要使某些行不能编辑，直接在props里使用disabled回使整列都不能编辑，请问怎么处理呢？
 ?

### 链接（http://jsrun.pro/P7bKp/edit)
![image](https://user-images.githubusercontent.com/44153193/67946248-e05cb780-fc1b-11e9-82be-38fc933a3b9f.png)
比如这样Name一列都禁用了，我只想禁用单独一个

 ?

### （必填）请填写版本号 Version

- os: win10
- browser:谷歌
- vue: 2.6.10
- vxe-table: 2.5.22

**Comment by xuliangzhan** [comment]
这种场景你可以使用自定义模板和 disabled 处理逻辑

**Comment by peng6298351** [comment]
我这里写成公共组件的，不能用自定义模板，disabled禁用的使一列。

**Comment by xuliangzhan** [comment]
配合 edit-actived 事件也行，方式很多
http://jsrun.pro/W6WKp/edit

**Comment by peng6298351** [comment]
谢谢  我先试试

**Comment by peng6298351** [comment]
![image](https://user-images.githubusercontent.com/44153193/67997660-06bc3a80-fc90-11e9-92c6-c7a1033ce591.png)
![image](https://user-images.githubusercontent.com/44153193/67997663-0b80ee80-fc90-11e9-8983-41ba5228c26f.png)
![image](https://user-images.githubusercontent.com/44153193/67997664-0fad0c00-fc90-11e9-9ee5-e06b15fb6602.png)
我在父组件中更改了变量（isNameDisabled），columns传到子组件里却没有更新

**Comment by xiaoxin1991** [comment]
楼主  找到解决方法了  我也遇到了  求指教

**Comment by xiaoxin1991** [comment]
根据可编辑列 设置的数据  控制某列的编辑状态   求作者解决

**Comment by peng6298351** [comment]
还有如图
![image](https://user-images.githubusercontent.com/44153193/68171096-5a3ec900-ffad-11e9-8bf6-e24ab8b9178d.png)
在这里可以使用原生事件吗？，该如何写呢？我这样写没有效果

**Comment by xlz26296** [comment]
你这是用的element的组件，那你就应该去看element的API能不能支持和表格没关系的哦

**Comment by peng6298351** [comment]
原生input可以，原生的keyup，keydown不行呢 我这样写的：{ field: 'Code', title: '条码', width: 100, editRender: { name: 'ElInput', events: { change: this.codeChange, keydown: this.codeKeydown } } },

**Comment by xuliangzhan** [comment]
参考 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/rowDisable

**Comment by greatflag** [comment]
> 参考
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/rowDisable
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/rowDisable
用plugin-element时，mode: 'row'的话，禁用状态在鼠标第二次点击时会失效

**Comment by maxrks** [comment]
v4.x版本中，可以这样禁用行单元格指定列编辑状态。
```
const colField = refTable.value.getColumnByField('COL_FIELD')
colField.editRender.enabled = false
```
在其他列的模板元素中，根据内容变化进行更新。
