### ISSUE TITLE
在開啟 highlight-current-row 的情況下選中表格中的單元格時，在表格外的輸入框中輸入字符再按 backspace 鍵會清空選中單元格的數據

### ISSUE THREAD

**Issue by yangwb1123** [xuliangzhan/vxe-table#483]
### （必填）请填写问题描述 Describe
在開啟 highlight-current-row 的情況下選中表格中的單元格時，在表格外的輸入框中輸入字符再按 backspace 鍵會清空選中單元格的數據
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
鏈接 http://jsrun.pro/P6WKp/edit
 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: Windows 10
- browser: chrome 77
- vue: 2.6
- vxe-table: 2.6.7

**Comment by xuliangzhan** [comment]
这个没看出有什么问题？

**Comment by yangwb1123** [comment]
![vxe-table 使用 - WEB源jscssH5 - JSRUN - Mozilla Firefox](https://user-images.githubusercontent.com/43594478/68095250-db7d5980-fee2-11e9-816b-3695d0b6864a.png)
![3](https://user-images.githubusercontent.com/43594478/68095251-de784a00-fee2-11e9-8a66-c70f687bd24c.gif)

**Comment by xuliangzhan** [comment]
建议更新到最新试下
