### ISSUE TITLE
使用reloadData加载数据，当使用方法删除某条数据，会导致滚动条滚动到其他位置，或者出现白屏的情况。

### ISSUE THREAD

**Issue by Leo-LL** [xuliangzhan/vxe-table#484]
### （必填）请填写问题描述 Describe the bug

 使用reloadData加载数据，当使用方法删除某条数据，会导致滚动条滚动到其他位置，或者出现白屏的情况。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

http://jsrun.pro/8vWKp/edit

### 填写报错信息或截图 Error message or screenshots

 1. 首先将滚动条滚动到某些位置，然后删除数据

![TIM截图20191101150923](https://user-images.githubusercontent.com/50311528/68008440-eef9ac00-fcb9-11e9-8308-7f65a4084110.png)

![TIM截图20191101151022](https://user-images.githubusercontent.com/50311528/68008456-f91baa80-fcb9-11e9-8ebf-9297a97d4c1f.png)

### （必填）请填写期望的结果 Expected behavior

 不出现白屏情况，以及滚动条保持不动

### （必填）请填写版本号 Version

- os: windows10
- browser:  chrome 78
- vue: 2.6
- vxe-table: 2.6.8

**Comment by xuliangzhan** [comment]
要是有虚拟滚动请先设置 show-overflow 哦

**Comment by Leo-LL** [comment]
但使用 `show-overflow` 后，有部分内容被隐藏了。这个有方法去处理吗？
![image](https://user-images.githubusercontent.com/50311528/68101156-24470980-ff07-11e9-8608-d8dcd579ab0b.png)

**Comment by xlz26296** [comment]
如果要显示动态行高就把虚拟滚动关了就行了，动态行高和虚拟滚动二选一

**Comment by z18391098287** [comment]
您好,这个问题处理了吗

**Comment by Leo-LL** [comment]
他这个框架不能支持，我后面是自己用vue-virtual-scroller重新封装了一个table，去做的。
