### ISSUE TITLE
當一個界面存在多個 vxe-table 時，鍵盤操作會作用於多個表格，怎麼讓鍵盤操作獨立於每個表格

### ISSUE THREAD

**Issue by yangwb1123** [xuliangzhan/vxe-table#485]
### 
![截圖](https://user-images.githubusercontent.com/43594478/68013203-3f2b3b00-fcc7-11e9-9f86-f8a965f94149.gif)

### （必填）请填写版本号 Version

- os: Windows 10
- browser: chrome 77
- vue: 2.6
- vxe-table: 2.6.7

**Comment by xuliangzhan** [comment]
建议更新到最新版本看下

**Comment by yangwb1123** [comment]
OK，這個問題已修復。但是數據沒有跟鍵盤操作同步，看下圖

**Comment by yangwb1123** [comment]
![1](https://user-images.githubusercontent.com/43594478/68095006-d91a0000-fee0-11e9-836b-dbec614ce70b.gif)

**Comment by yangwb1123** [comment]
另外作者大大有沒有免費動態截圖軟件推薦啊

**Comment by xuliangzhan** [comment]
数据同步是啥意思？

**Comment by yangwb1123** [comment]
鼠標點到表格第一行時，當前行 (currentRow) 是第一行的數據，鍵盤按下 arrowdown 鍵到表格第一行時，當前行數據也是第一行的數據，我想要這樣的效果

**Comment by xuliangzhan** [comment]
方向键移动目前只能用于 单元格或当前行 二选一

**Comment by 939595081** [comment]
多个表格在一个页面，编辑也会有问题，一个表格编辑了以后再编辑其他表格，就只会修改视图层，不会修改数据
