### ISSUE TITLE
实例错误，恳请修复

### ISSUE THREAD

**Issue by Heisenberg-Mr** [xuliangzhan/vxe-table#486]
### （必填）请填写问题描述 Describe the bug
恳求作者更新一下您在这个网页的上内嵌的实例代码。
原文一字不差拷贝在codesandbox里无法实现效果。
https://xuliangzhan.github.io/vxe-table/#/table/grid/toolbar
 

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

jsfiddle几乎打不开，jsrun.net死了，jsrun.pro能用，但没有vue-cl模版。
codesandbox非常慢，勉强能打开，我的问题重复链接如下：
（请点击👇这个按钮）
<a href="https://codesandbox.io/s/vxe-table-u23zv?fontsize=14">
  <img alt="Edit Vxe-table" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

 
https://codesandbox.io/s/vxe-table-u23zv?fontsize=14
### 填写报错信息或截图 Error message or screenshots

<a href="https://sm.ms/image/7rIKMlZsdyV1uYz" target="_blank"><img src="https://i.loli.net/2019/11/02/7rIKMlZsdyV1uYz.png" ></a>
 
https://sm.ms/image/7rIKMlZsdyV1uYz
### （必填）请填写期望的结果 Expected behavior
不报错，能用，达到该网页展示的效果
https://xuliangzhan.github.io/vxe-table/#/table/grid/toolbar
 

### （必填）请填写版本号 Version

- os:  Mac10.15
- browser: 78.0.3904.70（正式版本）beta （64 位）
- vue: 2.6.10
- vxe-table: 2.6.11

**Comment by Yourroot** [comment]
版本升级
