### ISSUE TITLE
fireFox下重载数据，悬浮列会出现样式问题

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#493]
### （必填）请填写问题描述 Describe the bug
fireFox下重载数据，悬浮列会出现样式问题

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） 

https://jsrun.pro/RIWKp/edit

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/30314164/68195362-b3c8e700-fff1-11e9-972b-4284664abebc.png)

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
建议更新到最新看下
