### ISSUE TITLE
使用reloadData渲染大数据复杂表格的问题，当渲染数据量少于600的时候渲染速度慢，而且页面卡顿

### ISSUE THREAD

**Issue by zhongjinglin** [xuliangzhan/vxe-table#495]
### （必填）请填写问题描述 Describe
参考（https://xuliangzhan.com/vxe-table/index.html#/table/scroll/fullRows）
示例做大数据表格功能，当列表数据量小于600（比如400,或500）的时候，渲染速度比渲染1000条数据更慢，而且渲染完成之后页面还会卡顿，但是渲染600条数据以上就很快而且页面很流畅，不会卡顿。求大神帮忙看看什么原因？
 
### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://jsfiddle.net/zhongjinglin/0Lku6xjz/

### 请填写报错信息或截图 Error message or screenshots
不会报错，文档（https://xuliangzhan.com/vxe-table/index.html#/table/scroll/fullRows）
给出的示例也是一样的，把加载数据改成loadList(500)就会比loadList(1000)更慢

### （必填）请填写版本号 Version

- os:  Win7
- browser:  Google Chrome 74.0.3729.169（正式版本） （64 位）
- vue:  2.6.10
- vxe-table:  2.6.8
- xe-utils: 2.2.11

**Comment by LynnLyc** [comment]
我这里也发现了类似的问题, 修改了api中的一个参数
![image](https://user-images.githubusercontent.com/46145519/68365260-20b3bc80-016b-11ea-92c3-febd2ad919ef.png)
解决了目前的卡顿.
但是不知道这样修改之后会不会引起其他问题.

**Comment by zhongjinglin** [comment]
感谢仁兄的提醒，是我自己没有熟悉api没看到这个配置，谢谢哈

**Comment by zhongjinglin** [comment]
感谢仁兄的提醒，是我自己没有熟悉api没看到这个配置，谢谢哈
