### ISSUE TITLE
单元格直接联动

### ISSUE THREAD

**Issue by LonelyAngul** [xuliangzhan/vxe-table#496]
### （必填）请填写问题描述 Describe
博主你这个项目怎么运行起来呢？
Array.from(new Array(this.$utils.random(3, 8))).forEach(
            (item, index) => {
              pnameList.push({
                label: `${ptype}-名称${index}`,
                value: `${ptype}_${index}`
              });
            }
          );

这里的this.$utils方法在哪里注册的呢？

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

"vxe-table": "^2.6.13",
    "vxe-table-plugin-element": "^1.2.4",
    "xe-utils": "^2.2.11"

**Comment by xuliangzhan** [comment]
#422
