### ISSUE TITLE
有分页加载后插入数据的方法吗

### ISSUE THREAD

**Issue by lishihong** [xuliangzhan/vxe-table#5]

**Comment by lishihong** [comment]
一次性增加多条数据，但是视图不会从顶部重新刷新一次，我把数据集合list concat分页数据后，再reload，滚动条会从顶部重新滚动下来。这个怎么解决呢

**Comment by xuliangzhan** [comment]
不太明白你的意思，你是要重新加载表格还是局部递增数据？

**Comment by lishihong** [comment]
我想局部增加数据，因为是分页请求数据，每页的数据请求了连接到原数据集合上面。看到有提供一个insert方法，但是每次只能怎讲一条数据吗？可以一次增加多条数据吗？

**Comment by xuliangzhan** [comment]
多少条都可以的，传数组就是多条

**Comment by lishihong** [comment]
好的
