### ISSUE TITLE
可编辑的表格，select选择完毕后，显示的是其value而不是正常的label

### ISSUE THREAD

**Issue by xiaofan007** [xuliangzhan/vxe-table#500]
### （必填）请填写问题描述 Describe the bug
未编辑之前，可以正常显示，但是改变了下拉框的值之后，显示的是数字value而不是正常的label

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

[jsfiddle](https://jsfiddle.net/xiaofan007/5zpyqsed/44/)

### 填写报错信息或截图 Error message or screenshots

 很奇怪，在 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/insert 里面的演示是正常显示的，而且没有做别的操作。

拿出来写的时候，下拉框的值只要改变了，就会出现这个情况。。。。
![image](https://user-images.githubusercontent.com/55171182/68374900-bdcd2000-0180-11ea-8e67-e13d661f8abe.png)

### （必填）请填写期望的结果 Expected behavior

可编辑的表格，在修改了下拉框的值的时候，能够正常显示label而不是value

### （必填）请填写版本号 Version

- os: Windos 10 1903
- browser:  谷歌 78
- vue: 2.6.10
- vxe-table: 2.6.13

**Comment by alwxkxk** [comment]
我使用时也是发现这种情况，所以我把value跟label都设置相同的值，额外用代码进行转换。。。

**Comment by xuliangzhan** [comment]
如果要使用原生的 select 那么 value 必须是字符串

**Comment by xiaofan007** [comment]
> 如果要使用原生的 select 那么 value 必须是字符串

@xuliangzhan 
原来如此，测试了下，果然改为了字符串可以了。

**Comment by xiaofan007** [comment]
> 如果要使用原生的 select 那么 value 必须是字符串

对于value必须是字符串。老兄计划是 1：保持现状。还是 2：在以后的某个版本中拓展为数字类型也可以？

**Comment by xuliangzhan** [comment]
你可以选择使用第三方组件库，原生的select只能是字符串，无法支持其他类型的

**Comment by xiaofan007** [comment]
> 你可以选择使用第三方组件库，原生的select只能是字符串，无法支持其他类型的

ok，明白了~  多谢老兄~
