### ISSUE TITLE
希望能优化一下纯前端分页功能

### ISSUE THREAD

**Issue by withyanni** [xuliangzhan/vxe-table#502]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 数据量不大的时候不需要后端分页，纯前端分页目前比较不友好。

### （必填）建议的 API 是什么样的 What does the proposed API look like

表格数据支持 纯前端过滤、筛选、分页等组合

### 是否已有其他不错的替代方案 Describe alternatives you've considered

未发现

**Comment by xuliangzhan** [comment]
你可以把表格单做子组件去封装

**Comment by tiger54910** [comment]
同样希望，能前端分页，如同bootstrap datatable一样，呵呵
