### ISSUE TITLE
希望丰富一下过滤的条件

### ISSUE THREAD

**Issue by withyanni** [xuliangzhan/vxe-table#504]
### （必填）这个需求解决了什么问题 What problem does this feature solve

更满足 后端筛选负责情景

### （必填）建议的 API 是什么样的 What does the proposed API look like
例如这个表格这样，可以有大于小于等于包含之类的
![image](https://user-images.githubusercontent.com/28222123/68465271-1ff35700-024d-11ea-81a7-2f9a108d10b9.png)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

未知，希望能有

**Comment by xuliangzhan** [comment]
渲染的设计本身就是支持任意扩展，请先看文档 
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/renderer/filter
