### ISSUE TITLE
可编辑渲染器的渲染函数能否添加一个用来区分当前行是新增或者编辑的参数吗？

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#507]
### （必填）这个需求解决了什么问题 What problem does this feature solve
可编辑渲染器的渲染函数能否添加一个用来区分当前行是新增或者编辑的参数吗？
这样就可以根据是新增或者编辑渲染出不同的东西，比如某系字段只允许新增不允许编辑，

https://xuliangzhan.com/vxe-table/index.html#/table/renderer/edit

![image](https://user-images.githubusercontent.com/4531974/68555504-11818700-0469-11ea-8d3a-8bd25ec89b82.png)

### （必填）建议的 API 是什么样的 What does the proposed API look like
希望能添加类似：
renderCell (h, editRender, { row, column, **isNew** }) {
            return [
              <span>{ row[column.property] }</span>
            ]
          }
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
可以通过函数调用 [$table.isInsertByRow(row)](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterNmae=%E5%88%A4%E6%96%AD) 判断

**Comment by jianliulin** [comment]
有这个函数也一样，谢谢！！！
