### ISSUE TITLE
请问有更新说明文档吗？

### ISSUE THREAD

**Issue by xiaofan007** [xuliangzhan/vxe-table#508]
### 请填写问题描述 Describe

版本更新很快，但是不知道新版本和旧版本直接有哪些提升。请问老兄在哪里可以看到各版本更新了哪些内容啊？

### 请填写版本号 Version

- os: Windows 10 1903
- browser: chrome 78
- vue: 2.6.10
- vxe-table: 2.6.13

**Comment by xuliangzhan** [comment]
https://github.com/xuliangzhan/vxe-table/releases

**Comment by xiaofan007** [comment]
> https://github.com/xuliangzhan/vxe-table/releases

哦哦，好哒，多谢多谢~
