### ISSUE TITLE
数据验证没有提示信息

### ISSUE THREAD

**Issue by ahmczsy** [xuliangzhan/vxe-table#51]
**描述 Describe**
数据验证没有提示信息,验证失败了只是一个红框,没有message的提示
验证失败也不会像示例代码一样左上角有红色小箭头

**问题重现**
https://codepen.io/ahmczsy/pen/JQoMGX

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: chrome 75
 - vue: 2.6.10
 - vxe-table: 1.0.1

**Comment by xuliangzhan** [comment]
请提供重现问题的代码或链接

**Comment by ahmczsy** [comment]
> 请提供重现问题的代码或链接

已添加代码
如果这个table在element ui里的dialog就会出现这样的问题

**Comment by xuliangzhan** [comment]
这个是是因为弹窗的 z-index 比较大被覆盖了，你可以通过设置 [zIndex](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=zIndex) 就行，[全局设置](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/use)
