### ISSUE TITLE
清空筛选条件this.$refs.xTable.clearFilter()之后应触发filter-change事件

### ISSUE THREAD

**Issue by withyanni** [xuliangzhan/vxe-table#510]
### （必填）这个需求解决了什么问题 What problem does this feature solve

比如在筛选改变之后，我会通过 filter-change事件对应的方法，将筛选条件封装到data的一个变量里，然后传给后端过滤数据。
但是清空筛选条件没有触发filter-change，导致只是前端清空了筛选条件，但是并未调用后端更新数据。结果是前端已经没有了筛选条件，但是数据并未更新
现在是通过手动清空data里数据做的，但是列多很麻烦。

### （必填）建议的 API 是什么样的 What does the proposed API look like

 可以选择性触发filter-change事件，方便后端同步更新数据

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
首先从API的设计上就已经明确说明了，事件的触发条件只能是用户行为；既然都可以手动调用方法，为什么不再手动调用相关的处理方法，所以这个不会支持哦
