### ISSUE TITLE
分页、不分页之间切换

### ISSUE THREAD

**Issue by withyanni** [xuliangzhan/vxe-table#512]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 仅仅是建议，可能会配合上导出功能。
目前导出仅是一页，如果想导出所有的，现在的解决方案是分页大小设置一个无限大那种。

### （必填）建议的 API 是什么样的 What does the proposed API look like
可参考
https://www.bootstrap-table.com.cn/examples/options/show-pagination-switch/

### 是否已有其他不错的替代方案 Describe alternatives you've considered
https://www.bootstrap-table.com.cn/examples/options/show-pagination-switch/
 ?

**Comment by yizixu** [comment]
多加一个导出全部按钮，啊哈哈

**Comment by StitchJian** [comment]
我是pagesizes push data.length

**Comment by xuliangzhan** [comment]
```javascript
const allData = [...]
this.$refs.xTable.exportData({
  data: allData 
})
```

**Comment by HappyDongD** [comment]
我也很想知道有没有好点的解决方案
