### ISSUE TITLE
编辑表格报错：Cannot read property 'then' of null at VueComponent._clearActived

### ISSUE THREAD

**Issue by fying-snow** [xuliangzhan/vxe-table#515]
### （必填）请填写问题描述 Describe
手动编辑模式下，点击“编辑”，然后出现以下报错
![image](https://user-images.githubusercontent.com/10750319/68728821-50e3db00-0603-11ea-8494-450d3f40ea6e.png)

很抱歉来提issue，在线编辑器【无法】复现问题，真是非常尴尬。

我在本地做了一些排查，可是没有找到问题：
为了排除项目中其他库的干扰，我在**vxe-table-demo-master/vxe-table-by-vue-cli3**中进行了测试，只做了以下改动：
    1. package.json vxt-table 版本更新
       ` "vxe-table": "^2.6.18",`
    2. xtable.js 添加edit和button的引用
    3. 将demo code放入src（demo链接附在下个问题中）

并且把这个项目在不同的电脑上测试，在mac、win7、win10都试过了，同样的报错，
实在找不到原因就只能来提问了。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
代码链接如下：
https://codesandbox.io/s/vxe-table-ceshide-demo-jhpu0
 
### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/10750319/68730752-bdada400-0608-11ea-9da7-b24deac352f6.png)

![image](https://user-images.githubusercontent.com/10750319/68730717-9951c780-0608-11ea-8e25-4feacbd525d3.png)

### （必填）请填写版本号 Version
- os: macOS 10.14.6
- browser: Chrome 78.0.3904.87
- vue: 2.6.10
- vxe-table: 2.6.18
- xe-utils: 2.2.11

**Comment by xuliangzhan** [comment]
是否用了校验？引入 Validator 模块或更新到最新版本试试

**Comment by fying-snow** [comment]
> 是否用了校验？引入 Validator 模块或更新到最新版本试试

没有用校验，不太理解这个和报错有什么关系，我在**点击编辑**这步就报错了。
后来找了一个vee-validate，但没有用。

最后并没有抱多大希望，升级了vxe-table版本，我周二装的2.6.18，现在已经2.6.20了！
问题解决了！居然解决了！！**_感谢大神如此高频地更新！_**
