### ISSUE TITLE
formatter的html里添加click事件，会自动触发，并且多次

### ISSUE THREAD

**Issue by withyanni** [xuliangzhan/vxe-table#516]
### （必填）请填写问题描述 Describe the bug

 formatter里返回html代码，里面包含click事件，页面加载时就自动每一行都触发一次

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 请见：https://codesandbox.io/s/vxe-table-ceshide-demo-srs4d

### 填写报错信息或截图 Error message or screenshots

由于公司安全，上传不了截图。
请见重现链接，会直接alert两次

### （必填）请填写期望的结果 Expected behavior

 应该将事件渲染到对应的单元格里，并且可以点击触发

### （必填）请填写版本号 Version

- os: win10
- browser: chrome78
- vue: 2.6.10
- vxe-table: 2.6.13

**Comment by xuliangzhan** [comment]
建议先看 vue 的基础语法
