### ISSUE TITLE
分页场景下，保留选中checkbox状态OK，但是数据丢失

### ISSUE THREAD

**Issue by lixing0323** [xuliangzhan/vxe-table#517]
对于分页场景下，如果想要保留选中状态，可以通过设置 checkbox-config 的 reserve 属性。分页勾选确实有，但是 select-change 返回的 { selection } 只保存了当前本页数据。并没有勾选的分页数据？ 

第一页选中了2条，console.log出来的结果也是2条，没有问题。
![image](https://user-images.githubusercontent.com/19339814/68824784-edc17980-06d2-11ea-8a40-a93c16f665f7.png)
第二页选中了2条，console.log出来的结果也是2条！！！（2+2）应该是4条，4条，4条。。。
![image](https://user-images.githubusercontent.com/19339814/68824850-19dcfa80-06d3-11ea-96fb-baf61e292e96.png)

table配置如下：
![image](https://user-images.githubusercontent.com/19339814/68824938-5577c480-06d3-11ea-93fb-1e7599bf0956.png)

### （必填）请填写期望的结果 Expected behavior
期望修改。

### （必填）请填写版本号 Version
- os: mac 
- browser: chrome
- vue: 3.1.0
- vxe-table: 2.6.18

**Comment by xuliangzhan** [comment]
保留状态的数据是 [reserves](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=reserves)，请先看文档哦
