### ISSUE TITLE
showOverflow在临界值的时候不能触发

### ISSUE THREAD

**Issue by yizixu** [xuliangzhan/vxe-table#519]
### （必填）请填写问题描述 Describe the bug

 ?showOverflow在当cell宽度为临界值的时候会出现省略号，但是鼠标悬浮不显示

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?见截图，开启resizable可以试出来

### 填写报错信息或截图 Error message or screenshots

 ?![image](https://user-images.githubusercontent.com/24697292/68821466-615e8900-06c9-11ea-89fc-a66736aeda40.png)
![image](https://user-images.githubusercontent.com/24697292/68821580-b0a4b980-06c9-11ea-9d1d-7e747415e86a.png)

### （必填）请填写期望的结果 Expected behavior

 ?解决这个bug

### （必填）请填写版本号 Version

- os:? windows10 1809
- browser: ?chrome版本 78.0.3904.97
- vue: ?2.6.10
- vxe-table: ?2.6.18

**Comment by yizixu** [comment]
![image](https://user-images.githubusercontent.com/24697292/68821810-44768580-06ca-11ea-94d6-7cd05b014e76.png)

**Comment by guyuan1234** [comment]
我也遇到了这个问题  好像除了中文正常  其他字符都不正常显示
