### ISSUE TITLE
复选框第三个demo点击行内任意位置选中此行无效

### ISSUE THREAD

**Issue by lzc752143280** [xuliangzhan/vxe-table#523]
多选表格，通过配置 trigger 设置触发源，使用渲染最快的 checkField 属性绑定方式
:checkbox-config="{checkField: 'checked', trigger: 'row'}">
此行代码可能无效，按照demo中的代码无法实现功能。

- os:  win10
- browser: chrome78
- vue: 2.6.10
- vxe-table: 2.6.18

**Comment by lzc752143280** [comment]
通过cell-click事件自己实现了

**Comment by xuliangzhan** [comment]
我觉得你如果遵循vue先定义后使用的原则，也许会有不一样结果
