### ISSUE TITLE
table列表开启虚拟滚动，切换页面后再切回来table内容显示不全！！！

### ISSUE THREAD

**Issue by luoxuancong** [xuliangzhan/vxe-table#525]
###  更新到 2.6.19（2.6.20也不行） 后,  table列表开启虚拟滚动切换别的页面再切回来，列表内容显示不全了!!!  之前的版本没有这个问题 

======================================================
### 暂时不好给链接，公司内部项目还没开放。

======================================================
### 填写报错信息或截图
![微信截图_20191115145305](https://user-images.githubusercontent.com/33108362/68922954-fb9cfa80-07b7-11ea-8690-cddb1501c723.png)
![222](https://user-images.githubusercontent.com/33108362/68922958-fdff5480-07b7-11ea-93d1-63d578dbf326.png)
========================================================

### （必填）请填写期望的结果 
切换回来之后可以正常显示就行了！
我用 V 2.6.11 的时候是没出现过这个问题,我看修复了表格高度才更新的V2.6.19，辛苦大佬看看怎么解决

### （必填）请填写版本号
2.6.19

- browser: Google Chrome

**Comment by xiaogaofudao** [comment]
页面数据不更新静态数据没这bug。定时全量更新数据，容易出现此类白屏错乱bug

**Comment by luoxuancong** [comment]
> 页面数据不更新静态数据没这bug。定时全量更新数据，容易出现此类白屏错乱bug

我现在的做法是每次回到这个页面的时候重新刷新一下table，暂时可以解决这个问题
