### ISSUE TITLE
手动编辑模式下，修改数据，点击取消按钮，修改仍被保存

### ISSUE THREAD

**Issue by fying-snow** [xuliangzhan/vxe-table#526]
### （必填）请填写问题描述 Describe the bug
表格手动编辑模式下，修改表格数据，然后点击【取消】，但是数据已经被改动，没有恢复到初始值。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
https://codesandbox.io/s/vxe-table-ceshide-demo-jhpu0?fontsize=14

### （必填）请填写期望的结果 Expected behavior
点击”取消“，数据恢复到改动前的值。

### （必填）请填写版本号 Version
- os: MAC 10.14.6 
- browser: chrome 78.0.3904.87
- vue: 2.6.10
- vxe-table: 2.6.20

大神辛苦 ^ ^

**Comment by xuliangzhan** [comment]
请先看文档哦 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/revert

**Comment by fying-snow** [comment]
> 请先看文档呢 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/revert

对，确实是没看到这个功能，多谢啦！
不过手动编辑的demo里，在“取消”按钮的事件中能把这个“恢复”放进去就更好了。
