### ISSUE TITLE
如何在校验后不触发列的编辑状态

### ISSUE THREAD

**Issue by janjon** [xuliangzhan/vxe-table#529]
### （必填）请填写问题描述 Describe
每次调用表格的validate 都会自动触发列的编辑
如何由开发者自动控制。
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=autoPos
