### ISSUE TITLE
为啥  我用全选和多选的这个事件  带有二级菜单的 返回的event 的数据是重复 children的  是bug 么？还是我写的问题！

### ISSUE THREAD

**Issue by 641475674** [xuliangzhan/vxe-table#53]
**问题描述 Describe the bug**
点击全选 或者多选 如果 初始数据带有children 的话 点击选中返回的数据会把 children的数据重复一遍

**重现问题的步骤 To Reproduce**
直接复制文档的例子自己写一些假数据 然后绑定 @select-change 事件  查看返回的selection

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/y7n0bw4e/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

不在重复 children的数据
**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ? 谷歌73.0.3683.103（正式版本） （32 位）
 - vue: ? vue 2.9+
 - vxe-table: ? yes

**Comment by xuliangzhan** [comment]
你这样提问题无解的，代码不提供也链接不提供

**Comment by 641475674** [comment]
是 树形 表格   返回数据 格式有误  
![image](https://user-images.githubusercontent.com/44958645/59586821-5bfb1380-9116-11e9-9e82-8f2597418689.png)

**Comment by xuliangzhan** [comment]
这个没问题，是返回勾选的数据

**Comment by 641475674** [comment]
你好  ，这个 可以优化一下么？ 这样的话 我直接赋值  包括 传给后台的数据 都不行  ，对开发者很不友好啊 ，而且 处理起来还很麻烦

**Comment by 641475674** [comment]
因为 对于 大多数开发者来说 只是想要拿到这个选中的数据把  没必要重复一下 子节点的数据把，包括全选也是

**Comment by xuliangzhan** [comment]
这个并非重复问题，该功能只返回所有勾选的行
如果只返回父节点那肯定是错误的，要是只勾选其中一个子节点呢

**Comment by 641475674** [comment]
那请问下 如果我选中了多个这样的数据结构之后 不需要这个重复的子节点该怎么办   数据怎么处理

**Comment by xuliangzhan** [comment]
你如果不要子节点，那就只能把数据过滤掉
