### ISSUE TITLE
table表格拖拽列宽，bug

### ISSUE THREAD

**Issue by SakuraDoramon** [xuliangzhan/vxe-table#533]
### （必填）问题描述 Describe the bug

 拖拽列宽，如果先拖拽Time列，其他列宽都会跟着变动
如果刚进入页面，先拖拽前面的列，则表格改变列宽正常

### （必填）重现问题的链接

 https://jsfiddle.net/13814066642/n75yqtba/2/

### （必填）请填写期望的结果 Expected behavior

进入页面，拖拽列宽，只改变拖拽的列宽，其他列宽保持不变

### （必填）请填写版本号 Version

- os: mac Os 
- browser: Chrome v.77.0.38
- vue: v2.6
- vxe-table: v2.6.10

**Comment by xuliangzhan** [comment]
你不来就没设置其他列的宽度，某一列变宽，自然就会把剩余宽度分配给其他列

**Comment by SakuraDoramon** [comment]
> 你本来就没设置其他列的宽度，某一列的宽度变窄，自然就会把剩余宽度分配给其他列

本来我也是这么认为的，如果我先拖拽第一列，剩余宽度会自动分配。
但是如果我先拖拽后面的列，宽度就没有自动分配，只改变了我拖拽的那一列宽度。
这是为什么呢？
