### ISSUE TITLE
树形表格 展开一些列之后再加载数据可以保留展开状态吗

### ISSUE THREAD

**Issue by DoveAz** [xuliangzhan/vxe-table#534]
### （必填）这个需求解决了什么问题 What problem does this feature solve

树形表格编辑完之后submit 会向服务器重新获取数据、刷新表格、之后展开状态消失

### （必填）建议的 API 是什么样的 What does the proposed API look like

 建议默认保留展开状态或加入参数可以配置

### 是否已有其他不错的替代方案 Describe alternatives you've considered

antd element 的树形表格都会保持展开状态

复现链接

https://jsrun.pro/tQWKp/edit

**Comment by qiangbro** [comment]
+1

**Comment by DoveAz** [comment]
此问题在2.9.9又复现了
