### ISSUE TITLE
表格表头和表体未能对齐

### ISSUE THREAD

**Issue by TCOT** [xuliangzhan/vxe-table#535]
### 表格表头和表体未能对齐，同时拉最后一列往前，会出现表单混乱的情况
以下截图都选自官方
 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/click
### 错误截图

![image](https://user-images.githubusercontent.com/28554662/69391544-22a28180-0d0e-11ea-81db-8dff6d96485c.png)

![image](https://user-images.githubusercontent.com/28554662/69391286-4b764700-0d0d-11ea-90d8-e2fec1d063a3.png)

### （必填）请填写期望的结果 Expected behavior
期望表头和表体对齐，同时最后多出来的那一块消失
### （必填）请填写版本号 Version
最新版本

**Comment by superhos** [comment]
这个问题很严重哦，为什么未处理未解答就关掉了，普遍都遇到的

**Comment by bambangsuryacx** [comment]
有什么解决方案么？

**Comment by bambangsuryacx** [comment]
> 有什么解决方案么？

我引用最新的版本vxe-table@4.17.15 解决了这个问题

**Comment by xuliangzhan** [comment]
#2987
