### ISSUE TITLE
footer行在列隐藏时导出无法正确显示数据

### ISSUE THREAD

**Issue by SecMao** [xuliangzhan/vxe-table#536]
### （必填）请填写问题描述 Describe the bug

1. footer行在导出时，单元格的值获取采用$table.getColumnIndex(column)获取索引，若存在隐藏列，则获取的索引值与实际的footer数据数组索引不对应，无法正确显示数据
2. 在导出时将footer隐藏，实际导出里仍旧显示footer

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://jsfiddle.net/5ast2qw7/1/
1. 点击打印按钮
2. 点击不带footer打印按钮

### 填写报错信息或截图 Error message or screenshots

footer行数据为空

### （必填）请填写期望的结果 Expected behavior

 footer数据正常导出

### （必填）请填写版本号 Version

- os: win 10
- browser: chrome 78
- vue: 2.6.10
- vxe-table: 2.6.22

**Comment by xuliangzhan** [comment]
请查看文档使用正确的用法 [print](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=print)
https://jsfiddle.net/jcpawsx5/

**Comment by SecMao** [comment]
> 请查看文档使用正确的用法 [print](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=print)
> https://jsfiddle.net/jcpawsx5/

谢谢回复，第二个问题解决了。
对于第一个问题，在导出打印方法中，footer的字符串拼接你使用了`rows[$table.getColumnIndex(column)]`来获取footer单元格的值，这个值无法使用print指定的几个方法来影响，请看下是否如此
