### ISSUE TITLE
开放键盘导航的回车事件

### ISSUE THREAD

**Issue by furuihe** [xuliangzhan/vxe-table#538]
### （必填）这个需求解决了什么问题 What problem does this feature solve
键盘导航功能，按下Enter时，能够编程指定单元格，而不是固定当前单元格下方

### （必填）建议的 API 是什么样的 What does the proposed API look like
类似于editMethod选项，可以覆盖回车事件

### 是否已有其他不错的替代方案 Describe alternatives you've considered
未发现

**Comment by xuliangzhan** [comment]
自行绑定事件监听即可

**Comment by Sesshoumaru** [comment]
能否给个例子？
