### ISSUE TITLE
【求助】集成第三方库element，如何让所有行中的元素默认都启用编辑。

### ISSUE THREAD

**Issue by xsdream** [xuliangzhan/vxe-table#539]
### （必填）请填写问题描述 Describe

集成第三方库element，如何让所有行中的元素默认都启用编辑，如下图。

### 请填写报错信息或截图 Error message or screenshots
我想让图中的所有行一样都是第一行的效果，用户一眼看上去就知道这是要编辑的。！
![image](https://user-images.githubusercontent.com/31870384/69489281-35ed5280-0eb0-11ea-8057-5d67b376c491.png)

### （必填）请填写版本号 Version

- browser: chrome
- vue: 3.7
- vxe-table: 2.6.52

**Comment by xsdream** [comment]
edit-config  的 model 只有 cell  和  row，能不能再添加一个属性 all ？，这样可以让所有行默认都是可编辑状态的

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/bad/edit
