### ISSUE TITLE
可编辑模式的三个问题

### ISSUE THREAD

**Issue by fooleap** [xuliangzhan/vxe-table#54]
**问题描述 Describe the bug**

在可编辑模式下，目前发现的问题有 3 个：

1. 当 trigger 为 click、mode 为 cell，同时 highlight-current-row 为 true，无论是否激活编辑，点击任何项都会触发 edit-closed。
2. 按回车完成编辑时，edit-closed 事件传过来的 row，rowIndex 等是下一行的数据。
3. 当 trigger 为 dblclick，mode 为 cell，单击某一单元格后，无论单元格是否可编辑，焦点在哪，按退格键都会清空该单元格的内容。

**重现问题的步骤 To Reproduce**

略

**请提供能重现问题的链接 Expected behavior**

https://jsrun.net/B8yKp/edit

**报错信息或截图 Error message or screenshots**

略

**期望的结果 Expected behavior**

修复错误

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: Google Chrome 74.0.3729.131
 - vue: 2.6.6
 - vxe-table: 1.0.2

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by fooleap** [comment]
@xuliangzhan  OK 了，谢谢
