### ISSUE TITLE
需要一个默认的初次排序列配置

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#541]
### （必填）这个需求解决了什么问题 What problem does this feature solve
表格初次渲染结束的排序结果，是按照配置的列来排序的，比如我有五列数据，然是我默认展示的时候是按照第二列的参数排序的
 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
![image](https://user-images.githubusercontent.com/30314164/69517423-ac14b680-0f8f-11ea-9d95-872dfa112001.png)

 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
可以设置 defaultSort
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/sort
