### ISSUE TITLE
【加急】VXETable is not defined？求助

### ISSUE THREAD

**Issue by arraycto** [xuliangzhan/vxe-table#544]
### （必填）请填写问题描述 Describe
VXETable is not defined

使用方式：
https://xuliangzhan.com/vxe-table/index.html

出现问题如下：
### （必填）请填写能重现问题的链接， 

直接本地运行vscode

### 请填写报错信息或截图 Error message or screenshots
[HMR] Waiting for update signal from WDS...
index.js?3672:11 Uncaught ReferenceError: VXETable is not defined
    at eval (index.js?3672:11)
    at Object../src/router/index.js (app.js:2527)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (main.js?1c90:1)
    at Object../src/main.js (app.js:2519)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.0 (app.js:2536)
    at __webpack_require__ (app.js:679)
(anonymous) @ index.js?3672:11
./src/router/index.js @ app.js:2527
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ main.js?1c90:1
./src/main.js @ app.js:2519
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:2536
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
vue.esm.js?c5de:9082 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

### （必填）请填写版本号 Version

- os: win10
- browser: 谷歌
- vue: 2.9
- vxe-table: 默认import的，应该是最新版本的

**Comment by yinyihui** [comment]
@arraycto 你好，请问你解决了么？我也出现这个问题，默认安装全局导入
