### ISSUE TITLE
checkbox-config中checkRowKeys动态修改不复选?

### ISSUE THREAD

**Issue by chinavane** [xuliangzhan/vxe-table#545]
### （必填）请填写问题描述 Describe
checkbox-config中设置了checkRowKeys，默认为空，但是通过外部传递参数动态修改了checkRowKeys，想借此进行筛选操作，但是并不生效。

运行代码
https://jsrun.pro/3EWKp/edit

### （必填）请填写版本号 Version

- os: mac
- browser: chrome
- vue: 2.5.10
- vxe-table: 2.6.22

**Comment by xlz26296** [comment]
那是默认值，不是选中值，先看文档吧 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/selection
