### ISSUE TITLE
单元格禁用只能禁止input，无法禁止select

### ISSUE THREAD

**Issue by HuiDemo** [xuliangzhan/vxe-table#548]
### （必填）请填写问题描述 Describe the bug
单元格禁用只能禁止input，无法禁止select
<vxe-table-column>中设置edit-render attr属性，添加disabled或者readyonly均无法对select生效

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/26273474/69705999-aeaf1180-1131-11ea-820b-7f14d5176839.png)

### （必填）请填写期望的结果 Expected behavior
希望能尽快回复，并解决，万分感谢

### （必填）请填写版本号 Version

- os: window
- browser: chrome
- vue: 2.9.6
- vxe-table: 2.6.22

**Comment by FinnWu** [comment]
2.7的版本并没有推上npm, 请作者有时间推下
