### ISSUE TITLE
表格数据使用绑定表格data的tableData数据直接添加的空行数据行,会造成行id相同，复选框选中一个会导致全选

### ISSUE THREAD

**Issue by youguangsheng** [xuliangzhan/vxe-table#550]
### （必填）请填写问题描述 Describe the bug
使用tableData新增的空行与用insertAt()添加的空行不同，行id会相同，复选框选中一个就会全选
 ?

### （必填）请填写能重现问题的链接，例如（） Reproduction link
https://jsfiddle.net/w54pcsyk/1/
 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior
通过绑定的data数据的tableData与insertAt()添加效果相同
 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
请先了解 js 的引用传递，你使用的是同一个 record 引用

**Comment by youguangsheng** [comment]
明白了，多谢，但能否帮助开发这不用管引用传递问题

**Comment by xuliangzhan** [comment]
克隆对象就行
```javascript
this.tableData.push(Object.assign({},this.record))
```
