### ISSUE TITLE
使用vxe-table-plugin-shortcut-key时，缺少必要的api

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#553]
### （必填）这个需求解决了什么问题 What problem does this feature solve
通过监听键盘事件去做处理时，只能拿到$table，但是table的api再使用tab切换单元格时，无法获取到当前的单元格，有提供设置选中当前单元格的api，却没有获取当前单元格的api,这 让基于cell的交互无法实现
![image](https://user-images.githubusercontent.com/30314164/69772420-dc946480-11ca-11ea-9c77-ee76b88031be.png)
类似这样的选中状态
![image](https://user-images.githubusercontent.com/30314164/69772590-4dd41780-11cb-11ea-9658-67d14d61374e.png)

 ?

### （必填）建议的 API 是什么样的 What does the proposed API look like
getSelectCell()
 ?

### 是否已有其他不错的替代方案 Describe alternatives you've considered
或者键盘事件中返回类似api中较完整的数据，row.cell...
 ?

**Comment by xuliangzhan** [comment]
获取选中有 API 的 
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=getMouseSelecteds
