### ISSUE TITLE
vxe-table 自定义模板使用elementui的el-date-picker组件不能选中日期数据

### ISSUE THREAD

**Issue by liulyu** [xuliangzhan/vxe-table#559]
### （必填）请填写问题描述 Describe the bug
vxe-table 自定义模板使用elementui的el-date-picker组件不能选中日期数据
点击选择日期 空间关闭 数据未被选中
 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior
选中日期数据并显示在表格中
 ?

### （必填）请填写版本号 Version
chrome 66.0.3359.170
2.6.10
2.6.22
- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by YidaHury** [comment]
vxe-table 自定义模板使用elementui的el-date-picker组件不能选中日期数据
点击选择日期 空间关闭 数据未被选中
?
