### ISSUE TITLE
edit-closed事件的event数据有问题

### ISSUE THREAD

**Issue by ahmczsy** [xuliangzhan/vxe-table#56]
**问题描述 Describe the bug**
用tab键移到下一个cell时,触发edit-closed的evnet数据中的columnIndex不太对
用鼠标点击触发的edit-closed是没问题的

**重现问题的步骤 To Reproduce**
代码:https://jsrun.net/qTyKp/edit

**操作步骤**
![VRBNwD.gif](https://s2.ax1x.com/2019/06/12/VRBNwD.gif)

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: chrome 75
 - vue: 2.6.10
 - vxe-table: 1.0.3

**Comment by xuliangzhan** [comment]
建议更新到最新看下
