### ISSUE TITLE
树形表格导入后层级变了

### ISSUE THREAD

**Issue by ZiyLynn** [xuliangzhan/vxe-table#560]
### （必填）请填写问题描述 Describe the bug

树形表格导入后层级变了。导入前树形表格能呈现树的层级，根据这个层级导出excel，完整的重新导入树层级就没了

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### （必填）请填写期望的结果 Expected behavior

导入后能保留树形

### （必填）请填写版本号 Version

- os: window 10
- browser: chrome 78
- vue: 2.5.2
- vxe-table: 2.7

**Comment by xuliangzhan** [comment]
树只支持导出列表
