### ISSUE TITLE
validate不能返回校验结果

### ISSUE THREAD

**Issue by qq592304796** [xuliangzhan/vxe-table#563]
### （必填）请填写问题描述 Describe the bug

var valid = await xTable.validate(rows)
返回校验结果为空，并且校验失败会抛出异常

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://jsrun.pro/2dWKp/edit

### 填写报错信息或截图 Error message or screenshots

 
![报错信息](https://user-images.githubusercontent.com/26601421/70013834-ce23bf80-15b3-11ea-84e8-f86a9a193e03.png)

### （必填）请填写期望的结果 Expected behavior

能够正常返回校验结果

### （必填）请填写版本号 Version

- os: windows10
- browser: chrome 78.0.3904.108
- vue: 2.6.10
- vxe-table: 2.7.0-beta.5

**Comment by qq592304796** [comment]
@xuliangzhan 重现代码连接已提供

**Comment by xuliangzhan** [comment]
你没有处理异常 
https://jsrun.pro/FJWKp/edit

**Comment by qq592304796** [comment]
validate方法不能返回true跟false吗？

**Comment by xuliangzhan** [comment]
但是你用的是 Promise 方式，你如果想要true和false就用回调的方式就行了

**Comment by tomsure** [comment]
必填校验不生效
