### ISSUE TITLE
grid放在Collapse中，Collapse默认不展开，表格列宽异常

### ISSUE THREAD

**Issue by virycs** [xuliangzhan/vxe-table#567]
### （必填）请填写问题描述 Describe the bug

 grid放在Collapse中，Collapse默认不展开，当点击展开Collapse表格宽度显示异常

### （必填）请填写能重现问题的链接
表格列配置代码如下：
columns: [
        { type: 'index', width: 60, align: 'center' },
        { title: '节点', field: 'taskId' },
        { title: '审批人',field: 'aprover' },
        { title: '审批时间', field: 'time' },
        { title: '审批意见', field: 'result' },
        { title: '备注', field: 'comment' }
      ]

### 填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/52852713/70056283-27243f80-1616-11ea-9bb0-ebf59d475dca.png)

### （必填）请填写期望的结果 Expected behavior

 期望展开Collapse后表格宽度和父容器一致

### （必填）请填写版本号 Version
- vue: 2.5.10
- vxe-table: 1.15.14

**Comment by xlz26296** [comment]
#230

**Comment by virycs** [comment]
多谢
