### ISSUE TITLE
可编辑表格新增几行后不能删除选中数据

### ISSUE THREAD

**Issue by YuppyHub** [xuliangzhan/vxe-table#57]
**问题描述 Describe the bug**
可编辑表格新增几行后不能删除选中数据

**重现问题的步骤 To Reproduce**
连续点几次新增，然后逐个编辑内容， 而后选择刚编辑好的数据点删除无效。

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/y7n0bw4e/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/fullEdit

**期望的结果 Expected behavior**
能不删除刚添加的数据。 而且获取 data.sync 绑定的表格数据发现数组实际内容是比显示的少的。

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: chrome 最新版本
 - vxe-table: 最新版， 线上测试环境。

**Comment by xuliangzhan** [comment]
建议更新到最新看下
