### ISSUE TITLE
每列都设置宽度后，所有列宽加一起不到table总宽度，表体出现空白

### ISSUE THREAD

**Issue by yan170772286** [xuliangzhan/vxe-table#570]
### （必填）请填写问题描述 Describe the bug

每列都设置宽度后，所有列宽加一起不到table总宽度，表体出现空白，出现断裂

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://jsrun.pro/hdWKp/edit

### 填写报错信息或截图 Error message or screenshots

 ?
![image](https://user-images.githubusercontent.com/5705070/70123486-c0eafb80-16ad-11ea-877c-05505d262174.png)

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: mac
- browser:  chrome
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
你应该理解下固定列宽是什么概念
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/width

**Comment by yan170772286** [comment]
> 你应该理解下固定列宽是什么概念
> https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/width

好吧，产品要求不一样，我关了
