### ISSUE TITLE
期待toolbar能够支持Renderer渲染，以便根据业务规则动态从后台获取配置

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#571]
### （必填）这个需求解决了什么问题 What problem does this feature solve

期待toolbar能够支持Renderer渲染，以便根据业务规则动态从后台获取配置，要是支持就能像grid的cell一样包罗万象，无所不能。

不同的业务规则可能生产的toobar截然不同，希望老大考虑一下，谢谢

![微信截图_20191204173615](https://user-images.githubusercontent.com/4531974/70131055-9e141380-16bc-11ea-827c-4a0d4053a5d2.png)

### （必填）建议的 API 是什么样的 What does the proposed API look like

toolbar.Render:[ { name: 'input' }]

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by xuliangzhan** [comment]
toolbar需要支持动态渲染的场景感觉应该不多吧，这个后续可能再考虑下

**Comment by jianliulin** [comment]
感谢考虑此功能！！！，

如果toolbar 在vxe-modal上的时候，动态渲染就很有用。比如点击订单列表中的一行，弹出一个vxe-modal，此时vxe-modal中的toolbar可以根据每个订单的不同状态产生不同的toolbar。
