### ISSUE TITLE
删除行后源数据tableData没有变化

### ISSUE THREAD

**Issue by nihao2015** [xuliangzhan/vxe-table#577]
（必填）请填写问题描述 Describe
删除行后源数据tableData没有变化
假如表格中有两行数据，用$refs.xTable.remove(tableData[1])删除第二行，原则上
原数据tableData应该变成一行，现在还是两行，也没有删除标签（删除状态）

（必填）请填写能重现问题的链接，例如（jsfiddle、codesandbox、jsrun） Reproduction link
暂无

请填写报错信息或截图 Error message or screenshots
没有报错信息

（必填）请填写版本号 Version
os: win
browser: chrome
vue: ^2.5.2
vxe-table: ^2.5.5

**Comment by nihao2015** [comment]
![image](https://user-images.githubusercontent.com/26034266/70227157-10542900-178d-11ea-82e5-501dc86d8609.png)

**Comment by xuliangzhan** [comment]
remove 函数不是这么用的，你要的是 vue 双向的这种
```javascript
this.tableData.splice(1,1)
```

**Comment by nihao2015** [comment]
谢谢作者的回复，对的，我是希望双向，现在是修改源数据this.tableData.splice(1,1)表格会变化，但是用表格api删除表格行(row)，源数据没有变化。

**Comment by xlz26296** [comment]
#202
如果使用一套表格自带 CRUD 是 insert、remove
如果使用 vue 双向数据源，自行去操作 data 即可
