### ISSUE TITLE
树形表格删除父级节点，同时也要删除子节点，怎么做？有这个功能吗？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#58]
同标题所示，谢谢

**Comment by xuliangzhan** [comment]
这个没看出有什么问题，具体业务你需要自行[实现](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/treeEdit)

**Comment by tiger54910** [comment]
解决了，谢谢，还是因为rowkey重复造成的问题。

**Comment by zg08** [comment]
你好 rowkey 重复怎么解决
