### ISSUE TITLE
v-slot:content="{ row, rowIndex }" 插槽无效

### ISSUE THREAD

**Issue by Nike-su** [xuliangzhan/vxe-table#581]
下面代码 展开行没有内容：
<vxe-table-column type="expand" width="60">
	<template v-slot:content="{ row, rowIndex }">
	  <template v-if="rowIndex === 1">
		<vxe-table
		  border
		  :data="tableData">
		  <vxe-table-column field="name" title="Name"></vxe-table-column>
		  <vxe-table-column field="age" title="Age"></vxe-table-column>
		</vxe-table>
	  </template>
	  <template v-else>
		<ul>
		  <li>
			 <span>name：</span> 
			<span>{{ row.name }}</span>
		  </li>
		  <li>
			<span>age：</span> 
			<span>{{ row.age }}</span>
		  </li>
		</ul>
	   </template>
	</template>
  </vxe-table-column>
改为下面默认插槽展开行有效，什么原因？
<vxe-table-column type="expand" width="60">
	<template v-slot="{ row, rowIndex }">
	  <template v-if="rowIndex === 1">
		<vxe-table
		  border
		  :data="tableData">
		  <vxe-table-column field="name" title="Name"></vxe-table-column>
		  <vxe-table-column field="age" title="Age"></vxe-table-column>
		</vxe-table>
	  </template>
	  <template v-else>
		<ul>
		  <li>
			 <span>name：</span> 
			<span>{{ row.name }}</span>
		  </li>
		  <li>
			<span>age：</span> 
			<span>{{ row.age }}</span>
		  </li>
		</ul>
	   </template>
	</template>
  </vxe-table-column>

**Comment by xuliangzhan** [comment]
slot=content 那是 v2.7 的新加的，之前版本使用 default 即可

**Comment by jiisn** [comment]
我使用  v-slot="{ row, rowIndex }"也是无效，浏览器提升row 未定义，都是参照文旦的写法写的，哎！
