### ISSUE TITLE
虚拟表格生成条数只能是大于500条

### ISSUE THREAD

**Issue by newfly35** [xuliangzhan/vxe-table#582]
### （必填）请填写问题描述 Describe
我在用官方实例的虚拟表格的时候，发现size小于500条，虚拟表格不生效，还是一次性全部加载出来数据，不知道为什么
 ?

### （必填）请填写能重现问题的链接
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/scroll
### 请填写报错信息或截图 Error message or screenshots
created () {
            this.$ajax.mockList(600).then(data => {
              this.tableData = data
            })
          }
把上面代码中的600改成小于500的数字，虚拟列表不起作用

**Comment by shekang** [comment]
表格属性设置: 
```js
optimization  = {
   scrollY : {
    gt: '300'
  }
}
```

**Comment by newfly35** [comment]
谢谢！

**Comment by xuliangzhan** [comment]
新版本不需要 optimization 这个
```
<vxe-table
  ...
  :scroll-y="{ gt: 300 }>
...
</vxe-table>
```
