### ISSUE TITLE
能不能直接通过script标签引用，跟引用vue.js一样，在普通的html中使用

### ISSUE THREAD

**Issue by gongxings** [xuliangzhan/vxe-table#586]
### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
当然可以，文档里面就有说明https://xuliangzhan.com/vxe-table/index.html#/table/start/install

**Comment by pcwe2002** [comment]
`<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		
	      <link rel="stylesheet" href="https://unpkg.com/vxe-table/lib/index.css">
	      <script src="https://unpkg.com/xe-utils"></script>
	      <script src="https://unpkg.com/vxe-table"></script>
      
		<script src="https://cdn.jsdelivr.net/npm/vue@2.6.0"></script>
	</head>
	<body>
		<div id="test" class="mui-content">
			<vxe-grid
		          border
		          resizable
		          height="500px"
		          :loading="loading"
		          :columns="tableColumn"
		          :data="tableData">
		    </vxe-grid>
		</div>
		
		<script>
			
			var vm = new Vue({
				el: '#test',
				data: {
					loading: false,
					tableColumn: [
					    { type: 'index', width: 50 },
					    { field: 'name', title: 'app.body.label.name' },
					    { field: 'sex', title: 'app.body.label.sex', showHeaderOverflow: true },
					    { field: 'address', title: 'Address', showOverflow: true }
					],
              		tableData:  
              		[
              		{"index":1,"name":"json","sex":"男","address":"南天门"},
            		{"index":2,"name":"json2","sex":"女","address":"南天门2"}
            		]

				}
			});

		</script>
	</body>
</html>`
应该不行，按说明像这样引用没有反应

**Comment by pcwe2002** [comment]
` <link rel="stylesheet" href="https://unpkg.com/vxe-table/lib/index.css">
	      <script src="https://unpkg.com/xe-utils"></script>
	      <script src="https://unpkg.com/vxe-table"></script>`
按说明这样引用应该就是最新版本了。

**Comment by wekerSnail** [comment]
那是因为你的引用顺序不对，vxe是基于vue的，你最后引入vue当然不行，vue必须首先引入

**Comment by pcwe2002** [comment]
发现是浏览器的问题，先引用vue, 在hbuilder中内置的浏览器引用会报错。
提示这个错误，"Uncaught TypeError: undefined is not a function"	https://unpkg.com/vxe-table@2.6.22/lib/index.js (17685)
换了顺序放到chrome去执行就对了。

**Comment by gongxings** [comment]
> 当然可以，文档里面就有说明https://xuliangzhan.com/vxe-table/index.html#/table/start/install

**Comment by gongxings** [comment]
了解了，谢谢各位大佬
