### ISSUE TITLE
配置式 列可滚动表格(vxe-grid),   变更表格数据为空数组,  表格滚动条消失

### ISSUE THREAD

**Issue by adoniscyz** [xuliangzhan/vxe-table#589]
渲染时表格数据为空数组, 滚动条正常,  渲染完成后,  变更表格数据为空数组,  表格滚动条消失

重现链接  https://jsfiddle.net/4jtbhuLc/4/

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/21983578/70584062-b1623a00-1bfa-11ea-823e-03db20bcc5c8.png)

变动数据为空后, 滚动条消失
![Uploading image.png…]()

### （必填）请填写期望的结果 Expected behavior
变动表格数据为空,  滚动条还会存在

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.6.22

**Comment by xuliangzhan** [comment]
#557
