### ISSUE TITLE
树形表格有一个节点不显示，但是能搜索到

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#59]
如题，树形表格有一个父节点不显示，但是搜索的时候可以显示。
![QQ图片20190612175635](https://user-images.githubusercontent.com/14190457/59342031-86765680-8d3b-11e9-9ed3-9cf7bb81ece6.png)
![QQ图片20190612175643](https://user-images.githubusercontent.com/14190457/59342034-870eed00-8d3b-11e9-81da-2c76c0ccf9c7.png)

**Comment by xuliangzhan** [comment]
你是说少了一个节点没显示？先检查下数据有没有问题，你应该提供下重现问题的链接

**Comment by tiger54910** [comment]
找到问题了，rowkey重复了，谢谢
