### ISSUE TITLE
根据demo配置的selec模糊搜索的功能，在vxe-grid模式下无法正常使用，由于column的变化会导致组件重渲染

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#591]
### （必填）请填写问题描述 Describe the bug
在vxe-table组件下使用是没问题的，因为options引用的单独的变量，options变化时不会导致表格组件重渲染，但是vxe-grid组件下，options属于column配置数据的一部分，options的变化导致整个column变化，导致表格组件重渲染，功能无法正常使用。
![GIF 2019-12-11 16-49-34](https://user-images.githubusercontent.com/30314164/70605873-46365900-1c36-11ea-9fbd-81e741f6c82a.gif)

 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
再此demo基础上做的修改：https://xuliangzhan.com/vxe-table/index.html#/table/plugin/elementPage
![image](https://user-images.githubusercontent.com/30314164/70605657-dfb13b00-1c35-11ea-8d79-e2530319a5d2.png)
![image](https://user-images.githubusercontent.com/30314164/70605731-04a5ae00-1c36-11ea-81e2-db3b6392835c.png)

 ?

### 填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by wekerSnail** [comment]
#561

**Comment by wekerSnail** [comment]
https://jsrun.pro/JxWKp/edit   复现demo @xuliangzhan

**Comment by wekerSnail** [comment]
目前通过重写一个下拉组件，把数据内部独立解决了这个问题，在elem-pluagin里面引入了一个自己的下拉组件，没想他其他更好的方法解决
![image](https://user-images.githubusercontent.com/30314164/70698165-dee5db00-1d01-11ea-8622-779b7b46642d.png)

**Comment by xuliangzhan** [comment]
这不可以吗 https://jsrun.pro/8GWKp/edit

**Comment by wekerSnail** [comment]
这样后期复制的方式确实可以让表格不重渲染，不过现在项目的交互比较复杂，这么写不太好实现或者比较麻烦，还是先用封装组件的方式吧
