### ISSUE TITLE
单元格设置右键菜单栏动态固定到左边/右边/取消，当将单元格固定到一边时，在重置数据时，会留下一片空白区域

### ISSUE THREAD

**Issue by youguangsheng** [xuliangzhan/vxe-table#592]
### （必填）请填写问题描述 Describe the bug
单元格设置右键菜单栏动态固定到左边/右边/取消，单元格宽度固定，当将单元格固定到一边时，在重置数据时，会留下一片空白区域
 ?

### （必填）请填写能重现问题的链接，例如（
https://codesandbox.io/s/vxe-table-ceshide-demo-lqw1s
 ?

### 填写报错信息或截图 Error message or screenshots
https://trade-erp.oss-cn-beijing.aliyuncs.com/2019_12_11/fpb6Xt2t_19115_system_%E5%9B%BE%E7%89%872019-12-11_1.png

https://trade-erp.oss-cn-beijing.aliyuncs.com/2019_12_11/ZzSskS8e_13026_system_%E5%9B%BE%E7%89%872019-12-11_2.png
 ?

### （必填）请填写期望的结果 Expected behavior

 ?

### （必填）请填写版本号 Version

- os: window
- browser: chrome
- vue: lastest
- vxe-table: lastest

**Comment by xuliangzhan** [comment]
https://codesandbox.io/s/vxe-table-ceshide-demo-yumts
