### ISSUE TITLE
表格横向滚动条会在清空数据消失

### ISSUE THREAD

**Issue by youguangsheng** [xuliangzhan/vxe-table#594]
### （必填）请填写问题描述 Describe
表格单元格宽度固定，tableData初始化未[],表格有横向滚动条，表头全可见，tableData获取数据后，在手动清空为[]，表格横向滚动消失，表头被遮盖
 ?

### （必填）请填写能重现问题的链接，例如
https://codesandbox.io/s/vxe-table-ceshide-demo-mm6ho
 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: window
- browser: chrome
- vue: laster
- vxe-table: laster

**Comment by xuliangzhan** [comment]
#557
