### ISSUE TITLE
结合element ui select下拉组件使用。初始值有一行，点击编辑并切换下拉框，选项值不变

### ISSUE THREAD

**Issue by abcdGJJ** [xuliangzhan/vxe-table#595]
### （必填）请填写问题描述 Describe the bug

 结合element ui select下拉组件使用。初始值有一行，点击编辑并切换下拉框，选项值不变

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 https://codesandbox.io/s/vxe-table-ceshide-demo-cpj3d

### （必填）请填写期望的结果 Expected behavior

点击编辑并切换下拉框，选项值改变

### （必填）请填写版本号 Version

- vue: 2.6.10
- vxe-table: 2.6.22
- vxe-table-plugin-element: 1.5.12
- element-ui  2.13.0

**Comment by xuliangzhan** [comment]
请先熟悉 vue 再使用这个组件，应该先去了解vue属性先定义后使用的原则

**Comment by abcdGJJ** [comment]
抱歉 我的锅  没注意到变量名拼错了
