### ISSUE TITLE
按照文档写的懒加载树表格，无效

### ISSUE THREAD

**Issue by webYouth** [xuliangzhan/vxe-table#596]
### （必填）请填写问题描述 Describe

 按照文档写的懒加载树表格，无效，设置hasChild为true,无法出现可点击的行

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 链接暂无

### 请填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/22173368/70844806-41b1b080-1e81-11ea-8c84-1c533002d4da.png)
![image](https://user-images.githubusercontent.com/22173368/70844811-542bea00-1e81-11ea-9ca1-01c6b44b6689.png)

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.6.10
- vxe-table: 2.6.22

**Comment by jianliulin** [comment]
v2.7才可以

**Comment by webYouth** [comment]
您好，npm只有2.6

**Comment by webYouth** [comment]
以解决，用了您文档上的CDN，npm更新一咯，小哥哥

**Comment by Justin20171102** [comment]
我把vxe-table升到2.7之后，报另外的错
<img width="996" alt="WX20191218-105434@2x" src="https://user-images.githubusercontent.com/33305938/71051940-d0c20f80-2184-11ea-9081-d655b73ddfd8.png"> 求助，谢谢！

**Comment by webYouth** [comment]
xeUtils和vxtable 这两个库是配套的，版本要一致，建议用文档的CDN，可以保证同步和最新，我就是这么解决的
