### ISSUE TITLE
在可编辑的表格新增 :data.sync 没有同步表格里的数据

### ISSUE THREAD

**Issue by YuppyHub** [xuliangzhan/vxe-table#60]
**问题描述 Describe the bug**
在可编辑的表格内，新增数据后没有同步到 ```javascript :data.sync="data" ``` data没有同步最新的数据。 只取了新增的第一条。

**重现问题的步骤 To Reproduce**
1. 在可编辑的表格新增几条数据，逐个写入内容
2. 在保存表格数据方式内获取 :data.sync 绑定的数据， 里内的数据会只有一条

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/y7n0bw4e/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**
暂无

**报错信息或截图 Error message or screenshots**
![WX20190613-101812](https://user-images.githubusercontent.com/20299293/59399083-478ce300-8dc5-11e9-9acb-141ce9688031.png)

**期望的结果 Expected behavior**
能看到 :data.sync 绑定的数据与表格内数据条数相同。。

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: chrome 最新版
 - vue: 3.4.0
 - vxe-table: 1.0.6

**Comment by xuliangzhan** [comment]
任何通过 instart 动态插入数据的都不属于 data 源，不会同步的，只能通过 getInsertRecords 获取；
如果需要同步你应该对 data 源进行操作，比如 this.tableData.push({name: ''})
