### ISSUE TITLE
Export Tree Table Data as html, table header value issue

### ISSUE THREAD

**Issue by abertaykevin** [xuliangzhan/vxe-table#601]
When data is exported , html title property is ignored for the header, its grabbing the header value from filed attribute, how to make it to grab it from the title property. Also how can i format columns when exporting if i want for some reason?

**Comment by abertaykevin** [comment]
Issue particularly with tree-config setting

**Comment by xuliangzhan** [comment]
You can do this by customizing the columns or data
https://xuliangzhan.github.io/vxe-table/#/table/api?filterName=exportData

**Comment by abertaykevin** [comment]
Take a look at this
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/export
Export to CSV works fine with correct title attributes

Now check this example ( Run Code ) from the same page above
https://jsrun.pro/cmXKp/edit
Export to CSV works but with in-correct title attributes
