### ISSUE TITLE
希望添加两个样式标签（ <vxe-form>  <vxe-form-item>)

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#604]
### （必填）这个需求解决了什么问题 What problem does this feature solve
  希望添加两个样式标签（ <vxe-form>  <vxe-form-item>) ，以便替换饿了么等第三方标签

    <el-form>
        <el-form-item label="名称" prop="Name">
             <vxe-input v-model="row.Name" style="width:400px" />              
       </el-form-item>
    </el-form>

### （必填）建议的 API 是什么样的 What does the proposed API look like

    <vxe-form>
        <vxe-form-item label="名称" prop="Name">
             <vxe-input v-model="row.Name" style="width:400px" />
       </vxe-form-item>
    </vxe-form>

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 ?

**Comment by huoshidehua** [comment]
有没有 title slot
