### ISSUE TITLE
表尾合计的列可以不跟随表格列配置而单独配置左右悬浮吗

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vxe-table#609]
### （必填）这个需求解决了什么问题 What problem does this feature solve
表尾合计的列可以不跟随表格列配置而单独配置左右悬浮（fixed），
### 在列比较多的情况下，横向滚动之后会看不到合计的行标题

![TIM图片20191218162256](https://user-images.githubusercontent.com/30314164/71068922-aa1acd80-21b2-11ea-8b8a-4fe6d8f26b50.png)

**Comment by xlz26296** [comment]
https://xuliangzhan.com/vxe-table/index.html#/table/advanced/footer

**Comment by wekerSnail** [comment]
这个是跟随表格列配置来的，不是独立的固定列
