### ISSUE TITLE
校验显示与滚动造成的问题

### ISSUE THREAD

**Issue by anyclub** [xuliangzhan/vxe-table#610]
### （必填）请填写问题描述 Describe the bug

1. 行内校验的提示方式, 会因为table默认的overflow设置,在只有一行时,校验无法显示(连接中第一个表格)

2. 采用tooltip方式作为提示,时
     2.1 实际项目环境接近下方连接,是在某个DIV内使用的滚动条
     2.2 用户在最底端保存按钮时,同时触发了表格校验与上方的各类表单校验,此时使用默认滚动到最顶部第一个报错位置,
     2.3 tooltip此时会发生错位

### （必填）请填写能重现问题的链接

https://codesandbox.io/s/vxe-table-ceshide-demo-lcyc7

### （必填）请填写期望的结果 Expected behavior

 行内校验能的dom结构变化,能不受table的overflow影响
或者
 控制tooltip能跟随滚动变化而重新定位

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xlz26296** [comment]
使用默认的就行，没必要用 tooltip 这种有可能要废弃的参数

**Comment by anyclub** [comment]
> 使用默认的就行，没必要用 tooltip 这种有可能要废弃的参数

默认的无法显示,因为其父级table组件拥有一个overflow:hidden的属性
可以看第一个表格的显示效果

**Comment by xlz26296** [comment]
更新最新版本这个是 bug 修复了
