### ISSUE TITLE
vxe-grid设置pager后高度100%时不能铺满父容器

### ISSUE THREAD

**Issue by xochina** [xuliangzhan/vxe-table#611]
### （必填）请填写问题描述 Describe the bug

 ?  vxe-grid设置pager后高度100%时显示不正确，刚好少了40px(行高)。 如果没有设置pager则没有问题。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ? [jsrun](https://jsrun.pro/sDWKp/edit) 网址 [https://jsrun.pro/sDWKp](https://jsrun.pro/sDWKp)

### 填写报错信息或截图 Error message or screenshots

 ?  [https://jsrun.pro/sDWKp](https://jsrun.pro/sDWKp)

### （必填）请填写期望的结果 Expected behavior

 ? vxe-grid设置pager后高度100%时能铺满父容器

### （必填）请填写版本号 Version

- os: ? macos
- browser: ? chrome
- vue: ? vue@2.6.11
- vxe-table: ? vxe-table@2.7.5

**Comment by xlz26296** [comment]
铺满父容器的值是 auto 而不是100%，两者是有点差别的

**Comment by xochina** [comment]
收到，非常感谢
