### ISSUE TITLE
是否支持slot-scope

### ISSUE THREAD

**Issue by airzg** [xuliangzhan/vxe-table#615]
### （必填）请填写问题描述 Describe
从 iview 转过来使用 vxe-table，vxe 最新版本是否支持slot-scope 写法，iview 从 3.2.0 版本开始支持 slot-scope 写法

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

https://iviewui.com/components/table#ZDYLMB
### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.5.10
- vxe-table: 2.7.6

**Comment by xlz26296** [comment]
插槽语法和任何组件都没任何关系
vue 3 支持 v-slot
vue 2.6 + 支持 v-slot 和 slot-scope
vue 2.6 - 支持 slot-scope

**Comment by airzg** [comment]
thanks for reply. 
vxe-column 支持slot-name的写法是怎么使用：
比如 iview组件的，类似这样<template slot="operate" slot-scope="{row}"> 其中slot="operate"中的operate是在column中指定的，如下
columns: [
        {
          title: 'Mark',
          key: 'orderMark',
          width: 85,
          fixed: 'left',
          align: 'center',
          slot: 'operate'
}

**Comment by airzg** [comment]
> thanks for reply.
> vxe-column 支持slot-name的写法是怎么使用：
> 比如 iview组件的，类似这样 其中slot="operate"中的operate是在column中指定的，如下
> columns: [
> {
> title: 'Mark',
> key: 'orderMark',
> width: 85,
> fixed: 'left',
> align: 'center',
> slot: 'operate'
> }
仔细看了vxe api，不支持columns动态绑定中指定slot name; 目前vxe-table 只支持v-slot: header、default、edit、icon、content、filter
