### ISSUE TITLE
如果要启用横向虚拟滚动，不支持分组表头，可以支持footer合并吗？

### ISSUE THREAD

**Issue by rayas51674** [xuliangzhan/vxe-table#618]
### （必填）请填写问题描述 Describe

https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/fullCols

写着 *如果要启用横向虚拟滚动，不支持分组表头*

请问可以添加一个footer，用footer-span-method自行计算吗？

谢谢
### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
支持合并
