### ISSUE TITLE
建议能按需引用对应的功能，有时候可能只需要一个合并功能，就要引入200KB的JS

### ISSUE THREAD

**Issue by 531431988** [xuliangzhan/vxe-table#62]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
这个建议很好，将在 1.1 重构模块化表格
