### ISSUE TITLE
快捷菜单在边缘展开二级菜单时位置错误

### ISSUE THREAD

**Issue by lucidwater** [xuliangzhan/vxe-table#623]
### （必填）请填写问题描述 Describe the bug

快捷菜单在边缘展开二级菜单时位置错误

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

http://jsrun.pro/4rWKp/edit

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/43023260/71497663-318fcd00-2894-11ea-9c50-97a2777c8e68.png)

### （必填）请填写期望的结果 Expected behavior

 自动切换方位

### （必填）请填写版本号 Version

- os: win7
- browser: chrome79.0.3945.88
- vue: 2.6.10
- vxe-table: 2.6.22

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下

**Comment by lucidwater** [comment]
最新版是对的，万分感谢！
