### ISSUE TITLE
当出现纵向滚动条时，表头和表体错位

### ISSUE THREAD

**Issue by NicholasZhaoS** [xuliangzhan/vxe-table#627]
当出现纵向滚动条时，表头和表体错位，没有滚动条时可以对齐

链接：https://jsrun.pro/c5WKp

图片：https://user-images.githubusercontent.com/50091070/71608714-22738c80-2bbe-11ea-916c-a066ed325906.png

**Comment by xuliangzhan** [comment]
#620
