### ISSUE TITLE
单元格编辑模式下出现key值undefined报错

### ISSUE THREAD

**Issue by victorting** [xuliangzhan/vxe-table#63]
**描述 Describe**
单元格编辑模式下加载两百多条数据出现了两百多条[Vue warn]: Duplicate keys detected: 'undefined'. This may cause an update error.的提示，看了下table tr的data-rowkey属性都是undefined，请问是什么原因，是我使用的问题吗

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/y7n0bw4e/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: chrome Version 74.0.3729.131 (Official Build) (64-bit)
 - vue: 2.6.10
 - vxe-table: 1.0.9

**Comment by victorting** [comment]
问题已经解决，是我使用的问题

**Comment by zg08** [comment]
你好 我也出现了这个问题 怎么解决呢

**Comment by victorting** [comment]
> 你好 我也出现了这个问题 怎么解决呢

你可以看下api文档 https://xuliangzhan.com/vxe-table/index.html#/table/api，对table设置row-key就可以了

**Comment by zg08** [comment]
我看了&nbsp; 没有看明白才去github找答案的&nbsp; 。
我的问题是树形图&nbsp; 我动态插入二级数据的时候提示的错误



---原始邮件---
发件人: "咸fish"<notifications@github.com&gt;
发送时间: 2019年10月25日(星期五) 下午4:10
收件人: "xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"zg08"<595158663@qq.com&gt;;
主题: Re: [xuliangzhan/vxe-table] 单元格编辑模式下出现key值undefined报错 (#63)


 
你好 我也出现了这个问题 怎么解决呢
  
你可以看下api文档 https://xuliangzhan.com/vxe-table/index.html#/table/api，对table设置row-key就可以了

**Comment by zg08** [comment]
我添加了之后还是不行 还是报那个错误

**Comment by victorting** [comment]
> 我添加了之后还是不行 还是报那个错误
你可以提供个demo复现一下嘛？
