### ISSUE TITLE
列表编辑和表尾合计不同步

### ISSUE THREAD

**Issue by NicholasZhaoS** [xuliangzhan/vxe-table#633]
表格数据进行修改后，表尾合计会自动修改，这个没问题

但是再次使用按钮进行数据刷新后，对tableData重新赋值，列表数据自动刷新了，但是表尾合计还是修改时的值

https://jsrun.pro/jRWKp

**Comment by senbrid** [comment]
按钮事件中可以调用刷新表尾合计方法this.$refs.xTable.updateFooter()

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下
