### ISSUE TITLE
展开行时再加载数据怎么做呀？

### ISSUE THREAD

**Issue by tiger54910** [xuliangzhan/vxe-table#64]
使用Vxe_table的展开行的时候，主要用于实现父子表的场景，怎么在展开某行的时候去获取数据？谢谢

**Comment by xuliangzhan** [comment]
[toggle-expand-change](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=toggle-expand-change)

**Comment by tiger54910** [comment]
哦，谢谢，解决了
