### ISSUE TITLE
有合并单元格时，固定列会导致错行

### ISSUE THREAD

**Issue by natee** [xuliangzhan/vxe-table#647]
### （必填）请填写问题描述 Describe the bug

 有合并单元格时，固定列会导致固定列的单元格高度为单行高度

### （必填）请填写能重现问题的链接 Reproduction link

 [jsrun](http://jsrun.pro/xKfKp/edit)

### 填写报错信息或截图 Error message or screenshots

 
![5041578992147_ pic](https://user-images.githubusercontent.com/4928035/72328891-be3ce680-36ee-11ea-9d9c-12c733a01484.jpg)

### （必填）请填写期望的结果 Expected behavior

 期望固定的列按照合并行的高度计算

### （必填）请填写版本号 Version

- os: mac
- browser: chrome
- vue: 2.6.11
- vxe-table: 2.7.24

**Comment by xuliangzhan** [comment]
该问题会在 v2.8+ 修复 http://jsrun.pro/wpfKp/edit
