### ISSUE TITLE
如何在表格中加载两个Iview的按钮？

### ISSUE THREAD

**Issue by 531431988** [xuliangzhan/vxe-table#65]
**描述 Describe**
如图

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

![image](https://user-images.githubusercontent.com/8703951/59587346-a3ce6a80-9117-11e9-8858-1fd4c92dd0c2.png)

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by 531431988** [comment]
找到了！
这个组件确实很强大，期待按需引入

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/use
