### ISSUE TITLE
列拖拽宽度为什么不变化

### ISSUE THREAD

**Issue by xxLion** [xuliangzhan/vxe-table#658]
### （必填）请填写问题描述 Describe

列拖拽时候，列的宽度不随之变化

### （必填）请填写能重现问题的链接
http://jsrun.pro/FkfKp/edit

### 请填写报错信息或截图 Error message or screenshots

无

### （必填）请填写版本号 Version

- os: win10
- browser: chrome78
- vue: 2.6x
- vxe-table: 2.x

**Comment by xxLion** [comment]
我只是好奇，data的宽度已经变化了，为什么没同步视图。

**Comment by xuliangzhan** [comment]
如果要动态改变列宽，通过 recalculate()  刷新；
如果要动态改变特殊属性，通过  refreshColumn() 刷新；
http://jsrun.pro/xkfKp/edit

**Comment by xxLion** [comment]
> 如果要动态改变列宽，通过 recalculate() 刷新；
> 如果要动态改变特殊属性，通过 refreshColumn() 刷新；
> http://jsrun.pro/xkfKp/edit

谢谢，第一次见作者反馈速度这么快。
