### ISSUE TITLE
请问在编辑状态下给表格通过操作数据源添加一个新行，如何才能默认使新行的第一个单元格被激活呢？

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#66]
**描述 Describe**

我需要对表格进行编辑，并且插入新数据。在插入新数据的时候，我本来想通过动态操作数据的方法insertAt，但是它不会同步修改数据源，所以我就直接给数据源添加了一个空值this.tableData = [ ...this.tableData,{'name':xxxx,'sex':xxxx}]，但是这样如何设置使用这一行的第一个单元格处于激活状态呢？
或者有没有更好的不停地插入新数据的方案呢？

**Comment by xuliangzhan** [comment]
如果非要操作数据源，那你就需要配合[手动激活编辑](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=setActive)

**Comment by 1057437122** [comment]
> 如果非要操作数据源，那你就需要配合[手动激活编辑](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=setActive)

这个设置激活的row的值如何获得呢？可以通过row-key获取吗？

**Comment by xuliangzhan** [comment]
row就是插入的值，比如
```javascript
let row = {name:''}
this.tableData.push(row)
this.$nextTick(() => {
  this.$refs.xTable.setActiveCell(row, 'name')
})
```

**Comment by 1057437122** [comment]
好的，谢谢
