### ISSUE TITLE
高亮列做列拖拽的问题

### ISSUE THREAD

**Issue by xxLion** [xuliangzhan/vxe-table#660]
### （必填）请填写问题描述 Describe

点击当前列高亮之后，前3列互相拖拽还显示高亮效果，如果拖到最后一列，高亮效果消失。

### （必填）请填写能重现问题的链接

https://jsrun.pro/qYfKp/edit

### 请填写报错信息或截图 Error message or screenshots
![chen](https://user-images.githubusercontent.com/26025205/72797511-36ba1f00-3c7c-11ea-9c73-f0b2f40215a1.gif)

### （必填）请填写版本号 Version

- os: win10
- browser: chrome78
- vue: 2.6.10
- vxe-table:

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下

**Comment by qinghechaoge** [comment]
新版不支持了？我看4.6.16 不能拖动高亮列啊
