### ISSUE TITLE
动态显示隐藏表头时固定列位置不对

### ISSUE THREAD

**Issue by qhhuang** [xuliangzhan/vxe-table#662]
### （必填）请填写问题描述 Describe the bug
例如用一个按钮控制表头的显示隐藏，表格存在横向滚动条时，固定列会在隐藏表头时错位

?

### （必填）请填写能重现问题的链接
http://jsrun.pro/eqfKp

 

### 填写报错信息或截图 Error message or screenshots

![A1](https://user-images.githubusercontent.com/14370207/73632124-df617900-4695-11ea-8725-cfb5bdc5b9dc.png)
![A2](https://user-images.githubusercontent.com/14370207/73632135-e4262d00-4695-11ea-84c6-ae37691d4589.png)
![A3](https://user-images.githubusercontent.com/14370207/73632139-e5eff080-4695-11ea-88b1-ae8cb9d5ef0d.png)

### （必填）请填写期望的结果 Expected behavior
表头位置正常

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.5.22  or 2.7.24

**Comment by xuliangzhan** [comment]
该问题会在 2.8 中修复 @2.8.0-beta.3

**Comment by qhhuang** [comment]
> 该问题会在 v2.8 中修复 https://jsrun.pro/QqfKp/edit

现在暂时用了一个傻子办法 v-if 把table全部隐藏。。。 nexttick再重新加载、。
需求是点击checkbox的时候隐藏header
然后记录选中的
显示后再set一下check的。。
  this.tableVisible = true
 let tempCheckboxRecords = (this.$refs.documentTable.getCheckboxRecords())
                    this.$nextTick(_ => {
                        this.tableVisible = true
                        this.$nextTick(_ => {
                            this.$refs.documentTable.setCheckboxRow(tempCheckboxRecords, true)

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下
