### ISSUE TITLE
源数据添加了值之后insertAt无效

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#67]
**问题描述 Describe the bug**

我需要往表格里插入数据，但是发现修改了数据源之后再调用insertAt无效
**重现问题的步骤 To Reproduce**
这是刚进页面时，获取到数据源之后添加一个空行，是正确的
![image](https://user-images.githubusercontent.com/6631168/59601077-47f9e680-9103-11e9-834d-2de1e8ac42f5.png)

然后在这个激活的框里输入值，跳出选择页面
![image](https://user-images.githubusercontent.com/6631168/59601317-edad5580-9103-11e9-820e-8e56771e1076.png)

双击选择对应的产品之后，先是把产品添加到数据源中，然后再添加一个空行并置为激活：
![image](https://user-images.githubusercontent.com/6631168/59601399-25b49880-9104-11e9-9338-cdbc925862ce.png)
但是没有再添加一个空行
![image](https://user-images.githubusercontent.com/6631168/59601415-31a05a80-9104-11e9-9d37-c240e560a000.png)

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ? chrome:75.0.3770.80
 - vue: ?
 - vxe-table: ?
![image](https://user-images.githubusercontent.com/6631168/59601510-7a581380-9104-11e9-8ba7-2b548adb6df3.png)

**Comment by xuliangzhan** [comment]
你不应该是数据赋值之后就马上插入，vue的响应不是实时的，你应该在$nextTick之后再调insert方法

**Comment by 1057437122** [comment]
好的，发现了，感谢
