### ISSUE TITLE
缺少必要的 "show-overflow" 参数，这可能会导致出现错误

### ISSUE THREAD

**Issue by zhangchenna** [xuliangzhan/vxe-table#672]
缺少必要的 "show-overflow" 参数，这可能会导致出现错误

**Comment by zhangchenna** [comment]
全都填了 也提示这个

**Comment by xiaogaofudao** [comment]
@zhangchenna 3.0.3 版本同样提示警告，你解决了吗

**Comment by yyqxjwxy** [comment]
同问

**Comment by xlz26296** [comment]
设置 :scroll-y="{enabled: false}" 就行了，虚拟滚动启动后必须设置 show-overflow

**Comment by xiaogaofudao** [comment]
在 <vxe-table 这一层加上  show-overflow="tooltip"
