### ISSUE TITLE
有筛选和排序时，如果标题内容省略，会把筛选和排序挤掉，无法显示

### ISSUE THREAD

**Issue by fls1215** [xuliangzhan/vxe-table#679]
### （必填）请填写问题描述 Describe the bug

 有筛选和排序时，如果标题内容省略，会把筛选和排序挤掉，无法显示

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

 http://jsrun.pro/vffKp/edit

### 填写报错信息或截图 Error message or screenshots

![1582617936253](https://user-images.githubusercontent.com/21237474/75227708-ab3b2d00-57e9-11ea-8b36-890c5a021523.jpg)

### （必填）请填写期望的结果 Expected behavior
希望后面的排序或者筛选都能显示
![1582618405848](https://user-images.githubusercontent.com/21237474/75227844-e8072400-57e9-11ea-8c1e-df216256b6ad.jpg)

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.7.24

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下
