### ISSUE TITLE
需要日期选择框

### ISSUE THREAD

**Issue by adoin** [xuliangzhan/vxe-table#684]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 表单很常见的需求就是日期，我不想去用为此引入antd 或者 element的datepicker

### （必填）建议的 API 是什么样的 What does the proposed API look like

 date类型的日期选择框，getter可获得正确时间格式 setter可重新渲染日期组件勾选日期之类的
 最好还有时间段的date组件

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 没有 暂时是改的antd 但是那个东西太难用了

**Comment by jianliulin** [comment]
原来不止我一个人又这样的想法

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下
