### ISSUE TITLE
请问如何在编辑模式下使用点击进入编辑状态时自动把input框中的内容选中呢？

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#69]
**描述 Describe**

设置的是单击进入单元格的编辑状态，此时原来的单元格中若有值的话光标是在单元格的后面，但是我想直接输入需要的值，而不是先把原来的值手动删除再改。（但是也不能直接把那个值置为空，因为也可以直接回车不修改数据结束编辑）

**Comment by xuliangzhan** [comment]
这个使用 edit-actived 事件就可以解决

```javascript
editActivedEvent ({ row, column, cell }, event) {
      this.$nextTick(() => {
        cell.querySelector('input').select() // 自行处理兼容性
      })
    }
```

**Comment by 1057437122** [comment]
> 这个使用 edit-actived 事件就可以解决
> 
> ```js
> editActivedEvent ({ row, column, cell }, event) {
>       this.$nextTick(() => {
>         cell.querySelector('input').select() // 自行处理兼容性
>       })
>     }
> ```

好的，谢谢
