### ISSUE TITLE
.vxe-cell 默认行高问题，请问有可替代方案？

### ISSUE THREAD

**Issue by Nolin-Lin** [xuliangzhan/vxe-table#695]
### （必填）请填写问题描述 Describe

 某一列需要展示多个数据。例如：
<vxe-table-column field="role" title="Role">
            <template v-slot="scope">
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
            </template>
</vxe-table-column>
但是因为height写死了，请问有可替代方案？

### （必填）请填写能重现问题的链接
https://jsfiddle.net/w8s4npu2/2/

### 请填写报错信息或截图 Error message or screenshots

 无

### （必填）请填写版本号 Version

- os: mac
- browser: chrome 80.0.3987.122 最新版本
- vue: 2.6.11
- vxe-table: 2.7.24

**Comment by Nolin-Lin** [comment]
<vxe-table-column field="role" title="Role">
            <template v-slot="scope">
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
            </template>
          </vxe-table-column>

**Comment by Nolin-Lin** [comment]
`
<vxe-table-column field="role" title="Role">
        <template v-slot="scope">
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
              <div>{{ scope.row.role}}</div>
        </template>
</vxe-table-column>`

**Comment by xuliangzhan** [comment]
只要关闭虚拟滚动就可以支持动态行高了
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/bad/lineHeight

**Comment by Nolin-Lin** [comment]
骚操作一下，哈哈
例子：https://jsfiddle.net/ev62Lh7b/2/

默认虚拟滚动，不使用optimization
props:
:max-height="600"
:cell-style="{height: `${cellHeight}px`}"

样式修改
.vxe-cell{
    max-height: fit-content!important;
}

这样是否有影响或者引起其他bug？
