### ISSUE TITLE
vxe+element-ui，编辑模式，点击无效

### ISSUE THREAD

**Issue by PineSongCN** [xuliangzhan/vxe-table#696]
点击table，触发了焦点事件，原本的显示消失，但是没有出现编辑

### （必填）请填写能重现问题的链接
本地未上线后台项目，不好放链接

### 请填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/39976617/75906324-7bdb8e80-5e81-11ea-84a6-63e166d08afe.png)
![image](https://user-images.githubusercontent.com/39976617/75906347-8564f680-5e81-11ea-91f6-5a964d6552cb.png)

### （必填）请填写版本号 Version

- os: Windows10
- browser: 谷歌
- vue: 2.6.10
- vxe-table: 2.8.13
- vxe-table-plugin-element: 1.7.0

代码：
`<vxe-grid
      border
      resizable
      show-overflow
      ref="xTable"
      height="460"
      :loading="loading"
      :data="tableData"
      :columns="tableColumn.base"
      :edit-config="{ trigger: 'click', mode: 'cell' }"
      @edit-actived="editActivedEvent"
      @edit-closed="editClosedEvent"
    >
      <template v-slot:top> </template>
      <template v-slot:buttons>
        <el-button @click="insertEvent()">新增</el-button>
        <el-button @click="saveEvent">保存</el-button>
      </template>
      <vxe-table-column field="processHandle">
        <template v-slot="{ row, rowIndex }">
          <vxe-button> 下一步 </vxe-button>
        </template>
      </vxe-table-column>
    </vxe-grid>`

`
data() {
    return {
      loading: false,
      tableData: [
        {
          quantity: 1,
          unit: 'xs'
        }
      ],
      selectRecords: [],
      tableColumn: {
        base: [
          { type: 'seq', field: 'sampleNo', title: '序号', width: 100 },
          {
            field: 'sampleType',
            title: '类型',
            width: 100,
            editRender: { name: 'sampleType', options: [] }
          },
          {
            type: 'seq',
            field: 'sampleOutNo',
            title: '提供方编号',
            width: 100
          },
          {
            field: 'quantity',
            title: '数量',
            width: 100,
            editRender: { name: 'quantity', props: { min: 0, max: 100000 } }
          },
          {
            field: 'unit',
            title: '单位',
            editRender: { name: 'unit' }
          },
          {
            field: 'gmtReceived',
            title: '收样时间',
            width: 220,
            editRender: {
              name: 'gmtReceived',
              props: { type: 'datetime', format: 'yyyy-MM-dd HH:mm:ss' }
            }
          }
        ],
        show: []
      }
    };
  }
`

**Comment by lmc19860810** [comment]
editActivedEvent 在这个事件中赋值。你试下。

**Comment by PineSongCN** [comment]
> editActivedEvent 在这个事件中赋值。你试下。

赋值？我直接复制的样例代码
`
  editActivedEvent({ row, column }, event) {
      console.log(row);
      console.log(column);
      console.log(`打开 ${column.title} 列编辑`);
    },


    editClosedEvent({ row, column }, event) {
      console.log(row);
      console.log(column);
      console.log(`关闭 ${column.title} 列编辑`);
    },
`

**Comment by lmc19860810** [comment]
editActivedEvent ({ row ,column}) {
      console.log(row.er_subject);
      console.log(row)
      console.log("abc")
      let er_sub=row.er_subject.split(',')
      console.log(`${JSON.stringify(column)}`)
      row.er_subject=er_sub
    },




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清霆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 上午10:41
收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"一行代码㎥"<6334497@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuliangzhan/vxe-table] vxe+element-ui，编辑模式，点击无效 (#696)



 
editActivedEvent 在这个事件中赋值。你试下。
  
赋值？我直接复制的样例代码
  editActivedEvent({ row, column }, event) { console.log(row); console.log(column); console.log(打开 ${column.title} 列编辑`);
 },
 editClosedEvent({ row, column }, event) {   console.log(row);   console.log(column);   console.log(`关闭 ${column.title} 列编辑`); },  
`

**Comment by PineSongCN** [comment]
> editActivedEvent ({ row ,column}) { console.log(row.er_subject); console.log(row) console.log("abc") let er_sub=row.er_subject.split(',') console.log(`${JSON.stringify(column)}`) row.er_subject=er_sub },
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月5日(星期四) 上午10:41 收件人:&nbsp;"xuliangzhan/vxe-table"<vxe-table@noreply.github.com&gt;; 抄送:&nbsp;"一行代码㎥"<6334497@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [xuliangzhan/vxe-table] vxe+element-ui，编辑模式，点击无效 (#696) editActivedEvent 在这个事件中赋值。你试下。 赋值？我直接复制的样例代码 editActivedEvent({ row, column }, event) { console.log(row); console.log(column); console.log(打开 ${column.title} 列编辑`); }, editClosedEvent({ row, column }, event) { console.log(row); console.log(column); console.log(`关闭 ${column.title} 列编辑`); }, ` — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，等会试一试

**Comment by PineSongCN** [comment]
> editActivedEvent 在这个事件中赋值。你试下。
你好，row.er_subject 为undefined
![image](https://user-images.githubusercontent.com/39976617/76009622-7a2acd00-5f4c-11ea-8666-9f2199800032.png)

**Comment by lmc19860810** [comment]
er_subject 这个字段是你自己的绑定字段。

**Comment by PineSongCN** [comment]
> er_subject 这个字段是你自己的绑定字段。

不好意思，没理解，【row.er_subject.split(',')】的作用是什么？

**Comment by PineSongCN** [comment]
> er_subject 这个字段是你自己的绑定字段。
你好，数字不支持split会直接报错，字符串不报错，但还是空
![image](https://user-images.githubusercontent.com/39976617/76054659-5ac38c80-5fac-11ea-9b9f-9033a0525db6.png)
