### ISSUE TITLE
为实现更简单的自定义列位置和宽度提出新需求特性

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#70]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
我需要的功能：
1）列拖动（列可以前后拖动）并且有对应的事件触发
2）列宽拖动有对应的事件触发
我的项目使用表格较多，而且一个表格的字段也特别多，那么一个屏幕可能放不下，不同的角色可能想优先显示不同的字段。这些新特性如果实现可以很方便的自定义列的前后顺序和宽度。
当然在现有功能下，也是可以通过其他方法实现这种需求的，只是我觉得添加了这2个新特性，可能实现起来更方便、容易

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
1）列拖动（列可以前后拖动）并且有对应的事件触发
2）列宽拖动有对应的事件触发

**是否有不错的替代方案 Describe alternatives you've considered**
可以参考 `ag-grid` 中的 `columnResized`、`columnMoved` 等事件

**Comment by xuliangzhan** [comment]
这种功能不需要重复造轮子，现有的库就可以支持 [demo](https://xuliangzhan.github.io/vxe-table/#/table/other/sortableColumn)

**Comment by fooleap** [comment]
目前有个需求，需要存储表格的状态，包括手动拖动列宽后的存储，需要获取拖动后的列宽。
@xuliangzhan 链接是列拖动的 Demo，vxe-table 可否提供列宽发生变化的事件？

**Comment by xuliangzhan** [comment]
v1.9+ 可以支持该事件了
