### ISSUE TITLE
设置了 align=center  checkbox的居中有偏差

### ISSUE THREAD

**Issue by DoveAz** [xuliangzhan/vxe-table#703]
### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/15158280/76375672-5bc83580-6381-11ea-8cb9-21df21780429.png)

### （必填）请填写期望的结果 Expected behavior

 正常显示

### （必填）请填写版本号 Version

- os: win 10
- browser: chrome latest
- vue: latest
- vxe-table: latest

**Comment by xuliangzhan** [comment]
建议更新到最新版本
