### ISSUE TITLE
在Type Script文件中使用vxe-table保错

### ISSUE THREAD

**Issue by nttd-haohe** [xuliangzhan/vxe-table#721]
### （必填）请填写问题描述 Describe

在Type Script文件中使用vxe-table保错

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link

暂时未提供

### 请填写报错信息或截图 Error message or screenshots
在TS代码中使用如下写法时：
this.$refs.xTable.reloadData(this.rirekiList);
报错：
Property '**reloadData**' does not exist on type 'Element | Element\[\] | Vue | Vue\[\]'. Property '**reloadData**' does not exist on type 'Element'.

Ts进行了类型检查，请问是否提供了types，可以直接安装，解决Ts代码不能识别类型的问题？
谢谢。

### （必填）请填写版本号 Version

- os: windows10
- browser: IE11
- vue: 2.6.11
- vxe-table: 2.8.18

**Comment by unhappy224** [comment]
这个不能识别不是vxe-table的问题，是vue和ts的问题，ts并不知道 ref 代表的是什么，甚至不知道是组件还是html元素，所以要做一个强制转换，也是vue的局限性。
应该用(( this.$refs.xTable as any) as Table).reloadData()  或者试试 (( this.$refs.xTable as Vue) as Table).reloadData()

**Comment by xlz26296** [comment]
可以通过声明 [ref](https://github.com/vuejs/vue-class-component/issues/94) 解决
```javascript
import { Table } from 'vxe-table'
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class MyTable extends Vue {
  $refs!: {
    xTable: Table;
  }
  data () {
    return {
      tableData: []
    }
  }
  savsEvent () {
    const selectRecords = this.$refs.xTable.getCheckboxRecords()
    console.log(selectRecords )
  }
}
```

**Comment by nttd-haohe** [comment]
@xlz26296 @xuliangzhan 
现在2.8.18版本中的Table定义还没有reloadData的方法定义，注意到以下代码已经更新，应该会release到下一个版本中吧？
[代码](https://github.com/xuliangzhan/vxe-table/blob/a3d8f24f21c23d8129ebb3a2eeb86a30870f633c/types/table.d.ts#L141)

**Comment by xlz26296** [comment]
你可以更新到 2.8.28+

**Comment by nttd-haohe** [comment]
升级最新版后已经找到定义的类型。已解决，谢谢各位的帮助。谢谢。
