### ISSUE TITLE
在同时设定固定列与show-overflow的时候，会出现表格内容的行高与固定列的行高不一致的情况。

### ISSUE THREAD

**Issue by nekorrrr** [xuliangzhan/vxe-table#724]
### （必填）请填写问题描述 Describe the bug
在同时设定固定列与show-overflow的时候，会出现表格内容的行高与固定列的行高不一致的情况。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/em6wnz20/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit)） Reproduction link
http://jsrun.pro/sUfKp/edit

### 填写报错信息或截图 Error message or screenshots
![image](https://user-images.githubusercontent.com/45645775/76951799-34580680-6947-11ea-8a25-94d4f00f6cc1.png)

### （必填）请填写期望的结果 Expected behavior
表格行高与固定列行高一致

### （必填）请填写版本号 Version

- os: windows 10 production 1909
- browser: firfox 74.0 X64
- vue: v2.6.11
- vxe-table: v2.8.28

**Comment by xlz26296** [comment]
启用 [虚拟滚动](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/bad/lineHeight) 或者设置 show-overflow，那么自定义模板中的所有兼容性都应该自行处理
