### ISSUE TITLE
希望支持表格排序的自定义轮转

### ISSUE THREAD

**Issue by wupeiwen233** [xuliangzhan/vxe-table#725]
### （必填）这个需求解决了什么问题 What problem does this feature solve

 大部分场景下 希望用户点击表头排序第一次为降序

### （必填）建议的 API 是什么样的 What does the proposed API look like

![image](https://user-images.githubusercontent.com/27689773/77054328-a180a000-6a0a-11ea-8056-ddaad114d30d.png)

### 是否已有其他不错的替代方案 Describe alternatives you've considered

 无

**Comment by xuliangzhan** [comment]
具体可以参考文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/sort
