### ISSUE TITLE
vxe-grid slots 紧急bug

### ISSUE THREAD

**Issue by wQueryLoveMm** [xuliangzhan/vxe-table#729]
### （必填）请填写问题描述 Describe the bug
vxe-grid 内部数据无法实时更新，我看了下源码是由于，
`packages/grid/src/grid.js`
toolbarSlots 用的是 `computed` 属性，这样无法获取实时的slots.
希望改成 `methods` 动态获取。

### （必填）请填写能重现问题的链接
[重现](https://codesandbox.io/s/vxe-table-ceshide-demo-duq8k)

### 填写报错信息或截图 Error message or screenshots

 [重现](https://codesandbox.io/s/vxe-table-ceshide-demo-duq8k)

### （必填）请填写期望的结果 Expected behavior
 所有computed 获取的slots 都要动态获取
### （必填）请填写版本号 Version

- os: macos 10.14.4
- browser: chrome
- vue: 2.6.11
- vxe-table: 2.8.13

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试

**Comment by wQueryLoveMm** [comment]
ok了，我看到你修复了. 辛苦啦 -v-。
