### ISSUE TITLE
给一个空数据源添加一行时，setActiveCell方法报错

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#75]
**问题描述 Describe the bug**

开始时源数据为空goodsList:[]，mounted后给它插入一条数据this.goodsList.push({'bar_code':xxx,'id':xxx}，然后对它进行setActiveCell时报错如下图：
![image](https://user-images.githubusercontent.com/6631168/59691606-8ebf0d80-91e3-11e9-92c7-92fc515aefa7.png)
![image](https://user-images.githubusercontent.com/6631168/59691660-a5656480-91e3-11e9-869a-2e3b1e0fbdeb.png)

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by 1057437122** [comment]
嗯，看到了更新了～感谢修复
