### ISSUE TITLE
vxe-radio style on firefox

### ISSUE THREAD

**Issue by Tlopasha** [xuliangzhan/vxe-table#751]
### （必填）请填写问题描述 Describe the bug
style of vxe-radio on the firefox is not correct

### 填写报错信息或截图 Error message or screenshots
![vxe-radio](https://user-images.githubusercontent.com/9284752/78013633-0c08d880-7347-11ea-8ac2-db0c5c0e5244.PNG)

### （必填）请填写期望的结果 Expected behavior

display correctly
 

### （必填）请填写版本号 Version

- os: windows10
- browser: firefox 74.0 (64-Bit)
- vue: ^2.5.17
- vxe-table: ^2.8.33

**Comment by xuliangzhan** [comment]
The problem was fix in v2.9+
