### ISSUE TITLE
vxe-grid 开启编辑后，使用clearActived结束编辑无效（报错）

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#76]
**问题描述 Describe the bug**
vxe-grid 开启编辑后，使用 `clearActived` 结束编辑无效（报错）

**重现问题的步骤 To Reproduce**
在控制台打印了 `this.$refs.xTable` 下的属性，没有找到 `clearActived` ，而是找到了 `clearActivedd`，但使用这个属性也无法退出编辑。

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: 1.2.4

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by maxmeng93** [comment]
升级后可以了
