### ISSUE TITLE
表格导出功能 表头有分组时不能完全导出 可能是BUG

### ISSUE THREAD

**Issue by joker-jrz** [xuliangzhan/vxe-table#762]
### （必填）请填写问题描述 Describe

 表格导出功能 表头有分组时表头缺失 表格导出插件也有同样问题

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-tablebiaogedaochugongnengwenti-w864d?file=/src/components/HelloWorld.vue

### 请填写报错信息或截图 Error message or screenshots

https://codesandbox.io/s/vxe-tablebiaogedaochugongnengwenti-w864d?file=/src/components/HelloWorld.vue

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: 2.6.11
- vxe-table: 2.9.0

**Comment by xuliangzhan** [comment]
目前是不支持分组表头导出的

**Comment by joker-jrz** [comment]
好的 谢谢

**Comment by xuliangzhan** [comment]
分组表头会在 3.0+ 中支持

**Comment by joker-jrz** [comment]
谢谢
