### ISSUE TITLE
通过 setCheckboxRow 勾选中的行，在 clearCheckboxRow 清除后。再更新表格的data，之前勾选中的选项会被重新选中

### ISSUE THREAD

**Issue by John60676** [xuliangzhan/vxe-table#763]
### （必填）请填写问题描述 Describe the bug

通过 setCheckboxRow 勾选中的行，在 clearCheckboxRow 清除后。再更新表格的data，之前勾选中的选项会被重新选中。  checkbox-config 的 reserve 是开启状态的

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-v2hwf

### 填写报错信息或截图 Error message or screenshots

 
![vxe-table--bug](https://user-images.githubusercontent.com/21698973/78762825-f9ca1280-79b6-11ea-95f9-560a6cea4ab8.gif)

### （必填）请填写期望的结果 Expected behavior

期望结果，通过current-change，去勾选当前的行，且同时仅能选中一个。在表格数据更新后，保持更新前选中的那行依旧是选中状态

### （必填）请填写版本号 Version

- os: macOS 10.15.3
- browser:  chrome  80.0.3987.149
- vue: 2.6.10
- vxe-table: 2.8.23

**Comment by xuliangzhan** [comment]
checkbox-config.reserve 清除的唯一途径是调用 clearCheckboxReserve() 方法

**Comment by John60676** [comment]
@xuliangzhan 感谢，问题解决了。但是就是有点疑惑，我行数据是通过 setCheckboxRow 来选中的，清除也是理应该用 clearCheckboxRow。但是这个 reserve(保留选中)应该是属于表格的内部状态吧，是不是 clearCheckboxRow 也能够同步清除这个状态才合理呢

**Comment by xuliangzhan** [comment]
是应该要保持一致行为，后续版本会修复
