### ISSUE TITLE
缺失 updateToolbarCustom 方法

### ISSUE THREAD

**Issue by John60676** [xuliangzhan/vxe-table#765]
### （必填）请填写问题描述 Describe the bug

 showColumn、hideColumn、resetColumn 这三个方法调用时都会报错，提示 updateToolbarCustom 不存在。查了一下，应该是npm安装的版本里面没有 updateToolbarCustom 这个方法

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-twm7l?file=/src/views/Demo1.vue

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/21698973/78850512-ffbd0380-7a49-11ea-824e-ae2e6b7a592e.png)

### （必填）请填写期望的结果 Expected behavior

 showColumn、hideColumn、resetColumn 正常调用

### （必填）请填写版本号 Version

- os: macOS 10.15.3
- browser: chrome 80.0.3987.149
- vue: 2.6.10
- vxe-table: 2.9.0

**Comment by John60676** [comment]
测试了一下，这个问题应该是从 2.9.0-beta.0 开始的

**Comment by xuliangzhan** [comment]
该问题会在下版本修复

**Comment by John60676** [comment]
已解决
