### ISSUE TITLE
vue-element-extends 能平滑升级到 vxe-table 吗

### ISSUE THREAD

**Issue by SundayCoding** [xuliangzhan/vxe-table#77]
看了vxe-table文档已经示例，有点见异思迁，
vue-element-extends做了一些动态列封装，不确定和vxe-table api 是否一样

**Comment by xuliangzhan** [comment]
这是完全不一样的两个表格，如果需要用到 vxe-table 的功能你可以逐步替换，换掉的要改的东西还是挺多的，如果 vue-element-extends 能满足需求建议是没必要全换 哈
