### ISSUE TITLE
请问vxe 有获取当前列数据的方法吗

### ISSUE THREAD

**Issue by haoyanhong** [xuliangzhan/vxe-table#775]
### （必填）请填写问题描述 Describe

 ?请问vxe 有获取当前列数据的方法吗，我在api中看到获取行数据暴露了对应的方法，没有找到获取列数据对应的方法
![image](https://user-images.githubusercontent.com/31054039/79205814-03e58880-7e71-11ea-9710-bfa6631b798d.png)
我现在想要获取当前高亮列的数据遇到了困难，
### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 ?

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by SLA0630** [comment]
请问一下您怎么解决的？
