### ISSUE TITLE
调用表单validate方法验证时，验证提示位置偏移

### ISSUE THREAD

**Issue by Gumplefik** [xuliangzhan/vxe-table#78]
**问题描述 Describe the bug**
调用表单validate验证表单后，提示消息位置偏移

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

![{9862922B-424A-4DAB-8F64-650EFB37A850}_20190619163002](https://user-images.githubusercontent.com/19474332/59749534-c5625a00-92af-11e9-89d1-ba909610aa4b.jpg)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
建议更新到最新看下

**Comment by Gumplefik** [comment]
![{DF2F612D-86E3-4DEC-B4A4-6CE6D094C810}_20190620144211](https://user-images.githubusercontent.com/19474332/59826844-b17b2e80-9369-11e9-9f6e-3fd27f28fc92.jpg)
一样的，最新的1.3.3，这个组件是子组件

**Comment by Gumplefik** [comment]
已解决，上述应该时页面没刷新导致的问题

**Comment by Gumplefik** [comment]
刚才有测试了一下，发现你这个提示没有追随目标，即验证后提示消息，滑动滚动条，提示消息还是在原来的位置，如果滚动了屏幕，那么提示应当消失或者继续追随目标

**Comment by xuliangzhan** [comment]
你应该检查下是否在 fixed 布局中使用
