### ISSUE TITLE
调用表单的validate时应返回所有的验证消息

### ISSUE THREAD

**Issue by Gumplefik** [xuliangzhan/vxe-table#79]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
调用表单的validate后，validate返回的第二个参数obj只有第一个验证失败的message，实际上应该返回所有数据的验证失败的消息，这样可以避免输入一个验证失败的值，点击后又提示验证失败，输入下一个，不断如此
![{5C0429CA-67F8-44A7-ADBD-24AF68B3FD9A}_20190619170246](https://user-images.githubusercontent.com/19474332/59751990-15dbb680-92b4-11e9-9b9d-a8582038898a.jpg)
设计上预期一次可以指出所有的错误地点，而不是完成一个输入再验证在输入

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
当数据较多时，完整的验证耗时较久，适用的场景有限；但也可以考虑支持该功能

**Comment by Gumplefik** [comment]
好的，麻烦了
