### ISSUE TITLE
建议把toolbar的resizable，custom 移table 一级，因为如果想用这个几个设置就必须要配置toolbar

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#791]
### 请填写问题描述 Describe
建议把toolbar的resizable，custom 移table 一级，因为如果想用这个两个设置就必须要配置toolbar
，有时候不想要toolbar 
![image](https://user-images.githubusercontent.com/4531974/79737847-81583f80-832e-11ea-9b80-aad200806d27.png)

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
是的，这功能和工具栏没关系，该需求后续版本会支持

**Comment by jianliulin** [comment]
谢谢！！
