### ISSUE TITLE
在配置 toolbar的时候 遇到文档未提及报错

### ISSUE THREAD

**Issue by ARencn** [xuliangzhan/vxe-table#798]
### （必填）请填写问题描述 Describe the bug
        在配置  export  = true 后 点击 按钮 ，会报错 
        缺少必要的 "export-config" 参数，这可能会导致出现错误 
        但是文档中 并没有提及如何去配置 export-config
       并且文档的在线运行中 也报这个错
 

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/I8WKp/edit
 

### 填写报错信息或截图 Error message or screenshots

 [vxe-table] 缺少必要的 "export-config" 参数，这可能会导致出现错误

### （必填）请填写期望的结果 Expected behavior

 希望尽快完善 文档 的内容 ，有很多内容并未完全收录入 api文档 ，查阅 的时候就只能去实例中查找，
如  toolbar中的 storage  在文档中未提及 实例中却有 ，十分之多 ，不一一列举了

### （必填）请填写版本号 Version

- os: macOS Mojave
- browser: Google Chrome 81.0.4044.113
- vue: ^2.6.10
- vxe-table: ^2.9.1

**Comment by xlz26296** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/exportPDF
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=export-config
