### ISSUE TITLE
filter 过滤。remote-sort，remote-filter等属性不应该在column中，而应该在table中。

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#80]
filter 过滤。不应该在column中，而应该在table中。我在修改文件中table.js中的
// 确认筛选 
confirmFilterEvent: function confirmFilterEvent(evnt) {
。。。。。
  if (!this.remoteFilter) {
          this.tableData = this.getTableData(true).tableData;
        }

        _tools.UtilTools.emitEvent(this, 'filter-change', [{
          remoteFilter:this.remoteFilter,
          column: column,
          prop: column.property,
          values: valueList
        }]);
}
这段代码中 _tools.UtilTools.emitEvent 不知道跳到哪去了。

在grid.js 中filterChangeEvent没有执行。

**Comment by xuliangzhan** [comment]
不知道你要实现什么，无法给你建议

**Comment by longa30** [comment]
使用服务器过滤时应当将所有列过滤的值传到服务器，而不是仅当前列的值。我贴上这段代码时希望更改但是找不到跳到哪去了。

**Comment by xuliangzhan** [comment]
这个问题会在 v1.5.0+ 修复
