### ISSUE TITLE
用open（）打开modal ，modal中的vxe-input初始化值不显示，选不了月份。

### ISSUE THREAD

**Issue by jianliulin** [xuliangzhan/vxe-table#807]
### 请填写问题描述 Describe

用open（）打开modal ，modal中的vxe-input初始化值不显示，选不了月份，请问是否是我哪里没做对。
http://jsrun.net/9ffKp/edit
![image](https://user-images.githubusercontent.com/4531974/80677048-b6148580-8aea-11ea-95fe-3d04e8ee3e63.png)

### 请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: ?

**Comment by xuliangzhan** [comment]
第50行属性写错了吧，项目中最好使用 jsx 
http://jsrun.net/2X2Kp/edit

**Comment by jianliulin** [comment]
把value放在props我也试过，选择新日期后，input ，change 事件都能抓到新值，可input中的值还是保持不变，重新赋值props.vaue也不行。

**Comment by xuliangzhan** [comment]
因为你用的是动态变量，并非 vue 的属性，vue 是无法监听自动更新的
http://jsrun.net/2X2Kp/edit

**Comment by jianliulin** [comment]
谢谢！！！
