### ISSUE TITLE
添加新的筛选功能

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#81]
我这个初学者太费劲了
![image](https://user-images.githubusercontent.com/17867961/59811673-85e24f00-933d-11e9-9fc5-2705c51d6d13.png)

**Comment by xuliangzhan** [comment]
这个使用[渲染器](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/advanced)就可以很容易实现了
或者使用最新的 [vxe-table-plugin-element](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/plugin/elementFilter) 也可以支持
