### ISSUE TITLE
“overflow 展示 tooltip” 不能检测到更深层的元素的 overflow

### ISSUE THREAD

**Issue by yft** [xuliangzhan/vxe-table#811]
### （必填）请填写问题描述 Describe the bug

当单元格渲染较为复杂时，设置overflow=”tooltip“无效

### （必填）请填写能重现问题的链接

[问题](https://codepen.io/yft/pen/zYvRjXM)

### 填写报错信息或截图 Error message or screenshots

无

### （必填）请填写期望的结果 Expected behavior

[类似于这样的效果](https://codepen.io/yft/pen/ExVQLzG)

### （必填）请填写版本号 Version

- os & browser: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36`
- vue: 2.6.11
- vxe-table: 2.9.2

**Comment by xuliangzhan** [comment]
因为用了自定义模板，那么所有逻辑就交给开发去自定义处理，你可以配合 [contentMethod](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/tooltip) 方法去获取自定义提示信息

**Comment by yft** [comment]
按照示例，发现并没有出现提示，不知道是什么原因？

http://jsrun.net/Rv2Kp

**Comment by yft** [comment]
> 按照示例，发现并没有出现提示，不知道是什么原因？
> 
> http://jsrun.net/Rv2Kp

再次打开，发现可以了，不知道之前为什么不可以ﾉ)ﾟДﾟ(

**Comment by yft** [comment]
关于这个问题，可以通过自己实现tooltip，关于内容是否有超出，可以用 `el.scrollWidth - el.offsetWidth` 进行判断。

```html
<el-popover
  v-if="showPopover"
  ref="popover"
  placement="bottom-start"
  :append-to-body="false"
>
	<p v-html="popoverContent"></p>
</el-popover>
```

```js
handleOverflowTooltip(cellChild) {
  this.closePopover();
  if (cellChild && cellChild.scrollWidth > cellChild.offsetWidth) {
    this.showPopover = false;
    this.$nextTick(function() {
      this.showPopover = true;
      this.$nextTick(function() {
        let popover = this.$refs.popover;
        this.popoverContent = cellChild.innerHTML;
        popover.$refs.reference = cellChild;
        popover.doShow();
      });
    });
  }
}
closePopover() {
	try {
		this.$refs.popover.doClose();
	} catch(e) {}
}
```
