### ISSUE TITLE
modal 内容是自定义的组件的时候 ，无法自适应modal的高度

### ISSUE THREAD

**Issue by huoshidehua** [xuliangzhan/vxe-table#815]
### （必填）请填写问题描述 Describe

modal 内容是自定义的组件的时候 ，无法自适应modal的高度 ?

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 https://codesandbox.io/s/vxe-table-ceshide-demo-6mlv0

### 请填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/8519297/81461306-d5e03380-91e5-11ea-894a-f446fcea9dd2.png)
![image](https://user-images.githubusercontent.com/8519297/81461318-e0023200-91e5-11ea-8aef-d395bb1fb514.png)
左图是官网的例子底下两条线说明有自适应，右侧是连接中的例子底下没有出现两条线说明没有自适应modal高度，这有办法解决吗？

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6+
- vxe-table: 2.9.5+

**Comment by xuliangzhan** [comment]
你既然要用这么多 div，那么就应该处理好相关的样式
https://codesandbox.io/s/vxe-table-ceshide-demo-z6k5x

**Comment by huoshidehua** [comment]
> 你既然要用这么多 div，那么就应该处理好相关的样式
> https://codesandbox.io/s/vxe-table-ceshide-demo-z6k5x

我在这个基础上 给 grid 加上了 form slot 结果就这样了
https://codesandbox.io/s/vxe-table-ceshide-demo-shv2q?file=/src/views/TableTest.vue
还有的救吗 大佬
![image](https://user-images.githubusercontent.com/8519297/81474928-a3652380-9243-11ea-9736-012220d794d6.png)

**Comment by xuliangzhan** [comment]
最新版应该救得了你
 https://codesandbox.io/s/vxe-table-ceshide-demo-ii0e0?file=/src/views/Demo1.vue
