### ISSUE TITLE
treeConfig 和 checkbox 混用时，父级行禁用的情况下，全选框会显示勾选状态

### ISSUE THREAD

**Issue by John60676** [xuliangzhan/vxe-table#817]
### （必填）请填写问题描述 Describe the bug

treeConfig 和 checkbox 混用时，父级行禁用的情况下，全选框会显示勾选状态。

_（附加）而且子级选中的情况下，父级也会被同时选中（这个问题不知道算不算BUG，但是我这边有这样的业务😂只选择子级，父级的数据不需要。目前是通过选中之后再把父级的数据给过滤掉）_

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://codesandbox.io/s/vxe-table-ceshide-demo-u9tgj

### 填写报错信息或截图 Error message or screenshots
 
![image](https://user-images.githubusercontent.com/21698973/81517853-bf191880-936e-11ea-8acd-63b6f87952cf.png)

![image](https://user-images.githubusercontent.com/21698973/81517959-18814780-936f-11ea-9dca-a9e9a0473f29.png)

### （必填）请填写期望的结果 Expected behavior

 父级行禁用的情况下，全选框不显示勾选状态。

### （必填）请填写版本号 Version

- os: macOS 10.15.3
- browser: chrome 80.0.3987.149
- vue: 2.6.10
- vxe-table: 2.9.6

**Comment by xlz26296** [comment]
那你把父子关联取消就行了
https://codesandbox.io/s/vxe-table-ceshide-demo-e24k6

**Comment by John60676** [comment]
@xlz26296  重点都不是tree-config这个问题。现实场景是：表格是分页表格，在某一页中全部行都不能选，这时候全选按钮就会勾上

**Comment by xlz26296** [comment]
> @xlz26296 重点都不是tree-config这个问题。现实场景是：表格是分页表格，在某一页中全部行都不能选，这时候全选按钮就会勾上

为啥不看文档 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/selection

**Comment by John60676** [comment]
如果认为这个“默认行为”是没问题的，那我只好关闭这个issue了

**Comment by ginkosen** [comment]
同样的bug，(https://github.com/x-extends/vxe-table/issues/2048)](https://github.com/x-extends/vxe-table/issues/2048)

目前只能使用checkbox-config下的visibleMethod或checkStrictly:true解决
