### ISSUE TITLE
CheckBox 在表格数据更新后，会被重新选中

### ISSUE THREAD

**Issue by John60676** [xuliangzhan/vxe-table#818]
### （必填）请填写问题描述 Describe the bug

 表格传入了row-id的情况下，先选中CheckBox，然后更新表格的数据，接着再把刚刚选中的CheckBox取消选中，此时再更新表格数据时，之前被选中的CheckBox会重新被选中

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 https://codesandbox.io/s/vxe-table-ceshide-demo-n5um2

### 填写报错信息或截图 Error message or screenshots

![Kapture 2020-05-11 at 10 34 27](https://user-images.githubusercontent.com/21698973/81519220-1325fc00-9373-11ea-9990-087186951409.gif)

### （必填）请填写期望的结果 Expected behavior

 CheckBox的选中状态能符合预期结果

### （必填）请填写版本号 Version

- os: macOS 10.15.3
- browser: chrome 80.0.3987.149
- vue: 2.6.10
- vxe-table: 2.9.6

**Comment by xuliangzhan** [comment]
该问题会在 2.9.7+ 修复 https://codesandbox.io/s/vxe-table-ceshide-demo-o9f2u
