### ISSUE TITLE
v-for="(config, index) in tableColumn"切换表格显示 动态设置 tableColumn 部分字段无法渲染

### ISSUE THREAD

**Issue by Amazingman1** [xuliangzhan/vxe-table#821]
### （必填）请填写问题描述 Describe

 `    <vxe-table
      ref="xTable"
      border="inner"
      highlight-hover-row
      highlight-current-row
      height="600"
      :data="listData"
    >
      <vxe-table-column v-for="(config, index) in tableColumn" :key="index" v-bind="config" />
    </vxe-table>`多个表格切换显示，tableColumn 动态设置，在切换的时候 部分字段不显示，字段不固定
### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 Reproduction link

### 请填写报错信息或截图 Error message or screenshots

 ?

### （必填）请填写版本号 Version

- os: mac os
- browser: chrome
- vue: 2.6.10
- vxe-table: 2.9.6

**Comment by Amazingman1** [comment]
第一次 tableColumn 如果有两条数据，在切换到5条数据时，5条数据的前两条的title会渲染，但是field不会渲染，

**Comment by Amazingman1** [comment]
`
    <vxe-table
      v-if="update"
      ref="xTable"
      border="inner"
      highlight-hover-row
      highlight-current-row
      height="600"
      :data="listData"
    >
      <vxe-table-column v-for="(config, index) in tableColumn" :key="index" v-bind="config" />
    </vxe-table>
`
用v-if做了一次强制刷新暂时解决。

**Comment by FugitiveLc** [comment]
感谢 使用v-if解决了
