### ISSUE TITLE
更新后筛选功能失效了

### ISSUE THREAD

**Issue by Leslie-vcc** [xuliangzhan/vxe-table#83]
**问题描述 Describe the bug**
更新后筛选功能失效了

**重现问题的步骤 To Reproduce**
点击filter按钮没有下拉

**请提供能重现问题的链接 
文档的demo可直接测 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/filter

**Comment by xuliangzhan** [comment]
建议更新到最新试下

**Comment by Leslie-vcc** [comment]
> 建议更新到最新试下

1.4.2 版本下测试，bug已修复
