### ISSUE TITLE
vxe-grid 使用 columns 配置列，slots 插槽的edit无效

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#84]
**问题描述 Describe the bug**
vxe-grid 使用 columns 配置列，slots 插槽的edit无效

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: 1.3.2

**Comment by xuliangzhan** [comment]
请提供能重现问题的链接

**Comment by maxmeng93** [comment]
``` javascript
const columns = [
  {label: '类型', prop: 'type', editRender: { name: 'AInput' }},
  {
    label: '名字',
    prop: 'name',
    slots: {
       default: () => {
           return '555';
        },
        header: () => {
           return '+++';
        },
        edit: () => {
           return [
              <a-input />
            ];
        }
    }
  }
];
```
使用 `setActiveRow` 方法开启编辑后，类型那一个单元格出现了输入框，但是名字那一栏没有出现输入框

**Comment by maxmeng93** [comment]
> ```js
> const columns = [
>   {label: '类型', prop: 'type', editRender: { name: 'AInput' }},
>   {
>     label: '名字',
>     prop: 'name',
>     slots: {
>        default: () => {
>            return '555';
>         },
>         header: () => {
>            return '+++';
>         },
>         edit: () => {
>            return [
>               <a-input />
>             ];
>         }
>     }
>   }
> ];
> ```
> 
> 使用 `setActiveRow` 方法开启编辑后，类型那一个单元格出现了输入框，但是名字那一栏没有出现输入框

不知道是不是 edit 那里写法有问题，一些在线编辑器在报错

**Comment by xuliangzhan** [comment]
你都没有开启[编辑列](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/template)，editRender
