### ISSUE TITLE
slot:form 的方式 proxy 方法无法关联 form 对象

### ISSUE THREAD

**Issue by huoshidehua** [xuliangzhan/vxe-table#846]
### （必填）请填写问题描述 Describe

slot:form 的方式 proxy 方法无法关联 form 对象 

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

 https://jsrun.net/gc2Kp/edit

### 请填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/8519297/82752241-96296680-9df7-11ea-99dd-c224b558f06a.png)
![image](https://user-images.githubusercontent.com/8519297/82752250-aa6d6380-9df7-11ea-9f71-583cc25f4fcb.png)
点击查询后 发现form 没有关联进来 只能手动调用data中的form
![image](https://user-images.githubusercontent.com/8519297/82752272-da1c6b80-9df7-11ea-95db-ebed61449cd0.png)
![image](https://user-images.githubusercontent.com/8519297/82752288-f91afd80-9df7-11ea-974c-413d1bf80868.png)
此时page 对象有关联到 因为使用的是对象配置的方式 不是使用slot的方式
### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.8

**Comment by xuliangzhan** [comment]
没代理表单哪来关联，自定义模板你就用自定义的对象
https://jsrun.net/6c2Kp/edit

**Comment by huoshidehua** [comment]
> 没 proxy form 哪来关联，如果自定义模板那就用自定义的对象
> https://jsrun.net/6c2Kp/edit

ok 明白了
