### ISSUE TITLE
modal 中使用vxe-form 的时候 span 貌似不是24

### ISSUE THREAD

**Issue by huoshidehua** [xuliangzhan/vxe-table#848]
### （必填）请填写问题描述 Describe

modal 中使用vxe-form 的时候 span 貌似不是24

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

https://jsrun.net/gc2Kp/edit

### 请填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/8519297/82795168-93d61380-9eae-11ea-8f29-5915dfda0b8f.png)
![image](https://user-images.githubusercontent.com/8519297/82795240-ae0ff180-9eae-11ea-85d1-8f485dc8f938.png)

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.8

**Comment by xuliangzhan** [comment]
该问题会在 2.9.10+ 修复
https://jsrun.net/3d2Kp/edit

**Comment by huoshidehua** [comment]
> 该问题会在 2.9.10+ 修复
> https://jsrun.net/3d2Kp/edit

好的 多谢
