### ISSUE TITLE
vxe-grid 如何结合 Ant-Design-vue 的AForm 和 FormItem 组件做表格验证

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#85]
**问题描述 Describe the bug**
vxe-grid 如何结合 Ant-Design-vue 的AForm 和 FormItem 组件做表格验证

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
表格的校验方法是 [validate](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=validate) 这个，和任何组件都没关系，需要校验的时候调用就行

**Comment by maxmeng93** [comment]
我想做的是输入框输入内容与验证规则不匹配时，可以自动弹出错误提示，或者边框变为红色等。但是如果用了其他UI框架的组件，就没有这些了

**Comment by xuliangzhan** [comment]
这个没看出和表格有什么关系？
