### ISSUE TITLE
修改了源数据页面表格没有同步刷新展示

### ISSUE THREAD

**Issue by 1057437122** [xuliangzhan/vxe-table#86]
current_edited_row是原来的数据，row是选择的上面弹出的dialog的数据，可以看到源数据中有current_edited_row的index，
![image](https://user-images.githubusercontent.com/6631168/59834606-8d5b2580-9348-11e9-9488-d4623855d157.png)
替换前后的值，是正确的
![image](https://user-images.githubusercontent.com/6631168/59835284-a912fb80-9349-11e9-8f90-956b361d8a6c.png)
结束后页面没有刷新，也没有跳到对应的单元格
![image](https://user-images.githubusercontent.com/6631168/59835313-b29c6380-9349-11e9-92f6-1b3705a3875a.png)

**Comment by 1057437122** [comment]
改成这样调了一下就可以了
![image](https://user-images.githubusercontent.com/6631168/59842082-08770880-9356-11e9-8d81-9c2faaf52f32.png)
应该是VUE的问题吧？

**Comment by xuliangzhan** [comment]
https://cn.vuejs.org/v2/guide/list.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
