### ISSUE TITLE
希望能有主动使表格获得焦点的方法

### ISSUE THREAD

**Issue by xiaofan007** [xuliangzhan/vxe-table#861]
### （必填）这个需求解决了什么问题 What problem does this feature solve
现在通过 .setCurrentRow() 选中之后，并没有使表格获得焦点。导致要使用上下按键的话，还是要鼠标点击一下表格才能生效。

### （必填）请填写问题链接来描述为什么无法实现该功能，例如

[codepen](https://codepen.io/xiaofan007/pen/xxwoJVB?__cf_chl_jschl_tk__=126b06a32a044819c83b2abb2b79a42cf92691a6-1590740719-0-AdFn2g1IJBcxIAlAnltTsV0wwVLUv8vQCx1SBdrGkdx_VtDAvm3GMT47pHlrfON0Ct_lu5RGCtmfWb-THgH-zNponPVqLRW0lu5psRfsl-pJqBMjvB3o2FcaS57GvgaKVW_9bpGglV7t9d5if2HyWzpsEDstPiLPuPUJ9U22r-mYT2n8wuUguzoW3kquJb65YEVKnQ-QhgzGPlywT-gXahegiu6Ifd4luwTHHxryyLDGSiphm2GpqKR7VRUqRY9JeIw0lOpb7RzsdhMsQzUnNKtjw3hg1tnQUBvVfHswXay8_V9LR96NA7KxvHcYZRf0dWNZn35322BTlV23tY0arX_O8D49Fx4jeze5t73vDew4)

### 建议的 API 是什么样的 What does the proposed API look like
 .setTableFocus()
 

### 是否已有其他不错的替代方案 Describe alternatives you've considered
无

**Comment by PythonMaker** [comment]
怎么实现的？

**Comment by xiaofan007** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api

搜索&nbsp;focus()








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x-extends/vxe-table"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 下午2:06
收件人:&nbsp;"x-extends/vxe-table"<vxe-table@noreply.github.com&gt;;
抄送:&nbsp;"电脑爱好者"<1327090102@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [x-extends/vxe-table] 希望能有主动使表格获得焦点的方法 (#861)





 
怎么实现的？
