### ISSUE TITLE
setCurrentRow(row)之后，无法使表格获得焦点。这时候按上下键并不能使表格焦点上下移动，还是要点击一下表格才能实现焦点的上下移动

### ISSUE THREAD

**Issue by xiaofan007** [xuliangzhan/vxe-table#865]
### （必填）请填写问题描述 Describe the bug
首先，表格设置了:keyboard-config="{isArrow: true}"
setCurrentRow(row)之后，无法使表格获得焦点。这时候按上下键并不能使表格焦点上下移动，还是要点击一下表格才能实现焦点的上下移动。

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

[codepen](https://codepen.io/xiaofan007/pen/xxwoJVB?__cf_chl_jschl_tk__=126b06a32a044819c83b2abb2b79a42cf92691a6-1590740719-0-AdFn2g1IJBcxIAlAnltTsV0wwVLUv8vQCx1SBdrGkdx_VtDAvm3GMT47pHlrfON0Ct_lu5RGCtmfWb-THgH-zNponPVqLRW0lu5psRfsl-pJqBMjvB3o2FcaS57GvgaKVW_9bpGglV7t9d5if2HyWzpsEDstPiLPuPUJ9U22r-mYT2n8wuUguzoW3kquJb65YEVKnQ-QhgzGPlywT-gXahegiu6Ifd4luwTHHxryyLDGSiphm2GpqKR7VRUqRY9JeIw0lOpb7RzsdhMsQzUnNKtjw3hg1tnQUBvVfHswXay8_V9LR96NA7KxvHcYZRf0dWNZn35322BTlV23tY0arX_O8D49Fx4jeze5t73vDew4)

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/55171182/83378824-8b309080-a40c-11ea-9ced-148bb5f83585.png)

### （必填）请填写期望的结果 Expected behavior

setCurrentRow之后，可以直接使用键盘的上下键。而不是需要通过手动点击表格一下之后才行。

### （必填）请填写版本号 Version

- os: win10-1909
- browser:  edge 81
- vue: 2.6.10
- vxe-table: 2.9.9

**Comment by xuliangzhan** [comment]
2.9.11+可以支持 focus 方法，建议更新到最新版本试下
https://codepen.io/xuliangzhan/pen/ExPxbBd

**Comment by xiaofan007** [comment]
@xuliangzhan  更新2.9.11之后， focus()方法可用。  老兄辛苦啦~  多谢~
