### ISSUE TITLE
vxe-grid多级表头，当最小级别列名相同时，显示/隐藏列显示重复问题

### ISSUE THREAD

**Issue by zxWendy** [xuliangzhan/vxe-table#87]
![image1](https://user-images.githubusercontent.com/6140203/59908787-c971b180-9440-11e9-8da9-07a3b8559fea.png)

**Comment by xuliangzhan** [comment]
这个你只能自行[实现](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/custom)或者属性名唯一，自带的工具栏不会支持相同属性

**Comment by zxWendy** [comment]
column的property不同可以label相同的，多级表头应该特殊处理下吧，自己实现可以参考哪个例子？

**Comment by xuliangzhan** [comment]
property 必须唯一的，特殊情况只能自己[实现](https://xuliangzhan.github.io/vxe-table/#/table/advanced/custom)了
