### ISSUE TITLE
配置完keyboard-config 后 无法复制单元格 信息比如这里的 “王五”无法复制 而且发现头部也无法复制

### ISSUE THREAD

**Issue by huoshidehua** [xuliangzhan/vxe-table#872]
### （必填）请填写问题描述 Describe
配置完keyboard-config 后 无法复制单元格 信息比如这里的 “王五”无法复制 而且发现头部也无法复制

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/s42Kp/edit

### 请填写报错信息或截图 Error message or screenshots

 
![image](https://user-images.githubusercontent.com/8519297/84001955-9b171a00-a9a2-11ea-9906-5633bc51fadf.png)

### （必填）请填写版本号 Version

- os: win10
- browser: chrome
- vue: 2.6+
- vxe-table: 2.9.11

**Comment by xuliangzhan** [comment]
目前不支持，后续可以考虑支持
