### ISSUE TITLE
列编辑时使用 editRender: {name: 'AInput'} 非常卡，但使用 slots edit  return [<a-input>]很流畅

### ISSUE THREAD

**Issue by maxmeng93** [xuliangzhan/vxe-table#88]
**问题描述 Describe the bug**
列编辑时使用 editRender: {name: 'AInput'} 非常卡，如果输入1-9等9个数字，可能要几秒钟后输入框才会显示一个数字，删除输入框的内容时，也会延迟很久，但使用 slots edit  return [<a-input>]很流畅。
具体请看重现链接demo

**重现问题的步骤 To Reproduce**
主要区别就是编号和名称这两列
``` javascript
const columns = [
        { label: '编号', prop: 'code', editRender: { name: 'AInput' } },
        { label: '名称',
          prop: 'name',
          editRender: {},
          slots: {
            edit: (options) => {
              return [
                <a-input />
              ];
            }
          }
        }
      ];
```

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**
重现链接 https://www.maxmeng.top/vxe-table-example/dist/#/
代码 https://github.com/maxmeng93/vxe-table-example

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: 1.5.1
 - vxe-table-plugin-antd: 1.1.0

**Comment by xuliangzhan** [comment]
建议使用自带原生输入框 editRender: { name: 'input' }   [Vue render 优化](https://xuliangzhan.github.io/vxe-table/#/table/optimize/edit)
使用插槽不卡那是因为你没有绑定值，你如果绑定值照样卡

**Comment by maxmeng93** [comment]
卡成那样肯定是有问题的，完全不能用。插槽在我项目上绑定值了，是不卡的。明天我更新下demo

**Comment by xuliangzhan** [comment]
这个取决于数据量，vue的机制是数组中的任意属性发生改变都会重新执行 render 函数，数据越大，js 执行时间就越久，卡顿就越明显

**Comment by maxmeng93** [comment]
今天我更新依赖后，修改了代码。发现以下问题，[demo还是上面的链接](https://www.maxmeng.top/vxe-table-example/dist/#/)
## 发现 AInput 输入框上的tooltop不会消失。
![123456.png](http://tc.lihail.cn/123456.png)

## 还是 AInput 卡顿问题
这次比较诡异了，在我的实际项目中，是不卡顿的，但是在我给你的demo中却很卡，还是只能输一个字符。demo依赖也是最新的，代码和实际基本相同，只是把无关代码有删减

**Comment by maxmeng93** [comment]
还遇到一种情况，代码如下：
```
const columns = [
    { label: '名称', prop: 'name', editRender: { name: 'AInput' } },
    { label: '别名', prop: 'alias', editRender: { name: 'AInput' } },
]
```
名称列和别名这两列都使用了 AInput，代码完全相同，但名称列不卡，别名列却很卡。
现在我已经都把 AInput 换为 input了，但还是希望能修改这种问题。
AAutoComplete  AInputNumber 这些组件我还没有试过，不过大概率也有这种问题。

**Comment by xuliangzhan** [comment]
AAutoComplete AInputNumber 这个两个一般不会，主要是 input 的 v-model，只有实时修改值的属性才会引发 Vue render 函数频繁执行；其实只要数据量控制好一般还是很流畅的，做好分页；
所有 vue 的列表相关的数据都会这个问题的，除非放弃双向绑定，否则数据量大卡是必然的
这个优化会在 v2.0 会对性能进行重构

**Comment by maxmeng93** [comment]
看看这个问题
鼠标在input上时，hover状态，输入文字，鼠标移出，输入的文字丢失。
但是在输入之前，把鼠标指针移除input框，就不会发生这种情况。
bug在我的项目上，demo上没有发生这种问题。
问题版本：1.5.4
昨天是1.5.3没有这种问题，但是我回退到1.5.3还是有这个问题
![11.gif](http://tc.lihail.cn/11.gif)

**Comment by maxmeng93** [comment]
如果输入时，鼠标不在input上，那么输入是正常的，但是如果输完后，鼠标移入input，文字也会消失
