### ISSUE TITLE
如何替换checkbox控件

### ISSUE THREAD

**Issue by windhuan** [xuliangzhan/vxe-table#883]
### （必填）请填写问题描述 Describe

 表格选中框的checkbox 如何改成其他组件库的checkbox,比如:element的 el-checkbox ?

### （必填）请填写能重现问题的链接

无错误，如描述

### （必填）请填写版本号 Version

- os: win10
- browser: Chrone
- vue: 2.6
- vxe-table: 2.9.11

**Comment by xlz26296** [comment]
很简单啊，连表格也一起替换就行了

**Comment by windhuan** [comment]
> 这么简单都不会啊，把表格换一下就行了

加上了slot 出现2个checkbox
