### ISSUE TITLE
el-tabs下table列宽显示不正常

### ISSUE THREAD

**Issue by akria00** [xuliangzhan/vxe-table#887]
### （必填）请填写问题描述 Describe the bug

el-tabs下table列宽显示不正常

### （必填）请填写能重现问题的链接，例如（[jsfiddle](https://jsfiddle.net/04Ldpsy8/)、[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.pro//vIyKp/edit)） Reproduction link

http://jsrun.net/WbvKp/edit

### 填写报错信息或截图 Error message or screenshots

 在代码中可以看到<el-tab-pane label="附件"> 如果在没有添加lazy的情况下,列宽是显示不正常的, 尝试多次后发现添加lazy或者按F12改变窗口大小, 列宽才自动撑开

### （必填）请填写期望的结果 Expected behavior

 这种情况我应该怎样修复呢 , 希望有比添加lazy更好的方法

### （必填）请填写版本号 Version

- os: ?
- browser: ?
- vue: ?
- vxe-table: 2.9.11

**Comment by xlz26296** [comment]
表格默认不允许放在隐藏元素中，如果非要的话可以加上响应式属性 [auto-resize](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=auto-resize)

**Comment by akria00** [comment]
> 表格默认不允许放在隐藏元素中，如果非要的话可以加上响应式属性 [auto-resize](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=auto-resize) 或者调用 [recalculate ](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/api?filterName=recalculate)方法重新计算表格

非常感谢
