### ISSUE TITLE
:select-config="{labelProp: 'name', checkMethod}">无法实现多选中某项禁止点击

### ISSUE THREAD

**Issue by kikyou1217** [xuliangzhan/vxe-table#90]
**问题描述 Describe the bug**

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
请提供重现问题的链接或相关代码

**Comment by xyx650** [comment]
不用管他用的0.x版本，已解决 @xuliangzhan
