### ISSUE TITLE
同一页面多表格切换后隐藏列失效

### ISSUE THREAD

**Issue by lkplyl** [xuliangzhan/vxe-table#91]
**问题描述 Describe the bug**
vxe-table使用v-if标签，和同一个页面的其他表格切换显示多次后，表格隐藏列失效

**重现问题的步骤 To Reproduce**
A,B,C三个表格在页面的同一位置显示，通过v-if进行切换，每个表格都配置了唯一的key属性，C表格包含隐藏列，直接A切换到B再切换到C没有问题，但是C切换回A或者B，然后再切换为C时，C的隐藏列就会显示出来

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: 1.5.2

**Comment by xuliangzhan** [comment]
请提供重现问题的链接或相关代码
