### ISSUE TITLE
formatter渲染次数异常

### ISSUE THREAD

**Issue by lkplyl** [xuliangzhan/vxe-table#92]
**问题描述 Describe the bug**
formatter渲染次数不等于数据行数，10条数据渲染了20多次

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（[jsfiddle](https://jsfiddle.net/gz3vektc/)、[codepen](https://codepen.io/anon/pen/gJEmRW)、[jsrun](https://jsrun.net/vIyKp/edit)） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - 浏览器版本: ?
 - vue: ?
 - vxe-table: ?

**Comment by xuliangzhan** [comment]
对于 vue 的渲染机制来说这是正常的，数组或者列表中任意一个数据发生改变，render 都会重新执行，如果不想重复执行，你可以在 row 属性提前格式化好；
这是双向绑定的优点同时也是缺点；

**Comment by lkplyl** [comment]
我有尝试element ui表格的formatter，在不改变数据的前提下，渲染次数与行数是一致的，不过点击数据行时会触发formatter。使用这个表格测试时发现就算不改变数据，渲染次数也远大于数据行数。

**Comment by xuliangzhan** [comment]
理论上是应该这样，目前除了数据源宽度计算的改变也会导致重新渲染，v2.0会重构，移除绝大部分双向绑定

**Comment by lkplyl** [comment]
好的，有时间麻烦也帮忙看下我提的上一个问题
