### ISSUE TITLE
在vex-table中使用v-for来动态渲染vxe-table-column，页面一片空白

### ISSUE THREAD

**Issue by Jack-Haoxuan** [xuliangzhan/vxe-table#93]
因为业务要求，想做一个动态表头的数据表格，便想通过vex-table-column来实现，但发现使用v-for来动态渲染，页面一片空白。经过测试，发现是vex-table-column使用v-for来渲染，会造成渲染失败，也就是没有表头，所以没有数据显示。

使用el-table-column进行v-for渲染是没有问题的，想问各位有什么解决的办法吗？

**Comment by longa30** [comment]
你这个可以使用vxe-grid 网络请求表的列表。实现动态。

**Comment by Jack-Haoxuan** [comment]
> 你这个可以使用vxe-grid网络请求表的列表。实现动态。

vxe-grid 没有 cell-dblclick 事件，只能通过vxe-table实现

**Comment by xuliangzhan** [comment]
vxe-table 用于静态化
vxe-gird 用于动态化，vxe-gird 继承 vxe-table 的所有事件和属性，性能也提高一倍
