### ISSUE TITLE
vxe-grid / table-column一个列多个值，如下图所示。最好可以自定义模板

### ISSUE THREAD

**Issue by longa30** [xuliangzhan/vxe-table#94]
![image](https://user-images.githubusercontent.com/17867961/60148307-1a97f180-9803-11e9-8473-297d60edb6c7.png)

**Comment by xuliangzhan** [comment]
请先看文档
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/template
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/template
